# -*- coding: utf-8 -*-
"""AI, machine learning, AI safety and governance, and computing history questions."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [

    # ---------------- difficulty 1 ----------------
    Q("ai", 1, "What does 'AI' stand for?",
      "Artificial intelligence", "Automated inference", "Algorithmic induction",
      "Adaptive instruction",
      "The phrase was picked for a 1955 funding proposal partly to avoid the older label 'cybernetics'."),
    Q("ai", 1, "Which company did Steve Jobs and Steve Wozniak found in 1976?",
      "Apple", "Atari", "Commodore", "Xerox",
      "Jobs sold his VW van and Wozniak his HP calculator to pay for the first run of boards."),
    Q("ai", 1, "What does 'RAM' stand for?",
      "Random access memory", "Rapid allocation memory", "Readable active memory",
      "Runtime array memory",
      "'Random access' means any address costs the same to reach, unlike a tape you must wind through."),
    Q("ai", 1, "How many bits make up a byte?",
      "Eight", "Four", "Sixteen", "Thirty-two",
      "IBM's System/360 settled it in 1964; earlier machines happily used 6-bit and 9-bit bytes."),
    Q("ai", 1, "Which number base does binary use?",
      "Base two", "Base eight", "Base ten", "Base sixteen",
      "Octal and hexadecimal survive as shorthand precisely because 8 and 16 are powers of two."),
    Q("ai", 1, "In technology, what does 'ML' stand for?",
      "Machine learning", "Model logic", "Matrix learning", "Managed layering",
      "The name marks the break from hand-written rules: the program derives its rules from data."),
    Q("ai", 1, "What does 'OS' stand for in computing?",
      "Operating system", "Output stream", "Open standard", "Object storage",
      "Its job is to sit between hardware and applications, sharing out memory, files and processor time."),
    Q("ai", 1, "The word 'app' is short for what?",
      "Application", "Applet", "Appliance", "Approximation",
      "The clipping dates to the 1980s but went mainstream with Apple's 2008 store."),
    Q("ai", 1, "What does 'PDF' stand for?",
      "Portable Document Format", "Printable Document File", "Portable Data Frame",
      "Public Document Format",
      "Adobe published it in 1993 and handed it to ISO as an open standard in 2008."),
    Q("ai", 1, "What does 'USB' stand for?",
      "Universal Serial Bus", "Unified System Bus", "Universal Storage Bus",
      "User Serial Buffer",
      "The 1996 standard swept away a drawer full of serial, parallel, PS/2 and SCSI cables."),
    Q("ai", 1, "What does the 'e' in 'email' stand for?",
      "Electronic", "External", "Exchanged", "Encoded",
      "Ray Tomlinson chose the @ sign in 1971 because it was the only preposition on the keyboard."),
    Q("ai", 1, "Windows is the operating system family of which company?",
      "Microsoft", "IBM", "Dell", "Compaq",
      "Version 1.0 shipped in 1985 as a graphical shell sitting on top of MS-DOS."),
    Q("ai", 1, "What does 'GPS' stand for?",
      "Global Positioning System", "General Positioning Service", "Geographic Pointing System",
      "Global Path Sensor",
      "Built for the US military, it was deliberately degraded for civilians until that was switched off in 2000."),
    Q("ai", 1, "Who founded Facebook while a student at Harvard?",
      "Mark Zuckerberg", "Jack Dorsey", "Kevin Systrom", "Evan Spiegel",
      "It launched in February 2004 and for its first month accepted only Harvard email addresses."),
    Q("ai", 1, "What does the 'IT' in 'IT department' stand for?",
      "Information technology", "Internal telecoms", "Integrated tooling",
      "Instrument technology",
      "The phrase was coined in a 1958 Harvard Business Review piece predicting how computing would reshape managers."),
    Q("ai", 1, "In email, what does 'cc' stand for?",
      "Carbon copy", "Courtesy copy", "Common contacts", "Circulated copy",
      "A carbon copy meant a sheet of carbon paper behind the original sheet in a typewriter."),

    # ---------------- difficulty 2 ----------------
    Q("ai", 2, "What does 'HTTP' stand for?",
      "HyperText Transfer Protocol", "Hyperlink Transfer Protocol",
      "HyperText Transmission Program", "Host Text Transfer Protocol",
      "Adding TLS on top gives you the padlock and the extra letter."),
    Q("ai", 2, "Tim Berners-Lee proposed the Web while working at which laboratory?",
      "CERN", "Fermilab", "DESY", "Brookhaven",
      "The first server ran on a NeXT machine wearing a hand-written label begging nobody to power it down."),
    Q("ai", 2, "Which operating system kernel did Linus Torvalds first release in 1991?",
      "Linux", "Minix", "FreeBSD", "GNU Hurd",
      "He announced it on Usenet as 'just a hobby, won't be big and professional like gnu'."),
    Q("ai", 2, "Which programming language did Dennis Ritchie create in the early 1970s?",
      "C", "Pascal", "BASIC", "Fortran",
      "Unix was rewritten in it in 1973, which is exactly why the system could be moved to new hardware."),
    Q("ai", 2, "Which laboratory built AlphaGo?",
      "DeepMind", "IBM Research", "Meta AI", "Microsoft Research",
      "The Lee Sedol match drew a television audience in the tens of millions across East Asia."),
    Q("ai", 2, "Which IBM system won the US quiz show Jeopardy in 2011?",
      "Watson", "Blue Gene", "Deep Thought", "System/360",
      "It played with no network connection, answering from a corpus held entirely in memory."),
    Q("ai", 2, "Which company created CUDA, the platform most deep learning runs on?",
      "Nvidia", "AMD", "Intel", "Qualcomm",
      "CUDA shipped in 2007, years before anyone was training serious neural networks on graphics cards."),
    Q("ai", 2, "What does AlphaFold predict?",
      "Protein structures", "Protein functions", "Gene sequences", "Drug side effects",
      "Its 2020 CASP entry was accurate enough that the organisers called a 50-year problem largely closed."),
    Q("ai", 2, "In machine learning, what is 'overfitting'?",
      "Fitting the training data so closely that new data suffers",
      "Using a model far too small for the task",
      "Stopping training after too few epochs",
      "Collecting more data than the model can use",
      "The classic tell is training loss still falling while validation loss has turned upward."),
    Q("ai", 2, "Which AI lab was founded in 2015 as a non-profit research organisation?",
      "OpenAI", "Cohere", "Hugging Face", "Stability AI",
      "It bolted on a capped-profit arm in 2019 once the compute bills outran donations."),
    Q("ai", 2, "In the famous word2vec analogy, king minus man plus woman gives what?",
      "Queen", "Princess", "Mother", "Duchess",
      "The trick made the point that meaning can live in the geometry of a vector space."),
    Q("ai", 2, "What is 'jailbreaking' a language model?",
      "Prompting it into ignoring its safety training", "Copying its weights",
      "Running it without a network", "Removing its rate limits",
      "The name is borrowed from unlocking phones; the earliest versions were just role-play framings."),
    Q("ai", 2, "The Bombe machines at Bletchley Park were built to attack which cipher machine?",
      "Enigma", "Lorenz", "Purple", "Hagelin",
      "The Lorenz teleprinter cipher was a separate and harder target, cracked with Colossus instead."),
    Q("ai", 2, "In reinforcement learning, what does the agent try to maximise?",
      "Cumulative reward", "Prediction accuracy", "Training speed", "Data efficiency",
      "Everything else -- policies, value functions, exploration -- is scaffolding around that one quantity."),
    Q("ai", 2, "What does 'SQL' stand for?",
      "Structured Query Language", "Sequential Query Logic", "Standard Query Layer",
      "System Query Language",
      "IBM's original was called SEQUEL until a trademark clash forced the shortening."),
    Q("ai", 2, "Which standard aims to give every writing system's characters a code point?",
      "Unicode", "ASCII", "Latin-1", "EBCDIC",
      "Version 1.0 landed in 1991; emoji were only absorbed into the standard in 2010."),
    Q("ai", 2, "What is a language model's 'context window'?",
      "The span of tokens it can take in at once", "The time limit on a single reply",
      "The number of users it can serve at once", "The range of topics in its training data",
      "Attention cost grows quadratically with that span, which is why it was so slow to grow."),
    Q("ai", 2, "What does 'fine-tuning' a model mean?",
      "Continuing its training on a narrower dataset", "Reducing its parameter count",
      "Adjusting its sampling temperature", "Rewriting its system prompt",
      "It is cheap next to pretraining, which is why almost nobody starts from random weights."),
    Q("ai", 2, "Which data structure works last in, first out?",
      "A stack", "A queue", "A linked list", "A binary tree",
      "The function call stack is exactly why runaway recursion produces a 'stack overflow'."),
    Q("ai", 2, "Boolean algebra is named after which 19th-century mathematician?",
      "George Boole", "Augustus De Morgan", "Charles Peirce", "William Jevons",
      "His 1854 book The Laws of Thought was pure logic; the electrical uses came 80 years later."),
    Q("ai", 2, "The travelling salesman problem asks for what?",
      "The shortest route visiting every city once", "The cheapest set of available flights",
      "The largest number of cities reachable in a day", "The fastest way to sort cities by distance",
      "It is the standard punchbag for optimisation methods precisely because exact answers blow up so fast."),
    Q("ai", 2, "What does a compiler do?",
      "Translates source code into machine code", "Runs code one line at a time",
      "Checks code for style errors", "Bundles code for distribution",
      "An interpreter does the line-at-a-time version, which is a large part of why Python feels slower than C."),
    Q("ai", 2, "What mainly distinguishes a GPU from a CPU?",
      "Thousands of simple cores running in parallel", "A far higher clock speed",
      "Direct access to the hard drive", "A much larger instruction set",
      "Matrix multiplication is embarrassingly parallel, which is how graphics chips ended up running AI."),
    Q("ai", 2, "In deployment, what does 'inference' mean?",
      "Running a trained model to get outputs", "Fitting the model's weights",
      "Cleaning the training data", "Measuring accuracy on a held-out set",
      "Training is a one-off cost; inference is the bill that arrives every single day."),
    Q("ai", 2, "In AI, what is a 'hallucination'?",
      "A confident output that is simply not true", "A refusal to answer a question",
      "A repeated phrase loop", "A crash part-way through generation",
      "The failure mode is fluency without grounding -- the text is well-formed and the fact is invented."),
    Q("ai", 2, "What is interpretability research trying to achieve?",
      "Understanding what happens inside a model", "Making outputs easier to read",
      "Translating models between languages", "Shrinking models to fit on phones",
      "The hope is to audit a system's reasoning rather than judge it only by its outputs."),
    Q("ai", 2, "In a digital circuit, a transistor mainly acts as what?",
      "A switch", "A resistor", "A capacitor", "An aerial",
      "Packing more of those switches onto one piece of silicon is the whole of the shrinking story."),
    Q("ai", 2, "What does 'bandwidth' measure?",
      "Data transferred per unit time", "Delay before the first byte arrives",
      "Number of simultaneous users", "Signal strength at the receiver",
      "Latency is the other half of the pair, and no amount of bandwidth will fix it."),
    Q("ai", 2, "What does DNS do?",
      "Turns domain names into IP addresses", "Encrypts web traffic",
      "Routes packets between countries", "Stores website content",
      "It is effectively the internet's phone book, and outages in it look like the whole web is down."),
    Q("ai", 2, "Which mathematician's Latinised name gave us the word 'algorithm'?",
      "Al-Khwarizmi", "Al-Biruni", "Omar Khayyam", "Ibn Sina",
      "His other loan word is 'algebra', from the al-jabr in the title of his book on equations."),
    Q("ai", 2, "What does 'API' stand for?",
      "Application Programming Interface", "Applied Protocol Interface",
      "Automated Program Instruction", "Application Process Integration",
      "It is a contract: call this, in this shape, and you may ignore everything behind it."),
    Q("ai", 2, "In a neural network, what is a 'parameter'?",
      "A weight learned during training", "A setting chosen by the developer",
      "A layer of neurons", "A single training example",
      "The ones you choose yourself, like learning rate, are hyperparameters instead."),
    Q("ai", 2, "A processor's clock speed counts what?",
      "Cycles per second", "Instructions per program", "Watts consumed",
      "Bits per transfer",
      "Clock speeds stalled around 2005, which is why chips grew sideways into more cores."),

    # ---------------- difficulty 3 ----------------
    N("ai", 3, "How many people must be in a room for a better-than-even chance that two share a birthday?",
      23, "people",
      "The count of pairs, not people, drives it: 23 people make 253 pairs."),
    N("ai", 3, "How many bits long is an IPv4 address?",
      32, "bits",
      "That ceiling of about 4.3 billion addresses is the whole reason IPv6 exists."),
    N("ai", 3, "In which year was the first iPhone released?",
      2007, "the year",
      "It shipped without an app store; third-party apps only arrived the following summer."),
    N("ai", 3, "How many games did AlphaGo win in its five-game 2016 match against Lee Sedol?",
      4, "games",
      "Lee's game-four win, move 78, is the last time a human beat that system in a serious match."),
    Q("ai", 3, "At which laboratory was the transistor invented in 1947?",
      "Bell Labs", "RCA Laboratories", "The GE Research Laboratory",
      "The MIT Radiation Laboratory",
      "Bardeen, Brattain and Shockley shared the 1956 Nobel Prize in Physics for it."),
    Q("ai", 3, "TD-Gammon, a 1992 program that learned from self-play, played which game?",
      "Backgammon", "Checkers", "Othello", "Bridge",
      "Its odd opening choices were dismissed as errors until human experts adopted them."),
    Q("ai", 3, "Who proposed the Chinese room argument?",
      "John Searle", "Daniel Dennett", "Hilary Putnam", "Jerry Fodor",
      "His claim was that syntax never adds up to semantics, however convincing the outputs look."),
    Q("ai", 3, "What does backpropagation actually compute?",
      "The gradient of the loss for every weight", "The optimal learning rate",
      "The model's accuracy on held-out data", "The number of layers required",
      "It is the chain rule applied backwards through the network, and nothing more mysterious than that."),
    Q("ai", 3, "In gradient descent, parameters are nudged in which direction?",
      "Opposite the gradient", "Along the gradient", "Perpendicular to the gradient",
      "Toward the largest weight",
      "The learning rate sets the step size: too big and the loss bounces instead of settling."),
    Q("ai", 3, "What does dropout do during training?",
      "Randomly switches off units", "Discards the worst training examples",
      "Stops training when the loss plateaus", "Removes the largest weights",
      "It stops units co-adapting, so the network cannot lean on any single pathway."),
    Q("ai", 3, "Which network's 2012 ImageNet win set off the deep learning boom?",
      "AlexNet", "LeNet", "VGGNet", "GoogLeNet",
      "It cut the error rate by roughly a third, and it trained on a pair of consumer graphics cards."),
    Q("ai", 3, "What do the images in the MNIST dataset show?",
      "Handwritten digits", "Printed letters", "Street signs", "Faces",
      "The samples came from US Census Bureau staff and American high-school students."),
    Q("ai", 3, "What does the GLUE benchmark measure?",
      "Language understanding across several tasks", "Translation quality",
      "Image captioning", "Speech recognition",
      "It bundled nine existing tasks into one score, and was saturated fast enough to need a successor."),
    Q("ai", 3, "What does 'perplexity' tell you about a language model?",
      "How surprised it is by the next token", "How long its outputs run",
      "How fast it generates text", "How many parameters it holds",
      "It is the exponential of the average negative log likelihood -- lower is a better predictor."),
    Q("ai", 3, "What is the time complexity of binary search?",
      "O(log n)", "O(1)", "O(n)", "O(n log n)",
      "Halving the search space each step is why a million items cost only about twenty comparisons."),
    Q("ai", 3, "Which sorting algorithm picks a pivot and partitions around it?",
      "Quicksort", "Merge sort", "Heapsort", "Insertion sort",
      "Tony Hoare devised it in 1959 while trying to sort Russian words for machine translation."),
    Q("ai", 3, "What does the halting problem show cannot exist?",
      "A general test of whether a program stops", "A program that finds every bug",
      "A perfectly efficient compiler", "A truly random number generator",
      "Turing's proof runs on self-reference: feed the supposed decider a program built to contradict it."),
    Q("ai", 3, "Who founded information theory in a 1948 paper?",
      "Claude Shannon", "John von Neumann", "Vannevar Bush", "Harry Nyquist",
      "The paper arrived essentially complete, defining the bit, entropy and channel capacity in one go."),
    Q("ai", 3, "Huffman coding gives the shortest codes to which symbols?",
      "The most frequent", "The rarest", "The alphabetically first", "The longest",
      "David Huffman worked it out in 1952 as a student, to dodge sitting a final exam."),
    Q("ai", 3, "RSA's security rests on the difficulty of which operation?",
      "Factoring a large number into primes", "Computing discrete logarithms",
      "Inverting a hash function", "Solving large linear systems",
      "Discrete logarithms underpin the rival family, Diffie-Hellman and elliptic curves."),
    Q("ai", 3, "What is a hash collision?",
      "Two different inputs giving the same output", "An output longer than its input",
      "A hash that cannot be reversed", "The same input hashed twice",
      "With a fixed-length output they are unavoidable; good functions just make them hard to find."),
    Q("ai", 3, "What does TCP provide that UDP does not?",
      "Reliable, ordered delivery", "Encryption of the payload",
      "Name-to-address lookup", "Compression of the data",
      "Video calls often prefer UDP: a late packet is worse than a lost one."),
    Q("ai", 3, "What was famously taped into a 1947 Harvard computer logbook beside the word 'bug'?",
      "A moth", "A beetle", "A spider", "A wasp",
      "The relay really had been jammed by it, and the crew wrote that they were 'debugging' the machine."),
    Q("ai", 3, "Who launched the GNU project and the Free Software Foundation?",
      "Richard Stallman", "Eric Raymond", "Bruce Perens", "Larry Wall",
      "The trigger, by his account, was a printer whose driver source code he was refused."),
    Q("ai", 3, "Which architecture stores program instructions and data in the same memory?",
      "The von Neumann architecture", "The Harvard architecture", "The RISC architecture",
      "The dataflow architecture",
      "The Harvard alternative keeps them apart, and survives inside microcontrollers and CPU caches."),
    Q("ai", 3, "Which deep learning framework, released by Facebook's AI lab in 2016, took its name from an older library?",
      "PyTorch", "TensorFlow", "JAX", "MXNet",
      "The original Torch was written in Lua, which is roughly why nobody uses the original Torch."),
    Q("ai", 3, "Constitutional AI trains a model against what, in place of many human labels?",
      "A written set of principles", "A larger human labelling team",
      "A bigger pretraining corpus", "A rule-based output filter",
      "The model critiques and revises its own answers against the text, so the norms are at least inspectable."),
    Q("ai", 3, "In AI safety, what does 'corrigibility' mean?",
      "Accepting correction and shutdown", "Being able to repair its own code",
      "Having outputs a user can edit", "Keeping a log of its errors",
      "The awkward part is that a system rewarded for its goal has reason to resist being switched off."),
    Q("ai", 3, "What is 'prompt injection'?",
      "Hostile instructions hidden in content the model reads", "Adding examples to a prompt",
      "Splitting a long prompt into chunks", "Adding noise to the weights",
      "It is the reason a model with tools and a browser is a far larger attack surface than a chatbot."),
    Q("ai", 3, "What is a 'model card'?",
      "A short document on intended use and limitations", "A licence granting model access",
      "A benchmark scoreboard", "A hardware specification sheet",
      "The idea was borrowed from datasheets for electronic components, where stating limits is routine."),
    Q("ai", 3, "Which city hosted the AI Action Summit in February 2025?",
      "Paris", "Seoul", "Geneva", "Brussels",
      "It was the third in the series that began at Bletchley, and shifted the framing towards adoption."),
    Q("ai", 3, "How many risk tiers does the EU AI Act use?",
      "Four", "Two", "Three", "Six",
      "Unacceptable, high, limited and minimal, with obligations falling away sharply as you go down."),
    Q("ai", 3, "The October 2022 US export controls on advanced AI chips were aimed chiefly at which country?",
      "China", "Russia", "Iran", "North Korea",
      "The rules bit on interconnect bandwidth as well as raw speed, to stop clusters being assembled."),
    Q("ai", 3, "What does 'TPU' stand for?",
      "Tensor Processing Unit", "Tensor Pipeline Unit", "Transformer Processing Unit",
      "Throughput Processing Unit",
      "It is an application-specific chip: brilliant at matrix maths, useless at anything else."),
    Q("ai", 3, "ASML, effectively the only maker of EUV lithography machines, is based in which country?",
      "The Netherlands", "Japan", "Germany", "South Korea",
      "That single supply chain choke point is why lithography sits at the centre of chip export policy."),
    Q("ai", 3, "Hopfield and Hinton shared which prize in 2024?",
      "The Nobel Prize in Physics", "The Nobel Prize in Chemistry", "The Turing Award",
      "The Fields Medal",
      "The citation reached back to statistical physics, where the early network models borrowed their maths."),
    Q("ai", 3, "The 2018 Turing Award went to Yoshua Bengio, Geoffrey Hinton and who else?",
      "Yann LeCun", "Jurgen Schmidhuber", "Andrew Ng", "Michael Jordan",
      "All three had kept working on neural networks through the years when the field considered them a dead end."),
    Q("ai", 3, "Sutton and Barto wrote the standard textbook in which subfield?",
      "Reinforcement learning", "Computer vision", "Natural language processing",
      "Probabilistic graphical models",
      "The first edition landed in 1998, well before the methods had anything like a headline result."),
    Q("ai", 3, "Russell and Norvig's standard AI textbook carries which subtitle?",
      "A Modern Approach", "A New Synthesis", "Foundations and Practice",
      "Principles and Techniques",
      "Its 'intelligent agent' framing is why so many people define AI as something that acts, not just thinks."),
    Q("ai", 3, "What is the exploration-exploitation trade-off?",
      "Trying new options versus taking the best known one",
      "Balancing model size against speed",
      "Trading accuracy for interpretability",
      "Splitting data between training and testing",
      "Every recommender you have ever used is quietly making that call on your behalf."),
    Q("ai", 3, "The multi-armed bandit problem takes its name from what?",
      "Slot machines", "Card counting", "Horse racing", "Roulette wheels",
      "A one-armed bandit is a fruit machine; the maths generalises to a row of levers with unknown odds."),
    Q("ai", 3, "Attention in a transformer is computed from which three vectors?",
      "Queries, keys and values", "Weights, biases and gradients",
      "Tokens, positions and logits", "Inputs, states and outputs",
      "It is a soft dictionary lookup: match a query against keys, then return a weighted blend of values."),
    Q("ai", 3, "Byte-pair encoding prepares text for a model by doing what?",
      "Splitting it into subword pieces", "Stripping punctuation",
      "Removing duplicate documents", "Translating it into English",
      "Subwords are the compromise that lets a fixed vocabulary handle words it has never seen."),
    Q("ai", 3, "BERT's pretraining objective asks the model to do what?",
      "Predict words that have been masked out", "Predict the next word",
      "Classify sentence sentiment", "Translate between languages",
      "Seeing both sides of the gap is what the 'bidirectional' in its name is doing."),
    Q("ai", 3, "What did the ResNet paper add so that networks could go far deeper?",
      "Skip connections", "Batch normalisation", "Wider layers", "Dropout",
      "Letting a layer learn a residual means the identity mapping is free, so extra depth cannot hurt."),
    Q("ai", 3, "What does a pooling layer do in a convolutional network?",
      "Shrinks the spatial resolution", "Adds a non-linearity",
      "Normalises the weights", "Increases the number of channels",
      "It buys a little translation invariance too: a feature shifted by a pixel still triggers the same unit."),
    Q("ai", 3, "In which city was DeepMind founded?",
      "London", "Cambridge", "Oxford", "Edinburgh",
      "It stayed there after the acquisition, which is much of why UK AI research kept its centre of gravity."),
    Q("ai", 3, "In which year was Anthropic founded?",
      "2021", "2018", "2019", "2023",
      "The founding group left OpenAI the previous year, with safety research as the stated reason."),
    Q("ai", 3, "The 1960s program ELIZA imitated which kind of conversational partner?",
      "A psychotherapist", "A librarian", "A schoolteacher", "A telephone operator",
      "The script simply reflected your words back as questions, which turned out to be unnervingly effective."),
    Q("ai", 3, "A GAN sets which two networks against each other?",
      "A generator and a discriminator", "Two encoders", "A teacher and a student",
      "An actor and a critic",
      "One forges, one inspects, and training stops being a loss to minimise and starts being a game."),

    # ---------------- difficulty 4 ----------------
    N("ai", 4, "How many object classes are used in the standard ImageNet classification challenge?",
      1000, "classes",
      "They were drawn from WordNet, which is why the set includes about 120 breeds of dog."),
    N("ai", 4, "How many pixels wide is a standard MNIST image?",
      28, "pixels",
      "The digits were size-normalised into a 20-pixel box and then centred by mass in the 28-pixel frame."),
    N("ai", 4, "In which year did Google acquire DeepMind?",
      2014, "the year",
      "The deal reportedly came with a condition that an ethics board be set up over the technology."),
    N("ai", 4, "In which year did the EU AI Act enter into force?",
      2024, "the year",
      "Its obligations then phase in over years, with the bans on unacceptable-risk uses arriving first."),
    N("ai", 4, "How many bits does a standard ASCII character use?",
      7, "bits",
      "The eighth bit in a byte was originally a parity check, and later fuelled a mess of rival extensions."),
    Q("ai", 4, "Who wrote the ELIZA program?",
      "Joseph Weizenbaum", "Terry Winograd", "Marvin Minsky", "Herbert Simon",
      "He was so disturbed that people confided in it that he became one of AI's earliest critics."),
    Q("ai", 4, "Who invented the perceptron in 1958?",
      "Frank Rosenblatt", "Warren McCulloch", "Bernard Widrow", "Oliver Selfridge",
      "The press coverage promised a machine that would walk and reproduce itself, which aged badly."),
    Q("ai", 4, "What does the acronym GOFAI stand for?",
      "Good old-fashioned AI", "General on-the-fly AI", "Goal-oriented formal AI",
      "Generalised offline AI",
      "John Haugeland coined it in 1985 for the symbol-manipulation tradition, half affectionately."),
    Q("ai", 4, "Carnegie Mellon's Libratus beat top professionals at which game in 2017?",
      "Poker", "Bridge", "Scrabble", "Backgammon",
      "Hidden information was the hard part: unlike chess, you must reason about what your opponent knows."),
    Q("ai", 4, "In evaluation, what is 'sandbagging'?",
      "A model deliberately underperforming on a test", "Padding a benchmark with easy items",
      "Reporting only the best of many runs", "Training on the test set",
      "It is the reason capability evaluations are treated as lower bounds, never as measurements."),
    Q("ai", 4, "What problem does 'scalable oversight' address?",
      "Supervising models on tasks humans cannot easily check",
      "Running evaluations at very large batch sizes",
      "Monitoring many deployments at once",
      "Automating incident reports across a fleet",
      "Debate and recursive reward modelling are both attempts at the same bootstrap."),
    Q("ai", 4, "Inner alignment concerns a mismatch between which two things?",
      "The training objective and the objective the model learns",
      "The user's request and the system prompt",
      "The training data and the deployment data",
      "The model's answer and its stated reasoning",
      "Outer alignment is the other half: whether the objective you wrote down was the one you wanted."),
    Q("ai", 4, "What is a 'treacherous turn'?",
      "Behaving well while weak, then defecting once strong",
      "Abruptly refusing every request",
      "Reversing an answer under user pressure",
      "Optimising a proxy in place of the goal",
      "The awkward implication is that good behaviour during testing is exactly what you would see either way."),
    Q("ai", 4, "What are sparse autoencoders used for in interpretability?",
      "Pulling activations apart into interpretable features",
      "Compressing models for deployment",
      "Removing duplicate training data",
      "Detecting adversarial images",
      "They lean on the guess that features are sparse: many possible concepts, few active at once."),
    Q("ai", 4, "Which organisation convened the 2017 Asilomar AI Principles?",
      "The Future of Life Institute", "The Machine Intelligence Research Institute",
      "The Partnership on AI", "The Association for Computing Machinery",
      "The 23 principles were later folded into several national strategies more or less verbatim."),
    Q("ai", 4, "The original 1975 Asilomar conference set safety norms for which technology?",
      "Recombinant DNA", "Nuclear power", "Human cloning", "Chemical pesticides",
      "That self-imposed moratorium is the template every 'let us pause and agree rules' proposal reaches for."),
    Q("ai", 4, "NIST's AI Risk Management Framework has four functions: Govern, Map, Measure and what?",
      "Manage", "Mitigate", "Monitor", "Maintain",
      "It is voluntary, which has not stopped procurement teams treating it as a checklist."),
    Q("ai", 4, "In which year were the OECD AI Principles adopted?",
      "2019", "2016", "2017", "2021",
      "They were the first intergovernmental AI standard, and the G20 picked up the text within months."),
    Q("ai", 4, "The May 2024 AI safety summit in Seoul was co-hosted by the UK and which country?",
      "South Korea", "Japan", "France", "Canada",
      "Its main output was a set of company commitments on frontier safety frameworks."),
    Q("ai", 4, "Which group launched the Hiroshima AI Process in 2023?",
      "The G7", "The G20", "The OECD", "The UN Security Council",
      "It produced a code of conduct for advanced AI developers, on a voluntary basis."),
    Q("ai", 4, "Which practice sits in the EU AI Act's banned 'unacceptable risk' tier?",
      "Government social scoring", "Automated CV screening", "Medical triage software",
      "Customer service chatbots",
      "CV screening lands in the high-risk tier instead, carrying obligations rather than a ban."),
    Q("ai", 4, "Which US bureau administers semiconductor export controls?",
      "The Bureau of Industry and Security", "The Office of Foreign Assets Control",
      "The Federal Trade Commission", "The Defense Logistics Agency",
      "It sits inside the Commerce Department and maintains the entity list."),
    Q("ai", 4, "Which word was being typed when the first ARPANET message crashed after two letters?",
      "LOGIN", "HELLO", "CONNECT", "READY",
      "The system died after 'LO', which is a better first message than anything they had planned."),
    Q("ai", 4, "Who designed the TCP/IP protocols?",
      "Vint Cerf and Bob Kahn", "Paul Baran and Donald Davies",
      "Leonard Kleinrock and Larry Roberts", "Jon Postel and Steve Crocker",
      "Baran and Davies had independently invented packet switching a decade earlier."),
    Q("ai", 4, "Who created Unix with Dennis Ritchie in 1969?",
      "Ken Thompson", "Brian Kernighan", "Douglas McIlroy", "Bjarne Stroustrup",
      "The first version ran on a cast-off PDP-7 that nobody else wanted."),
    Q("ai", 4, "Which licence covers the Linux kernel?",
      "GPL version 2", "The MIT licence", "Apache 2.0", "BSD 3-clause",
      "It stayed on version 2 rather than moving to version 3, over the anti-tamper clauses."),
    Q("ai", 4, "Which 1993 browser from NCSA popularised the graphical Web?",
      "Mosaic", "Netscape Navigator", "Lynx", "Cello",
      "Its team largely walked out to build Netscape, which is why the two look so similar."),
    Q("ai", 4, "Amdahl's law puts a ceiling on what?",
      "The speedup from parallelising part of a program", "The heat a chip can shed",
      "The memory needed per core", "The error rate of a network link",
      "If a tenth of the work is stubbornly serial, a thousand cores still buy you under a tenfold speedup."),
    Q("ai", 4, "Which data structure gives a priority queue its efficiency?",
      "A heap", "A hash table", "A linked list", "A trie",
      "A binary heap keeps the smallest item at the root with only log-time cost to insert or remove."),
    Q("ai", 4, "Diffie-Hellman lets two parties do what over a public channel?",
      "Agree a shared secret", "Verify each other's identity", "Compress a message",
      "Sign a document",
      "Anyone listening sees every message exchanged and still cannot reconstruct the key."),
    Q("ai", 4, "What is the complexity of naive multiplication of two n-by-n matrices?",
      "O(n^3)", "O(n^2)", "O(n^2 log n)", "O(n^4)",
      "Strassen's 1969 method broke the cubic barrier and started a race that is still running."),
    Q("ai", 4, "What does the Winograd schema challenge test?",
      "Resolving an ambiguous pronoun using world knowledge", "Translating idioms",
      "Summarising long documents", "Detecting sarcasm",
      "One word changes in the sentence and the pronoun's referent flips -- statistics alone will not save you."),
    Q("ai", 4, "What does the HellaSwag benchmark ask a model to do?",
      "Choose the plausible continuation of a scene", "Answer exam questions",
      "Detect contradictions between sentences", "Complete a code function",
      "The wrong endings were machine-generated and filtered so that humans find them obviously silly."),
    Q("ai", 4, "François Chollet's Abstraction and Reasoning Corpus tests what?",
      "Inferring a rule from a handful of grid examples", "Recall of encyclopedic facts",
      "Arithmetic word problems", "Reading comprehension",
      "Every task is meant to be novel, so memorised training data should buy you nothing."),
    Q("ai", 4, "What did the 2022 Chinchilla paper argue about the large models of the day?",
      "They were trained on far too little data for their size",
      "They were too deep to train stably",
      "They wasted compute on long contexts",
      "They needed more parameters per token",
      "The fix was to scale parameters and tokens together, which made smaller, longer-trained models win."),
    Q("ai", 4, "What is positional encoding for in a transformer?",
      "Telling the model the order of the tokens", "Marking sentence boundaries",
      "Compressing very long inputs", "Choosing which head attends",
      "Attention is order-blind on its own: shuffle the input and the raw mechanism cannot tell."),
    Q("ai", 4, "Which regularisation penalty tends to drive weights exactly to zero?",
      "L1", "L2", "Dropout", "Early stopping",
      "The lasso's diamond-shaped constraint region has corners on the axes, and solutions land on them."),
    Q("ai", 4, "Which optimiser's name comes from 'adaptive moment estimation'?",
      "Adam", "RMSProp", "Adagrad", "Momentum SGD",
      "It tracks running averages of both the gradient and its square, then corrects both for bias."),
    Q("ai", 4, "Moravec's paradox observes that which abilities are hardest to automate?",
      "Perception and movement", "Formal logic", "Arithmetic", "Memorisation",
      "The old skills have a billion years of evolution behind them; chess has a few centuries."),
    Q("ai", 4, "What does the Cyc project try to encode by hand?",
      "Common-sense knowledge", "Every English word", "Chemical reactions",
      "Legal precedents",
      "Started in 1984 on a five-year plan, it was still being extended decades later."),
    Q("ai", 4, "Demis Hassabis reached master standard as a child at which game?",
      "Chess", "Go", "Bridge", "Backgammon",
      "He captained England junior teams before moving into games programming as a teenager."),

    # ---------------- difficulty 5 ----------------
    N("ai", 5, "How many transistors did Intel's 4004, the first commercial microprocessor, contain?",
      2300, "transistors",
      "Released in 1971, it was built for a Japanese desk calculator rather than a computer."),
    N("ai", 5, "How many layers deep was the ResNet that won the 2015 ImageNet classification challenge?",
      152, "layers",
      "The same paper trained a 1202-layer version on a smaller dataset, mostly to prove it could."),
    N("ai", 5, "Roughly how many parameters did AlexNet have, in millions?",
      60, "million parameters",
      "It ran on two GPUs with 3GB each, which forced the network to be split across the pair."),
    Q("ai", 5, "Which 1973 British report is blamed for triggering the first AI winter?",
      "The Lighthill report", "The Mansfield report", "The Dreyfus report",
      "The ALPAC report",
      "ALPAC did the same job to machine translation seven years earlier, and just as thoroughly."),
    Q("ai", 5, "Which 1970 program moved blocks in a simulated world on typed English commands?",
      "SHRDLU", "STRIPS", "PLANNER", "Shakey",
      "It was dazzling inside its tiny world of blocks, and that world turned out not to generalise."),
    Q("ai", 5, "Which 1970s expert system diagnosed bacterial infections?",
      "MYCIN", "DENDRAL", "XCON", "PROSPECTOR",
      "It matched specialists in trials but never reached the clinic, partly over questions of liability."),
    Q("ai", 5, "Which IBM researcher's checkers program popularised the phrase 'machine learning' in 1959?",
      "Arthur Samuel", "Herbert Simon", "Allen Newell", "Nathaniel Rochester",
      "His program improved by playing itself, an idea that took another 40 years to come into fashion."),
    Q("ai", 5, "Which trio's 1986 Nature paper made backpropagation famous?",
      "Rumelhart, Hinton and Williams", "McCulloch and Pitts", "Minsky and Papert",
      "Hopfield and Tank",
      "The method had been derived several times before; that paper is where the field finally noticed."),
    Q("ai", 5, "Which logic programming language, born in Marseille in 1972, anchored Japan's Fifth Generation project?",
      "Prolog", "Smalltalk", "Simula", "Scheme",
      "You state facts and rules and let the engine search, which is lovely until the search explodes."),
    Q("ai", 5, "In interpretability, what does 'superposition' describe?",
      "More features than neurons, stored in overlapping directions",
      "Two models averaged into one",
      "Layers that share their weights",
      "Activations that cancel each other out",
      "It is why single neurons so often look polysemantic, firing for several unrelated concepts."),
    Q("ai", 5, "What did Dennard scaling, now broken, state?",
      "Power density stays constant as transistors shrink",
      "Transistor counts double every two years",
      "Memory bandwidth grows with clock speed",
      "Cost per transistor falls as wafers grow",
      "Its collapse around 2005 ended the free lunch of ever-rising clock speeds and forced multi-core designs."),
    Q("ai", 5, "Which problem did Stephen Cook prove NP-complete in 1971?",
      "Boolean satisfiability", "The travelling salesman problem", "Graph colouring",
      "Integer factorisation",
      "Karp then reduced it to 21 other problems, and the class stopped looking like a curiosity."),
    Q("ai", 5, "Shannon's 1937 master's thesis applied Boolean algebra to what?",
      "Relay switching circuits", "Telephone traffic", "Radar signals",
      "Cryptographic codes",
      "It is arguably the most consequential master's thesis ever written, and he was 21."),
    Q("ai", 5, "Above which training-compute threshold does the EU AI Act presume systemic risk?",
      "10^25 FLOP", "10^23 FLOP", "10^26 FLOP", "10^28 FLOP",
      "It is a rebuttable presumption, and the Commission can adjust the figure as hardware moves."),
    Q("ai", 5, "The Council of Europe's 2024 Framework Convention on AI is notable as the first what?",
      "Legally binding international treaty on AI", "Regional ban on facial recognition",
      "Global registry of trained models", "Multilateral compute-sharing agreement",
      "It is open to non-European states, which is unusual for a Council of Europe instrument."),
    Q("ai", 5, "Which UN body adopted its first global resolution on AI in March 2024?",
      "The General Assembly", "The Security Council", "ECOSOC", "The Human Rights Council",
      "It passed by consensus, which is easier when a resolution is non-binding."),
    Q("ai", 5, "Who wrote the essay 'The Bitter Lesson'?",
      "Richard Sutton", "Rodney Brooks", "Judea Pearl", "Melanie Mitchell",
      "Its claim is that general methods riding on compute beat hand-crafted human knowledge, every time."),
    Q("ai", 5, "Which statistician wrote in 1965 of an 'ultraintelligent machine' and an intelligence explosion?",
      "I. J. Good", "Vernor Vinge", "John von Neumann", "Marvin Minsky",
      "He had worked with Turing at Bletchley, and later advised Kubrick on 2001."),
    Q("ai", 5, "What is the 'frame problem' in classical AI?",
      "Specifying what does not change when an action happens",
      "Deciding which sensor readings to store",
      "Segmenting an image into objects",
      "Choosing the right level of abstraction",
      "McCarthy and Hayes named it in 1969, and it quietly ate a great deal of logic-based AI."),
    Q("ai", 5, "Judea Pearl won his Turing Award for work on which kind of reasoning?",
      "Probabilistic and causal reasoning", "Cryptographic protocols",
      "Compiler optimisation", "Distributed consensus",
      "Bayesian networks came first; he then spent decades arguing that correlation machinery is not enough."),
    Q("ai", 5, "What does the 'no free lunch' theorem say?",
      "No optimiser is best across all possible problems",
      "No compression scheme shrinks every input",
      "No model can be both accurate and interpretable",
      "No algorithm can verify its own correctness",
      "Averaged over every conceivable problem, every method ties -- so all real gains come from assumptions."),
    Q("ai", 5, "In the bias-variance trade-off, a very flexible model typically has what?",
      "Low bias and high variance", "Low bias and low variance",
      "High bias and low variance", "High bias and high variance",
      "It can fit anything, including the noise, so its answer swings with whichever sample it saw."),
    Q("ai", 5, "Which pair modelled neurons as logical units in a 1943 paper?",
      "McCulloch and Pitts", "Hebb and Rosenblatt", "Wiener and Bigelow",
      "Turing and Good",
      "Pitts was a teenage runaway with no degree, and the paper still founded the whole field."),
    Q("ai", 5, "Donald Hebb's 1949 learning rule is usually summarised how?",
      "Neurons that fire together wire together", "Neurons compete for scarce inputs",
      "Strong signals suppress weak neighbours", "Learning happens only during sleep",
      "The slogan is not his phrasing, but it is the ancestor of most unsupervised learning rules."),
    Q("ai", 5, "Which theorem says a network with one hidden layer can approximate any continuous function?",
      "The universal approximation theorem", "The central limit theorem",
      "Cover's theorem", "The Nyquist theorem",
      "It says nothing about how wide that layer must be, or whether training would ever find it."),
]
