# -*- coding: utf-8 -*-
"""
film_b.py -- FILM & TV, batch two. Depth for a category the rebalance leans on.

CALIBRATION
    The players are around thirty, live in the United States, and one of them
    is British. So: big films, prestige television, British sitcoms, and the
    kind of behind-the-camera fact a strong pub quizzer knows -- NOT cinephile
    canon. "Hard" here means a good pub team gets it on the second guess, not
    that you need to have seen the Sight and Sound top fifty.

    Nothing whose answer moves: no box-office records, no "most nominated",
    no current-run series. Spread runs 1 to 5, weighted to the middle.
"""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [

    # ---------------- difficulty 1 ----------------
    Q("film", 1, "Which superhero is Bruce Wayne?",
      "Batman", "Superman", "Spider-Man", "Iron Man",
      "Bill Finger devised the cowl, the cape, the name Gotham and most of the rest, and went uncredited for about fifty years."),
    Q("film", 1, "Which animated film features a snowman called Olaf?",
      "Frozen", "Tangled", "Moana", "Encanto",
      "'Let It Go' was written while Elsa was still the villain, and the song was so good the writers rebuilt her as a heroine around it."),
    Q("film", 1, "Who plays Jack Sparrow in the Pirates of the Caribbean films?",
      "Johnny Depp", "Orlando Bloom", "Colin Farrell", "Russell Crowe",
      "He modelled the walk and the slur on Keith Richards, and the studio spent the early rushes convinced the performance was a disaster."),
    Q("film", 1, "What is the name of the cowboy doll in Toy Story?",
      "Woody", "Buzz", "Rex", "Slinky",
      "Early drafts made him a sarcastic bully, and a screening so bad it nearly cancelled the film forced Pixar to rewrite him from scratch."),

    # ---------------- difficulty 2 ----------------
    Q("film", 2, "Who directed both Titanic and Avatar?",
      "James Cameron", "Ridley Scott", "Michael Bay", "Peter Jackson",
      "He made thirty-three dives to the real wreck, which adds up to more time on the Titanic than its passengers ever had."),
    Q("film", 2, "Which actor plays Tony Stark in the Marvel films?",
      "Robert Downey Jr", "Chris Evans", "Mark Ruffalo", "Jeremy Renner",
      "The studio had to be talked into hiring him, his insurance was a problem, and the entire decade of films turned on that one casting."),
    Q("film", 2, "Which American sitcom features a regional manager called Michael Scott?",
      "The Office", "Parks and Recreation", "30 Rock", "Superstore",
      "Steve Carell deliberately avoided watching the British original, on the grounds that he would only end up imitating it."),
    Q("film", 2, "Which drama series follows the British royal family decade by decade?",
      "The Crown", "Downton Abbey", "Victoria", "Bridgerton",
      "The entire cast is replaced every two series, so the actors age with the characters rather than under prosthetics."),
    Q("film", 2, "Which 1999 film ends with the revelation that Bruce Willis's character has been dead throughout?",
      "The Sixth Sense", "Unbreakable", "The Others", "Fight Club",
      "Shyamalan shot every scene so that it plays twice, and the colour red turns up only where the two worlds touch."),
    Q("film", 2, "In Star Wars, what is Luke Skywalker's home planet?",
      "Tatooine", "Alderaan", "Naboo", "Endor",
      "It was shot in Tunisia, and the name is borrowed from the real town of Tataouine a short drive down the road."),
    Q("film", 2, "Which British sitcom is set in a Torquay hotel?",
      "Fawlty Towers", "Porridge", "Dad's Army", "Only Fools and Horses",
      "Twelve episodes exist in total, written after the Monty Python team stayed at a hotel whose owner really was that rude to them."),
    Q("film", 2, "Which Christopher Nolan film is about entering other people's dreams?",
      "Inception", "Interstellar", "Memento", "Tenet",
      "Nolan cuts to black before the top settles, and has said the point is that Cobb has stopped caring, not that the audience gets an answer."),
    Q("film", 2, "Which HBO series follows a New Jersey mob boss who goes into therapy?",
      "The Sopranos", "Boardwalk Empire", "Goodfellas", "The Wire",
      "Goodfellas is a film rather than a series, which did not stop about a third of its cast turning up in this one."),
    Q("film", 2, "Which 1994 film gave us the line about life being like a box of chocolates?",
      "Forrest Gump", "Rain Man", "Big", "Philadelphia",
      "It took Best Picture over Pulp Fiction and The Shawshank Redemption, a result the internet has never fully forgiven."),
    Q("film", 2, "Which actor played the Joker in The Dark Knight?",
      "Heath Ledger", "Jack Nicholson", "Joaquin Phoenix", "Jared Leto",
      "He won the Oscar posthumously, and Nolan has said almost every mannerism was Ledger's own invention rather than anything on the page."),
    Q("film", 2, "Which director made Goodfellas, Raging Bull and The Departed?",
      "Martin Scorsese", "Francis Ford Coppola", "Brian De Palma", "Michael Mann",
      "The Departed finally won him Best Director on his sixth nomination, and it is a remake of the Hong Kong thriller Infernal Affairs."),

    # ---------------- difficulty 3 ----------------
    Q("film", 3, "Which Wes Anderson film is set in a fictional Central European republic called Zubrowka?",
      "The Grand Budapest Hotel", "Moonrise Kingdom", "The Darjeeling Limited", "The French Dispatch",
      "Each of its three time periods is shot in a different aspect ratio, so the shape of the screen quietly tells you which decade you are in."),
    Q("film", 3, "Which actor has played James Bond in the most official films?",
      "Roger Moore", "Sean Connery", "Daniel Craig", "Pierce Brosnan",
      "Seven to Connery's six, and Connery's unofficial seventh, Never Say Never Again, has never been counted by anybody who matters."),
    Q("film", 3, "Which actor won an Academy Award for playing Freddie Mercury?",
      "Rami Malek", "Taron Egerton", "Sacha Baron Cohen", "Ben Whishaw",
      "Sacha Baron Cohen was attached for years and walked away when it became clear the surviving band wanted a much gentler film."),
    Q("film", 3, "Which film actually won Best Picture at the 2017 ceremony, after the wrong envelope was opened?",
      "Moonlight", "Manchester by the Sea", "Hidden Figures", "Arrival",
      "The La La Land producers were well into their acceptance speeches before somebody got the right card onto the stage."),
    Q("film", 3, "Which Coen brothers film features a hitman who kills with a captive bolt pistol?",
      "No Country for Old Men", "Fargo", "Blood Simple", "Burn After Reading",
      "Javier Bardem has said the haircut unsettled him considerably more than the character ever did."),
    Q("film", 3, "Which film features a shipboard computer called HAL 9000?",
      "2001: A Space Odyssey", "Solaris", "Silent Running", "Forbidden Planet",
      "Shift each letter of HAL forward by one and you get IBM, which Kubrick and Arthur C. Clarke both swore blind was a coincidence."),
    Q("film", 3, "Which Studio Ghibli film is set in a bathhouse for spirits?",
      "Spirited Away", "My Neighbour Totoro", "Princess Mononoke", "Howl's Moving Castle",
      "It was the first film not in English to take the Best Animated Feature Oscar, and Miyazaki stayed away from the ceremony in protest at the Iraq war."),
    Q("film", 3, "Which prequel series follows the lawyer Jimmy McGill?",
      "Better Call Saul", "Breaking Bad", "El Camino", "Ozark",
      "It ran six seasons, roughly four more than anyone expects of a spin-off, and a good many critics ended up rating it above the original."),
    Q("film", 3, "Which film opens with a lavish wedding at the Corleone family compound?",
      "The Godfather", "Goodfellas", "Once Upon a Time in America", "Scarface",
      "Brando stuffed his cheeks with cotton wool for the screen test and wore a purpose-made dental appliance for the film itself."),
    Q("film", 3, "Which Denis Villeneuve film stars Amy Adams as a linguist sent to meet aliens?",
      "Arrival", "Contact", "Interstellar", "Annihilation",
      "The alien writing is circular, with no beginning and no end, which is the entire plot expressed as a single design decision."),
    Q("film", 3, "Which British series follows a Birmingham crime family after the First World War?",
      "Peaky Blinders", "Boardwalk Empire", "Ripper Street", "Gangs of London",
      "There really was a Birmingham gang of that name; the razor blades sewn into the flat caps are almost certainly folklore."),
    Q("film", 3, "Which Pixar film takes place largely inside a girl's mind?",
      "Inside Out", "Soul", "Coco", "Up",
      "The five emotions were whittled down from a much longer list drawn up with psychologists, and each one is colour-coded through the whole film."),
    Q("film", 3, "Which comedy series is set in the parks department of Pawnee, Indiana?",
      "Parks and Recreation", "Community", "Superstore", "Veep",
      "It was commissioned as an Office spin-off and rewritten into its own show after a first season nobody much liked."),
    Q("film", 3, "Which actor has played both Gandalf and Magneto?",
      "Ian McKellen", "Patrick Stewart", "Christopher Lee", "Michael Gambon",
      "He officiated at the wedding of Patrick Stewart, the man he spent four films glowering at across a chessboard."),
    Q("film", 3, "Which action franchise follows an agent called Ethan Hunt?",
      "Mission: Impossible", "The Bourne Identity", "John Wick", "Jack Reacher",
      "Cruise has done his own stunts throughout, and the hardest part of the Burj Khalifa sequence was reportedly getting anybody to insure it."),
    Q("film", 3, "Which sitcom is set in a failing Philadelphia bar called Paddy's Pub?",
      "It's Always Sunny in Philadelphia", "Brooklyn Nine-Nine", "Barney Miller", "Superstore",
      "The pilot was shot on a camcorder for a couple of hundred dollars, and sold to the network on that alone."),
    Q("film", 3, "Which composer wrote the scores for The Good, the Bad and the Ugly and Once Upon a Time in the West?",
      "Ennio Morricone", "Nino Rota", "Elmer Bernstein", "Jerry Goldsmith",
      "He wrote the second one before filming started, and Leone played it aloud on set so the actors would move at the tempo of the music."),
    Q("film", 3, "Which actress has won the most Academy Awards for acting?",
      "Katharine Hepburn", "Meryl Streep", "Bette Davis", "Ingrid Bergman",
      "Four, every one of them for Best Actress, and she never turned up to collect a single one of them."),
    Q("film", 3, "Which film series is set in a dystopia where children are made to fight in televised games?",
      "The Hunger Games", "Divergent", "The Maze Runner", "Battle Royale",
      "Battle Royale is the Japanese novel it was endlessly compared to, which Suzanne Collins has said she had never read."),
    Q("film", 3, "Which was Daniel Craig's first film as James Bond?",
      "Casino Royale", "Quantum of Solace", "Skyfall", "Spectre",
      "It is the only Bond film to open in black and white, marking the two kills that earn him the double-0 in the first place."),
    Q("film", 3, "Which 1977 film made its director a fortune because he took merchandising rights instead of a bigger fee?",
      "Star Wars", "Close Encounters of the Third Kind", "Superman", "Saturday Night Fever",
      "Lucas gave up a directing fee of half a million dollars for the sequel and merchandising rights, and became a billionaire off the toys."),
    Q("film", 3, "Which series is built around a Korean debt-driven death game?",
      "Squid Game", "Alice in Borderland", "3%", "The Platform",
      "Hwang Dong-hyuk wrote it in 2009 and spent the next decade being told it was far too far-fetched to make."),
    Q("film", 3, "Which Aardman film is about chickens escaping a farm?",
      "Chicken Run", "Early Man", "Flushed Away", "Arthur Christmas",
      "It is The Great Escape with poultry, right down to the bloke tunnelling out of the exercise yard."),
    Q("film", 3, "In which film did Robert De Niro play a young Vito Corleone?",
      "The Godfather Part II", "The Godfather", "Once Upon a Time in America", "The Sicilian",
      "He won an Oscar for a character Brando had already won one for, the only time two actors have managed that with the same role."),
    Q("film", 3, "Which anthology series sets each season in a different time and place, beginning in Minnesota?",
      "Fargo", "True Detective", "American Horror Story", "Black Mirror",
      "Every season opens by claiming to be a true story, which is a lie the Coen brothers' film told first."),
    Q("film", 3, "Which actor turned down the role of Neo in The Matrix?",
      "Will Smith", "Brad Pitt", "Nicolas Cage", "Johnny Depp",
      "He made Wild Wild West instead, and has been extremely good-natured about the comparison ever since."),
    Q("film", 3, "Which director made Mulholland Drive and Twin Peaks?",
      "David Lynch", "David Cronenberg", "Terrence Malick", "Nicolas Winding Refn",
      "Mulholland Drive was shot as a television pilot, turned down flat by the network, then rebuilt into a film with new material."),
    Q("film", 3, "Which ITV drama starred Olivia Colman and David Tennant investigating a boy's death on a Dorset beach?",
      "Broadchurch", "Happy Valley", "The Fall", "Shetland",
      "The cast were sent scripts that concealed the killer's identity, so several of them genuinely did not know until near the end."),
    Q("film", 3, "Which director made Moonlight and If Beale Street Could Talk?",
      "Barry Jenkins", "Ryan Coogler", "Ava DuVernay", "Steve McQueen",
      "He and the playwright whose work Moonlight is based on grew up in the same Miami housing project without ever meeting."),
    Q("film", 3, "Which director made both Roma and Gravity?",
      "Alfonso Cuaron", "Guillermo del Toro", "Alejandro Gonzalez Inarritu", "Pablo Larrain",
      "He and those first two rivals are known as the Three Amigos, and between them took Best Director five times in six years."),
    Q("film", 3, "Which 2022 film involves a multiverse, a laundrette and a bagel?",
      "Everything Everywhere All at Once", "Doctor Strange in the Multiverse of Madness",
      "Into the Spider-Verse", "Coherence",
      "The part was originally written for Jackie Chan, and the directors rebuilt the whole film when Michelle Yeoh took it instead."),
    Q("film", 3, "Which monster's name blends the Japanese words for gorilla and whale?",
      "Godzilla", "Mothra", "King Kong", "Rodan",
      "Gojira, from gorira and kujira -- and the 1954 original is an entirely undisguised allegory about nuclear testing."),
    Q("film", 3, "Which country's film industry is nicknamed Nollywood?",
      "Nigeria", "Nepal", "New Zealand", "Norway",
      "It grew out of the direct-to-video boom of the 1990s, and its breakthrough hit, Living in Bondage, was sold on cassette."),
    Q("film", 3, "Which 2008 Best Picture winner was shot largely on the streets of Mumbai?",
      "Slumdog Millionaire", "The King's Speech", "Gandhi", "The Last King of Scotland",
      "Danny Boyle used small digital cameras to work unnoticed in real streets, and put the child actors' fees into trust funds."),
    Q("film", 3, "Which 1937 release was the first feature-length animated film in colour with sound?",
      "Snow White and the Seven Dwarfs", "Fantasia", "Pinocchio", "Gulliver's Travels",
      "The industry called it Disney's Folly the entire time it was in production, and it out-earned everything else released the following year."),
    Q("film", 3, "Which series about a chess prodigy sent chess-set sales through the roof in 2020?",
      "The Queen's Gambit", "Mindhunter", "Unorthodox", "The Serpent",
      "Garry Kasparov consulted on it, and every board position shown in the series is a real, playable one."),

    # ---------------- difficulty 4 ----------------
    Q("film", 4, "Which cinematographer shot Sicario, Blade Runner 2049 and 1917?",
      "Roger Deakins", "Emmanuel Lubezki", "Greig Fraser", "Hoyte van Hoytema",
      "He was nominated thirteen times before finally winning, for Blade Runner 2049, then won again two years later."),
    Q("film", 4, "Which 2014 film about a Broadway comeback is cut to look like a single continuous take?",
      "Birdman", "Rope", "Victoria", "Russian Ark",
      "Victoria and Russian Ark actually were single takes; this one is stitched together out of very long ones."),
    Q("film", 4, "Which Japanese director shot most of his films from a low position, at the eye-line of somebody kneeling?",
      "Yasujiro Ozu", "Kenji Mizoguchi", "Mikio Naruse", "Masaki Kobayashi",
      "The tatami shot, about three feet off the floor, which puts the viewer in the room as a guest rather than an observer."),
    Q("film", 4, "What is the Wilhelm scream?",
      "A stock sound effect of a man yelling", "A camera move", "A type of edit", "A lighting rig",
      "Recorded in 1951 and dropped into hundreds of films since as an in-joke between sound editors, most audibly all over Star Wars."),
    Q("film", 4, "In film-making, what is a MacGuffin?",
      "A plot device that motivates the characters but does not matter in itself",
      "A hidden camera trick", "A cameo by the director", "A deliberately unresolved subplot",
      "Hitchcock popularised the term and delighted in pointing out that the less the audience is told about it, the better it works."),
    Q("film", 4, "Which shot warps the background by zooming in one direction while the camera tracks the other way?",
      "The dolly zoom", "The whip pan", "The crash zoom", "The Dutch angle",
      "Invented for Vertigo, then reused so memorably in Jaws that half the industry now calls it the Jaws shot."),
    Q("film", 4, "Which studio's logo is a mountain ringed with stars?",
      "Paramount", "Universal", "Columbia", "RKO",
      "The stars in the original stood one apiece for the contract players the studio had on its books at the time."),
    Q("film", 4, "Which British series is set in a Yorkshire valley and follows a police sergeant called Catherine Cawood?",
      "Happy Valley", "Broadchurch", "Vera", "Unforgotten",
      "The title is what the local police were said to call the area, and it was nothing to do with the scenery."),
    Q("film", 4, "Which 1968 rating system replaced Hollywood's old production code?",
      "The MPAA ratings", "The Hays Code", "The Legion of Decency list", "The Breen Office system",
      "The Hays Code was the thing being replaced -- it had governed what American films could show since the 1930s and had become unenforceable."),
    Q("film", 4, "Which director's films are usually shot in Academy ratio and feature Bill Murray?",
      "Wes Anderson", "Noah Baumbach", "Spike Jonze", "Sofia Coppola",
      "Murray has appeared in almost every one of his films since Rushmore, occasionally for a single line."),
    N("film", 4, "For roughly how many minutes is Anthony Hopkins on screen in The Silence of the Lambs?",
      16, "minutes",
      "About a quarter of an hour of screen time won Best Actor, which remains one of the shortest performances ever to take the award."),
    N("film", 4, "In what year was the first Academy Awards ceremony held?",
      1929, "the year",
      "It lasted fifteen minutes, the winners had been announced three months earlier, and the tickets cost five dollars."),
    N("film", 4, "How many episodes of Fawlty Towers were made in total?",
      12, "episodes",
      "Two series of six, six years apart, and Cleese has turned down every offer to make more of them since."),

    # ---------------- difficulty 5 ----------------
    Q("film", 5, "Which 1927 film broke the silent era with synchronised singing and a few spoken lines?",
      "The Jazz Singer", "Don Juan", "Steamboat Willie", "The Broadway Melody",
      "Lights of New York, a year later, was the first feature that talked the whole way through -- this one only talks in patches."),
    Q("film", 5, "Which 1995 movement was launched with a manifesto called the Vow of Chastity?",
      "Dogme 95", "The French New Wave", "Italian Neorealism", "The New German Cinema",
      "No props, no added lighting, no credited director; von Trier and Vinterberg reportedly drew up the whole set of rules in under an hour."),
    Q("film", 5, "Which film topped the Sight and Sound critics' poll for fifty years?",
      "Citizen Kane", "Vertigo", "The Rules of the Game", "Bicycle Thieves",
      "Vertigo finally displaced it in 2012, and Jeanne Dielman displaced Vertigo a decade after that."),
    Q("film", 5, "Which blacklisted screenwriter won two Academy Awards under names that were not his own?",
      "Dalton Trumbo", "Elia Kazan", "Carl Foreman", "Ring Lardner Jr",
      "Roman Holiday went out under a friend's name and The Brave One under an invented one; the credits were put right decades later."),
    Q("film", 5, "What did the Kuleshov effect demonstrate?",
      "The same shot of a face reads differently depending on what follows it",
      "Colour shifts caused by different film stocks",
      "Tension created by an unresolved musical chord",
      "A camera move that reveals something hidden in frame",
      "He cut one neutral expression against a bowl of soup, a coffin and a woman, and audiences praised the actor's extraordinary range."),
]
