# -*- coding: utf-8 -*-
"""Film and television: landmark pictures, the Oscars, British and American TV, animation, world cinema, craft and the business."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [
    # ---- difficulty 1 ----
    Q("film", 1, "Which 1997 James Cameron film ends with a liner sinking in the North Atlantic?",
      "Titanic", "The Poseidon Adventure", "A Night to Remember", "Master and Commander",
      "Cameron dived to the real wreck in 1995 and the footage he brought back opens the film."),
    Q("film", 1, "Which cartoon character made his debut in the 1928 short Steamboat Willie?",
      "Mickey Mouse", "Donald Duck", "Bugs Bunny", "Felix the Cat",
      "Walt Disney supplied the squeaky voice himself for the first two decades."),
    Q("film", 1, "In The Sound of Music, which country do the von Trapps flee?",
      "Austria", "Switzerland", "Germany", "Hungary",
      "They walk over the mountains towards Switzerland, which from Salzburg would have led them into Germany."),
    Q("film", 1, "In which Spielberg film does a boy cycle past the moon with an alien in the basket?",
      "E.T. the Extra-Terrestrial", "Close Encounters of the Third Kind", "Flight of the Navigator", "The BFG",
      "That silhouette became the logo of Spielberg's production company, Amblin."),
    Q("film", 1, "Which BBC series follows a time traveller who pilots a police box?",
      "Doctor Who", "Blake's 7", "Quantum Leap", "Sapphire and Steel",
      "The police box was a 1963 disguise the ship then got permanently stuck in."),
    Q("film", 1, "Which actor plays Indiana Jones?",
      "Harrison Ford", "Kurt Russell", "Tom Selleck", "Sam Neill",
      "Selleck was cast first, but CBS would not release him from Magnum P.I."),
    Q("film", 1, "Which Disney film follows a young cub named Simba who flees his uncle Scar?",
      "The Lion King", "The Jungle Book", "Tarzan", "Brother Bear",
      "The plot borrows the shape of Hamlet, murderous uncle and haunting father included."),
    Q("film", 1, "Which film series is set largely at a school called Hogwarts?",
      "Harry Potter", "His Dark Materials", "Percy Jackson", "The Chronicles of Narnia",
      "Eight films from seven books, all shot in Britain under a rule that the cast stay British."),
    Q("film", 1, "Which comedy team made Life of Brian?",
      "Monty Python", "The Goodies", "Beyond the Fringe", "The Two Ronnies",
      "EMI pulled out days before shooting and George Harrison put up the money instead."),
    Q("film", 1, "Which 1985 film uses a DeLorean as a time machine?",
      "Back to the Future", "Time Bandits", "Bill and Ted's Excellent Adventure", "Time After Time",
      "The car was chosen because its gullwing doors could pass for a spacecraft."),
    Q("film", 1, "Which sitcom's characters meet at a coffee house called Central Perk?",
      "Friends", "Mad About You", "How I Met Your Mother", "Will and Grace",
      "The orange sofa was dug out of the Warner Bros basement and never replaced."),
    Q("film", 1, "Which 1993 film features cloned dinosaurs on a Costa Rican island?",
      "Jurassic Park", "King Kong", "Congo", "Anaconda",
      "Most of the dinosaur screen time is animatronic puppetry, not computer animation."),
    Q("film", 1, "Which DreamWorks animation stars an ogre living in a swamp?",
      "Shrek", "Monsters vs Aliens", "Madagascar", "Antz",
      "It won the first Academy Award for Best Animated Feature, handed out in 2002."),
    Q("film", 1, "Which animated series is set in Springfield and follows the family of Homer and Bart?",
      "The Simpsons", "King of the Hill", "Family Guy", "Futurama",
      "It started as filler shorts on The Tracey Ullman Show in 1987."),

    # ---- difficulty 2 ----
    Q("film", 2, "In which 1942 film does Rick Blaine run a nightclub in Morocco?",
      "Casablanca", "The Maltese Falcon", "To Have and Have Not", "Algiers",
      "The script was still being rewritten during shooting, so the cast did not know who would board the plane."),
    Q("film", 2, "Who composed the score for the first Star Wars film?",
      "John Williams", "Jerry Goldsmith", "Alan Silvestri", "Elmer Bernstein",
      "Lucas wanted existing classical recordings; Spielberg talked him into an original symphonic score."),
    Q("film", 2, "In Fawlty Towers, which country is Manuel from?",
      "Spain", "Portugal", "Italy", "Greece",
      "The Spanish dub made him Italian, which conveniently moved the joke's target."),
    Q("film", 2, "Which actor played Del Boy in Only Fools and Horses?",
      "David Jason", "Nicholas Lyndhurst", "Ricky Tomlinson", "Warren Mitchell",
      "Lyndhurst played his younger brother Rodney, though the two actors are about two decades apart."),
    Q("film", 2, "Which comedy series starred Rowan Atkinson as a schemer in four different historical eras?",
      "Blackadder", "Yes Minister", "Up Pompeii", "Chelmsford 123",
      "Ben Elton joined as co-writer from the second series, and the character stopped being the idiot."),
    Q("film", 2, "Who directed Schindler's List?",
      "Steven Spielberg", "Sydney Pollack", "Alan Pakula", "Barry Levinson",
      "He refused a fee, calling it blood money, and shot almost the whole film in black and white."),
    Q("film", 2, "Hindi cinema's studio industry is centred on which city?",
      "Mumbai", "Delhi", "Chennai", "Hyderabad",
      "Tamil cinema centres on Chennai and Telugu on Hyderabad, each with its own star system."),
    Q("film", 2, "Which actor plays the title machine in The Terminator?",
      "Arnold Schwarzenegger", "Dolph Lundgren", "Michael Biehn", "Jesse Ventura",
      "Lance Henriksen was the earlier choice and ended up playing the detective instead."),
    Q("film", 2, "Which Pixar film follows a rat with a talent for cooking?",
      "Ratatouille", "A Bug's Life", "Monsters, Inc.", "Brave",
      "Thomas Keller devised the layered vegetable dish that the critic is finally served."),
    Q("film", 2, "Which television drama is set in the Seven Kingdoms of Westeros?",
      "Game of Thrones", "The Witcher", "Rome", "Vikings",
      "Dubrovnik and Northern Ireland both built tourist industries on the locations."),
    Q("film", 2, "Which series follows Don Draper through a Madison Avenue advertising agency?",
      "Mad Men", "Halt and Catch Fire", "The Hour", "Rubicon",
      "Matthew Weiner wrote the pilot before joining The Sopranos, then sat on it for years."),
]
