# -*- coding: utf-8 -*-
"""Food and drink: world cuisines, technique, ingredients, protected names, drink and food history."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [
    Q("food", 1, "Which meat is in a traditional shepherd's pie?",
      "Lamb", "Beef", "Pork", "Veal",
      "Made with beef it is properly a cottage pie -- the shepherd minds sheep."),
    Q("food", 1, "Which fruit is harvested by flooding the bogs it grows in?",
      "Cranberries", "Blueberries", "Lingonberries", "Elderberries",
      "The berries hold air pockets, so they float up and can be corralled off the water."),
    Q("food", 1, "Hamantaschen are eaten at which festival?",
      "Purim", "Hanukkah", "Sukkot", "Rosh Hashanah",
      "The three corners are read as Haman's hat, or his ears, or his pockets."),
    Q("food", 1, "A tagine is a stew and also what?",
      "An earthenware pot", "A spice blend", "A flat griddle", "A serving basket",
      "The conical lid returns condensed steam to the food, so very little liquid is needed."),
    Q("food", 1, "The failure of which crop caused the Great Irish Famine?",
      "The potato", "Wheat", "Oats", "Barley",
      "One variety, the lumper, was planted almost everywhere, so the blight met no resistance."),
    Q("food", 1, "Which cocktail is classically gin and dry vermouth, stirred?",
      "The martini", "The gimlet", "The Manhattan", "The Bramble",
      "The ratio drifted from roughly 2:1 in the 1900s to almost neat gin by the 1950s."),
    Q("food", 1, "Which fruit is the base of guacamole?",
      "Avocado", "Tomatillo", "Chayote", "Papaya",
      "The Nahuatl 'ahuacamolli' means avocado sauce, which is exactly what it still is."),
    Q("food", 1, "Churning which dairy product makes butter?",
      "Cream", "Whey", "Skimmed milk", "Curds",
      "Churning tears the fat globules' membranes so the fat clumps and the liquid runs out."),
    Q("food", 1, "Pho is the national noodle soup of which country?",
      "Vietnam", "Cambodia", "Laos", "Thailand",
      "The broth wants charred ginger and onion with star anise and cassia, simmered for hours."),
    Q("food", 1, "Raisins are the dried form of which fruit?",
      "Grapes", "Plums", "Figs", "Dates",
      "Sultanas and currants are grapes too -- different varieties, dried the same way."),
    Q("food", 1, "Which vegetable is layered through a classic moussaka?",
      "Aubergine", "Courgette", "Fennel", "Leek",
      "The custardy top is a bechamel, added to the Greek version in the 1920s by Tselementes."),
    Q("food", 1, "Which spirit is the base of a Bloody Mary?",
      "Vodka", "Gin", "Tequila", "White rum",
      "Swap in tequila and it becomes a Bloody Maria; use clam juice and it is a Caesar."),
    Q("food", 1, "Which sauce is pounded from basil, garlic, cheese, oil and pine nuts?",
      "Pesto", "Salsa verde", "Chermoula", "Gremolata",
      "The name comes from 'pestare', to pound: the mortar is the point, not the basil."),
    Q("food", 1, "Tzatziki is built on which dairy base?",
      "Yoghurt", "Soured cream", "Curd cheese", "Buttermilk",
      "Straining it first is what stops the grated cucumber turning the bowl to soup."),
    Q("food", 1, "Which cheese tops a margherita pizza?",
      "Mozzarella", "Provolone", "Scamorza", "Fontina",
      "The 1889 story has it dressed in tomato, basil and white cheese for the Italian flag."),
    Q("food", 2, "Marmite is a by-product of which industry?",
      "Brewing", "Cheesemaking", "Sugar refining", "Flour milling",
      "Spent brewer's yeast was waste until chemists worked out how to concentrate it."),
    Q("food", 2, "Which Scottish sweet of sugar, butter and condensed milk sets grainy and brittle?",
      "Tablet", "Macaroon bar", "Puff candy", "Butterscotch",
      "The sugar is deliberately allowed to crystallise, which is the one thing fudge avoids."),
    Q("food", 2, "Which cut is the signature of Central Texas barbecue?",
      "Brisket", "Pork shoulder", "Beef short rib", "Spare ribs",
      "It came off the German and Czech butchers' meat markets, sold by weight on butcher paper."),
    Q("food", 2, "Which ingredient does traditional Texas chili leave out?",
      "Beans", "Cumin", "Dried chillies", "Beef suet",
      "The chili queens sold it in San Antonio's plazas; the bean question still ends friendships."),
    Q("food", 2, "Boston baked beans are traditionally sweetened with what?",
      "Molasses", "Maple syrup", "Brown sugar", "Honey",
      "Molasses arrived on the rum trade, which is also how the city came to be Beantown."),
    Q("food", 2, "Sufganiyot, eaten in Israel at Hanukkah, are what?",
      "Jam doughnuts", "Potato pancakes", "Sesame biscuits", "Honey fritters",
      "Anything fried marks the oil that lasted eight nights; the diaspora went for latkes instead."),
    Q("food", 2, "At the Passover seder, which dish stands for the mortar used by the slaves?",
      "Charoset", "Maror", "Karpas", "Chazeret",
      "Apples, nuts and wine in the Ashkenazi version; dates and figs in many Sephardi ones."),
    Q("food", 2, "What is done to a bagel before it goes in the oven?",
      "It is boiled", "It is steamed", "It is fried", "It is frozen",
      "The brief boil gelatinises the crust's starch, and that is where the chew and shine come from."),
    Q("food", 2, "For a fish to be kosher it must have fins and what else?",
      "Scales", "A backbone", "Gills", "A swim bladder",
      "That rules out catfish, eel, monkfish and every shellfish on the menu."),
    Q("food", 2, "Fesenjan is thickened with ground walnuts and soured with what?",
      "Pomegranate molasses", "Tamarind paste", "Dried barberries", "Verjuice",
      "The long simmer turns walnut oil and fruit acid into a near-black gravy."),
]
