# -*- coding: utf-8 -*-
"""General knowledge bank A: measures and time, the body, materials, myth, transport,
money, animals, flags, famous firsts, and games."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [

    # ---- measures, numbers, calendar, time, zodiac, cards, chess, dice ----
    Q("general", 1, "How many cards are in a standard deck with the jokers removed?",
      "52", "48", "54", "60",
      "Four suits of thirteen. The jokers were a late American addition, invented for euchre."),
    Q("general", 1, "In chess, which piece may move only diagonally?",
      "The bishop", "The rook", "The knight", "The queen",
      "A bishop is stuck on the colour it starts on, which is why the pair covers the board between them."),
    Q("general", 1, "How many degrees are there in a right angle?",
      "90", "45", "60", "180",
      "The 360-degree circle is Babylonian, built on their base-60 counting rather than anything about circles."),
    Q("general", 2, "Which zodiac sign is depicted as an archer?",
      "Sagittarius", "Aquarius", "Capricorn", "Leo",
      "He is drawn as a centaur drawing a bow, which is why the sign's glyph is a simple arrow."),
    Q("general", 2, "Pure gold is described as how many carats?",
      "24", "18", "22", "32",
      "The scale is in 24ths, so 18 carat is 18 parts gold to 6 parts other metal."),
    Q("general", 2, "On a standard die, which number sits on the face opposite the five?",
      "Two", "One", "Three", "Six",
      "Opposite faces on a standard die always add up to seven, which is a quick way to spot a fake."),
    Q("general", 3, "Which chess move shifts two of your own pieces in a single turn?",
      "Castling", "En passant", "Promotion", "Fianchetto",
      "It is the only such move, and it was invented in the 1500s to speed the opening up."),
    Q("general", 3, "In the abbreviation GMT, what does the M stand for?",
      "Mean", "Meridian", "Median", "Metric",
      "Mean, because true solar time runs fast or slow by up to sixteen minutes across the year."),
    Q("general", 3, "How many feet make one fathom?",
      "Six", "Three", "Eight", "Ten",
      "Roughly the span of a sailor's outstretched arms, which is how sounding line was measured out."),
    N("general", 3, "How many seconds are there in a week?",
      604800, "seconds",
      "Worth knowing because it turns up constantly in code as a cache or cookie lifetime."),
    Q("general", 4, "A century year is a leap year only if it divides exactly by which number?",
      "400", "100", "200", "800",
      "That is why 1900 was not a leap year but 2000 was, trimming the calendar by three days per 400 years."),
    Q("general", 4, "A nautical mile equals one minute of arc of what?",
      "Latitude", "Longitude", "Declination", "Right ascension",
      "Sixty to a degree, which is why a chart's side scale doubles as its distance ruler."),
    Q("general", 4, "Which two jacks in a standard deck are drawn in profile, showing a single eye?",
      "Spades and hearts", "Clubs and diamonds", "Hearts and diamonds", "Spades and clubs",
      "The king of diamonds is one-eyed too, all of them side effects of centuries of sloppy copying."),
    Q("general", 5, "The word calendar comes from the Latin kalendae, which named what?",
      "The first day of the month", "The day of the full moon",
      "The last day of the year", "The monthly market day",
      "Debts came due on the kalends, so the account book was literally a calendarium."),
    Q("general", 5, "In the Latin-suited decks of Spain and Italy, the suit of coins corresponds to which French suit?",
      "Diamonds", "Hearts", "Spades", "Clubs",
      "Swords became spades and cups became hearts, so the four suits survived translation more or less intact."),

    # ---- the human body, medicine, first aid, the senses ----
    Q("general", 1, "What is the largest organ of the human body?",
      "The skin", "The liver", "The brain", "The lungs",
      "Around two square metres of it, and it renews itself roughly every month."),
    Q("general", 2, "Which vitamin does the skin manufacture when exposed to sunlight?",
      "Vitamin D", "Vitamin A", "Vitamin C", "Vitamin K",
      "It behaves more like a hormone than a vitamin, which is why northern winters cause such widespread shortfall."),
    Q("general", 2, "What is the anatomical name for the kneecap?",
      "The patella", "The scapula", "The sternum", "The tibia",
      "It is a sesamoid bone, grown inside a tendon, and it works as a pulley for the thigh muscle."),
    Q("general", 2, "What does the abbreviation CPR stand for?",
      "Cardiopulmonary resuscitation", "Cardiac pulse recovery",
      "Chest pressure resuscitation", "Circulatory pressure relief",
      "Modern guidance is compressions at about 110 a minute, roughly the tempo of Stayin' Alive."),
    N("general", 3, "How many bones are there in the adult human body?",
      206, "bones",
      "Babies start with around 270 -- several fuse during childhood, notably in the skull and the spine."),
    Q("general", 3, "Which is the smallest bone in the human body?",
      "The stapes", "The malleus", "The incus", "The lacrimal bone",
      "It is the stirrup of the middle ear, about three millimetres long, and it drives the inner ear fluid."),
    Q("general", 3, "Which blood group is the universal donor for red cell transfusions?",
      "O negative", "O positive", "AB negative", "A negative",
      "The reverse holds for plasma, where AB is the universal donor -- the antigens and antibodies swap roles."),
    Q("general", 3, "Which of the basic tastes was the last to be accepted in the West?",
      "Umami", "Sour", "Bitter", "Salt",
      "Identified in Tokyo in 1908 from kombu stock, but the receptor was not confirmed until 2000."),
    Q("general", 4, "What is the medical name for a nosebleed?",
      "Epistaxis", "Epiphora", "Halitosis", "Rhinitis",
      "Most start in a shallow web of vessels just inside the nostril, which is why pinching the soft part works."),
    Q("general", 4, "In the first-aid mnemonic RICE for a sprain, what does the R stand for?",
      "Rest", "Rub", "Restrict", "Rotate",
      "Rest, ice, compression, elevation -- though current advice pushes gentle movement sooner than it used to."),
    Q("general", 4, "Which structures of the inner ear give us our sense of balance?",
      "The semicircular canals", "The cochlea", "The ossicles", "The eustachian tubes",
      "Three loops set at right angles, so fluid sloshing in them reports rotation in all three planes."),
    N("general", 4, "How many teeth are there in a complete set of adult human teeth?",
      32, "teeth",
      "Eight per quadrant, wisdom teeth included -- children make do with twenty milk teeth."),
    Q("general", 5, "Which bone in the human body joins to no other bone?",
      "The hyoid", "The sternum", "The patella", "The coccyx",
      "It floats in the throat on muscle alone, anchoring the tongue, and its fracture is a classic sign of strangling."),
    Q("general", 5, "In current UK first-aid guidance, what is the Heimlich manoeuvre usually called?",
      "Abdominal thrusts", "Chest compressions", "Back slaps", "Rescue breaths",
      "UK protocol asks for five back blows first, then five thrusts, alternating until the airway clears."),

    # ---- everyday materials, household chemistry, colours, tools ----
    Q("general", 1, "Table salt is which chemical compound?",
      "Sodium chloride", "Sodium carbonate", "Potassium chloride", "Calcium chloride",
      "Both halves are lethal alone -- sodium metal explodes in water and chlorine is a war gas."),
    Q("general", 2, "Which gas makes up roughly 78 per cent of the Earth's atmosphere?",
      "Nitrogen", "Oxygen", "Argon", "Carbon dioxide",
      "It is almost inert, which is why crisp packets and wine casks are flushed with it."),
    Q("general", 2, "Which acid gives vinegar its sourness?",
      "Acetic acid", "Citric acid", "Lactic acid", "Formic acid",
      "Table vinegar is about five per cent of it, produced when bacteria oxidise the alcohol in wine or cider."),
    Q("general", 2, "Which unit measures electrical resistance?",
      "The ohm", "The volt", "The ampere", "The farad",
      "Its symbol is the Greek omega simply because the letter O would have been mistaken for a zero."),
    Q("general", 3, "Colour printing mixes which three inks, plus black?",
      "Cyan, magenta and yellow", "Red, green and blue",
      "Red, yellow and blue", "Cyan, violet and yellow",
      "They are subtractive: each ink removes one of the additive primaries from the light bouncing off the page."),
    Q("general", 3, "Which mineral sits at 1 on the Mohs hardness scale, the softest point?",
      "Talc", "Gypsum", "Calcite", "Feldspar",
      "The scale is only an ordering, not a measure -- diamond at 10 is many times harder than corundum at 9."),
    Q("general", 3, "Stainless steel resists rust thanks to the addition of which element?",
      "Chromium", "Nickel", "Zinc", "Manganese",
      "It forms an invisible oxide skin that seals the surface and reseals itself when scratched."),
    Q("general", 4, "On a pencil, what do the letters HB stand for?",
      "Hard black", "Heavy black", "Half black", "High bond",
      "The scale runs from 9H to 9B, and the American number 2 pencil is the same grade as HB."),
    Q("general", 4, "Before synthetic pigments, ultramarine blue was ground from which stone?",
      "Lapis lazuli", "Malachite", "Azurite", "Turquoise",
      "It came overland from Afghanistan and cost more than gold, so painters saved it for the Virgin's robe."),
    Q("general", 4, "Mixing household bleach with which other product releases chloramine gas?",
      "Ammonia", "Vinegar", "Washing-up liquid", "Baking soda",
      "Many glass cleaners are ammonia-based, which is how people gas themselves cleaning a bathroom."),
    Q("general", 5, "Which element is used to colour fireworks green?",
      "Barium", "Strontium", "Copper", "Lithium",
      "Strontium burns red and copper burns blue -- the same flame tests used to identify metals in a lab."),
    Q("general", 5, "Aqua regia, which dissolves gold, is a mixture of which two acids?",
      "Nitric and hydrochloric", "Sulphuric and nitric",
      "Hydrochloric and sulphuric", "Nitric and phosphoric",
      "De Hevesy dissolved two Nobel medals in it in 1940 to hide them from the Nazis, then recovered the gold."),

    # ---- myth and legend ----
    Q("general", 1, "Which Norse god carries the hammer Mjolnir?",
      "Thor", "Odin", "Loki", "Baldr",
      "The hammer was forged short in the handle because Loki, as a fly, kept pestering the smiths."),
    Q("general", 2, "In Greek myth, which hero killed the Minotaur?",
      "Theseus", "Perseus", "Jason", "Bellerophon",
      "He found his way out on Ariadne's thread, then sailed home and forgot to change his black sails."),
    Q("general", 2, "What is the name of King Arthur's sword?",
      "Excalibur", "Durendal", "Gram", "Tizona",
      "Older tellings prize the scabbard more than the blade, since it stopped the wearer bleeding."),
    Q("general", 2, "In Egyptian myth, which god is shown with the head of a jackal?",
      "Anubis", "Horus", "Set", "Sobek",
      "Jackals scavenged desert graves, so the animal that threatened the dead was made their guardian instead."),
    Q("general", 3, "In Norse myth, what is the burning rainbow bridge to Asgard called?",
      "Bifrost", "Gjallarbru", "Valgrind", "Ginnungagap",
      "It is fated to shatter under the weight of the riders crossing it at Ragnarok."),
    Q("general", 3, "In Egyptian myth, which god was murdered by his brother and restored by his wife?",
      "Osiris", "Ra", "Ptah", "Amun",
      "Isis reassembled him long enough to conceive Horus, after which he ruled the dead rather than the living."),
    Q("general", 3, "Who cut the Gordian knot?",
      "Alexander the Great", "Julius Caesar", "Xerxes", "Hannibal",
      "The oracle promised Asia to whoever untied it -- he simply declined to accept the terms of the puzzle."),
    Q("general", 4, "In Arthurian legend, which enchantress is usually cast as Arthur's half-sister?",
      "Morgan le Fay", "Nimue", "Elaine", "Guinevere",
      "She begins as a healer who carries him to Avalon and only hardens into a villain in later retellings."),
    Q("general", 4, "In Norse myth, which wolf kills Odin at Ragnarok?",
      "Fenrir", "Garm", "Skoll", "Hati",
      "The gods bound him with a ribbon made of impossible things, and Tyr lost a hand as the pledge."),
    Q("general", 4, "In Egyptian myth, which ibis-headed god served as scribe to the gods?",
      "Thoth", "Khnum", "Sobek", "Bes",
      "The Greeks matched him to Hermes, and the resulting hybrid gave us the word hermetic."),
    Q("general", 5, "In Arthurian legend, which knight is the son of Lancelot?",
      "Galahad", "Gawain", "Percival", "Bors",
      "He was written in late as the flawless one, since the earlier Grail hero Percival was too rough for the job."),
    Q("general", 5, "What is the name of Odin's spear?",
      "Gungnir", "Gram", "Tyrfing", "Laevateinn",
      "Oaths sworn on it could not be broken, and it never missed whatever it was thrown at."),

    # ---- transport: cars, planes, trains, ships, signs ----
    Q("general", 1, "Which car maker's badge is a prancing horse?",
      "Ferrari", "Lamborghini", "Maserati", "Alfa Romeo",
      "The horse came from a First World War fighter ace, and the yellow behind it is the colour of Modena."),
    Q("general", 2, "On a ship facing forward, which side is port?",
      "The left", "The right", "The front", "The rear",
      "It replaced larboard, which sounded far too much like starboard when shouted in a gale."),
    Q("general", 2, "Which car maker's badge is four interlocking rings?",
      "Audi", "BMW", "Volvo", "Mazda",
      "One ring for each of the four firms that merged into Auto Union in 1932."),
    Q("general", 2, "The Beaufort scale measures the strength of what?",
      "Wind speed", "Wave height", "Rainfall", "Air pressure",
      "It was defined by what a sailor could see -- smoke, sails, spray -- long before anemometers were standard."),
    Q("general", 3, "In the NATO phonetic alphabet, which word stands for the letter J?",
      "Juliett", "Jupiter", "Jackal", "Jericho",
      "Spelt with two Ts so French speakers would not read the final T as silent."),
    Q("general", 3, "The distress call mayday comes from a French phrase meaning what?",
      "Come and help me", "Save our souls", "We are sinking", "Send assistance",
      "Chosen in the 1920s at Croydon aerodrome, where much of the traffic was flying to and from Paris."),
    Q("general", 3, "What does the RMS in RMS Titanic stand for?",
      "Royal Mail Ship", "Royal Navy Ship", "Registered Merchant Ship", "Regular Mail Service",
      "Carrying the mails paid a subsidy and demanded speed, which is part of why she was pushed so hard."),
    Q("general", 3, "On British road signs, which shape is used for orders that must be obeyed?",
      "Circles", "Triangles", "Rectangles", "Diamonds",
      "Triangles warn and rectangles inform, so shape alone tells you the force of the sign at a glance."),
    Q("general", 4, "What does the Plimsoll line on a ship's hull mark?",
      "The maximum safe loading depth", "The depth of the keel",
      "The height of the main deck", "The length at the waterline",
      "Samuel Plimsoll pushed it through Parliament to stop owners overloading and insuring coffin ships."),
    Q("general", 4, "Which US airport uses the code ORD?",
      "Chicago O'Hare", "Orlando International", "Ontario International", "Portland International",
      "The letters survive from Orchard Field, the aircraft factory strip the airport was built on."),
    N("general", 4, "Standard railway gauge measures how many millimetres between the rails?",
      1435, "millimetres",
      "That is 4 feet 8 and a half inches, a figure inherited from horse-drawn colliery wagons in the north of England."),
    Q("general", 5, "Which ship completed the first circumnavigation of the globe, in 1522?",
      "The Victoria", "The Trinidad", "The San Antonio", "The Concepcion",
      "One of five that set out, she came home with eighteen men aboard, and Magellan was not among them."),

    # ---- money, currencies, banknotes, economics ----
    Q("general", 1, "What is the currency of Switzerland?",
      "The Swiss franc", "The euro", "The krone", "The mark",
      "Its code CHF stands for Confoederatio Helvetica, the Latin name used to avoid choosing between four languages."),
    Q("general", 2, "Whose portrait appears on the US hundred dollar bill?",
      "Benjamin Franklin", "Thomas Jefferson", "Ulysses S. Grant", "Andrew Jackson",
      "He is one of only two non-presidents on current US notes, the other being Hamilton on the ten."),
    Q("general", 2, "What is the term for a sustained fall in the general level of prices?",
      "Deflation", "Recession", "Stagnation", "Devaluation",
      "It is feared more than mild inflation because buyers wait for lower prices and demand keeps sinking."),
    Q("general", 3, "Before decimalisation, how many shillings made up a pound sterling?",
      "20", "12", "16", "24",
      "Twelve pence to the shilling gave 240 pence to the pound, a number that divides very neatly."),
    Q("general", 3, "The Gini coefficient is a measure of what?",
      "Inequality", "Inflation", "Unemployment", "Productivity",
      "Zero means everyone holds the same, one means a single household holds the lot -- real economies sit near 0.3."),
    Q("general", 3, "Which country was the first to use paper money?",
      "China", "Italy", "Sweden", "India",
      "Tang and Song merchants used it centuries before Sweden issued the first European banknotes in 1661."),
    Q("general", 4, "One hundred agorot make up which currency unit?",
      "The shekel", "The dinar", "The dirham", "The riyal",
      "The name is biblical, revived in 1980 when it replaced the Israeli lira."),
    Q("general", 4, "The reverse of every euro banknote carries a picture of what?",
      "A bridge", "A window", "A doorway", "A monument",
      "All fictional, so no member state could claim its own landmark -- though Holland later built some for real."),
    Q("general", 4, "Which US coin carries a portrait facing to the right?",
      "The cent", "The dime", "The quarter", "The nickel",
      "Every other circulating coin looks left, an accident of the engraver copying a plaque of Lincoln."),
    Q("general", 5, "Which economic law is summed up as bad money drives out good?",
      "Gresham's law", "Say's law", "Okun's law", "Wagner's law",
      "If two coins are legal at the same face value, people spend the debased one and hoard the heavier one."),
    N("general", 5, "Under the Bretton Woods system, gold was fixed at how many US dollars per ounce?",
      35, "dollars",
      "Set in 1934 and held until Nixon closed the gold window in 1971, ending convertibility for good."),

    # ---- animals ----
    Q("general", 1, "Which is the fastest land animal?",
      "The cheetah", "The pronghorn", "The greyhound", "The lion",
      "It can only hold the pace for about half a minute before overheating forces it to stop."),
    Q("general", 2, "What is the collective noun for a group of lions?",
      "A pride", "A pack", "A troop", "A herd",
      "It is the only truly social cat, and the related females do nearly all of the hunting."),
    Q("general", 2, "Which is the largest living bird?",
      "The ostrich", "The emu", "The albatross", "The cassowary",
      "Its eye is bigger than its brain, and its egg is the largest single cell produced by any living animal."),
    Q("general", 3, "What is the collective noun for a group of owls?",
      "A parliament", "A congress", "A senate", "A council",
      "The term is literary rather than ancient, popularised by C. S. Lewis in the Narnia books."),
    Q("general", 3, "What is a group of geese in flight called?",
      "A skein", "A gaggle", "A clutch", "A covey",
      "On the ground the same birds are a gaggle, so the noun changes the moment they take off."),
    Q("general", 3, "Which animal was the first to be domesticated by humans?",
      "The dog", "The sheep", "The goat", "The cow",
      "It happened among hunter-gatherers well before farming, so wolves were tamed before any crop was sown."),
    Q("general", 4, "What is the collective noun for a group of ferrets?",
      "A business", "A commotion", "A rabble", "A shuffle",
      "It is a worn-down form of busyness, which is a fair description of what they actually do."),
    Q("general", 5, "The domestic cat is descended from which wild animal?",
      "The African wildcat", "The European wildcat", "The sand cat", "The jungle cat",
      "It moved in on grain stores in the Near East, so cats effectively domesticated themselves."),

    # ---- flags, symbols, heraldry, anthems ----
    Q("general", 1, "Which country's flag is a plain red disc on a white field?",
      "Japan", "Bangladesh", "South Korea", "Laos",
      "It was only made the legal national flag in 1999, having flown unofficially for well over a century."),
    Q("general", 2, "How many stripes are there on the flag of the United States?",
      "13", "11", "12", "15",
      "One per founding colony. Stars were added for new states, but the stripes went back to thirteen in 1818."),
    Q("general", 2, "Which is the only national flag that is neither a rectangle nor a square?",
      "Nepal", "Bhutan", "Sri Lanka", "Switzerland",
      "Two stacked pennants, and its exact geometry is set out in the constitution as a construction diagram."),
    Q("general", 3, "In heraldry, what is the term for the tincture blue?",
      "Azure", "Vert", "Sable", "Purpure",
      "In black-and-white engraving it is shown as horizontal lines, one of a whole code of hatchings for colour."),
    Q("general", 3, "Which mythical creature is the national animal of Scotland?",
      "The unicorn", "The griffin", "The dragon", "The phoenix",
      "It is shown chained, because a free one was held to be far too dangerous to handle."),
    Q("general", 3, "Which tree appears on the flag of Lebanon?",
      "The cedar", "The olive", "The palm", "The oak",
      "The species is named for the country, and the biblical timber trade all but stripped the mountains bare."),
    Q("general", 4, "In heraldry, an animal described as rampant is doing what?",
      "Rearing on its hind legs", "Walking with one paw raised",
      "Lying down", "Standing on all fours",
      "Passant walks, couchant lies and statant stands, so the posture is a word in its own right."),
    Q("general", 4, "Which country's national flag includes an AK-47?",
      "Mozambique", "Angola", "Zimbabwe", "Cuba",
      "It sits with a hoe and a book, and parliament has repeatedly voted to keep it despite proposals to drop it."),
    Q("general", 4, "Advance Australia Fair became the Australian anthem in 1984, replacing which song?",
      "God Save the Queen", "Waltzing Matilda", "Song of Australia", "I Am Australian",
      "A national poll in 1977 chose it, and Waltzing Matilda came second by a comfortable margin."),
    Q("general", 5, "Which country claims the oldest continuously used national flag?",
      "Denmark", "Austria", "Scotland", "The Netherlands",
      "Legend has the Dannebrog falling from the sky during a battle in Estonia in 1219."),

    # ---- famous firsts and inventions ----
    Q("general", 1, "Who is generally credited with inventing the telephone?",
      "Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Samuel Morse",
      "He filed on the same day as Elisha Gray, and the two spent years in court over the difference of hours."),
    Q("general", 2, "Which brothers made the first sustained powered aeroplane flight?",
      "The Wright brothers", "The Montgolfier brothers",
      "The Lumiere brothers", "The Farman brothers",
      "The first hop covered 37 metres, less than the wingspan of a modern airliner."),
    Q("general", 3, "Who was the first woman in space?",
      "Valentina Tereshkova", "Svetlana Savitskaya", "Sally Ride", "Helen Sharman",
      "She flew in 1963, and no woman followed her into orbit for nineteen years."),
    Q("general", 3, "Which Soviet dog was the first animal to orbit the Earth?",
      "Laika", "Belka", "Strelka", "Zvezdochka",
      "She was a stray picked up in Moscow, and the craft was never designed to bring her back."),
    Q("general", 3, "Which country was the first to grant women the vote in national elections?",
      "New Zealand", "Finland", "Norway", "Australia",
      "In 1893, though women could not stand for its parliament for another twenty-six years."),
    N("general", 3, "In which year was the first iPhone released?",
      2007, "the year",
      "It shipped without an app store, copy and paste, or 3G -- all of which arrived in the following two years."),
    Q("general", 4, "Who first flew faster than the speed of sound in level flight?",
      "Chuck Yeager", "Scott Crossfield", "Howard Hughes", "Wiley Post",
      "He did it in 1947 with two broken ribs, having sawn off a broom handle to close the hatch."),
    Q("general", 4, "Which country issued the world's first adhesive postage stamp?",
      "The United Kingdom", "France", "The United States", "Switzerland",
      "Hence the odd convention that British stamps alone need carry no country name."),
    Q("general", 4, "Which game was the first commercially successful arcade video game?",
      "Pong", "Space Invaders", "Computer Space", "Breakout",
      "Its predecessor Computer Space flopped because players found the instructions impossible to follow."),
    Q("general", 5, "What was the first item ever sold on eBay?",
      "A broken laser pointer", "A used Walkman", "A signed baseball", "A Beanie Baby",
      "The buyer collected them deliberately, which is when the founder realised the site would work for anything."),
    Q("general", 5, "The first product scanned at a shop checkout with a barcode, in 1974, was a packet of what?",
      "Chewing gum", "Cigarettes", "Coffee", "Crisps",
      "It was chosen to prove the scanner could read a label too small to hold a printed price."),

    # ---- board games, card games, dominoes, darts, snooker, Scrabble ----
    Q("general", 1, "What is the highest score possible with three darts?",
      "180", "150", "170", "200",
      "The board's number order is designed so that missing a treble twenty drops you into a one or a five."),
    Q("general", 2, "In chess, what is it called when the player to move has no legal move but is not in check?",
      "Stalemate", "Checkmate", "Zugzwang", "Perpetual check",
      "It is a draw, which turns a lost position into a genuine defensive resource."),
    Q("general", 3, "In English Scrabble, which two letters are worth ten points?",
      "Q and Z", "J and X", "K and V", "X and Z",
      "The values came from counting letters on the front page of the New York Times."),
    Q("general", 3, "In snooker, how many points is the blue ball worth?",
      "Five", "Four", "Six", "Three",
      "It sits on the centre spot, which makes it the pivot of most positional play around the table."),
    Q("general", 3, "What is the maximum break in a standard frame of snooker?",
      "147", "140", "155", "167",
      "Fifteen reds each followed by a black, then the colours in order -- 155 is only possible after a free ball."),
    N("general", 4, "How many tiles are there in a standard double-six set of dominoes?",
      28, "tiles",
      "Every unordered pair from blank to six, doubles included, which is seven times eight halved."),
    N("general", 4, "How many tiles are there in a standard English Scrabble set?",
      100, "tiles",
      "Twelve of them are E and only one apiece for Q, Z, J, K and X."),
    Q("general", 4, "In bridge, what is a contract to win all thirteen tricks called?",
      "A grand slam", "A small slam", "A rubber", "A vulnerable game",
      "Winning twelve is a small slam, and the bonus gap between them is why the last trick matters so much."),
    Q("general", 5, "In Cluedo, a secret passage links the kitchen with which room?",
      "The study", "The library", "The lounge", "The conservatory",
      "The passages run corner to corner, so the lounge and conservatory are joined the same way."),
    Q("general", 5, "In darts, which score with three darts is known as bed and breakfast?",
      "26", "45", "33", "19",
      "From two and six, the old price of bed and breakfast -- it is what you get hitting 20, 5 and 1."),
]
