# -*- coding: utf-8 -*-
"""Political and human geography: capitals, borders, flags, languages, blocs, territories."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [

    # ---------------- difficulty 1 ----------------
    Q("geo", 1, "What is the capital of Australia?",
      "Canberra", "Sydney", "Melbourne", "Perth",
      "It was built from scratch after 1913 as a compromise between the two rival cities."),
    Q("geo", 1, "Which US state is nicknamed the Lone Star State?",
      "Texas", "Arizona", "Nevada", "Montana",
      "The single star comes from the flag of the short-lived republic that existed there from 1836."),
    Q("geo", 1, "What is the capital of Scotland?",
      "Edinburgh", "Glasgow", "Aberdeen", "Stirling",
      "Its parliament reconvened in 1999 after a gap of nearly three centuries."),
    Q("geo", 1, "Which country's flag is a plain red disc on a white field?",
      "Japan", "Bangladesh", "Palau", "South Korea",
      "Bangladesh puts a red disc on green, and Palau a yellow one on blue."),
    Q("geo", 1, "Which is the largest country in the world by area?",
      "Russia", "Canada", "China", "The United States",
      "It covers roughly an eighth of the world's inhabited land."),
    Q("geo", 1, "What is the official language of Brazil?",
      "Portuguese", "Spanish", "French", "Dutch",
      "The 1494 Treaty of Tordesillas handed Portugal everything east of a line through the Atlantic."),
    Q("geo", 1, "What is the capital of Egypt?",
      "Cairo", "Alexandria", "Giza", "Luxor",
      "The Fatimids founded it in 969 as al-Qahira, 'the victorious'."),
    Q("geo", 1, "In which city are the headquarters of the United Nations?",
      "New York", "Geneva", "Vienna", "Brussels",
      "The East River site was bought in 1946 with a donation from John D. Rockefeller Jr."),
    Q("geo", 1, "Bavaria is a state of which country?",
      "Germany", "Austria", "Switzerland", "Czechia",
      "It styles itself a Freistaat, or free state, a title it has kept since 1918."),
    Q("geo", 1, "Which country borders the United States to the south?",
      "Mexico", "Guatemala", "Cuba", "Belize",
      "The border runs about 3,145 km, much of it down the middle of the Rio Grande."),

    # ---------------- difficulty 2 ----------------
    Q("geo", 2, "What is the capital of Turkey?",
      "Ankara", "Istanbul", "Izmir", "Bursa",
      "The capital was moved inland in 1923, away from a coast that had just been occupied."),
    Q("geo", 2, "What is the capital of Switzerland?",
      "Bern", "Zurich", "Geneva", "Basel",
      "It is legally only the 'federal city' -- the constitution names no capital at all."),
    Q("geo", 2, "What is the capital of Brazil?",
      "Brasilia", "Rio de Janeiro", "Sao Paulo", "Salvador",
      "Inaugurated in 1960, its street plan by Lucio Costa is laid out in the shape of an aeroplane."),
    Q("geo", 2, "What is the capital of Nigeria?",
      "Abuja", "Lagos", "Kano", "Ibadan",
      "Purpose-built near the geographic centre of the country and made capital in 1991."),
    Q("geo", 2, "Which of these is a member state of the European Union?",
      "Croatia", "Norway", "Switzerland", "Iceland",
      "It joined in 2013 and is still the newest member; the other three have all stayed out."),
    Q("geo", 2, "Which Nordic country uses the euro?",
      "Finland", "Sweden", "Denmark", "Norway",
      "It signed up at the euro's launch in 1999 while its neighbours kept their kronor and kroner."),
    Q("geo", 2, "Burma is now officially known by what name?",
      "Myanmar", "Cambodia", "Laos", "Bangladesh",
      "The ruling junta changed the English name in 1989; several governments took decades to follow."),
    Q("geo", 2, "Which city was formerly called Constantinople?",
      "Istanbul", "Athens", "Thessaloniki", "Edirne",
      "The new name was made official for postal purposes in 1930, though locals had used it for centuries."),
    Q("geo", 2, "Barcelona is the capital of which autonomous community?",
      "Catalonia", "Aragon", "Valencia", "Navarre",
      "Spain has 17 such communities; this one's parliament sits in the Parc de la Ciutadella."),
    Q("geo", 2, "Which two countries share the island of Hispaniola?",
      "Haiti and the Dominican Republic", "Cuba and Jamaica",
      "Haiti and Puerto Rico", "Jamaica and the Dominican Republic",
      "Haiti holds the western third; the border between them was fixed by treaty in 1929."),
    Q("geo", 2, "Which country lies in the Pyrenees between France and Spain?",
      "Andorra", "Monaco", "San Marino", "Luxembourg",
      "It is a co-principality: its two heads of state are a French president and a Spanish bishop."),
    Q("geo", 2, "Greenland is a self-governing part of which kingdom?",
      "Denmark", "Norway", "Iceland", "Sweden",
      "It won home rule in 1979 and then left the European Communities in 1985."),
    Q("geo", 2, "Accra is the capital of which country?",
      "Ghana", "Senegal", "Sierra Leone", "Cameroon",
      "The country took its name at independence from a medieval empire that lay well to the northwest."),
    Q("geo", 2, "Which country's flag features a cedar tree?",
      "Lebanon", "Cyprus", "Jordan", "Syria",
      "Those cedars appear all through the Hebrew Bible as the timber of Solomon's temple."),
    Q("geo", 2, "Afrikaans developed chiefly out of which European language?",
      "Dutch", "German", "French", "Portuguese",
      "It absorbed Malay, Portuguese and Khoi vocabulary and was recognised as separate in 1925."),
    Q("geo", 2, "Nairobi is the capital of which country?",
      "Kenya", "Tanzania", "Uganda", "Zambia",
      "It began in 1899 as a railway depot on the line running inland from Mombasa."),
    Q("geo", 2, "San Marino is entirely surrounded by which country?",
      "Italy", "Switzerland", "Austria", "Croatia",
      "The microstate claims to be the oldest surviving republic, founded by tradition in the year 301."),
    Q("geo", 2, "Which US state is nicknamed the Sunshine State?",
      "Florida", "California", "Arizona", "Hawaii",
      "California is the Golden State; this nickname was made official by statute in 1970."),
    Q("geo", 2, "The shekel is the currency of which country?",
      "Israel", "Jordan", "Egypt", "Lebanon",
      "The name revives an ancient unit of weight used for silver across the Levant."),
    Q("geo", 2, "Which US state is named after a president?",
      "Washington", "Virginia", "Georgia", "Louisiana",
      "The other three are named for monarchs: Elizabeth I, George II and Louis XIV."),

    # ---------------- difficulty 3 ----------------
    Q("geo", 3, "Which country uses the internet country code .za?",
      "South Africa", "Zambia", "Zimbabwe", "Tanzania",
      "The letters come from the Dutch form of the name, Zuid-Afrika."),
    Q("geo", 3, "In which city does the International Court of Justice sit?",
      "The Hague", "Geneva", "Strasbourg", "Brussels",
      "It occupies the Peace Palace, paid for by Andrew Carnegie and opened in 1913."),
    Q("geo", 3, "In which city does the European Parliament hold its monthly plenary sessions?",
      "Strasbourg", "Brussels", "Luxembourg", "Frankfurt",
      "The monthly move from Brussels is written into the treaties, so no vote can end it easily."),
    Q("geo", 3, "Which of these countries drives on the left?",
      "Indonesia", "The Philippines", "Vietnam", "South Korea",
      "The Dutch East Indies kept to the left, and the country never switched after independence."),
    Q("geo", 3, "What is the capital of Morocco?",
      "Rabat", "Casablanca", "Marrakesh", "Fez",
      "Casablanca is several times larger, but the palace and the ministries are elsewhere."),
    Q("geo", 3, "Which capital was renamed Nur-Sultan in 2019, then changed back in 2022?",
      "Astana", "Almaty", "Bishkek", "Tashkent",
      "The capital had itself been moved north from Almaty in 1997."),
    Q("geo", 3, "Which Iranian city grew up around the shrine of Imam Reza?",
      "Mashhad", "Qom", "Shiraz", "Yazd",
      "The shrine complex is one of the largest religious sites in the world by floor area."),
    Q("geo", 3, "Which US state borders only one other state?",
      "Maine", "Florida", "Washington", "Vermont",
      "Only New Hampshire touches it; the rest is ocean, Canada and forest."),
    Q("geo", 3, "Which city is the seat of South Africa's parliament?",
      "Cape Town", "Pretoria", "Johannesburg", "Durban",
      "Pretoria holds the executive and Bloemfontein the senior courts -- three capitals in all."),
    Q("geo", 3, "The Gambia is surrounded on three sides by which country?",
      "Senegal", "Guinea", "Mali", "Mauritania",
      "The borders were drawn to follow the navigable river, reportedly within range of a gunboat."),
    Q("geo", 3, "Which is the smallest member state of the European Union by area?",
      "Malta", "Luxembourg", "Cyprus", "Slovenia",
      "About 316 square kilometres; it joined in 2004 and adopted the euro in 2008."),
    Q("geo", 3, "Which EU member state is not part of the Schengen Area?",
      "Ireland", "Croatia", "Slovenia", "Estonia",
      "It keeps the Common Travel Area with the UK instead, so passport checks stay in place."),
    Q("geo", 3, "In which city are NATO's headquarters?",
      "Brussels", "The Hague", "Geneva", "Luxembourg",
      "They moved from Paris in 1967 after France pulled out of the integrated command."),
    Q("geo", 3, "Which of these countries is in the European Union but not in NATO?",
      "Austria", "Poland", "Romania", "Slovakia",
      "Its neutrality has been written into constitutional law since 1955."),
    Q("geo", 3, "Which is the only landlocked country in Southeast Asia?",
      "Laos", "Cambodia", "Myanmar", "Vietnam",
      "The Mekong forms much of its western border and long served as its main highway."),
    Q("geo", 3, "Which country borders only Russia and China?",
      "Mongolia", "Kazakhstan", "Kyrgyzstan", "Nepal",
      "It is the second-largest landlocked country in the world, after Kazakhstan."),
    Q("geo", 3, "The Line of Control divides which disputed region?",
      "Kashmir", "Punjab", "Balochistan", "Sindh",
      "Drawn as a ceasefire line in 1949, it was given its present name by the 1972 Simla Agreement."),
    Q("geo", 3, "The Durand Line separates Afghanistan from which country?",
      "Pakistan", "Iran", "Turkmenistan", "Uzbekistan",
      "A British official drew it in 1893, and Kabul has never accepted it as a settled border."),
    Q("geo", 3, "What are the Falkland Islands called in Spanish?",
      "Las Malvinas", "Las Marianas", "Las Baleares", "Las Canarias",
      "The name traces back to Saint-Malo, whose sailors planted a settlement there in 1764."),
    Q("geo", 3, "In which South American country is Dutch the official language?",
      "Suriname", "Guyana", "Belize", "Panama",
      "It stayed Dutch until 1975, long after the rest of the continent had broken with Europe."),
    Q("geo", 3, "Which is the largest of the Channel Islands?",
      "Jersey", "Guernsey", "Alderney", "Sark",
      "The islands are Crown Dependencies and have never been part of the United Kingdom."),
    Q("geo", 3, "San Juan is the capital of which US territory?",
      "Puerto Rico", "Guam", "The US Virgin Islands", "American Samoa",
      "Founded in 1521, it is one of the oldest continuously inhabited European-founded cities in the Americas."),
    Q("geo", 3, "Which is the largest country in Africa by area?",
      "Algeria", "Sudan", "Libya", "Chad",
      "It inherited the title in 2011, when South Sudan split away from the previous holder."),
    Q("geo", 3, "Which country's name comes from the Latin word for silver?",
      "Argentina", "Chile", "Uruguay", "Peru",
      "Little silver was mined there -- it was shipped down the river from the mines of Potosi."),
    Q("geo", 3, "Which country is known as the Land of the Thunder Dragon?",
      "Bhutan", "Nepal", "Mongolia", "Laos",
      "Druk Yul in Dzongkha, which is also why its monarch is styled the Dragon King."),
    Q("geo", 3, "Which country keeps a single time zone despite spanning some 5,000 km?",
      "China", "India", "Brazil", "Australia",
      "One national clock has been kept since 1949, though Xinjiang runs an unofficial local time two hours behind."),
    Q("geo", 3, "Which capital city was known as Batavia under colonial rule?",
      "Jakarta", "Cape Town", "Colombo", "Paramaribo",
      "The Dutch named it after the Batavi, a Germanic tribe of the Rhine delta."),
    N("geo", 3, "How many countries share a land border with Germany?",
      9, "countries",
      "Denmark, Poland, Czechia, Austria, Switzerland, France, Luxembourg, Belgium and the Netherlands."),
    N("geo", 3, "How many federal states, or Laender, does Germany have?",
      16, "states",
      "Five were re-created in the east on reunification in 1990, joining the eleven of the west."),
    N("geo", 3, "How many London boroughs are there, not counting the City of London?",
      32, "boroughs",
      "They were created in 1965; the City is a separate and far older corporation."),

    # ---------------- difficulty 4 ----------------
    Q("geo", 4, "Which city did Shah Abbas I make his capital in 1598?",
      "Isfahan", "Tabriz", "Shiraz", "Qazvin",
      "He laid out the great maidan there, and the saying went that the city was half the world."),
    Q("geo", 4, "Iran shares its longest land border with which country?",
      "Iraq", "Turkmenistan", "Afghanistan", "Pakistan",
      "About 1,600 km of it, and the line along which the 1980s war was fought."),
    Q("geo", 4, "Nakhchivan is cut off from the rest of Azerbaijan by which country?",
      "Armenia", "Georgia", "Iran", "Turkey",
      "The exclave touches Iran and Turkey but has no land link to its own state."),
    Q("geo", 4, "Birobidzhan is the administrative centre of which Russian region?",
      "The Jewish Autonomous Oblast", "The Altai Republic",
      "The Republic of Tuva", "The Sakha Republic",
      "Stalin designated it in 1934 as a Yiddish-speaking homeland, conveniently far from Moscow."),
    Q("geo", 4, "Which city is Bolivia's constitutional capital?",
      "Sucre", "La Paz", "Santa Cruz", "Cochabamba",
      "The government decamped to La Paz in 1899, but the supreme court stayed put."),
    Q("geo", 4, "What is the capital of Tanzania?",
      "Dodoma", "Dar es Salaam", "Arusha", "Mwanza",
      "The move inland was decided in 1973 and took some forty years to complete."),
    Q("geo", 4, "What is the capital of Cote d'Ivoire?",
      "Yamoussoukro", "Abidjan", "Bouake", "Korhogo",
      "The president's birthplace, promoted in 1983; most embassies never left Abidjan."),
    Q("geo", 4, "Which purpose-built city houses most of Malaysia's federal government?",
      "Putrajaya", "Kuala Lumpur", "Johor Bahru", "Ipoh",
      "Kuala Lumpur remains the legal capital and still keeps parliament and the king."),
    Q("geo", 4, "Which country was known as Dahomey until 1975?",
      "Benin", "Togo", "Niger", "Guinea",
      "The new name came from the bight offshore rather than from the old kingdom on its soil."),
    Q("geo", 4, "Which capital city was called Christiania until 1925?",
      "Oslo", "Copenhagen", "Stockholm", "Helsinki",
      "It had been renamed for Christian IV, who rebuilt it after a fire in 1624."),
    Q("geo", 4, "Which African capital was known as Leopoldville until 1966?",
      "Kinshasa", "Brazzaville", "Luanda", "Lubumbashi",
      "It and Brazzaville stare at each other across the river -- the closest pair of capitals anywhere."),
    Q("geo", 4, "Which former Portuguese colony joined the Commonwealth in 1995?",
      "Mozambique", "Angola", "Guinea-Bissau", "Cape Verde",
      "It was the first member with no constitutional link to Britain, admitted at its neighbours' urging."),
    Q("geo", 4, "In which city are OPEC's headquarters?",
      "Vienna", "Riyadh", "Geneva", "Kuwait City",
      "Founded in Baghdad in 1960, the organisation started out in Geneva and moved in 1965."),
    Q("geo", 4, "In which city was ASEAN founded in 1967?",
      "Bangkok", "Jakarta", "Manila", "Singapore",
      "Five foreign ministers signed the declaration there; the secretariat later settled in Jakarta."),
    Q("geo", 4, "Russia shares its telephone calling code, +7, with which country?",
      "Kazakhstan", "Belarus", "Ukraine", "Mongolia",
      "A leftover of the Soviet network that was simply never unpicked after 1991."),
    Q("geo", 4, "Which country's territories span more time zones than any other?",
      "France", "Russia", "The United States", "The United Kingdom",
      "Twelve in all, thanks to Polynesia, the Caribbean, the Indian Ocean and South America."),
    Q("geo", 4, "Which country skipped 30 December 2011 entirely to change sides of the date line?",
      "Samoa", "Tonga", "Fiji", "Kiribati",
      "It jumped forward a day to line up its working week with Australia and New Zealand."),
    Q("geo", 4, "Which is the only officially bilingual Canadian province?",
      "New Brunswick", "Quebec", "Ontario", "Manitoba",
      "Quebec is officially French-only; this province has run in both languages since 1969."),
    Q("geo", 4, "Which German state is entirely surrounded by Brandenburg?",
      "Berlin", "Hamburg", "Bremen", "Saxony",
      "The two put a merger to a referendum in 1996 and the surrounding state voted it down."),
    Q("geo", 4, "Whitehorse is the capital of which Canadian territory?",
      "Yukon", "The Northwest Territories", "Nunavut", "Alberta",
      "It took over from Dawson City in 1953, once the highway rather than the goldfields mattered."),
    Q("geo", 4, "Which European country switched from driving on the left to the right in 1967?",
      "Sweden", "Denmark", "Austria", "Portugal",
      "Dagen H, the changeover morning, passed with fewer accidents than an ordinary day."),
    Q("geo", 4, "Which country has a land border with both Israel and Saudi Arabia?",
      "Jordan", "Egypt", "Iraq", "Kuwait",
      "Egypt meets Israel but not Saudi Arabia by land, and Iraq the other way round."),
    N("geo", 4, "In which year did Spain join NATO?",
      1982, "the year",
      "It joined seven years after Franco's death and four years before entering the European Community."),
    N("geo", 4, "In which year did Reza Shah ask foreign governments to call his country Iran?",
      1935, "the year",
      "The name had been used internally for centuries; outsiders had stuck with Persia."),
    N("geo", 4, "How many minutes ahead of UTC is Indian Standard Time?",
      330, "minutes",
      "Five and a half hours, set on a meridian near Allahabad so one clock covers the whole country."),

    # ---------------- difficulty 5 ----------------
    Q("geo", 5, "The tangle of enclaves at Baarle puts Belgian land inside which country?",
      "The Netherlands", "Luxembourg", "Germany", "France",
      "Some twenty Belgian parcels sit there, several with Dutch counter-enclaves inside them."),
    Q("geo", 5, "In which city does Sri Lanka's parliament sit?",
      "Sri Jayawardenepura Kotte", "Colombo", "Kandy", "Galle",
      "The complex opened in 1982 on reclaimed marshland outside Colombo, which kept the commerce."),
    Q("geo", 5, "The oil-rich exclave of Cabinda belongs to which country?",
      "Angola", "The Democratic Republic of the Congo", "Gabon", "Congo-Brazzaville",
      "A narrow corridor of Congolese land along the river cuts it off from the rest of the country."),
    Q("geo", 5, "Which country's national flag depicts human figures?",
      "Belize", "Guyana", "Barbados", "Suriname",
      "Two woodcutters, one mestizo and one of African descent, stand beneath a mahogany tree."),
    Q("geo", 5, "Which is the only sovereign country named after a real woman?",
      "Saint Lucia", "Grenada", "Dominica", "Saint Kitts and Nevis",
      "French sailors named it for Lucy of Syracuse, reportedly landing on her feast day."),
    Q("geo", 5, "What is the capital of Vanuatu?",
      "Port Vila", "Suva", "Nukualofa", "Apia",
      "The country was run jointly by Britain and France until 1980, with two of everything."),
    Q("geo", 5, "Bandar Seri Begawan is the capital of which country?",
      "Brunei", "Oman", "Qatar", "Bahrain",
      "The name was adopted in 1970 to honour the sultan who had abdicated in favour of his son."),
    Q("geo", 5, "Which country was known as Portuguese Guinea before 1974?",
      "Guinea-Bissau", "Guinea", "Equatorial Guinea", "The Gambia",
      "Its capital was tacked onto the name to keep it apart from the former French colony next door."),
    Q("geo", 5, "The Trucial States became which country in 1971?",
      "The United Arab Emirates", "Oman", "Qatar", "Kuwait",
      "The truces in question were anti-piracy agreements signed with Britain from the 1830s."),
    Q("geo", 5, "Mercosur's founding treaty of 1991 is named after which city?",
      "Asuncion", "Montevideo", "Brasilia", "Buenos Aires",
      "The bloc's secretariat ended up in Montevideo, and its court in the same city's suburbs."),
    Q("geo", 5, "Tajik, the Persian variety of Tajikistan, is written in which script?",
      "Cyrillic", "Arabic", "Latin", "Georgian",
      "Soviet policy moved it from Arabic to Latin in 1928 and to Cyrillic a decade later."),
    Q("geo", 5, "The internet domain .io was originally issued to which territory?",
      "The British Indian Ocean Territory", "The British Virgin Islands",
      "The Cayman Islands", "The Falkland Islands",
      "The code covers the Chagos Archipelago, whose largest island holds a military base."),
    Q("geo", 5, "Dhivehi is the official language of which country?",
      "The Maldives", "Mauritius", "The Seychelles", "Sri Lanka",
      "It is written in the Thaana script, which runs right to left and borrows Arabic numerals as letters."),
    N("geo", 5, "How many US states share a border with Canada?",
      13, "states",
      "Ohio and Pennsylvania count, since their boundary runs through the water of Lake Erie."),
    N("geo", 5, "In which year was the Schengen Agreement signed?",
      1985, "the year",
      "Five countries signed it on a boat moored at a village in Luxembourg, outside the EEC framework."),
]
