# -*- coding: utf-8 -*-
"""Physical geography: rivers, mountains, oceans, ice, climate, tectonics."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [
    # ---- difficulty 1 ----
    Q("geo", 1, "Which river flows through London?",
      "The Thames", "The Severn", "The Trent", "The Mersey",
      "It is tidal as far upstream as Teddington, where a lock marks the limit."),
    Q("geo", 1, "Which is the longest river in Africa?",
      "The Nile", "The Congo", "The Niger", "The Zambezi",
      "The Congo is shorter but discharges roughly ten times as much water."),
    Q("geo", 1, "Which volcano buried Pompeii in AD 79?",
      "Vesuvius", "Etna", "Stromboli", "Vulcano",
      "It has erupted dozens of times since, most recently in 1944."),
    Q("geo", 1, "Which mountain range runs along the border of Spain and France?",
      "The Pyrenees", "The Alps", "The Apennines", "The Carpathians",
      "Its highest summit, Aneto, tops 3,400 m on the Spanish side."),
    Q("geo", 1, "Mount Everest stands in which mountain range?",
      "The Himalayas", "The Karakoram", "The Hindu Kush", "The Pamirs",
      "The Karakoram next door holds K2 and three more of the fourteen 8,000ers."),
    Q("geo", 1, "Which mountain range runs down the western side of South America?",
      "The Andes", "The Sierra Madre", "The Atlas Mountains", "The Great Dividing Range",
      "At about 7,000 km it is the longest continental mountain chain on Earth."),
    Q("geo", 1, "Which is the largest island in the world?",
      "Greenland", "New Guinea", "Borneo", "Madagascar",
      "Australia is more than three times bigger but counts as a continent."),
    Q("geo", 1, "Which is the largest desert in Africa?",
      "The Sahara", "The Kalahari", "The Namib", "The Danakil",
      "Six thousand years ago much of it was grassland dotted with lakes."),
    Q("geo", 1, "Spain and Portugal occupy which peninsula?",
      "The Iberian Peninsula", "The Balkan Peninsula", "The Apennine Peninsula",
      "The Anatolian Peninsula",
      "The name comes from the Ebro, which the Romans called the Iberus."),
    Q("geo", 1, "The prime meridian is defined by the old observatory in which London district?",
      "Greenwich", "Woolwich", "Deptford", "Blackheath",
      "The satellite zero sits about 100 m east of the brass line, thanks to a different datum."),

    # ---- difficulty 2 ----
    Q("geo", 2, "Which river flows through Paris?",
      "The Seine", "The Loire", "The Rhone", "The Somme",
      "The Marne joins it at the city's south-eastern edge."),
    Q("geo", 2, "The Nile empties into which sea?",
      "The Mediterranean", "The Red Sea", "The Arabian Sea", "The Black Sea",
      "Its delta has been retreating since the Aswan dams cut off the silt supply."),
    Q("geo", 2, "Which is the highest peak in the Alps?",
      "Mont Blanc", "The Matterhorn", "Monte Rosa", "The Eiger",
      "Its summit is a dome of ice, so the surveyed height shifts by a metre or two."),
    Q("geo", 2, "Which is the second-highest mountain in the world?",
      "K2", "Kangchenjunga", "Lhotse", "Makalu",
      "The K is for Karakoram, from a survey that never turned up a local name."),
    Q("geo", 2, "Which river carved the Grand Canyon?",
      "The Colorado", "The Rio Grande", "The Snake", "The Gila",
      "It has cut down through nearly two billion years of rock."),
    Q("geo", 2, "Which desert covers most of Botswana?",
      "The Kalahari", "The Namib", "The Karoo", "The Danakil",
      "Strictly a semi-desert -- enough rain falls for grass and acacia."),
    Q("geo", 2, "The Gobi Desert lies in Mongolia and which other country?",
      "China", "Kazakhstan", "Russia", "Kyrgyzstan",
      "A cold desert on a high plateau: winter nights drop below minus 30C."),
    Q("geo", 2, "Which sea lies between Italy and the Balkan peninsula?",
      "The Adriatic", "The Aegean", "The Ionian", "The Tyrrhenian",
      "Venice sits at its shallow northern head, where river silt keeps piling up."),
    Q("geo", 2, "Which sea is enclosed by Cuba, Central America and the Lesser Antilles?",
      "The Caribbean Sea", "The Gulf of Mexico", "The Coral Sea", "The Timor Sea",
      "Its floor is a tectonic plate of its own, rimmed by a volcanic island arc."),
    Q("geo", 2, "Which sea lies immediately west of India?",
      "The Arabian Sea", "The Red Sea", "The Andaman Sea", "The Java Sea",
      "Its monsoon winds reverse twice a year, which is how the dhow trade worked."),
    Q("geo", 2, "Which is the largest lake in Africa by surface area?",
      "Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Turkana",
      "Tanganyika is far deeper and holds several times as much water."),
    Q("geo", 2, "Which is the largest island in the Caribbean?",
      "Cuba", "Hispaniola", "Jamaica", "Puerto Rico",
      "Its Sierra Maestra rises to almost 2,000 m at Pico Turquino."),
    Q("geo", 2, "What is a hurricane called in the north-west Pacific?",
      "A typhoon", "A cyclone", "A tornado", "A monsoon",
      "Same storm, different basin -- in the Indian Ocean it is simply a cyclone."),
    Q("geo", 2, "On a weather map, what do isobars join?",
      "Points of equal pressure", "Points of equal temperature",
      "Points of equal rainfall", "Points of equal altitude",
      "The tighter they crowd together, the harder the wind blows."),
    Q("geo", 2, "Which cave formation hangs down from the roof?",
      "A stalactite", "A stalagmite", "A flowstone", "A helictite",
      "The c clings to the ceiling; the g grows up from the ground."),
    Q("geo", 2, "Which fault runs most of the length of California?",
      "The San Andreas Fault", "The Hayward Fault", "The New Madrid Fault",
      "The Wasatch Fault",
      "A transform boundary: the Pacific plate grinds north-west past the North American."),
    Q("geo", 2, "What is the broad crater left when a volcano collapses after a huge eruption?",
      "A caldera", "A maar", "A cinder cone", "A lava dome",
      "Crater Lake in Oregon fills one, left when Mount Mazama fell in on itself."),
    Q("geo", 2, "What is the highest mountain in Iran?",
      "Damavand", "Sabalan", "Zard-Kuh", "Alvand",
      "A dormant volcano in the Alborz, and the highest peak anywhere in the Middle East."),
    Q("geo", 2, "Which line of latitude marks the southern tropic?",
      "The Tropic of Capricorn", "The Tropic of Cancer", "The Antarctic Circle",
      "The Equator",
      "The Sun stands directly overhead there at the December solstice."),
    Q("geo", 2, "Which biome is the treeless zone between the Arctic ice and the northern forests?",
      "Tundra", "Steppe", "Chaparral", "Veld",
      "Its subsoil stays frozen all year, so summer meltwater pools on the surface."),

    # ---- difficulty 3 ----
    N("geo", 3, "Roughly what percentage of the Earth's surface is covered by ocean?",
      71, "%",
      "Land takes the other 29 per cent, and almost all of the far south is water."),
    N("geo", 3, "What is the highest force on the Beaufort wind scale?",
      12, "the force number",
      "Force 12 starts at 118 km/h; some countries extend the scale to 17 for typhoons."),
    N("geo", 3, "How many degrees north of the equator is the Tropic of Cancer, to the nearest degree?",
      23, "degrees",
      "It sits at 23.44 degrees, set by the tilt of the Earth's axis, and drifts slowly."),
    Q("geo", 3, "The deepest known point of the ocean lies in which trench?",
      "The Mariana Trench", "The Tonga Trench", "The Java Trench",
      "The Puerto Rico Trench",
      "The Challenger Deep is about 11 km down -- Everest would sit under 2 km of water."),
    Q("geo", 3, "Which effect makes storm systems spin one way in the north and the other in the south?",
      "The Coriolis effect", "The Ekman effect", "The Venturi effect", "The Magnus effect",
      "It is also why tropical cyclones cannot form within a few degrees of the equator."),
    Q("geo", 3, "What is the dry belt on the leeward side of a mountain range called?",
      "A rain shadow", "A dry line", "A lee trough", "A chinook belt",
      "Air sheds its moisture climbing the windward slope, then warms as it sinks."),
    Q("geo", 3, "Which map projection notoriously inflates Greenland to the size of Africa?",
      "Mercator", "Gall-Peters", "Robinson", "Winkel tripel",
      "Its payoff is that a straight line on the chart is a constant compass bearing."),
    Q("geo", 3, "Which river flows through Baghdad?",
      "The Tigris", "The Euphrates", "The Karun", "The Orontes",
      "It merges with the Euphrates north of Basra to form the Shatt al-Arab."),
    Q("geo", 3, "The Rhine reaches the sea in which country?",
      "The Netherlands", "Germany", "Belgium", "France",
      "It breaks into a maze of distributaries across the Rhine-Meuse delta."),
    Q("geo", 3, "Victoria Falls lies on which river?",
      "The Zambezi", "The Limpopo", "The Orange", "The Okavango",
      "The local name, Mosi-oa-Tunya, means the smoke that thunders."),
    Q("geo", 3, "The Volga drains into which body of water?",
      "The Caspian Sea", "The Black Sea", "The Baltic Sea", "The Sea of Azov",
      "Europe's longest river never reaches an ocean at all."),
    Q("geo", 3, "The Mississippi rises at which lake?",
      "Lake Itasca", "Lake Winnibigoshish", "Lake Pepin", "Leech Lake",
      "Its tributary the Missouri is longer than the stretch above their confluence."),
    Q("geo", 3, "Edinburgh stands on the estuary of which river?",
      "The Forth", "The Tay", "The Clyde", "The Tweed",
      "The Tay's firth lies about 40 miles north, at Dundee."),
    Q("geo", 3, "The Ganges and Brahmaputra build the world's largest delta, known by what name?",
      "The Sundarbans", "The Rann of Kutch", "The Terai", "The Doab",
      "Its mangroves hold the only tiger population living in salt marsh."),
    Q("geo", 3, "Which river flows through Hamburg?",
      "The Elbe", "The Weser", "The Ems", "The Oder",
      "It rises in the Czech mountains and is still tidal up at the city."),
    Q("geo", 3, "The Rio Grande empties into which body of water?",
      "The Gulf of Mexico", "The Pacific Ocean", "The Gulf of California",
      "The Caribbean Sea",
      "In dry years irrigation takes so much flow that the mouth silts shut."),
    Q("geo", 3, "Which river flows through Lisbon?",
      "The Tagus", "The Douro", "The Guadiana", "The Mondego",
      "Porto sits on the Douro instead, some 300 km up the coast."),
    Q("geo", 3, "Which river runs through Isfahan?",
      "The Zayandeh Rud", "The Karun", "The Sefid Rud", "The Aras",
      "It ends in the Gavkhouni salt marsh and reaches no sea."),
    Q("geo", 3, "Ben Macdui and Braeriach are summits of which Scottish range?",
      "The Cairngorms", "The Trossachs", "The Cuillin", "The Ochils",
      "Britain's largest expanse above 1,000 m, with a plateau climate closer to the Arctic."),
    Q("geo", 3, "Which volcanic island erupted catastrophically in 1883, in what is now Indonesia?",
      "Krakatoa", "Tambora", "Mount Agung", "Mount Merapi",
      "The bang was heard on Rodrigues, some 4,800 km away across the Indian Ocean."),
    Q("geo", 3, "Which is the largest of the Earth's tectonic plates?",
      "The Pacific Plate", "The North American Plate", "The Eurasian Plate",
      "The African Plate",
      "It is shrinking, consumed at the subduction zones around most of its rim."),
    Q("geo", 3, "Iceland sits astride the boundary between which two tectonic plates?",
      "North American and Eurasian", "African and Eurasian",
      "North American and Pacific", "South American and African",
      "The island widens a couple of centimetres a year, prising open the Thingvellir rift."),
    Q("geo", 3, "Which is the highest mountain in the Americas?",
      "Aconcagua", "Denali", "Mount Logan", "Huascaran",
      "At 6,961 m it is also the highest summit anywhere outside Asia."),
    Q("geo", 3, "The Khyber Pass links Pakistan with which country?",
      "Afghanistan", "Iran", "Tajikistan", "India",
      "It threads the Spin Ghar range at a fairly modest 1,070 m."),
    Q("geo", 3, "Mount Elbrus, the highest peak in Europe, stands in which range?",
      "The Caucasus", "The Carpathians", "The Balkans", "The Taurus",
      "A dormant twin-coned volcano, 5,642 m at the western summit."),
    Q("geo", 3, "Which mountain range runs across Morocco, Algeria and Tunisia?",
      "The Atlas Mountains", "The Ahaggar", "The Tibesti", "The Drakensberg",
      "They wring the rain out of Atlantic air and leave the desert dry behind them."),
    Q("geo", 3, "The dunes of Sossusvlei rise in which desert?",
      "The Namib", "The Kalahari", "The Karoo", "The Danakil",
      "Fog off the cold Benguela current is the main water source for its beetles."),
    Q("geo", 3, "Which biome is the belt of conifer forest stretching across Canada and Siberia?",
      "Taiga", "Temperate rainforest", "Savanna", "Steppe",
      "The largest land biome on Earth, and a bigger carbon store than the tropics."),
    Q("geo", 3, "What is the term for limestone country full of sinkholes, caves and underground rivers?",
      "Karst", "Loess", "Moraine", "Machair",
      "Named after the Kras plateau above Trieste; a quarter of the world drinks from such rock."),
    Q("geo", 3, "What is a coastal inlet formed by a drowned glacial valley called?",
      "A fjord", "A ria", "A firth", "A cirque",
      "Sognefjord runs over 200 km inland and more than 1,300 m deep."),

    # ---- difficulty 4 ----
    Q("geo", 4, "Niagara Falls sits on the river between which two Great Lakes?",
      "Erie and Ontario", "Huron and Erie", "Michigan and Huron", "Superior and Huron",
      "The lip has retreated some 11 km upstream since the ice sheets withdrew."),
    Q("geo", 4, "The Iguazu Falls lie on the border of Brazil and which country?",
      "Argentina", "Paraguay", "Uruguay", "Bolivia",
      "The river joins the Parana just downstream, where three countries meet."),
    Q("geo", 4, "Which isthmus joins Africa to Asia?",
      "The Isthmus of Suez", "The Isthmus of Panama", "The Isthmus of Corinth",
      "The Isthmus of Kra",
      "About 125 km of desert, and the only land bridge between the two continents."),
    Q("geo", 4, "Which cape is the southernmost point of Africa?",
      "Cape Agulhas", "The Cape of Good Hope", "Cape Point", "Cape Recife",
      "The Cape of Good Hope, the famous one, lies about 150 km to the north-west."),
    Q("geo", 4, "What do sailors call the belt of fickle, windless water near the equator?",
      "The doldrums", "The horse latitudes", "The trade winds", "The roaring forties",
      "Formally the intertropical convergence zone, where the trades of both hemispheres meet."),
    Q("geo", 4, "Which warm, dry wind pours down the lee slopes of the Alps?",
      "The Foehn", "The Bora", "The Sirocco", "The Levanter",
      "Air that has dumped its rain on the windward side warms as it sinks again."),
    Q("geo", 4, "Which Pacific warming pattern shifts rainfall right around the globe?",
      "El Nino", "The Indian Ocean Dipole", "The North Atlantic Oscillation",
      "The Madden-Julian Oscillation",
      "Spanish for the boy: Peruvian fishermen named it because it peaked near Christmas."),
    Q("geo", 4, "The Indian summer monsoon brings winds from which direction?",
      "The south-west", "The north-east", "The south-east", "The north-west",
      "It reverses in winter, when a dry north-east monsoon blows back out to sea."),
    Q("geo", 4, "Jet streams flow near the boundary between which two layers of the atmosphere?",
      "The troposphere and stratosphere", "The stratosphere and mesosphere",
      "The mesosphere and thermosphere", "The thermosphere and exosphere",
      "That boundary, the tropopause, is lower over the poles than over the tropics."),
    Q("geo", 4, "Which 1991 eruption cooled global temperatures by about half a degree?",
      "Mount Pinatubo", "Mount Unzen", "El Chichon", "Nevado del Ruiz",
      "Its sulphate haze sat in the stratosphere dimming sunlight for two years."),
    Q("geo", 4, "Which volcano blew out its own north face in 1980?",
      "Mount St Helens", "Mount Hood", "Mount Rainier", "Mount Shasta",
      "The collapse took 400 m off the summit and left a horseshoe crater."),
    Q("geo", 4, "The Gulf of Aqaba is an arm of which sea?",
      "The Red Sea", "The Mediterranean Sea", "The Arabian Sea", "The Persian Gulf",
      "Four countries crowd its head, and the gulf runs over 1,800 m deep."),
    Q("geo", 4, "Which strait separates Sicily from the Italian mainland?",
      "The Strait of Messina", "The Strait of Bonifacio", "The Strait of Otranto",
      "The Strait of Sicily",
      "Its whirlpools and rocks are the likeliest originals for Scylla and Charybdis."),
    Q("geo", 4, "Which strait links the Sea of Marmara to the Aegean?",
      "The Dardanelles", "The Strait of Kerch", "The Kasos Strait",
      "The Strait of Otranto",
      "The Gallipoli peninsula forms its northern shore, barely 1.2 km across at the narrows."),
    Q("geo", 4, "Which current keeps north-west Europe mild for its latitude?",
      "The North Atlantic Drift", "The Canary Current", "The Labrador Current",
      "The Benguela Current",
      "An arm of the Gulf Stream: it is why Britain is milder than Labrador at the same latitude."),
    Q("geo", 4, "Surtsey, an island born from the sea in a 1963 eruption, lies off which country?",
      "Iceland", "Norway", "Japan", "New Zealand",
      "It has been left alone ever since so botanists can watch life arrive from scratch."),
    Q("geo", 4, "Which is the largest lake in Iran?",
      "Lake Urmia", "Lake Hamun", "Lake Bakhtegan", "Lake Maharloo",
      "A hypersaline lake with no outlet, cut to a fraction of its area by dams and irrigation."),
    Q("geo", 4, "Which scale rates an eruption by its ejected volume and plume height?",
      "The Volcanic Explosivity Index", "The Mercalli scale", "The Moment magnitude scale",
      "The Mohs scale",
      "It runs 0 to 8, and each step up means roughly ten times the erupted volume."),
    Q("geo", 4, "Which strait separates Tasmania from the Australian mainland?",
      "The Bass Strait", "The Torres Strait", "The Foveaux Strait", "The Clarence Strait",
      "The Torres Strait does the same job at the far north, towards New Guinea."),
    Q("geo", 4, "By the standard definition of a desert, low precipitation, which is the largest on Earth?",
      "Antarctica", "The Sahara", "The Arctic", "The Gobi",
      "Its interior gets a few centimetres of snow a year, drier than most of the Sahara."),
    Q("geo", 4, "Which plate subducts beneath South America to build the Andes?",
      "The Nazca Plate", "The Cocos Plate", "The Scotia Plate", "The Caribbean Plate",
      "It is swallowed along the Peru-Chile Trench, which runs 8,000 m deep."),
    Q("geo", 4, "Measured from its base on the sea floor, which mountain is taller than Everest?",
      "Mauna Kea", "Mauna Loa", "Denali", "Mount Teide",
      "About 10,200 m from foot to summit, though only 4,207 m of that is above water."),
    Q("geo", 4, "Which Pacific island nation shifted the international date line east in 1995?",
      "Kiribati", "Tonga", "Samoa", "Tuvalu",
      "Its eastern islands had been a day behind its west, which made governing awkward."),
    N("geo", 4, "At what wind speed in km/h does a tropical storm become a hurricane?",
      119, "km/h",
      "The threshold is 64 knots, which is 74 mph, and it climbs from there through five categories."),
    N("geo", 4, "How many kilometres is one degree of latitude, to the nearest kilometre?",
      111, "km",
      "So a full 360 degrees round the meridian comes to about 40,000 km."),

    # ---- difficulty 5 ----
    Q("geo", 5, "Which is the highest mountain in the contiguous United States?",
      "Mount Whitney", "Mount Rainier", "Mount Elbert", "Pikes Peak",
      "It stands about 135 km from Badwater Basin, the lowest point in North America."),
    Q("geo", 5, "Which summit is the furthest point on land from the centre of the Earth?",
      "Chimborazo", "Everest", "Aconcagua", "Kilimanjaro",
      "The equatorial bulge puts it some 2 km further out, despite being 2,300 m shorter."),
    Q("geo", 5, "What is the name of the boundary between the Earth's crust and mantle?",
      "The Mohorovicic discontinuity", "The Gutenberg discontinuity",
      "The Lehmann discontinuity", "The Conrad discontinuity",
      "Usually shortened to the Moho: about 35 km down under continents, 7 km under oceans."),
    Q("geo", 5, "Which warm current runs down the east coast of southern Africa?",
      "The Agulhas Current", "The Somali Current", "The Leeuwin Current",
      "The Canary Current",
      "It rounds the Cape, then mostly doubles back on itself into the Indian Ocean."),
    Q("geo", 5, "What is the slow global circulation of deep water driven by heat and salt called?",
      "The thermohaline circulation", "The Ekman spiral", "The Langmuir circulation",
      "The Sverdrup balance",
      "Nicknamed the global conveyor belt; one full circuit takes something like a thousand years."),
    Q("geo", 5, "Which Kyrgyz lake, over 600 m deep, never freezes despite sitting at 1,600 m?",
      "Issyk-Kul", "Lake Sevan", "Lake Van", "Song-Kol",
      "Its depth plus a touch of salinity keep the ice off; the name means warm lake."),
    Q("geo", 5, "Which South Atlantic archipelago is the most remote inhabited group in the world?",
      "Tristan da Cunha", "St Helena", "Ascension Island", "The Falklands",
      "Its nearest neighbour, St Helena, lies about 2,400 km away."),
    Q("geo", 5, "Which dry, dust-laden wind blows off the Sahara across West Africa in winter?",
      "The Harmattan", "The Sirocco", "The Simoom", "The Levanter",
      "It drops humidity so sharply that the season is nicknamed the doctor."),
    Q("geo", 5, "The Blue Nile flows out of which lake?",
      "Lake Tana", "Lake Turkana", "Lake Albert", "Lake Kyoga",
      "Ethiopian highland rain reaching it gives the Nile most of its summer flood."),
    Q("geo", 5, "Which Icelandic eruption of 1783 poisoned the island and hazed over Europe?",
      "Laki", "Hekla", "Katla", "Askja",
      "A fifth of Icelanders died in the famine that followed, and crops failed across Europe."),
    Q("geo", 5, "The 1902 eruption of Mount Pelee wiped out which town?",
      "Saint-Pierre", "Fort-de-France", "Basse-Terre", "Roseau",
      "A pyroclastic flow killed some 28,000 people on Martinique in a couple of minutes."),
    Q("geo", 5, "In the Koppen climate classification, arid climates are given which letter?",
      "B", "A", "D", "E",
      "A is tropical, C temperate, D continental and E polar; the second letter sets the degree."),
    N("geo", 5, "What was the moment magnitude of the 1960 Valdivia earthquake in Chile?",
      9.5, "magnitude",
      "It ruptured about 1,000 km of the plate boundary and sent a tsunami to Japan."),
    N("geo", 5, "In which year did the great earthquake and tsunami destroy Lisbon?",
      1755, "the year",
      "It struck on All Saints' Day, and the shock helped push seismology into a science."),
    N("geo", 5, "How many metres is the greatest tidal range in the Bay of Fundy, to the nearest metre?",
      16, "metres",
      "The basin's length happens to resonate with the tidal period, amplifying the swing."),
]
