# -*- coding: utf-8 -*-
"""Science bank B: life sciences and earth sciences -- biology, medicine, evolution, geology, history of science."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [

    # ---------------- difficulty 1 (10) ----------------
    Q("science", 1, "Which vessels carry blood away from the heart?",
      "Arteries", "Veins", "Capillaries", "Venules",
      "They have thick muscular walls because they take the full force of each heartbeat."),
    Q("science", 1, "What is the transformation of a caterpillar into a butterfly called?",
      "Metamorphosis", "Gestation", "Germination", "Regeneration",
      "Inside the pupa most of the larval tissue is broken down and rebuilt from small discs of cells."),
    Q("science", 1, "Which organs filter waste from the blood to make urine?",
      "The kidneys", "The liver", "The spleen", "The pancreas",
      "They process the body's entire blood volume roughly every five minutes."),
    Q("science", 1, "Who wrote 'On the Origin of Species'?",
      "Charles Darwin", "Alfred Russel Wallace", "Thomas Huxley", "Jean-Baptiste Lamarck",
      "He sat on the idea for two decades and only published when a rival letter forced his hand."),
    Q("science", 1, "Which green pigment lets plants capture light?",
      "Chlorophyll", "Carotene", "Melanin", "Xanthophyll",
      "It reflects green because that is the part of the spectrum it is worst at absorbing."),
    Q("science", 1, "Which dinosaur's name means 'tyrant lizard king'?",
      "Tyrannosaurus rex", "Velociraptor", "Allosaurus", "Spinosaurus",
      "It lived closer in time to us than to Stegosaurus, which was already 80 million years extinct."),
    Q("science", 1, "Which vitamin is found in large amounts in oranges and lemons?",
      "Vitamin C", "Vitamin A", "Vitamin K", "Vitamin B12",
      "Humans, guinea pigs and most bats are among the few mammals that cannot make it themselves."),
    Q("science", 1, "Frogs, toads and newts belong to which class of animals?",
      "Amphibians", "Reptiles", "Molluscs", "Arthropods",
      "The name comes from the Greek for 'both lives' -- water first, then land."),
    Q("science", 1, "What is the largest animal known to have lived?",
      "The blue whale", "The sperm whale", "The fin whale", "The African elephant",
      "Its tongue alone can weigh as much as a small car, and its heart as much as a person."),
    Q("science", 1, "Which part of a plant takes up water and minerals from the soil?",
      "The roots", "The leaves", "The stem", "The flowers",
      "Fine hairs on them multiply the surface area many times over."),

    # ---------------- difficulty 2 (20) ----------------
    Q("science", 2, "Which scale, devised in 1935, was the first widely used measure of earthquake magnitude?",
      "The Richter scale", "The Beaufort scale", "The Saffir-Simpson scale", "The Fujita scale",
      "It is logarithmic: each whole step up is about thirty times more energy released."),
    Q("science", 2, "Which class of rock forms when molten rock cools and solidifies?",
      "Igneous", "Sedimentary", "Metamorphic", "Clastic",
      "Cool it slowly underground and you get big crystals; quench it at the surface and you get glass."),
    Q("science", 2, "Which is the largest artery in the human body?",
      "The aorta", "The vena cava", "The carotid artery", "The pulmonary vein",
      "It arches straight out of the left ventricle and runs the length of the trunk."),
    Q("science", 2, "Which organ produces insulin?",
      "The pancreas", "The liver", "The adrenal gland", "The thyroid",
      "It comes from clusters of hormone cells called the islets of Langerhans, named after their discoverer."),
    Q("science", 2, "What is the hardest substance in the human body?",
      "Tooth enamel", "Bone", "Dentine", "Cartilage",
      "It contains no living cells, which is why it cannot repair itself once damaged."),
    Q("science", 2, "In DNA, which base pairs with adenine?",
      "Thymine", "Guanine", "Cytosine", "Uracil",
      "They are held together by two hydrogen bonds; the other pair uses three, so it is harder to prise apart."),
    Q("science", 2, "What is fossilised tree resin, sometimes containing trapped insects, called?",
      "Amber", "Jet", "Obsidian", "Onyx",
      "The oldest pieces with insects inside are over 100 million years old, but the DNA does not survive."),
    Q("science", 2, "Who noticed in 1928 that a mould on a culture plate was killing the bacteria around it?",
      "Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Paul Ehrlich",
      "He could not purify the active substance; Florey and Chain did that a decade later and shared his Nobel."),
    Q("science", 2, "Which human disease was declared eradicated worldwide in 1980?",
      "Smallpox", "Polio", "Rinderpest", "Measles",
      "The last natural case was in Somalia in 1977, found by a hospital cook."),
    Q("science", 2, "What is the anatomical name for the voice box?",
      "The larynx", "The pharynx", "The trachea", "The epiglottis",
      "It grows sharply in male puberty, which lowers the voice and produces the Adam's apple."),
    Q("science", 2, "Which blood component clumps together to seal a wound?",
      "Platelets", "White blood cells", "Lymphocytes", "Red blood cells",
      "They are not really cells at all but fragments shed by giant cells in the bone marrow."),
    Q("science", 2, "Mushrooms and yeasts belong to which kingdom?",
      "Fungi", "Plantae", "Protista", "Monera",
      "They are closer relatives of animals than of plants, and store energy as glycogen just as we do."),
    Q("science", 2, "Which layer makes up the largest share of the Earth's volume?",
      "The mantle", "The crust", "The outer core", "The inner core",
      "It is about 84 per cent of the planet, and it flows -- very slowly -- like extremely stiff toffee."),
    Q("science", 2, "Which is the only mammal capable of true sustained flight?",
      "The bat", "The flying squirrel", "The colugo", "The sugar glider",
      "The others only glide; a bat's wing is a webbed hand, with the membrane stretched between elongated fingers."),
    Q("science", 2, "Which coloured part of the eye controls the size of the pupil?",
      "The iris", "The cornea", "The lens", "The sclera",
      "Its pattern is set before birth and is different even between identical twins."),
    Q("science", 2, "Which butterfly-shaped gland in the neck sets the body's metabolic rate?",
      "The thyroid", "The pituitary", "The adrenal gland", "The pineal gland",
      "It needs iodine to work, which is why table salt has been iodised in many countries since the 1920s."),
    Q("science", 2, "Enzymes belong to which class of biological molecule?",
      "Proteins", "Lipids", "Carbohydrates", "Nucleic acids",
      "Their catalytic power comes from shape, which is why heat, which unfolds them, destroys their activity."),
    Q("science", 2, "Which organ stores the bile made by the liver?",
      "The gallbladder", "The spleen", "The appendix", "The duodenum",
      "You can live perfectly well without it -- bile then simply drips continuously into the gut."),
    Q("science", 2, "Which iron-containing protein gives blood its colour and carries oxygen?",
      "Haemoglobin", "Myoglobin", "Keratin", "Albumin",
      "Carbon monoxide is deadly because it latches onto it hundreds of times more tightly than oxygen does."),
    Q("science", 2, "The cochlea in the inner ear is the organ of which sense?",
      "Hearing", "Balance", "Smell", "Taste",
      "It is a coiled tube in which different points along the spiral respond to different pitches."),

    # ---------------- difficulty 3 (30) ----------------
    Q("science", 3, "Marble is the metamorphosed form of which rock?",
      "Limestone", "Sandstone", "Granite", "Shale",
      "Heat and pressure recrystallise the calcite, wiping out any fossils the original rock contained."),
    Q("science", 3, "Which geological era is known as the age of reptiles?",
      "The Mesozoic", "The Palaeozoic", "The Cenozoic", "The Precambrian",
      "It runs from about 252 to 66 million years ago and holds the Triassic, Jurassic and Cretaceous."),
    Q("science", 3, "Which geological period ended 66 million years ago?",
      "The Cretaceous", "The Jurassic", "The Triassic", "The Palaeogene",
      "Its boundary shows up worldwide as a thin clay layer rich in iridium, an element common in asteroids."),
    Q("science", 3, "Whose laboratory produced Photo 51, the X-ray image that cracked the DNA double helix?",
      "Rosalind Franklin", "Dorothy Hodgkin", "Barbara McClintock", "Gertrude Elion",
      "The image was taken by her student Raymond Gosling at King's College London in 1952."),
    Q("science", 3, "Which friar worked out the basic laws of inheritance by breeding pea plants?",
      "Gregor Mendel", "Hugo de Vries", "Thomas Hunt Morgan", "William Bateson",
      "His 1866 paper sat almost unread for 34 years until three botanists rediscovered it independently."),
    Q("science", 3, "Robert Koch identified the bacterium behind which disease in 1882?",
      "Tuberculosis", "Cholera", "Typhoid", "Diphtheria",
      "The bug's waxy coat resists ordinary stains, so he had to invent a new staining method to see it."),
    Q("science", 3, "Which fluid makes up roughly 55 per cent of the volume of whole blood?",
      "Plasma", "Serum", "Lymph", "Interstitial fluid",
      "It is over 90 per cent water, and carries the clotting proteins, salts and hormones."),
    Q("science", 3, "What is the division of a cell into two genetically identical daughter cells called?",
      "Mitosis", "Meiosis", "Binary fission", "Budding",
      "The other kind halves the chromosome number and shuffles them, which is what makes eggs and sperm."),
    Q("science", 3, "What is the term for a close relationship in which both species benefit?",
      "Mutualism", "Commensalism", "Parasitism", "Predation",
      "Lichens are the classic case: a fungus housing an alga that feeds it."),
    Q("science", 3, "What word describes a species that occurs naturally in one place and nowhere else?",
      "Endemic", "Invasive", "Cosmopolitan", "Naturalised",
      "Islands are full of them, which is also why island species are so easily wiped out."),
    Q("science", 3, "Which species is the fruit fly that became a workhorse of genetics?",
      "Drosophila melanogaster", "Caenorhabditis elegans", "Danio rerio", "Arabidopsis thaliana",
      "It has only four pairs of chromosomes and breeds in about ten days, which is why the labs love it."),
    Q("science", 3, "What is the study of fungi called?",
      "Mycology", "Bryology", "Entomology", "Phycology",
      "One of its subjects, a honey fungus in Oregon, covers several square kilometres as a single organism."),
    Q("science", 3, "CRISPR gene editing was adapted from a defence system found in which organisms?",
      "Bacteria", "Viruses", "Fungi", "Plants",
      "They keep snippets of past invaders' genetic code on file and use them to recognise a repeat attack."),
    Q("science", 3, "Which pair shared the 2020 Nobel Prize in Chemistry for CRISPR-Cas9?",
      "Jennifer Doudna and Emmanuelle Charpentier", "Feng Zhang and George Church",
      "Craig Venter and Francis Collins", "Kary Mullis and Frederick Sanger",
      "It was the first science Nobel awarded to two women with no male co-recipient."),
    Q("science", 3, "Which organelle assembles proteins from amino acids?",
      "The ribosome", "The Golgi apparatus", "The lysosome", "The nucleolus",
      "Many antibiotics work by jamming the bacterial version while leaving ours alone."),
    Q("science", 3, "What is the rigid outer shell of the Earth, broken into tectonic plates, called?",
      "The lithosphere", "The asthenosphere", "The biosphere", "The mesosphere",
      "It rides on a hotter, weaker layer beneath that deforms rather than cracking."),
    Q("science", 3, "What did Alfred Wegener name the single landmass that existed about 300 million years ago?",
      "Pangaea", "Gondwana", "Laurasia", "Rodinia",
      "He was mocked for decades because he had no mechanism -- sea-floor spreading only arrived in the 1960s."),
    Q("science", 3, "What is the junction at which one nerve cell passes a signal to the next?",
      "The synapse", "The axon", "The dendrite", "The node of Ranvier",
      "A single human neuron can have thousands of them, which is where most of the computing happens."),
    Q("science", 3, "The loss of which neurotransmitter's producing cells causes Parkinson's disease?",
      "Dopamine", "Serotonin", "Acetylcholine", "GABA",
      "Symptoms usually appear only after most of the cells in one small midbrain region are already gone."),
    Q("science", 3, "Which brain structure is essential for forming new long-term memories?",
      "The hippocampus", "The amygdala", "The thalamus", "The hypothalamus",
      "The patient known as H.M. lost his after surgery and could form no new memories for 55 years."),
    Q("science", 3, "Which human organ can regrow substantial amounts of lost tissue?",
      "The liver", "The kidney", "The lung", "The pancreas",
      "A donor can give away most of theirs and both halves grow back to working size within months."),
    Q("science", 3, "What is the loss of water vapour from a plant's leaves called?",
      "Transpiration", "Respiration", "Guttation", "Translocation",
      "The pull it creates is what hauls water up a hundred metres of trunk without any pump."),
    Q("science", 3, "Which physician had the Broad Street pump handle removed during London's 1854 cholera outbreak?",
      "John Snow", "William Farr", "Edwin Chadwick", "Joseph Bazalgette",
      "He mapped the deaths street by street when the official view was still that bad air caused disease."),
    Q("science", 3, "What is the term for a disease that jumps from animals to humans?",
      "A zoonosis", "An epizootic", "A nosocomial infection", "An endemic disease",
      "Rabies, plague and most new flu strains all arrive this way."),
    Q("science", 3, "Archaeopteryx is famous as a transitional fossil between dinosaurs and which group?",
      "Birds", "Bats", "Crocodiles", "Pterosaurs",
      "The first good specimen turned up in 1861, two years after Darwin published, which was excellent timing."),
    Q("science", 3, "Who devised the two-part Latin naming system for species?",
      "Carl Linnaeus", "Georges Cuvier", "Comte de Buffon", "John Ray",
      "He named around 12,000 species himself, and made his own bookish self the type specimen for ours."),
    Q("science", 3, "In biological classification, which rank sits between order and genus?",
      "Family", "Class", "Phylum", "Kingdom",
      "In animals its name almost always ends in -idae, as in Felidae or Hominidae."),
    N("science", 3, "How many teeth are there in a complete set of adult human teeth?",
      32, "teeth", "Twelve of them are molars, which erupt fresh and never replace a milk tooth."),
    N("science", 3, "A full-term human pregnancy is counted as how many weeks from the last period?",
      40, "weeks", "Dating it from the last period adds roughly two weeks to the true age of the embryo."),
    N("science", 3, "How many pairs of ribs does a typical adult human have?",
      12, "pairs", "The lowest two pairs are called floating ribs: attached to the spine but not to the breastbone."),

    # ---------------- difficulty 4 (25) ----------------
    Q("science", 4, "Who shared the 1962 Nobel Prize with Watson and Crick?",
      "Maurice Wilkins", "Erwin Chargaff", "Linus Pauling", "Oswald Avery",
      "The prize is never awarded posthumously, and Rosalind Franklin had died four years earlier."),
    Q("science", 4, "A deficiency of thiamine, vitamin B1, causes which disease?",
      "Beriberi", "Pellagra", "Rickets", "Kwashiorkor",
      "It spread through Asia when steam-powered mills began stripping the vitamin-rich husk off rice."),
    Q("science", 4, "Which molecule ferries amino acids to the ribosome during translation?",
      "Transfer RNA", "Messenger RNA", "Ribosomal RNA", "Micro RNA",
      "Each one is a clover-shaped adaptor: it reads three letters of code at one end and carries the cargo at the other."),
    Q("science", 4, "Which blood group system did Karl Landsteiner discover in 1901?",
      "The ABO system", "The Rhesus system", "The MN system", "The Duffy system",
      "Before it, transfusion was a lottery -- roughly a third of random donor pairings are incompatible."),
    Q("science", 4, "Which anaesthetic was famously demonstrated in a Boston operating theatre in 1846?",
      "Ether", "Chloroform", "Nitrous oxide", "Cocaine",
      "The room at Massachusetts General is still called the Ether Dome and is open to visitors."),
    Q("science", 4, "Lucy, found in Ethiopia in 1974, belongs to which species?",
      "Australopithecus afarensis", "Homo habilis", "Australopithecus africanus", "Ardipithecus ramidus",
      "She walked upright but had a brain the size of a chimpanzee's, settling which came first."),
    Q("science", 4, "Reef-building corals live in symbiosis with which photosynthetic partners?",
      "Zooxanthellae", "Cyanobacteria", "Diatoms", "Coccolithophores",
      "Bleaching is the coral expelling them under heat stress, which is why it turns white and then starves."),
    Q("science", 4, "Which thick bundle of fibres connects the two hemispheres of the brain?",
      "The corpus callosum", "The brainstem", "The pons", "The fornix",
      "Cutting it was once a treatment for severe epilepsy, and the patients gave neuroscience its split-brain studies."),
    Q("science", 4, "Which mass extinction, about 252 million years ago, is nicknamed the Great Dying?",
      "The Permian-Triassic extinction", "The Ordovician-Silurian extinction",
      "The Devonian extinction", "The Triassic-Jurassic extinction",
      "It removed the majority of marine species -- the closest life has come to being switched off entirely."),
    Q("science", 4, "Which enzyme does HIV use to copy its RNA genome into DNA?",
      "Reverse transcriptase", "Integrase", "DNA polymerase", "Protease",
      "It works in the opposite direction to the usual flow of genetic information, which is why the discovery caused a stir."),
    Q("science", 4, "Which is the largest of the Earth's tectonic plates?",
      "The Pacific Plate", "The Eurasian Plate", "The North American Plate", "The African Plate",
      "It is shrinking: subduction is eating its edges faster than the East Pacific Rise adds new floor."),
    Q("science", 4, "Which volcanic rock makes up most of the ocean floor?",
      "Basalt", "Granite", "Andesite", "Rhyolite",
      "It is denser than continental rock, which is why ocean floor sits low and gets pushed under, not over."),
    Q("science", 4, "Which Hungarian doctor cut deaths on a Vienna maternity ward by insisting on hand disinfection?",
      "Ignaz Semmelweis", "Joseph Lister", "Florence Nightingale", "Louis Pasteur",
      "Colleagues took it as an accusation and rejected him; he died in an asylum before germ theory vindicated him."),
    Q("science", 4, "Which is the most abundant protein in the human body?",
      "Collagen", "Keratin", "Actin", "Albumin",
      "It is the scaffolding of skin, tendon and bone, and vitamin C is needed to build it properly."),
    Q("science", 4, "Which lymphocytes mature in the bone marrow and give rise to antibody-producing cells?",
      "B cells", "T cells", "Natural killer cells", "Dendritic cells",
      "They were named after the bursa of Fabricius, the organ where they were first traced in birds."),
    Q("science", 4, "T cells are named after which organ, where they mature?",
      "The thymus", "The spleen", "The bone marrow", "The lymph nodes",
      "It is largest in childhood and slowly shrinks away, which is part of why immunity weakens with age."),
    Q("science", 4, "The word 'vaccine' comes from the Latin name for which animal?",
      "The cow", "The horse", "The sheep", "The goat",
      "Jenner used cowpox matter; Pasteur later extended the term to every such preparation in his honour."),
    Q("science", 4, "Which genus of mosquito transmits human malaria?",
      "Anopheles", "Aedes", "Culex", "Mansonia",
      "Only the females bite -- they need a blood meal to make eggs, and the parasite exploits the trip."),
    Q("science", 4, "The 1918 influenza pandemic was caused by which subtype of influenza A?",
      "H1N1", "H2N2", "H3N2", "H5N1",
      "The virus was reconstructed in 2005 from tissue preserved in the Alaskan permafrost."),
    Q("science", 4, "Which pores let a leaf exchange gases with the air?",
      "Stomata", "Xylem vessels", "Lenticels", "Root hairs",
      "Each is flanked by two guard cells that swell to open it and slacken to shut it in dry weather."),
    Q("science", 4, "Which is the tallest tree species on Earth?",
      "The coast redwood", "The giant sequoia", "The Douglas fir", "The mountain ash",
      "Around 115 metres seems to be the ceiling, set by how far water can be pulled up against gravity."),
    Q("science", 4, "What is the name for the rise of free oxygen in Earth's atmosphere about 2.4 billion years ago?",
      "The Great Oxidation Event", "The Cambrian explosion", "Snowball Earth", "The Late Heavy Bombardment",
      "For most life at the time it was a poisoning, which is why it is sometimes called the oxygen catastrophe."),
    N("science", 4, "In which year did Martha, the last passenger pigeon, die at Cincinnati Zoo?",
      1914, "the year", "A century earlier the species numbered in the billions and its flocks darkened the sky for hours."),
    N("science", 4, "Roughly what percentage of an average adult man's body mass is water?",
      60, "%", "Newborns run nearer 75 per cent, and the share falls with age and with body fat."),
    N("science", 4, "How many litres of blood does an average adult human body hold?",
      5, "litres", "That is about 8 per cent of body weight, which is why a donation of under half a litre is easily replaced."),

    # ---------------- difficulty 5 (15) ----------------
    Q("science", 5, "In which 1665 book did Robert Hooke publish his microscope drawings and coin the word 'cell'?",
      "Micrographia", "Systema Naturae", "De Humani Corporis Fabrica", "Historia Plantarum",
      "The cork he sliced reminded him of the bare little rooms that monks slept in."),
    Q("science", 5, "Who named the nucleus of the cell in 1831?",
      "Robert Brown", "Matthias Schleiden", "Theodor Schwann", "Rudolf Virchow",
      "The same Scottish botanist gave his name to the jittery motion of particles suspended in a fluid."),
    Q("science", 5, "Which naval surgeon ran a shipboard citrus trial in 1747, an early controlled experiment?",
      "James Lind", "John Hunter", "William Withering", "Joseph Lister",
      "The Navy took another forty years to issue lemon juice as standard, by which time scurvy had killed thousands."),
    Q("science", 5, "Which Canadian fossil site is famous for its soft-bodied Cambrian animals?",
      "The Burgess Shale", "The Green River Formation", "The Morrison Formation", "The Hell Creek Formation",
      "Charles Walcott found it in 1909; a mudslide buried the animals so fast that guts and gills survived."),
    Q("science", 5, "A deficiency of which vitamin causes pellagra?",
      "Niacin", "Thiamine", "Riboflavin", "Folate",
      "Joseph Goldberger proved in the 1910s that it was a diet problem, not the infection everyone assumed."),
    Q("science", 5, "Which enzyme rebuilds the repeated DNA caps at the ends of chromosomes?",
      "Telomerase", "Ligase", "Topoisomerase", "Primase",
      "Most adult body cells switch it off, which is one reason they can only divide a limited number of times."),
    Q("science", 5, "Barbara McClintock discovered jumping genes while studying which crop?",
      "Maize", "Wheat", "Rice", "Barley",
      "The speckled colour of the kernels was her readout, and she won an unshared Nobel for it in 1983."),
    Q("science", 5, "Which biologist spent decades arguing that mitochondria began as free-living bacteria?",
      "Lynn Margulis", "Rachel Carson", "Rita Levi-Montalcini", "Nettie Stevens",
      "Her 1967 paper was turned down by around fifteen journals before one would print it."),
    Q("science", 5, "What is the boundary between the Earth's crust and the mantle called?",
      "The Mohorovicic discontinuity", "The Gutenberg discontinuity",
      "The Lehmann discontinuity", "The Conrad discontinuity",
      "It was spotted in 1909 because earthquake waves arrived twice, one set having sped up in the denser rock below."),
    Q("science", 5, "Which mineral group is the most abundant in the Earth's crust?",
      "Feldspar", "Quartz", "Mica", "Olivine",
      "Between them the plagioclase and alkali varieties account for well over half the crust by volume."),
    Q("science", 5, "Which British botanist coined the word 'ecosystem' in 1935?",
      "Arthur Tansley", "Charles Elton", "Julian Huxley", "Frederic Clements",
      "He introduced it while attacking the fashionable idea that a plant community behaves like a single organism."),
    Q("science", 5, "Carl Woese's 1977 work on ribosomal RNA established which third domain of life?",
      "Archaea", "Protista", "Eukarya", "Monera",
      "They look like bacteria down a microscope but their molecular machinery is closer to ours."),
    Q("science", 5, "Which faunal boundary, running between Bali and Lombok, is named after a 19th-century naturalist?",
      "The Wallace Line", "The Weber Line", "The Lydekker Line", "The Huxley Line",
      "The strait is only about 35 km across but deep, so it stayed flooded through the ice ages and kept the faunas apart."),
    N("science", 5, "In which year was the Human Genome Project declared complete?",
      2003, "the year", "It ran for thirteen years and finished early, spurred on by a race with a rival private effort."),
    N("science", 5, "In which year was Dolly the sheep born?",
      1996, "the year", "She was named after Dolly Parton because the cell she was cloned from came from a mammary gland."),
]
