# -*- coding: utf-8 -*-
"""Science bank A: physics, chemistry, astronomy and mathematics."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [

    # ---------------- difficulty 1 ----------------
    Q("science", 1, "Which planet orbits closest to the Sun?",
      "Mercury", "Venus", "Mars", "Earth",
      "It is not the hottest, though -- Venus keeps that title thanks to a runaway greenhouse effect."),
    Q("science", 1, "At sea level, water boils at what temperature in Celsius?",
      "100 degrees", "90 degrees", "110 degrees", "120 degrees",
      "The scale was built around it: Celsius fixed 0 at freezing and 100 at boiling for pure water."),
    Q("science", 1, "Which planet is the largest in the solar system?",
      "Jupiter", "Saturn", "Neptune", "Uranus",
      "It outweighs every other planet combined, twice over, and still falls far short of being a star."),
    Q("science", 1, "Which planet is circled by the solar system's brightest ring system?",
      "Saturn", "Jupiter", "Neptune", "Uranus",
      "The rings are mostly water ice, and they are only tens of metres thick in places."),
    Q("science", 1, "What is pi rounded to two decimal places?",
      "3.14", "3.12", "3.16", "3.41",
      "The fraction 22/7 gets you to 3.1428, which was good enough for engineers for centuries."),
    Q("science", 1, "How many degrees are there in a complete turn?",
      "360", "180", "270", "400",
      "Surveyors briefly pushed a metric circle of 400 gradians, and it survives on some calculators."),
    Q("science", 1, "Which force pulls a dropped apple towards the ground?",
      "Gravity", "Friction", "Magnetism", "Inertia",
      "It is by far the weakest of the four fundamental forces -- a fridge magnet beats the whole planet."),
    Q("science", 1, "Whose equation is E = mc squared?",
      "Albert Einstein", "Niels Bohr", "Max Planck", "Enrico Fermi",
      "It appeared in a three-page afterthought to his 1905 paper on special relativity."),
    Q("science", 1, "What is the dense central part of an atom called?",
      "The nucleus", "The electron shell", "The orbital", "The valence shell",
      "It holds almost all the mass in about a hundred-thousandth of the atom's width."),
    Q("science", 1, "A triangle with three sides of equal length is called what?",
      "Equilateral", "Isosceles", "Scalene", "Obtuse",
      "All three angles are then forced to be 60 degrees, which is why triangular tiling works so neatly."),

    # ---------------- difficulty 2 ----------------
    Q("science", 2, "What is the SI unit of electrical resistance?",
      "The ohm", "The volt", "The watt", "The farad",
      "Its symbol is the Greek capital omega, chosen because a Latin O would look like a zero."),
    Q("science", 2, "Which metal has the chemical symbol Pb?",
      "Lead", "Tin", "Zinc", "Nickel",
      "From the Latin plumbum, which also gives us plumbing -- Roman water pipes were made of it."),
    Q("science", 2, "Which effect makes a passing siren drop in pitch?",
      "The Doppler effect", "The Coriolis effect", "The Venturi effect", "The Zeeman effect",
      "The same trick on starlight is how we know distant galaxies are rushing away from us."),
    Q("science", 2, "What is the bending of light as it passes from air into water called?",
      "Refraction", "Diffraction", "Reflection", "Polarisation",
      "Light slows in water, and the change of speed is what kinks the ray at the surface."),
    Q("science", 2, "The elements in group 1 of the periodic table are known as what?",
      "The alkali metals", "The alkaline earth metals", "The halogens", "The transition metals",
      "They get more violent with water going down the group -- caesium explodes on contact."),
    Q("science", 2, "Which acid gives vinegar its sharp taste?",
      "Acetic acid", "Citric acid", "Lactic acid", "Formic acid",
      "Table vinegar is only about five per cent of it -- the rest is essentially water."),
    Q("science", 2, "What is a substance that speeds up a reaction without being consumed?",
      "A catalyst", "A reagent", "A solvent", "A buffer",
      "It works by offering a lower-energy route, not by pushing the reaction anywhere new."),
    Q("science", 2, "Brass is an alloy of copper and which other metal?",
      "Zinc", "Tin", "Lead", "Nickel",
      "Swap the zinc for tin and you get bronze, which is harder and far older."),
    Q("science", 2, "Which process powers the Sun?",
      "Nuclear fusion", "Nuclear fission", "Combustion", "Radioactive decay",
      "Four hydrogen nuclei become one helium nucleus, and the missing mass leaves as energy."),
    Q("science", 2, "What is the brightest star in the night sky?",
      "Sirius", "Vega", "Canopus", "Betelgeuse",
      "It is not especially luminous -- it just happens to sit only 8.6 light years away."),
    Q("science", 2, "The Plough sits inside which constellation?",
      "Ursa Major", "Ursa Minor", "Cassiopeia", "Bootes",
      "Two of its stars point straight at Polaris, which is why it has guided travellers for millennia."),
    Q("science", 2, "Which Apollo mission was crippled by an exploding oxygen tank?",
      "Apollo 13", "Apollo 11", "Apollo 12", "Apollo 8",
      "The crew swung round the Moon and came home on the lunar module used as a lifeboat."),
    Q("science", 2, "What was the first artificial satellite to orbit Earth?",
      "Sputnik 1", "Explorer 1", "Vostok 1", "Telstar",
      "It carried little more than a radio beeper, which amateurs worldwide could tune in and hear."),
    Q("science", 2, "Which space telescope launched in 1990 with a flawed mirror?",
      "The Hubble Space Telescope", "The Chandra Observatory", "The Kepler telescope",
      "The Spitzer telescope",
      "The mirror was ground too flat by about a fiftieth of a hair's width; a 1993 servicing flight fixed it."),
    Q("science", 2, "What is the longest side of a right-angled triangle called?",
      "The hypotenuse", "The adjacent", "The opposite", "The perpendicular",
      "From the Greek for 'stretching under' -- it always sits opposite the right angle."),
    Q("science", 2, "Which result says a squared plus b squared equals c squared?",
      "Pythagoras' theorem", "Thales' theorem", "Ptolemy's theorem", "Euclid's theorem",
      "Babylonian tablets list the same number triples over a thousand years before Pythagoras."),
    Q("science", 2, "Which Greek mathematician wrote the Elements?",
      "Euclid", "Archimedes", "Apollonius", "Eratosthenes",
      "It stayed a standard school text for well over two thousand years."),
    Q("science", 2, "Whose thought experiment leaves a cat in a box with a radioactive trigger?",
      "Erwin Schrödinger", "Werner Heisenberg", "Niels Bohr", "Paul Dirac",
      "He meant it as a reductio -- the absurd cat was an attack on the theory, not a fan letter."),
    Q("science", 2, "Give a paper strip a half twist and join the ends, and you get what?",
      "The Möbius strip", "The Klein bottle", "The torus", "The helix",
      "Run a pencil along it and you return to the start having covered what looks like both sides."),
    Q("science", 2, "Newton's second law says force equals what?",
      "Mass times acceleration", "Mass times velocity", "Momentum over distance", "Energy over time",
      "Newton actually wrote it as the rate of change of momentum, which still holds when mass varies."),

    # ---------------- difficulty 3 ----------------
    Q("science", 3, "Which law of thermodynamics says entropy in an isolated system never decreases?",
      "The second law", "The first law", "The third law", "The zeroth law",
      "It is the reason heat flows one way and why a perfect engine is impossible."),
    Q("science", 3, "Who discovered electromagnetic induction in 1831?",
      "Michael Faraday", "Alessandro Volta", "Hans Christian Oersted", "Georg Ohm",
      "He had almost no mathematics, so he thought in field lines -- the picture we still teach."),
    Q("science", 3, "Whose four equations unified electricity, magnetism and light?",
      "James Clerk Maxwell", "Hendrik Lorentz", "Heinrich Hertz", "Andre-Marie Ampere",
      "Born in Edinburgh; his equations predicted that light itself is an electromagnetic wave."),
    Q("science", 3, "Whose gold foil experiment revealed that atoms have a tiny dense centre?",
      "Ernest Rutherford", "J.J. Thomson", "Niels Bohr", "Henry Moseley",
      "He compared it to firing a shell at tissue paper and having it bounce back at you."),
    Q("science", 3, "Einstein's 1921 Nobel Prize was for explaining which effect?",
      "The photoelectric effect", "The Compton effect", "The Zeeman effect", "The Casimir effect",
      "Not relativity -- the committee thought the light-quantum paper was the safer bet."),
    Q("science", 3, "What is the term for a fast-moving clock ticking slowly as seen from rest?",
      "Time dilation", "Length contraction", "Frame dragging", "Lorentz invariance",
      "GPS satellites correct for it daily, or navigation would drift by kilometres."),
    Q("science", 3, "Which particle carries the electromagnetic force?",
      "The photon", "The W boson", "The graviton", "The muon",
      "It has no mass, which is exactly why the force it carries reaches out to infinity."),
    Q("science", 3, "Which physicist showed that black holes should slowly radiate and evaporate?",
      "Stephen Hawking", "Roger Penrose", "Kip Thorne", "John Wheeler",
      "The smaller the hole, the hotter it glows -- so the last moments are a burst, not a fade."),
    Q("science", 3, "Which element takes its symbol from the Latin word natrium?",
      "Sodium", "Potassium", "Nickel", "Niobium",
      "Potassium's K comes the same way, from kalium, the Latin for potash."),
    Q("science", 3, "Which halogen is a liquid at room temperature?",
      "Bromine", "Iodine", "Chlorine", "Fluorine",
      "It and mercury are the only two elements that are liquid in a normal room."),
    Q("science", 3, "Which element was found in the Sun before it was ever found on Earth?",
      "Helium", "Neon", "Argon", "Hydrogen",
      "An unexplained yellow line in the 1868 eclipse spectrum gave it away; the name means sun."),
    Q("science", 3, "The Curies named which element after Marie's native country?",
      "Polonium", "Radium", "Curium", "Francium",
      "A pointed choice in 1898, when Poland did not exist as a state on any map."),
    Q("science", 3, "Steel is iron alloyed chiefly with which element?",
      "Carbon", "Chromium", "Nickel", "Manganese",
      "Under about two per cent by weight and it is steel; above that and it becomes brittle cast iron."),
    Q("science", 3, "The Haber process combines nitrogen and hydrogen to make what?",
      "Ammonia", "Nitric acid", "Hydrazine", "Urea",
      "It feeds roughly half the people alive by turning air into fertiliser."),
    Q("science", 3, "What is the name for a sheet of carbon exactly one atom thick?",
      "Graphene", "Graphite", "Fullerene", "Carbon nanotube",
      "It was first isolated in Manchester using sticky tape to peel layers off pencil lead."),
    Q("science", 3, "Which moon is the most volcanically active world in the solar system?",
      "Io", "Europa", "Triton", "Callisto",
      "Jupiter's tidal pull kneads its interior, so its sulphurous surface repaves itself constantly."),
    Q("science", 3, "Which moon has a thick nitrogen atmosphere and lakes of liquid methane?",
      "Titan", "Ganymede", "Europa", "Triton",
      "It is the only place besides Earth where we have found standing liquid on the surface."),
    Q("science", 3, "Which probe sent back the first close-up pictures of Pluto in 2015?",
      "New Horizons", "Voyager 2", "Juno", "Dawn",
      "It flew past at 14 km per second, so the whole encounter was over in hours after a nine-year trip."),
    Q("science", 3, "Which spacecraft studied Saturn for 13 years before burning up in its atmosphere?",
      "Cassini", "Galileo", "Magellan", "Juno",
      "It was deliberately destroyed in 2017 so it could never contaminate Enceladus or Titan."),
    Q("science", 3, "What is the ring of icy bodies beyond Neptune's orbit called?",
      "The Kuiper Belt", "The Oort Cloud", "The asteroid belt", "The heliosphere",
      "Pluto is simply one of its larger members, which is the heart of why it lost planet status."),
    Q("science", 3, "What is the Sun's outer atmosphere, seen as a halo during a total eclipse?",
      "The corona", "The chromosphere", "The photosphere", "The heliopause",
      "It is millions of degrees hotter than the surface below it, and nobody fully agrees why."),
    Q("science", 3, "What will the Sun eventually become once it has shed its outer layers?",
      "A white dwarf", "A neutron star", "A black hole", "A brown dwarf",
      "An Earth-sized ember of carbon and oxygen, cooling quietly for longer than the universe has existed."),
    Q("science", 3, "What is the faint afterglow of the early universe, first detected in 1964?",
      "The cosmic microwave background", "The solar wind", "Synchrotron radiation",
      "The Lyman-alpha forest",
      "It was released when the universe first turned transparent, about 380,000 years in."),
    Q("science", 3, "What is the stretching of light from a galaxy rushing away from us called?",
      "Redshift", "Blueshift", "Parallax", "Aberration",
      "Space itself expanding stretches the wave in flight -- the galaxy is not really moving through space."),
    Q("science", 3, "Whose incompleteness theorems shook the foundations of mathematics in 1931?",
      "Kurt Gödel", "David Hilbert", "Bertrand Russell", "Alan Turing",
      "Any system rich enough for arithmetic contains true statements it cannot prove."),
    Q("science", 3, "Who developed calculus independently of Newton?",
      "Gottfried Leibniz", "Leonhard Euler", "Blaise Pascal", "Pierre-Simon Laplace",
      "His notation won -- the dy/dx and the elongated S for integration are both his."),
    Q("science", 3, "Which conjecture claims every even number above two is a sum of two primes?",
      "Goldbach's conjecture", "The twin prime conjecture", "The Collatz conjecture",
      "The abc conjecture",
      "Checked by computer past four quintillion, and still nobody has a proof."),
    N("science", 3, "How old is the universe in billions of years, to one decimal place?",
      13.8, "billion years",
      "Pinned down by the pattern of ripples in the cosmic background, not by dating anything directly."),
    N("science", 3, "What is absolute zero in degrees Celsius, to two decimal places?",
      -273.15, "degrees Celsius",
      "It is a limit, not a destination: you can get arbitrarily close but never actually reach it."),
    N("science", 3, "In which year did astronomers reclassify Pluto as a dwarf planet?",
      2006, "the year",
      "The deciding clause was clearing its orbital neighbourhood, which Pluto shares with the Kuiper Belt."),

    # ---------------- difficulty 4 ----------------
    Q("science", 4, "Which metal has the highest melting point of any element?",
      "Tungsten", "Rhenium", "Osmium", "Tantalum",
      "At 3,422 degrees Celsius, which is why it spent a century as the filament in light bulbs."),
    Q("science", 4, "Which element is named after a village in the Scottish Highlands?",
      "Strontium", "Yttrium", "Hafnium", "Rhenium",
      "Strontian in Argyll, where the mineral was dug out of a lead mine in the 1790s."),
    Q("science", 4, "Which element is named after the Greek titan who stole fire?",
      "Promethium", "Titanium", "Thorium", "Vanadium",
      "Fitting for an element with no stable isotope, plucked from the wreckage of nuclear fission."),
    Q("science", 4, "Vulcanising rubber means heating it with which element?",
      "Sulphur", "Carbon", "Phosphorus", "Silicon",
      "The sulphur bridges lock the polymer chains together, so the rubber stops going sticky in heat."),
    Q("science", 4, "Teflon is the trade name for which polymer?",
      "Polytetrafluoroethylene", "Polyvinyl chloride", "Polystyrene", "Polypropylene",
      "Found by accident in 1938 when a cylinder of gas polymerised itself into a waxy white powder."),
    Q("science", 4, "In the Bronsted-Lowry scheme, an acid is a substance that does what?",
      "Donates a proton", "Accepts a proton", "Accepts an electron pair", "Releases a hydroxide ion",
      "Lewis went further and defined acids by electron pairs, which catches species with no hydrogen at all."),
    Q("science", 4, "Which particle carries the strong force between quarks?",
      "The gluon", "The W boson", "The Z boson", "The pion",
      "Unusually, it carries the charge it acts on, so gluons pull on each other as well as on quarks."),
    Q("science", 4, "Who discovered the neutron in 1932?",
      "James Chadwick", "Frederick Soddy", "Patrick Blackett", "John Cockcroft",
      "It closed the puzzle of why atomic mass was roughly double atomic number."),
    Q("science", 4, "Which principle forbids two electrons in an atom from having identical quantum numbers?",
      "The Pauli exclusion principle", "Hund's rule", "The Aufbau principle",
      "The correspondence principle",
      "It is why electrons stack into shells at all, and so why chemistry has any structure."),
    Q("science", 4, "Who led the 1919 eclipse expedition that confirmed light bending near the Sun?",
      "Arthur Eddington", "Oliver Lodge", "James Jeans", "Harold Jeffreys",
      "A Quaker pacifist championing a German physicist's theory months after the war was pointed news."),
    Q("science", 4, "The first gravitational waves detected in 2015 came from the merger of what?",
      "Two black holes", "Two neutron stars", "Two white dwarfs", "A star and a black hole",
      "The signal lasted a fifth of a second and moved the detector mirrors by a fraction of a proton's width."),
    Q("science", 4, "What is the eerie blue glow in the water of a nuclear reactor pool called?",
      "Cherenkov radiation", "Bremsstrahlung", "Synchrotron radiation", "Fluorescence",
      "It appears when particles outrun light in water -- an optical version of a sonic boom."),
    Q("science", 4, "The 2019 redefinition pinned the kilogram to a fixed value of which constant?",
      "The Planck constant", "Avogadro's constant", "The Boltzmann constant",
      "The gravitational constant",
      "The old platinum-iridium cylinder in Paris had quietly drifted against its own copies for decades."),
    Q("science", 4, "The SI second is defined by a transition in an atom of which element?",
      "Caesium", "Rubidium", "Strontium", "Ytterbium",
      "Exactly 9,192,631,770 oscillations, a number chosen to match the old astronomical second."),
    Q("science", 4, "Since 1983, the metre has been defined in terms of what?",
      "The speed of light", "A platinum-iridium bar", "A wavelength of krypton-86",
      "A fraction of the Earth's meridian",
      "That fixes light's speed by definition, so measuring it now just measures your ruler."),
    Q("science", 4, "Which radio telescope's 305-metre dish collapsed in 2020?",
      "Arecibo", "Jodrell Bank", "Green Bank", "Parkes",
      "Slung across a Puerto Rican sinkhole, it sent the 1974 interstellar message towards cluster M13."),
    Q("science", 4, "Which lander touched down on comet 67P in 2014?",
      "Philae", "Huygens", "Beagle 2", "Hayabusa",
      "Its harpoons failed, so it bounced a kilometre high and ended up in shadow with dying batteries."),
    Q("science", 4, "Who spotted the first pulsar in 1967 while a research student?",
      "Jocelyn Bell Burnell", "Vera Rubin", "Annie Jump Cannon", "Cecilia Payne-Gaposchkin",
      "The signal was so regular that the team half-jokingly labelled it LGM-1, for little green men."),
    Q("science", 4, "What is the supermassive black hole at the centre of our galaxy called?",
      "Sagittarius A*", "Cygnus X-1", "M87*", "Centaurus A",
      "About four million solar masses, inferred from watching stars whip around an invisible point."),
    Q("science", 4, "Which moon of Saturn sprays plumes of water ice from its south pole?",
      "Enceladus", "Mimas", "Dione", "Rhea",
      "The plumes feed Saturn's E ring and hint at a salty ocean under the ice."),
    Q("science", 4, "Who proved the Poincaré conjecture and then turned down the Fields Medal?",
      "Grigori Perelman", "Terence Tao", "Yitang Zhang", "Michael Atiyah",
      "He also declined the million-dollar Clay prize, saying the recognition itself was of no interest."),
    Q("science", 4, "Which theorem, settled in 1976, was the first major proof to lean on a computer?",
      "The four colour theorem", "The Kepler conjecture", "The Jordan curve theorem",
      "The prime number theorem",
      "It reduced the problem to nearly 2,000 configurations, each checked by machine -- and mathematicians grumbled."),
    N("science", 4, "In dry air at 20 degrees Celsius, how fast does sound travel in metres per second?",
      343, "metres per second",
      "It depends on temperature, not pressure, so sound is slower on a cold day than a warm one."),
    N("science", 4, "What is Earth's escape velocity in kilometres per second, to the nearest whole number?",
      11, "km per second",
      "It ignores air resistance, and it is the same whatever direction you fire in."),
    N("science", 4, "Avogadro's constant is about 6.022 times ten to the power of what?",
      23, "the power",
      "Since 2019 it is an exact defined number, and it is what now fixes the size of the mole."),

    # ---------------- difficulty 5 ----------------
    Q("science", 5, "Which Swedish village has four chemical elements named after it?",
      "Ytterby", "Falun", "Kiruna", "Sala",
      "Yttrium, ytterbium, terbium and erbium all trace back to one small quarry outside Stockholm."),
    Q("science", 5, "Which element is named after the Roman name for Paris?",
      "Lutetium", "Gallium", "Francium", "Europium",
      "Lutetia; its discovery in 1907 set off a bitter three-way priority row across Europe."),
    Q("science", 5, "Which element was the first to be produced artificially in a laboratory?",
      "Technetium", "Neptunium", "Astatine", "Francium",
      "Made in 1937 by bombarding molybdenum, and its name simply means artificial."),
    Q("science", 5, "Which effect expels magnetic field from a superconductor, letting a magnet levitate?",
      "The Meissner effect", "The Josephson effect", "The Hall effect", "The Casimir effect",
      "It is the real signature of superconductivity -- zero resistance alone would not push the field out."),
    Q("science", 5, "Which satellite first mapped tiny temperature ripples in the cosmic background in 1992?",
      "COBE", "WMAP", "Planck", "IRAS",
      "The variations are about one part in a hundred thousand, and they seeded every galaxy there is."),
    Q("science", 5, "Which industrial process turns ammonia into nitric acid?",
      "The Ostwald process", "The Contact process", "The Solvay process", "The Frasch process",
      "Paired with Haber, it let a country make explosives and fertiliser without importing a thing."),
    Q("science", 5, "Emmy Noether's theorem links every continuous symmetry to what?",
      "A conservation law", "A quantum number", "A gauge boson", "A broken symmetry",
      "Symmetry in time gives conservation of energy; symmetry in space gives conservation of momentum."),
    Q("science", 5, "Which 1887 experiment failed to find the aether and cleared the way for relativity?",
      "The Michelson-Morley experiment", "The Cavendish experiment", "The Fizeau experiment",
      "The Kaufmann experiment",
      "Its celebrated null result is arguably the most productive failure in the history of physics."),
    Q("science", 5, "Which experiment split a beam of silver atoms in two, revealing quantised spin?",
      "The Stern-Gerlach experiment", "The Franck-Hertz experiment", "The Davisson-Germer experiment",
      "The Compton experiment",
      "The silver only showed up on the plate because one of them smoked cheap, sulphurous cigars."),
    Q("science", 5, "Which Japanese detector is a vast tank of ultrapure water ringed with photomultipliers?",
      "Super-Kamiokande", "IceCube", "SNO", "Borexino",
      "It showed that neutrinos change flavour in flight, which means they must have mass."),
    Q("science", 5, "Which two LHC experiments jointly announced the Higgs boson discovery in 2012?",
      "ATLAS and CMS", "ALICE and LHCb", "CDF and D0", "BaBar and Belle",
      "They are deliberately built on different principles, so neither can talk the other into a false signal."),
    Q("science", 5, "Who proved in 1882 that pi is transcendental?",
      "Ferdinand von Lindemann", "Charles Hermite", "Joseph Liouville", "Georg Cantor",
      "That killed squaring the circle for good -- no ruler and compass can ever manage it."),
    Q("science", 5, "Mathematicians measure collaboration distance using whose number?",
      "Paul Erdos", "John von Neumann", "George Polya", "Alfred Renyi",
      "He wrote around 1,500 papers while living out of a suitcase and staying on colleagues' sofas."),
    N("science", 5, "What is the Chandrasekhar limit in solar masses, to one decimal place?",
      1.4, "solar masses",
      "Above it, electron pressure loses to gravity and the white dwarf collapses -- the trigger for a type Ia supernova."),
    N("science", 5, "What is the temperature of the Sun's visible surface in kelvin, to the nearest hundred?",
      5800, "kelvin",
      "The core runs at about 15 million kelvin, so the surface is the cool skin over the furnace."),
]
