# -*- coding: utf-8 -*-
"""Sport questions: football, Olympics, tennis, cricket, rugby, golf, motorsport, cycling, US sports, and more."""


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a,
            "wrong": [w1, w2, w3], "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = [
    # ---- batch 1 ----
    Q("sport", 1, "In golf, what is the name for the person who carries a player's clubs?",
      "A caddie", "A marshal", "A starter", "A steward",
      "The word came into golf from the French cadet, a younger son, by way of Scots."),
    Q("sport", 1, "What is the name of Wimbledon's principal show court?",
      "Centre Court", "No. 1 Court", "Grandstand Court", "Championship Court",
      "Its roof was only finished in 2009, ending decades of rain-delayed finals."),
    Q("sport", 1, "How many squares are there on a chessboard?",
      "64", "72", "81", "100",
      "Eight ranks by eight files, which is why chess notation only ever needs a1 to h8."),
    Q("sport", 1, "Which ballpark is the home of the Boston Red Sox?",
      "Fenway Park", "Wrigley Field", "Yankee Stadium", "Camden Yards",
      "Opened in 1912, it is the oldest ground still in use in Major League Baseball."),
    Q("sport", 2, "Which country beat Brazil 3-0 in the 1998 World Cup final?",
      "France", "Italy", "The Netherlands", "Croatia",
      "Zinedine Zidane headed two of them, from corners, inside the first half."),
    Q("sport", 2, "Which stadium hosted the 1966 World Cup final?",
      "Wembley Stadium", "Villa Park", "Goodison Park", "Hillsborough",
      "Goodison Park took a semi-final that year, the only one played outside London."),
    Q("sport", 2, "Which city hosted the 1936 Summer Olympics?",
      "Berlin", "Munich", "Amsterdam", "Antwerp",
      "The torch relay from Olympia was invented for these Games, not the ancient ones."),
    Q("sport", 2, "Which club did Manchester United beat in the 1999 Champions League final?",
      "Bayern Munich", "Borussia Dortmund", "Real Madrid", "Internazionale",
      "Their opponents had already tied ribbons in their colours to the trophy."),
    Q("sport", 2, "Which Grand Slam tennis tournament is played at Melbourne Park?",
      "The Australian Open", "The US Open", "Wimbledon", "The French Open",
      "It moved there in 1988 from Kooyong, and was the first major with a retractable roof."),
    Q("sport", 2, "Which cricket ground is known as the home of cricket?",
      "Lord's", "The Oval", "Trent Bridge", "Edgbaston",
      "Thomas Lord's third ground, opened in 1814, still slopes about two and a half metres."),
    Q("sport", 3, "The Premier League broke away from which competition in 1992?",
      "The Football League First Division", "The Football Alliance", "The Southern League",
      "The Football Combination",
      "The point of the split was to keep the television money rather than share it downward."),
    Q("sport", 3, "Which club won the first five European Cups, from 1956 to 1960?",
      "Real Madrid", "Benfica", "AC Milan", "Internazionale",
      "The fifth was a 7-3 win at Hampden Park, still cited as the finest final played."),
    Q("sport", 3, "Which country won Euro 2004 at odds of about 150-1?",
      "Greece", "Portugal", "The Czech Republic", "Denmark",
      "They beat the hosts twice, in the opening game and again in the final."),
    Q("sport", 3, "Which nation won Euro 1992 after being called up to replace Yugoslavia?",
      "Denmark", "Sweden", "Norway", "Belgium",
      "Yugoslavia had qualified but was excluded under sanctions weeks before kick-off."),
    Q("sport", 3, "How long is a cricket pitch between the two sets of stumps?",
      "22 yards", "20 yards", "24 yards", "25 yards",
      "One chain, an old surveyor's unit, which is also why an acre is ten square chains."),
    Q("sport", 3, "Which Houston venue was the world's first domed sports stadium when it opened in 1965?",
      "The Astrodome", "The Superdome", "The Kingdome", "The Silverdome",
      "Its glare-proofed roof killed the grass, so the replacement turf was named after the team."),
    Q("sport", 3, "Which trophy is awarded to the winner of the Super Bowl?",
      "The Vince Lombardi Trophy", "The Halas Trophy", "The Rozelle Trophy", "The Thorpe Trophy",
      "Tiffany makes a fresh one each year, so winners keep it rather than pass it on."),
    Q("sport", 4, "Which country won the first European Championship, in 1960?",
      "The Soviet Union", "Yugoslavia", "Spain", "Italy",
      "Only four teams reached the finals, and Spain had withdrawn rather than travel to Moscow."),
    Q("sport", 4, "Who missed the decisive penalty in the 1994 World Cup final shoot-out?",
      "Roberto Baggio", "Franco Baresi", "Daniele Massaro", "Giuseppe Signori",
      "Baresi had missed the first one, having played the match weeks after knee surgery."),
    Q("sport", 4, "Which stadium hosted the 1994 World Cup final?",
      "The Rose Bowl", "Soldier Field", "Giants Stadium", "The Cotton Bowl",
      "Pasadena also staged the 1984 Olympic football final and the 1999 women's final."),
    Q("sport", 4, "What was the name of the dog that found the stolen World Cup trophy in 1966?",
      "Pickles", "Bramble", "Rufus", "Nipper",
      "He sniffed it out wrapped in newspaper under a hedge in south London, a week after the theft."),
    Q("sport", 4, "Which Manchester United player survived the Munich crash and captained the club to the 1968 European Cup?",
      "Bobby Charlton", "Denis Law", "Nobby Stiles", "Bill Foulkes",
      "He also scored twice in that final, having been pulled from the wreckage ten years earlier."),
    Q("sport", 5, "Which club did Nottingham Forest beat in the 1979 European Cup final?",
      "Malmo FF", "Hamburg", "Club Brugge", "Borussia Monchengladbach",
      "Trevor Francis headed the only goal, in his first season as Britain's costliest player."),
    Q("sport", 5, "In which newspaper did the 1882 mock obituary that created cricket's Ashes appear?",
      "The Sporting Times", "The Sporting Life", "The Cricketer", "The Pall Mall Gazette",
      "It mourned English cricket and said the body would be cremated, the ashes taken to Australia."),
    Q("sport", 5, "Which world chess champion was known as the Magician from Riga?",
      "Mikhail Tal", "Mikhail Botvinnik", "Tigran Petrosian", "Vasily Smyslov",
      "He took the title in 1960 at 23 and lost it back to Botvinnik a year later."),

    # ---- batch 2 ----
    Q("sport", 1, "What colour is the background of the Olympic flag?",
      "White", "Blue", "Grey", "Cream",
      "Coubertin chose the five ring colours plus white so every competing nation had one of them."),
    Q("sport", 1, "In a standard tennis game, what score comes after 30?",
      "40", "45", "50", "Game",
      "The sequence probably ran 15-30-45 on a clock face before 45 got shortened in speech."),
    Q("sport", 1, "Which flag is waved to signal the end of a Formula One race?",
      "The chequered flag", "The yellow flag", "The red flag", "The black flag",
      "A black flag is aimed at one car and means come in, you are disqualified."),
    Q("sport", 2, "Which swimmer won eight gold medals at the 2008 Beijing Olympics?",
      "Michael Phelps", "Ian Thorpe", "Mark Spitz", "Ryan Lochte",
      "One of the eight was won by a hundredth of a second in the 100 metres butterfly."),
    Q("sport", 2, "Who was the first man to run a mile in under four minutes?",
      "Roger Bannister", "Chris Chataway", "John Landy", "Gordon Pirie",
      "Chataway was one of his pacemakers at Iffley Road, and Landy broke it again 46 days later."),
    Q("sport", 2, "Which computer beat Garry Kasparov in a match in 1997?",
      "Deep Blue", "Deep Thought", "Hydra", "Fritz",
      "Kasparov had beaten the same machine the year before, then demanded a rematch he lost."),
    Q("sport", 2, "How many innings make up a standard Major League Baseball game?",
      "Nine", "Seven", "Eight", "Ten",
      "If the home side already leads after the visitors bat in the ninth, the last half is not played."),
    Q("sport", 2, "What is the standard height of a basketball hoop above the floor?",
      "10 feet", "9 feet", "11 feet", "12 feet",
      "It is where the peach baskets happened to be nailed in the gym in 1891, and nobody moved it."),
    Q("sport", 3, "Which London cricket ground traditionally stages the final Test of an English summer?",
      "The Oval", "Trent Bridge", "Old Trafford", "Headingley",
      "It hosted England's first home Test, in 1880, and sits on land leased from the Duchy of Cornwall."),
    Q("sport", 3, "In which year did the Five Nations become the Six Nations?",
      "2000", "1996", "1998", "2002",
      "Italy marked the expansion by beating Scotland 34-20 in Rome in their opening match."),
    Q("sport", 3, "Which trophy do England and Scotland contest in rugby union?",
      "The Calcutta Cup", "The Millennium Trophy", "The Centenary Quaich", "The Triple Crown",
      "It was made from melted-down silver rupees when the Calcutta club wound itself up in 1878."),
    Q("sport", 3, "Which country won the first Rugby World Cup, in 1987?",
      "New Zealand", "Australia", "France", "South Africa",
      "There was no qualifying that year -- sixteen sides were simply invited."),
    Q("sport", 3, "Which golf major is played on the same course every year?",
      "The Masters", "The Open Championship", "The US Open", "The PGA Championship",
      "It is also the youngest of the four, first played in 1934, and the only one its club owns."),
    Q("sport", 3, "What is the name of the trophy awarded to the Open Championship winner?",
      "The Claret Jug", "The Wanamaker Trophy", "The Green Jacket", "The Gold Vase",
      "It replaced the original prize, a red leather belt, which a three-time winner kept outright."),
    Q("sport", 3, "In which year was the first Formula One World Championship contested?",
      "1950", "1946", "1948", "1954",
      "Seven races counted, six in Europe plus the Indianapolis 500, which the regulars skipped."),
    Q("sport", 3, "Which corner at Spa-Francorchamps sweeps steeply uphill out of a valley?",
      "Eau Rouge", "Tamburello", "Parabolica", "Ascari",
      "It is named after the reddish stream that runs under the track at the bottom of the dip."),
    Q("sport", 4, "Which Colombian goalkeeper produced the scorpion kick save at Wembley in 1995?",
      "Rene Higuita", "Faryd Mondragon", "Oscar Cordoba", "Jose Chilavert",
      "The shot was drifting out anyway, so the flourish was entirely for the cameras."),
    Q("sport", 4, "Which African nation reached the World Cup quarter-finals in 1990?",
      "Cameroon", "Nigeria", "Morocco", "Senegal",
      "They opened by beating the holders Argentina with nine men still on the pitch."),
    Q("sport", 4, "Which country did Antonin Panenka represent when he chipped his famous 1976 penalty?",
      "Czechoslovakia", "Hungary", "Poland", "Yugoslavia",
      "He had practised it for two years against his club goalkeeper, betting chocolate on the outcome."),
    Q("sport", 4, "Which German player scored the golden goal that decided Euro 96?",
      "Oliver Bierhoff", "Jurgen Klinsmann", "Andreas Moller", "Stefan Kuntz",
      "He had come on as a substitute, equalised, then won it -- the first tournament settled that way."),
    Q("sport", 4, "Which club did Trevor Francis join in 1979 to become Britain's first million-pound footballer?",
      "Nottingham Forest", "Aston Villa", "Manchester City", "Everton",
      "Brian Clough insisted the fee was really 999,999 pounds so the tag would not go to his head."),
    Q("sport", 4, "Which surface did the Australian Open use before switching to hard courts in 1988?",
      "Grass", "Clay", "Carpet", "Shale",
      "It was played at the Kooyong club, and for years fell awkwardly around Christmas."),
    Q("sport", 4, "Games for injured servicemen at which English hospital grew into the Paralympics?",
      "Stoke Mandeville", "Roehampton", "Headley Court", "Papworth",
      "Ludwig Guttmann staged an archery contest there on the day the 1948 London Olympics opened."),
    Q("sport", 5, "Which driver was awarded the 1970 Formula One world title after his death at Monza?",
      "Jochen Rindt", "Piers Courage", "Bruce McLaren", "Jo Siffert",
      "His points lead held up over the four remaining races, the only posthumous title in the sport."),
    Q("sport", 5, "Which British boxer floored Cassius Clay at Wembley Stadium in 1963?",
      "Henry Cooper", "Brian London", "Joe Bugner", "Billy Walker",
      "His left hook landed at the end of round four; a split glove bought time and Clay won in the fifth."),
    Q("sport", 5, "Amen Corner at Augusta National covers which three holes?",
      "The 11th, 12th and 13th", "The 10th, 11th and 12th", "The 12th, 13th and 14th",
      "The 13th, 14th and 15th",
      "The writer Herbert Warren Wind named the stretch in 1958, borrowing from a jazz record title."),

    # ---- batch 3 ----
    Q("sport", 1, "What is the highest score possible with three darts?",
      "180", "150", "170", "200",
      "170 is the highest possible finish, since a leg must end on a double -- treble 20, treble 20, bullseye."),
    Q("sport", 1, "Which chess piece cannot move backwards?",
      "The pawn", "The bishop", "The rook", "The knight",
      "That one-way journey is why reaching the far rank promotes it, usually to a queen."),
    Q("sport", 1, "What is the name of the scoring area at each end of an American football field?",
      "The end zone", "The red zone", "The goal box", "The touch area",
      "The red zone is something else -- the last twenty yards before it, where offences tighten up."),
    Q("sport", 2, "What is a score of one over par on a golf hole called?",
      "A bogey", "A buzzard", "A condor", "A snowman",
      "A condor is four under on one hole, recorded only a handful of times anywhere."),
    Q("sport", 2, "How many yards must a team gain to earn a fresh set of downs in American football?",
      "Ten yards", "Five yards", "Fifteen yards", "Twenty yards",
      "Four attempts to make it, which is why teams so often kick on the fourth."),
    Q("sport", 2, "What is the term for a baseball home run hit with all three bases occupied?",
      "A grand slam", "A grounder", "A double play", "A sacrifice fly",
      "It scores four, the most a single swing can produce."),
    Q("sport", 2, "How many rounds are scheduled in a modern world championship boxing bout?",
      "Twelve", "Ten", "Fifteen", "Fourteen",
      "Title fights were cut from fifteen in the mid-1980s after a series of late-round tragedies."),
    Q("sport", 2, "Which country did England beat in the 2003 Rugby World Cup final?",
      "Australia", "New Zealand", "South Africa", "France",
      "Jonny Wilkinson's drop goal came with about 26 seconds of extra time left, off his weaker foot."),
    Q("sport", 3, "Which Yorkshire club plays its home matches at Hillsborough?",
      "Sheffield Wednesday", "Sheffield United", "Barnsley", "Leeds United",
      "The ground is named after the district, which in turn is named after an 18th-century politician."),
    Q("sport", 3, "Which German club plays at Signal Iduna Park?",
      "Borussia Dortmund", "Schalke 04", "Bayer Leverkusen", "VfB Stuttgart",
      "Its south terrace, the Yellow Wall, holds around 25,000 standing spectators."),
    Q("sport", 3, "Which London club plays at Selhurst Park?",
      "Crystal Palace", "Fulham", "Charlton Athletic", "Millwall",
      "The ground was designed by Archibald Leitch, who also drew up Ibrox, Anfield and Old Trafford."),
    Q("sport", 3, "Which club did Manchester United sign Eric Cantona from in 1992?",
      "Leeds United", "Sheffield Wednesday", "Nimes", "Marseille",
      "The call that started it was about a defender; the fee ended up being 1.2 million pounds."),
    Q("sport", 3, "Which Italian club led 3-0 at half time in the 2005 Champions League final?",
      "AC Milan", "Internazionale", "Juventus", "Roma",
      "Six minutes of the second half undid it, and the shoot-out finished 3-2."),
    Q("sport", 3, "Which manager was the first from outside the British Isles to win the Premier League?",
      "Arsene Wenger", "Jose Mourinho", "Ruud Gullit", "Gerard Houllier",
      "He took the 1997-98 double barely eighteen months after arriving as a near-unknown."),
    Q("sport", 3, "Which hill around mile 20 tests runners in the Boston Marathon?",
      "Heartbreak Hill", "Bunker Hill", "Beacon Hill", "Breakneck Hill",
      "It only climbs about 27 metres -- the cruelty is where it sits, not how steep it is."),
    Q("sport", 4, "Which Celtics coach won nine NBA championships between 1957 and 1966?",
      "Red Auerbach", "Bill Fitch", "Tommy Heinsohn", "K.C. Jones",
      "He lit a cigar on the bench once a win looked safe, which opponents found unbearable."),
    Q("sport", 4, "Which team did the New England Patriots beat for their first Super Bowl title, in 2002?",
      "The St. Louis Rams", "The Green Bay Packers", "The Oakland Raiders", "The Pittsburgh Steelers",
      "The Rams were two-touchdown favourites and were nicknamed the Greatest Show on Turf."),
    Q("sport", 4, "Which Boston Bruins defenceman scored the 1970 Stanley Cup winner while airborne?",
      "Bobby Orr", "Phil Esposito", "Johnny Bucyk", "Ray Bourque",
      "He had been tripped as he shot, and the photograph of him flying is the sport's best known image."),
    Q("sport", 4, "Which Houston NFL franchise relocated to Tennessee in 1997?",
      "The Oilers", "The Texans", "The Mavericks", "The Colts",
      "They kept the old name in Nashville for two seasons before becoming the Titans."),
    Q("sport", 4, "Which Italian ground is officially named the Stadio Giuseppe Meazza?",
      "The San Siro", "The Stadio Olimpico", "The Stadio delle Alpi", "The Stadio San Paolo",
      "Two clubs share it, and only one of them ever uses the official name."),
    Q("sport", 4, "Which Alpine climb of the Tour de France has 21 numbered hairpin bends?",
      "Alpe d'Huez", "Col du Galibier", "Col d'Izoard", "La Plagne",
      "Each bend carries a plaque naming a past stage winner there, counting down to the summit."),
    Q("sport", 5, "The Lisbon Lions won the 1967 European Cup by beating which club?",
      "Internazionale", "Benfica", "Real Madrid", "AC Milan",
      "Every player in that Celtic side had been born within about thirty miles of Glasgow."),
    Q("sport", 5, "Which ground did Manchester United use for home matches after Old Trafford was bombed in 1941?",
      "Maine Road", "Bank Street", "The Cliff", "Boundary Park",
      "They borrowed their neighbours' ground until 1949 and paid rent of 5,000 pounds a year."),
    Q("sport", 5, "Which hotel hosted the 1895 meeting at which rugby league split from rugby union?",
      "The George Hotel in Huddersfield", "The Queens Hotel in Leeds",
      "The Midland Hotel in Manchester", "The Grand Hotel in Bradford",
      "Twenty-one northern clubs resigned so that they could compensate players for lost wages."),
    Q("sport", 5, "Who hit the first televised nine-dart finish, in 1984?",
      "John Lowe", "Eric Bristow", "Jocky Wilson", "Bobby George",
      "It was worth 102,000 pounds, more than the tournament winner collected."),

    # ---- batch 4 ----
    Q("sport", 1, "Which Formula One term describes the lane where cars stop for fresh tyres?",
      "The pit lane", "The paddock", "The apron", "The grid",
      "The paddock is the enclosure behind it, where the teams park their motorhomes."),
    Q("sport", 1, "In cricket, what is a batter's score of zero called?",
      "A duck", "A dot", "A blank", "A cipher",
      "Out first ball is a golden duck; out first ball of the match is a diamond one."),
    Q("sport", 2, "Which club won the Premier League in 2015-16 having started the season at 5000-1?",
      "Leicester City", "Tottenham Hotspur", "Everton", "Southampton",
      "Bookmakers offered the same odds that year on Elvis being found alive."),
    Q("sport", 2, "Which team went through the 2003-04 Premier League season unbeaten?",
      "Arsenal", "Chelsea", "Liverpool", "Manchester City",
      "The run reached 49 league games before it ended at Old Trafford in October 2004."),
    Q("sport", 2, "Who succeeded Alex Ferguson as Manchester United manager in 2013?",
      "David Moyes", "Louis van Gaal", "Jose Mourinho", "Roy Hodgson",
      "He was handed a six-year contract and lasted ten months of it."),
    Q("sport", 2, "Which country won the 2006 World Cup?",
      "Italy", "France", "Germany", "Brazil",
      "They did it while their domestic league was mid-scandal, with several of the squad implicated."),
    Q("sport", 2, "Which country won the 2010 World Cup?",
      "Spain", "The Netherlands", "Germany", "Uruguay",
      "They scored eight goals in the whole tournament and won four knockout games 1-0."),
    Q("sport", 2, "How many points is a conversion worth in rugby union?",
      "Two", "Three", "One", "Four",
      "The kick is taken in line with where the try was grounded, so corner tries are punished twice."),
    Q("sport", 3, "Which club paid Barcelona a world-record fee for Neymar in 2017?",
      "Paris Saint-Germain", "Manchester City", "Chelsea", "Juventus",
      "The release clause had to be paid in one lump, which is why the figure was 222 million euros."),
    Q("sport", 3, "Which club did Diego Maradona join for a world-record fee in 1984?",
      "Napoli", "Roma", "Internazionale", "Lazio",
      "They had never won the Italian league before he arrived, and won it twice while he was there."),
    Q("sport", 3, "Who scored the extra-time goal that won the 2010 World Cup final?",
      "Andres Iniesta", "David Villa", "Xavi", "Cesc Fabregas",
      "It came in the 116th minute of a final that produced fourteen yellow cards."),
    Q("sport", 3, "Whom did Zinedine Zidane headbutt in the 2006 World Cup final?",
      "Marco Materazzi", "Fabio Cannavaro", "Gennaro Gattuso", "Alessandro Nesta",
      "The two had already traded a penalty and an equaliser earlier in the same match."),
    Q("sport", 3, "Which nation won the 1988 European Championship?",
      "The Netherlands", "West Germany", "Italy", "The Soviet Union",
      "Marco van Basten's volley in the final is the goal everyone remembers from that tournament."),
    Q("sport", 3, "Which Boston arena is shared by the Celtics and the Bruins?",
      "TD Garden", "Agganis Arena", "Matthews Arena", "The Hynes Auditorium",
      "It replaced the old Boston Garden in 1995 and has been renamed three times since."),
    Q("sport", 3, "Which Houston Rockets centre was nicknamed The Dream?",
      "Hakeem Olajuwon", "Ralph Sampson", "Moses Malone", "Yao Ming",
      "He arrived in Texas from Lagos having played football first, which is where the footwork came from."),
    Q("sport", 3, "How long is a period in a National Hockey League game?",
      "20 minutes", "15 minutes", "25 minutes", "30 minutes",
      "Three of them, and the ice is resurfaced between each, which is why intervals run long."),
    Q("sport", 4, "In which two years did the Houston Rockets win back-to-back NBA titles?",
      "1994 and 1995", "1993 and 1994", "1995 and 1996", "1996 and 1997",
      "Both came while Michael Jordan was away from the game, a point rivals still enjoy making."),
    Q("sport", 4, "Which Manchester United captain of the 1980s was nicknamed Captain Marvel?",
      "Bryan Robson", "Steve Bruce", "Norman Whiteside", "Gordon McQueen",
      "He arrived in 1981 for a British record fee and signed the forms on the pitch before a match."),
    Q("sport", 4, "Which stand at Old Trafford has long been known as the Stretford End?",
      "The West Stand", "The East Stand", "The North Stand", "The South Stand",
      "It was the last part of the ground to lose its terracing, in 1992."),
    Q("sport", 4, "Which trophy did Manchester United win in 1963, their first after Munich?",
      "The FA Cup", "The league title", "The European Cup", "The League Cup",
      "They finished 19th in the league that same season, one place above relegation."),
    Q("sport", 4, "Which Manchester United player scored the injury-time equaliser in the 1999 Champions League final?",
      "Teddy Sheringham", "Dwight Yorke", "Andy Cole", "Jesper Blomqvist",
      "Both goals came from substitutes, and both from corners taken by David Beckham."),
    Q("sport", 4, "Which cycling race is nicknamed the Hell of the North?",
      "Paris-Roubaix", "The Tour of Flanders", "Liege-Bastogne-Liege", "Milan-San Remo",
      "The name dates from 1919, when organisers rode through country wrecked by the war."),
    Q("sport", 5, "Which 19-year-old scored for Manchester United in the 1968 European Cup final on his birthday?",
      "Brian Kidd", "David Sadler", "John Aston", "Shay Brennan",
      "He was a Manchester boy who had grown up watching the side that died at Munich."),
    Q("sport", 5, "Which ground did Newton Heath leave when they moved to Old Trafford in 1910?",
      "Bank Street", "North Road", "Moss Lane", "Whalley Range",
      "Chemical works either side of it meant the pitch was regularly wreathed in fumes."),
    Q("sport", 5, "Which Cuban held the world chess championship from 1921 to 1927?",
      "Jose Raul Capablanca", "Emanuel Lasker", "Alexander Alekhine", "Max Euwe",
      "He went about eight years without losing a single tournament game before taking the title."),
]
