#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_lingua2.py — the EXPANDED build of core/data/lingua.js.

`_build/gen_lingua.py` is another session's script and is not mine to edit, so
this one:
  * keeps its 93 shipped samples byte-for-byte (they are already validated),
  * appends every language declared in _build/lingua_table.py, taking the TEXT
    and the English GLOSS from the harvested UDHR corpus
    (_build/cache/lingua_candidates.json, built by _build/lingua_harvest.py),
  * re-runs the giveaway check: no sample text and no hint may name any country,
    capital or demonym in countries.js, nor the language's own name,
  * emits the same shape and the same two globals.

    python3 _build/gen_lingua2.py            # build + report
    python3 _build/gen_lingua2.py --report    # validate only

Every `text` is verbatim published text (the Universal Declaration of Human
Rights). Nothing is composed, machine-translated, or transliterated. Stdlib only.
"""

import json
import os
import re
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'core', 'data', 'lingua.js')
CANDS = os.path.join(HERE, 'cache', 'lingua_candidates.json')
sys.path.insert(0, HERE)

MAX_HINT = 200

HEADER = '''/* core/data/lingua.js -- window.AD_LINGUA : real language + writing-system samples
   for LINGUAGUESSR ("read the writing, place the language").

   SOURCES (every `text` is VERBATIM published text; nothing here was composed,
   machine-translated, or transliterated for the game)
     UDHR -- Universal Declaration of Human Rights, XML corpus formerly published by
             the Unicode Consortium as "UDHR in Unicode" and now maintained at
             https://github.com/eric-muller/udhr (data/udhr/udhr_<code>.xml).
             The UDHR is a United Nations document. Article paragraphs only.
     WIKI -- Wikipedia REST summaries (https://<wiki>.wikipedia.org/api/rest_v1/),
             CC BY-SA 4.0, for the three languages the UDHR corpus does not carry.
   Each sample records its own `src`; `gloss` is the English of the SAME paragraph
   of the same document, so the translation is the UN's, not ours.

   Script names, families, answer countries, speaker estimates and the three
   escalating hints are authored metadata (_build/lingua_table.py), checked against
   the sources above. No sample text and no hint names any country, capital or
   demonym -- machine-enforced against core/data/countries.js.

   Generated by _build/gen_lingua2.py -- do not edit by hand, re-run the script.
*/
'''


def load_countries():
    src = open(os.path.join(ROOT, 'core', 'data', 'countries.js'), encoding='utf-8').read()
    m = re.search(r'window\.AD_COUNTRIES\s*=\s*(\[.*?\n\]);', src, re.S)
    return json.loads(m.group(1))


def load_shipped():
    """The 93 samples already in the file, exactly as they are."""
    src = open(OUT, encoding='utf-8').read()
    i = src.index('window.AD_LINGUA =')
    j = src.index('{', i)
    k = src.index('\n};', j)
    return json.loads(src[j:k + 2])


def fold(s):
    s = unicodedata.normalize('NFKD', s)
    s = ''.join(c for c in s if not unicodedata.combining(c))
    return re.sub(r'[^a-z0-9 ]+', ' ', s.lower())


# Folded country strings that are also ordinary English words, so blocking them
# costs a real hint and buys nothing: `island` is only here because countries.js
# carries Iceland's endonym Ísland, and `male` because the Maldivian capital is
# Malé. The unambiguous forms (iceland, icelandic, maldives) still block.
FALSE_FRIENDS = {'island', 'male'}


def blocklist(countries):
    """Every string that would hand a player the answer."""
    out = set()
    for c in countries:
        for s in [c.get('n'), c.get('cap'), c.get('demo')] + list(c.get('alt') or []):
            if s and len(s) >= 4:
                out.add(fold(s).strip())
    # a few the DB spells differently from ordinary prose
    out |= {'persia', 'holland', 'burma', 'britain', 'england', 'scotland', 'wales',
            'america', 'russia', 'china', 'india', 'iran', 'israel', 'egypt', 'japan',
            'korea', 'ireland', 'brazil', 'mexico', 'spain', 'france', 'italy'}
    return {t for t in out - FALSE_FRIENDS if len(t) >= 4}


def own_terms(isos, by):
    """The blocklist that applies to a SAMPLE'S OWN TEXT.

    The text is a verbatim foreign-language passage, so the giveaway to guard
    against is the passage naming the country it comes from — not an accidental
    homograph. The Kven UDHR contains the Finnish word `oman` ("one's own"),
    which the global blocklist read as Oman and which gives away nothing.
    """
    out = set()
    for i in isos:
        c = by.get(i) or {}
        for s in [c.get('n'), c.get('cap'), c.get('demo')] + list(c.get('alt') or []):
            if s and len(s) >= 4:
                out.add(fold(s).strip())
    return {t for t in out if len(t) >= 4}


def has_blocked(text, block):
    f = ' ' + fold(text).strip() + ' '
    for t in block:
        if ' ' + t + ' ' in f:
            return t
    return None


def region_of(iso, by):
    c = by.get(iso) or {}
    return c.get('sub') or c.get('reg') or ''


def build():
    import lingua_table as T

    countries = load_countries()
    by = {c['i']: c for c in countries}
    block = blocklist(countries)

    cands = json.load(open(CANDS, encoding='utf-8'))
    # index the corpus by iso and by file code
    by_file = {c['f']: c for c in cands}
    by_iso = {}
    for c in sorted(cands, key=lambda d: (len(d['f']), d['f'])):
        by_iso.setdefault((c['iso'], c['sc']), c)
        by_iso.setdefault(c['iso'], c)

    shipped = load_shipped()
    samples = list(shipped['samples'])
    used_keys = {s['key'] for s in samples}

    errs, warns, added = [], [], 0
    for key, spec in T.LANGS.items():
        name, family, isos, speakers, near = spec[0], spec[1], spec[2], spec[3], spec[4]
        fcode = T.FILE.get(key, key)
        cd = by_file.get(fcode) or by_iso.get(fcode) or by_iso.get(key)
        if cd is None:
            errs.append('%s: no UDHR candidate for file code %r' % (key, fcode))
            continue
        if key in used_keys:
            errs.append('%s: key collides with a shipped sample' % key)
            continue
        sc = cd['sc']
        script_label, script_tell = T.SCRIPTS.get(sc, (sc, ''))
        script_label = T.SCRIPT_OVERRIDE.get(key, script_label)
        if not script_tell:
            errs.append('%s: no script tell authored for %r' % (key, sc))
            continue

        isos = [i for i in isos if i in by and (by[i].get('capll') or by[i].get('ll'))]
        if not isos:
            errs.append('%s: no answer country that exists in countries.js' % key)
            continue

        # hint 0 — the script tell. The table owns it, because for Latin the
        # useful tell is which non-English letters are actually on the screen.
        hint0 = T.script_tell(key, sc, cd['chars'], family, script_tell)
        # hint 1 — family and region, derived so it can never contradict the data
        branch = family.split('>')[-1].strip()
        reg = region_of(isos[0], by)
        hint1 = 'A %s language of %s.' % (branch, reg) if reg else 'A %s language.' % branch
        if len(spec) > 5 and spec[5]:
            hint1 = spec[5]
        hints = [hint0, hint1, near]

        bad = None
        for h in hints:
            b = has_blocked(h, block)
            if b:
                bad = ('hint', b, h)
                break
        if not bad:
            b = has_blocked(cd['text'], own_terms(isos, by))
            if b:
                bad = ('text', b, cd['text'][:60])
        if not bad and fold(name).strip() and fold(name).strip() in fold(cd['text']):
            bad = ('text', name, 'names its own language')
        if bad:
            errs.append('%s: %s names %r (%s)' % (key, bad[0], bad[1], bad[2][:50]))
            continue
        for h in hints:
            if len(h) > MAX_HINT:
                warns.append('%s: hint %d chars (soft max %d)' % (key, len(h), MAX_HINT))

        samples.append({
            'key': key, 'lang': name, 'script': script_label, 'sc': sc,
            'family': family, 'text': cd['text'], 'gloss': cd['gloss'],
            'countries': isos, 'speakers': int(speakers), 'hints': hints,
            'src': 'UDHR :: udhr_%s.xml, Article %d' % (cd['f'], cd['art']),
        })
        used_keys.add(key)
        added += 1

    samples.sort(key=lambda s: s['key'])
    meta = {
        'version': 2,
        'generated': '2026-07-29',
        'sources': {
            'UDHR': 'UDHR (github.com/eric-muller/udhr, ex-unicode.org/udhr)',
            'WIKI': 'Wikipedia REST summaries (CC BY-SA 4.0)',
        },
        'counts': {
            'samples': len(samples),
            'scripts': len({s['sc'] for s in samples}),
            'families': len({s['family'].split('>')[0].strip() for s in samples}),
        },
        'samples': samples,
    }
    return meta, errs, warns, added, shipped


def write_out(meta):
    body = json.dumps(meta, ensure_ascii=False, separators=(',', ':'))
    body = body.replace('},{"key":', '},\n{"key":')
    body = body.replace('"samples":[{"key":', '"samples":[\n{"key":')
    with open(OUT, 'w', encoding='utf-8') as fh:
        fh.write(HEADER)
        fh.write('window.AD_LINGUA = ')
        fh.write(body)
        fh.write(';\n\n')
        fh.write('window.AD_LINGUA_BY = (function (a, o) {\n'
                 '  for (var k = 0; k < a.length; k++) { o[a[k].key] = a[k]; }\n'
                 '  return o;\n'
                 '})(window.AD_LINGUA.samples, {});\n')
    return os.path.getsize(OUT)


def main():
    meta, errs, warns, added, shipped = build()
    n = len(meta['samples'])
    print('=' * 74)
    print('LINGUAGUESSR — %d samples (%d kept + %d new), %d scripts'
          % (n, len(shipped['samples']), added, meta['counts']['scripts']))
    print('=' * 74)
    scs = {}
    for s in meta['samples']:
        scs[s['sc']] = scs.get(s['sc'], 0) + 1
    print('  scripts: ' + ' '.join('%s:%d' % (k, scs[k]) for k in sorted(scs)))
    if warns:
        print('\nWARNINGS (%d) — first 15' % len(warns))
        for w in warns[:15]:
            print('  ! ' + w)
    if errs:
        print('\nERRORS (%d) — these languages were DROPPED' % len(errs))
        for e in errs[:60]:
            print('  X ' + e)
    if '--report' not in sys.argv:
        size = write_out(meta)
        print('\nwrote %s  (%d bytes, %.0f B/sample)' % (OUT, size, size / float(n)))
    return 1 if errs else 0


if __name__ == '__main__':
    sys.exit(main())
