#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_connections2.py — the EXPANDED build of core/data/connections.js.

Why a second file: `_build/gen_connections.py` is another session's script and is
not mine to edit. This one imports its validator wholesale, adds the new authored
batches, relaxes only the dataset-wide tile-reuse ceiling (unavoidable at 400+
boards), and writes the same output file in the same shape.

    python3 _build/gen_connections2.py                    # build + validate + report
    python3 _build/gen_connections2.py --report           # validate only
    python3 _build/gen_connections2.py --check-module M   # validate ONE authored batch

The six packs and their proportions are fixed by the players (CONTRACT §7):
general ~36%, united ~18%, places ~15%, persia ~11%, ai ~11%, jewish ~9%.
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "core", "data", "connections.js")
sys.path.insert(0, HERE)

import gen_connections as G   # noqa: E402  (validator + loader, reused verbatim)

# A tile string may legally appear in this many boards dataset-wide. The original
# build capped it at 3 across 110 boards; at 400+ boards common English words
# (LEAD, SPRING, ORANGE) recur honestly and a hard 3 would just push authors into
# worse tiles. Reported in full below so the number stays visible.
MAX_REUSE = 6

PACKS = [
    ("general", "MIXED BAG",
     "The main archive. Wordplay, general knowledge, and a purple that bites.",
     ["conn_general1", "conn_general2", "conn_general3", "conn_general4",
      "conn_general5", "conn_general6", "conn_general7", "conn_general8",
      "conn_general9"]),
    ("persia", "PERSIAN BLUE",
     "Nowruz, poets, food, carpets, and the words English quietly borrowed.",
     ["conn_persia", "conn_persia2"]),
    ("united", "RED DEVILS",
     "Old Trafford and the Premier League. The FOURMATIONS archive, rehoused.",
     ["conn_united", "conn_united2", "conn_united3"]),
    ("places", "FOUR CITIES",
     "Cambridge, London, Edinburgh, Houston. Squares, closes, bayous, feeder roads.",
     ["conn_places", "conn_places2", "conn_places3"]),
    ("ai", "THE ALIGNMENT",
     "Alignment, evals, compute governance, the labs, the papers, the acronyms.",
     ["conn_ai", "conn_ai2"]),
    ("jewish", "DIASPORA",
     "Holidays, food, Yiddish and Hebrew in English, texts, music, and Israel.",
     ["conn_jewish", "conn_jewish2"]),
]

HEADER = """// core/data/connections.js — grouping puzzles for QUARTETS (window.AD_CONNECTIONS).
// Source: hand-authored for this arcade (_build/conn_*.py). Generated by
// _build/gen_connections2.py — do not edit by hand, re-run the script.
// Colours y<g<b<p ascend in difficulty. Every board is machine-verified uniquely
// solvable against its declared double-fits; see the generator's report.
"""


# Batches authored under the 400-day expansion. The byte budget and the
# every-board-declares-a-trap rule are enforced on these only — the original 110
# boards predate both rules and are another session's work, so they stand as-is.
NEW_MODULES = set("""conn_general5 conn_general6 conn_general7 conn_general8
conn_general9 conn_persia2 conn_united2 conn_united3 conn_places2 conn_places3
conn_ai2 conn_jewish2""".split())

SRC = {}   # (pack_id, board_id) -> module name


def collect(pack_defs):
    packs, flat, missing = [], [], []
    for pid, pname, blurb, modules in pack_defs:
        boards = []
        for m in modules:
            got = G.load_module(m)
            if got is None:
                missing.append(m)
                continue
            for b in got:
                boards.append((m, b))
        out_boards = []
        for n, (mod, b) in enumerate(boards, 1):
            SRC[(pid, n)] = mod
            ob = {
                "id": n,
                "title": b["title"],
                "diff": b["diff"],
                "groups": [
                    {"name": g["name"], "colour": G.COLOURS[i],
                     "tiles": list(g["tiles"]), "note": g["note"]}
                    for i, g in enumerate(b["groups"])
                ],
                "epilogue": b["epilogue"],
            }
            out_boards.append(ob)
            flat.append((pid, n, b, ob))
        packs.append({"id": pid, "name": pname, "blurb": blurb, "boards": out_boards})
    return packs, flat, missing


def budget_errors(flat):
    """Byte-budget rules that only this expanded build enforces (see
    _build/AUTHORING_QUARTETS.md). The shipped file has to stay loadable on a
    phone, so notes and epilogues are capped."""
    errs = []
    for pid, bid, raw, ob in flat:
        if SRC.get((pid, bid)) not in NEW_MODULES:
            continue
        tag = "%s#%d" % (pid, bid)
        if len(ob["title"]) > 24:
            errs.append("%s: title %d chars (max 24)" % (tag, len(ob["title"])))
        for g in ob["groups"]:
            if len(g["name"]) > 40:
                errs.append("%s: category name %d chars (max 40): %r"
                            % (tag, len(g["name"]), g["name"]))
            if len(g["note"]) > 95:
                errs.append("%s: note %d chars (max 95): %r"
                            % (tag, len(g["note"]), g["note"][:60]))
        if len(ob["epilogue"]) > 150:
            errs.append("%s: epilogue %d chars (max 150)" % (tag, len(ob["epilogue"])))
        if not raw.get("traps"):
            errs.append("%s: no declared double-fit — every board needs one trap" % tag)
    return errs


def write_out(packs):
    payload = {"packs": packs}
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    # one pack per line keeps the file diffable without pretty-printing it
    body = body.replace('},{"id":"', '},\n{"id":"')
    body = body.replace('"boards":[{', '"boards":[\n{')
    body = body.replace('},{"id":', '},\n{"id":')
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write("window.AD_CONNECTIONS = ")
        fh.write(body)
        fh.write(";\n")
    return os.path.getsize(OUT)


def check_module(name):
    boards = G.load_module(name)
    if boards is None:
        print("no such module: _build/%s.py" % name)
        return 1
    NEW_MODULES.add(name)
    packs, flat, missing = collect([("check", "CHECK", "", [name])])
    G.MAX_REUSE = MAX_REUSE
    errs, warns, info = G.validate(packs, flat)
    errs += budget_errors(flat)
    dd = {}
    for _, _, _, ob in flat:
        dd[ob["diff"]] = dd.get(ob["diff"], 0) + 1
    print("module %s: %d boards   diff spread %s"
          % (name, len(flat), " ".join("%d:%d" % (k, dd[k]) for k in sorted(dd))))
    for w in warns:
        print("  ! " + w)
    for e in errs:
        print("  X " + e)
    print("OK" if not errs else "FAILED (%d errors)" % len(errs))
    return 0 if not errs else 1


def main():
    args = sys.argv[1:]
    if "--check-module" in args:
        return check_module(args[args.index("--check-module") + 1])

    packs, flat, missing = collect(PACKS)
    G.MAX_REUSE = MAX_REUSE
    errs, warns, info = G.validate(packs, flat)
    errs += budget_errors(flat)

    nb = sum(len(p["boards"]) for p in packs)
    print("=" * 74)
    print("QUARTETS — %d boards, %d groups, %d tiles"
          % (nb, nb * 4, info["total_tiles"]))
    print("=" * 74)
    for p in packs:
        dd = {}
        for b in p["boards"]:
            dd[b["diff"]] = dd.get(b["diff"], 0) + 1
        print("  %-9s %-13s %3d boards  (%4.1f%%)  diff %s"
              % (p["id"], p["name"], len(p["boards"]),
                 100.0 * len(p["boards"]) / max(1, nb),
                 " ".join("%d:%d" % (k, dd[k]) for k in sorted(dd))))
    if missing:
        print("\n  batches not yet on disk: " + ", ".join(missing))

    print("\nINVARIANTS")
    print("  4 groups x 4 tiles, 16 distinct per board ... %s"
          % ("PASS (%d boards)" % nb if not any(
              "tiles (need 16)" in e or "repeated tile" in e or "has %d tiles" in e
              for e in errs) else "FAIL"))
    print("  tiles uppercase and <= %d chars ............. %s"
          % (G.MAX_TILE, "PASS" if not any("bad tile" in e for e in errs) else "FAIL"))
    print("  every group has a note, every board an epilogue  %s"
          % ("PASS" if not any("no note" in e or "no epilogue" in e for e in errs) else "FAIL"))
    print("  every board declares a double-fit ........... %s"
          % ("PASS" if not any("no declared double-fit" in e for e in errs) else "FAIL"))
    print("  unique solution per board (exact cover == 1)  %s"
          % ("PASS (%d/%d)" % (nb, nb) if not any("UNIQUELY" in e for e in errs) else "FAIL"))
    print("  cross-board tile reuse <= %d ................ %s"
          % (MAX_REUSE, "PASS" if not any("reused in" in e for e in errs) else "FAIL"))
    print("     distinct tile strings %d, reuse histogram %s"
          % (info["distinct_tiles"],
             " ".join("%dx:%d" % (k, info["reuse_hist"][k]) for k in sorted(info["reuse_hist"]))))
    print("  no FOURMATIONS group outside `united` ...... %s"
          % ("PASS" if not any("FOURMATIONS" in e for e in errs) else "FAIL"))
    print("     %s" % info["fourmations"])
    print("  declared double-fits ....................... %d" % len(info["traps"]))

    if warns:
        print("\nWARNINGS (%d) — first 25" % len(warns))
        for w in warns[:25]:
            print("  ! " + w)
    if errs:
        print("\nERRORS (%d)" % len(errs))
        for e in errs[:80]:
            print("  X " + e)
        print("\nBUILD FAILED — output NOT written")
        return 1

    if "--report" not in args:
        size = write_out(packs)
        print("\nwrote %s  (%d bytes, %.0f B/board)" % (OUT, size, size / float(nb)))
    print("\nOK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
