#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
gen_chrono2.py — the EXPANDED build of core/data/chrono.js.

`_build/gen_chrono.py` is another session's script and is not mine to edit. It
also cannot express the expanded bank: its BANK is a dict keyed by year, so it
can hold only one entry per year, and the widened spec allows two (with no
shared clue and no shared subject).

This one merges BOTH sources —

    _build/chrono_bank_[a-e].py   the original python banks (one entry per year)
    _build/chrono_x*.json         the authored JSON batches (list of entries)

— re-runs `check_chrono.validate` over the union (5 clues each, clue <= 190
chars, note <= 150, NO four-digit 1700..2100 anywhere in any clue or note, no
duplicate clue text anywhere in the bank, year in 1800..2025, at most 2 entries
per year and those two sharing no clue), and writes the same file in the same
shape as gen_chrono.py, with the playable range widened to 1800..2025.

    python3 _build/gen_chrono2.py             # build + report
    python3 _build/gen_chrono2.py --report    # validate only, write nothing

The cabinet reads `lo`/`hi` out of the data (games/chrono/game.js), so widening
the range is a pure-data change and no game code moves. Stdlib only.
"""

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "core", "data", "chrono.js")
sys.path.insert(0, HERE)

import check_chrono as CC   # noqa: E402  (loader + validator, reused verbatim)

LO, HI = 1800, 2025


def collect():
    entries = CC.load_existing()
    batches = sorted(glob.glob(os.path.join(HERE, "chrono_x*.json")))
    for p in batches:
        entries += CC.load_json(p)
    return entries, batches


def emit(entries):
    """Same shape as gen_chrono.py, one entry per line so the file stays diffable.

    Entries are sorted by year and then by source, so the on-disk order is
    deterministic; the cabinet walks a seeded permutation over the array, so the
    order itself is never player-visible.
    """
    entries = sorted(entries, key=lambda e: (e["y"], e.get("_src", ""), e["c"][0]))
    rows = ["{y:%d,c:%s,n:%s}" % (e["y"],
                                  json.dumps(e["c"], ensure_ascii=False),
                                  json.dumps(e["n"], ensure_ascii=False))
            for e in entries]
    body = ",\n".join(rows)
    js = (
        "/* ============================================================================\n"
        "   core/data/chrono.js  ->  window.AD_CHRONO\n"
        "   CHRONO's clue bank: %d entries over %d distinct years (%d..%d), five clues\n"
        "   each, ordered HARDEST first and most obvious last, plus a one-line note\n"
        "   shown after the round. A year may carry two entries; where it does they\n"
        "   share no clue and no subject matter.\n"
        "\n"
        "   GENERATED by _build/gen_chrono2.py from _build/chrono_bank_[a-e].py and\n"
        "   _build/chrono_x*.json. Do not hand-edit: edit a bank or a batch and re-run\n"
        "   the script, which enforces five clues per entry, no four-digit year inside\n"
        "   any clue or note, and no duplicate clue text anywhere in the bank.\n"
        "\n"
        "   Sources: general-reference history, cross-checked entry by entry. Anything\n"
        "   that could not be dated with confidence was dropped rather than guessed.\n"
        "   ========================================================================== */\n"
        "window.AD_CHRONO = {\n"
        "  lo: %d, hi: %d,\n"
        "  years: [\n%s\n  ]\n"
        "};\n"
    ) % (len(entries), len({e["y"] for e in entries}),
         min(e["y"] for e in entries), max(e["y"] for e in entries),
         LO, HI, body)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)
    return len(js.encode("utf-8"))


def main():
    entries, batches = collect()
    errs, warns, per_year = CC.validate(entries)

    print("=" * 74)
    print("CHRONO — %d entries over %d distinct years (%d..%d)"
          % (len(entries), len(per_year), min(per_year), max(per_year)))
    print("=" * 74)
    print("  sources: %d python bank entries + %s"
          % (len(CC.load_existing()),
             ", ".join(os.path.basename(b) for b in batches) or "(no JSON batches)"))
    dec = {}
    for y, es in per_year.items():
        dec[y // 10 * 10] = dec.get(y // 10 * 10, 0) + len(es)
    print("  per decade: " + " ".join("%ds:%d" % (k, dec[k]) for k in sorted(dec)))
    gaps = [d for d in range(LO, HI + 1, 10) if d not in dec]
    if gaps:
        print("  decades with NO entries: " + " ".join(str(g) for g in gaps))
    longest = max((len(c) for e in entries for c in e["c"]), default=0)
    print("  longest clue: %d chars (limit %d)" % (longest, CC.MAX_CLUE))
    print("  two-entry years: %d" % sum(1 for es in per_year.values() if len(es) == 2))

    if warns:
        print("\nWARNINGS (%d)" % len(warns))
        for w in warns[:20]:
            print("  ! " + w)
    if errs:
        print("\nERRORS (%d)" % len(errs))
        for e in errs[:80]:
            print("  X " + e)
        print("\nBUILD FAILED — output NOT written")
        return 1

    if "--report" not in sys.argv:
        size = emit(entries)
        print("\nwrote %s  (%d bytes, %.1f KB)" % (OUT, size, size / 1024.0))
    print("\nOK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
