# -*- coding: utf-8 -*-
"""
phylo_bank.py — the hand-authored tree of life behind PHYLO (games/phylo).

The whole cabinet is one data structure: a rooted tree whose internal nodes are
CLADES with an age in millions of years (Ma), and whose leaves are ORGANISMS.
Everything the game says is derived from it — the distance between two
organisms is simply the age of their most recent common ancestor.

    C(name, sci, age, *children, gloss=, rank=)   a clade
    T(name, sci, tier=, clue=, alt=, ext=)        an organism (leaf)

AGES
  Node ages are median divergence-time estimates, rounded, from TimeTree v5
  (Kumar et al. 2022, timetree.org) and the standard primary literature behind
  it. They are estimates and the game says so out loud — it prints "≈".
  Rounding is deliberate: a game that prints 96.4 Ma implies a precision that
  molecular clocks do not have. The rule the validator enforces is that a child
  is always strictly younger than its parent, because that is what makes the
  puzzle's logic sound.

  Deep nodes (>1 Ga) are the least certain and are given as round numbers.
  Very recent nodes are given in fractions of a Ma (0.03 = 30,000 years).

TOPOLOGY
  Standard consensus. Places that are genuinely unresolved are left as
  polytomies rather than faked into a resolution — the base of the animals
  (sponge-sister vs ctenophore-sister is still argued) is the loudest example.
  A polytomy is honest: it means "these separated at about the same time, and
  nobody can order them yet".

TIERS
  1  famous — anyone would name it. Fair game as the day's answer.
  2  known — a reader of natural history would place it. Fair game.
  3  guess-only — real and typable, never the day's answer (obscure, or a
     laboratory organism, or a fossil taxon whose placement carries caveats).

Nothing here is generated. Every organism was chosen because a person could
plausibly type it, and every scientific name is one I could vouch for.
"""


def C(name, sci, age, *kids, **kw):
    """A clade: named group, age of its most recent common ancestor, children."""
    return {
        "k": "c", "name": name, "sci": sci, "age": float(age), "kids": list(kids),
        "gloss": kw.get("gloss"), "rank": kw.get("rank"), "id": kw.get("id"),
    }


def T(name, sci, **kw):
    """An organism at the tip of a branch."""
    return {
        "k": "t", "name": name, "sci": sci, "tier": kw.get("tier", 2),
        "clue": kw.get("clue"), "alt": tuple(kw.get("alt", ())),
        "ext": 1 if kw.get("ext") else 0, "id": kw.get("id"),
    }


# ══════════════════════════════════════════════════════════════════════════════
# BACTERIA + ARCHAEA — the two-thirds of life nobody draws
# ══════════════════════════════════════════════════════════════════════════════

BACTERIA = C(
    "Bacteria", "Bacteria", 3400,
    C("Cyanobacteria", "Cyanobacteriota", 2600,
      T("Cyanobacterium", "Synechococcus sp.", tier=3,
        alt=("blue-green algae", "cyanobacteria"),
        clue="its ancestors put the oxygen in the air, then moved into plants"),
      T("Spirulina", "Arthrospira platensis", tier=3,
        clue="skimmed off alkaline lakes and sold as a green powder"),
      gloss="the bacteria that invented oxygen photosynthesis and rusted the sky"),
    C("Gram-positive bacteria", "Bacillota and Actinomycetota", 3000,
      T("Lactobacillus", "Lactobacillus delbrueckii", tier=3,
        alt=("lactobacillus", "yoghurt bacterium"),
        clue="turns milk into yoghurt by souring it with lactic acid"),
      T("Tuberculosis bacterium", "Mycobacterium tuberculosis", tier=3,
        alt=("tb", "tuberculosis"),
        clue="a waxy coat lets it live inside the very cells sent to kill it"),
      T("Anthrax bacterium", "Bacillus anthracis", tier=3, alt=("anthrax",),
        clue="waits out decades in dry soil as a spore")),
    C("Proteobacteria", "Pseudomonadota", 2800,
      T("Escherichia coli", "Escherichia coli", tier=2,
        alt=("e coli", "ecoli", "e. coli"),
        clue="the workhorse of every molecular biology lab — and of your gut"),
      T("Salmonella", "Salmonella enterica", tier=3,
        clue="the reason nobody eats raw chicken"),
      T("Cholera bacterium", "Vibrio cholerae", tier=3, alt=("cholera",),
        clue="John Snow traced it to one water pump on Broad Street")),
    T("Thermus aquaticus", "Thermus aquaticus", tier=3, alt=("taq", "taq polymerase"),
      clue="lifted from a Yellowstone hot spring; its enzyme made PCR possible"),
    rank="domain",
    gloss="single cells with no nucleus — the oldest and most numerous life there is")

ARCHAEA = C(
    "Archaea", "Archaea", 3200,
    T("Methanogen", "Methanobrevibacter smithii", tier=3, alt=("methanogen",),
      clue="breathes out methane; lives in swamps, in cows and in you"),
    T("Halobacterium", "Halobacterium salinarum", tier=3, alt=("halophile",),
      clue="dyes salt lakes pink and needs brine to hold itself together"),
    T("Sulfolobus", "Saccharolobus solfataricus", tier=3,
      clue="lives in boiling acid around volcanic vents"),
    rank="domain",
    gloss="a third domain of single cells — and the lineage our own cells came out of")


# ══════════════════════════════════════════════════════════════════════════════
# THE OTHER EUKARYOTES — algae, amoebae, and the things that cause plagues
# ══════════════════════════════════════════════════════════════════════════════

SAR = C(
    "SAR clade", "Sar", 1450,
    C("Stramenopiles", "Stramenopiles", 1100,
      C("Brown algae", "Phaeophyceae", 200,
        T("Giant kelp", "Macrocystis pyrifera", tier=2, alt=("kelp",),
          clue="grows half a metre a day into an underwater forest"),
        T("Bladderwrack", "Fucus vesiculosus", tier=3, alt=("wrack", "seaweed"),
          clue="the popping bladders underfoot on a Scottish shore"),
        gloss="seaweed that built a forest without ever becoming a plant"),
      T("Diatom", "Thalassiosira pseudonana", tier=2, alt=("diatoms",),
        clue="a single cell in a glass box; makes a fifth of the world's oxygen"),
      T("Potato blight", "Phytophthora infestans", tier=3, alt=("blight", "late blight"),
        clue="emptied Ireland in the 1840s — and it is not a fungus")),
    C("Alveolates", "Alveolata", 1000,
      T("Malaria parasite", "Plasmodium falciparum", tier=2, alt=("malaria", "plasmodium"),
        clue="spends half its life in a mosquito and half in your red blood cells"),
      T("Paramecium", "Paramecium caudatum", tier=2,
        clue="a slipper-shaped cell that swims with thousands of tiny oars"),
      T("Dinoflagellate", "Karenia brevis", tier=3, alt=("dinoflagellate", "red tide"),
        clue="makes the sea glow at night, and sometimes makes it lethal")),
    T("Foraminiferan", "Globigerina bulloides", tier=3, alt=("foraminifera", "foram"),
      clue="a cell in a chalk shell; trillions of them are the White Cliffs"),
    gloss="kelp, diatoms, malaria and half the plankton in the sea — not one of them a plant")

AMOEBOZOA = C(
    "Amoebozoa", "Amoebozoa", 1100,
    T("Amoeba", "Amoeba proteus", tier=2, alt=("amoeba", "ameba"),
      clue="has no fixed shape at all; flows around its food and swallows it"),
    T("Slime mould", "Physarum polycephalum", tier=2, alt=("slime mold",),
      clue="one enormous cell with many nuclei; solves mazes with no brain"),
    gloss="cells that move by pouring themselves forwards")


# ══════════════════════════════════════════════════════════════════════════════
# PLANTS — one captured cyanobacterium, and then everything green
# ══════════════════════════════════════════════════════════════════════════════

GRASSES = C(
    "Grasses", "Poaceae", 80,
    C("BOP grasses", "BOP clade", 55,
      T("Rice", "Oryza sativa", tier=1, clue="grown in standing water; feeds half the planet"),
      T("Bamboo", "Phyllostachys edulis", tier=1, clue="a grass that can grow a metre in a day"),
      C("Wheat and barley", "Triticeae", 13,
        T("Wheat", "Triticum aestivum", tier=1, clue="six copies of the genome; bread depends on its gluten"),
        T("Barley", "Hordeum vulgare", tier=2, clue="malted for beer and whisky before it is ever eaten"))),
    C("PACMAD grasses", "PACMAD clade", 60,
      T("Maize", "Zea mays", tier=1, alt=("corn", "sweetcorn"),
        clue="bred out of a scrappy Mexican grass called teosinte"),
      T("Sugarcane", "Saccharum officinarum", tier=2,
        clue="a grass so full of sugar the stem is pressed like fruit")),
    rank="family",
    gloss="the family that feeds the world and covers a quarter of its land")

MONOCOTS = C(
    "Monocots", "Monocotyledons", 150,
    C("Alismatales", "Alismatales", 130,
      T("Duckweed", "Lemna minor", tier=2, clue="the smallest flowering plant; a green film on a still pond"),
      T("Eelgrass", "Zostera marina", tier=3, alt=("seagrass",),
        clue="a flowering plant that went back into the sea and pollinates underwater")),
    C("Lily-like monocots", "Lilianae", 130,
      C("Liliales", "Liliales", 115,
        T("Tulip", "Tulipa gesneriana", tier=1, clue="crashed the Dutch economy in 1637"),
        T("Lily", "Lilium candidum", tier=2, clue="six tepals, and pollen that stains everything")),
      C("Asparagales", "Asparagales", 120,
        T("Vanilla orchid", "Vanilla planifolia", tier=2, alt=("orchid", "vanilla"),
          clue="a climbing orchid whose pod is the world's second-costliest spice"),
        T("Onion", "Allium cepa", tier=1, clue="cutting it releases a gas that makes you cry"),
        T("Garlic", "Allium sativum", tier=1, clue="crushing the clove is what creates the smell"),
        T("Daffodil", "Narcissus pseudonarcissus", tier=2, clue="a trumpet inside a ring of petals, first out in spring"),
        T("Saffron crocus", "Crocus sativus", tier=2, alt=("saffron",),
          clue="three red threads per flower, picked by hand at dawn"))),
    C("Commelinids", "Commelinids", 125,
      C("Palms", "Arecaceae", 100,
        T("Coconut palm", "Cocos nucifera", tier=1, alt=("coconut",),
          clue="its seed floats across oceans and arrives ready to drink"),
        T("Date palm", "Phoenix dactylifera", tier=2, alt=("dates",),
          clue="cultivated in Mesopotamia for six thousand years"),
        rank="family"),
      C("Zingiberales", "Zingiberales", 90,
        T("Banana", "Musa acuminata", tier=1, clue="a giant herb, not a tree; the fruit is seedless and cloned"),
        T("Ginger", "Zingiber officinale", tier=2, clue="the part you cook with is an underground stem")),
      C("Poales", "Poales", 110,
        T("Pineapple", "Ananas comosus", tier=2, clue="a hundred small fruits fused into one"),
        T("Papyrus", "Cyperus papyrus", tier=3, alt=("sedge",),
          clue="a Nile sedge sliced and pressed into the first paper"),
        GRASSES)),
    gloss="one seed leaf, parallel veins — grasses, palms, orchids, lilies")

ROSIDS = C(
    "Rosids", "Rosids", 120,
    T("Grapevine", "Vitis vinifera", tier=1, alt=("grape", "vine"),
      clue="domesticated in the Caucasus; the same vine makes every wine"),
    C("Fabids", "Fabids", 110,
      C("Legumes", "Fabaceae", 90,
        T("Pea", "Pisum sativum", tier=1, clue="Mendel counted its wrinkled and round seeds"),
        T("Soybean", "Glycine max", tier=2, clue="fixes its own nitrogen; feeds more livestock than people"),
        T("Peanut", "Arachis hypogaea", tier=2, clue="flowers above ground, then buries its own fruit"),
        T("Acacia", "Vachellia tortilis", tier=2, alt=("thorn tree",),
          clue="the flat-topped tree on every savannah horizon"),
        rank="family"),
      C("Rosales", "Rosales", 95,
        C("Rose family", "Rosaceae", 60,
          T("Rose", "Rosa gallica", tier=1, clue="the petals are distilled for the perfume of Kashan"),
          T("Apple", "Malus domestica", tier=1, clue="came out of the wild forests of Kazakhstan"),
          T("Strawberry", "Fragaria ananassa", tier=1, clue="the red part is swollen stem; the seeds are the real fruit"),
          T("Cherry", "Prunus avium", tier=2, clue="Japan tracks a front of its blossom moving north each spring"),
          rank="family"),
        C("Fig family", "Moraceae", 70,
          T("Fig", "Ficus carica", tier=1, clue="the flowers are inside the fruit, pollinated by one wasp"),
          T("Mulberry", "Morus alba", tier=2, clue="silkworms eat nothing else")),
        C("Hemp family", "Cannabaceae", 65,
          T("Hops", "Humulus lupulus", tier=2, clue="the cone that makes beer bitter"),
          T("Cannabis", "Cannabis sativa", tier=2, alt=("hemp", "marijuana"),
            clue="grown for rope and sail for millennia before anything else"))),
      C("Fagales", "Fagales", 95,
        T("Oak", "Quercus robur", tier=1, clue="drops acorns; can stand for eight hundred years"),
        T("Beech", "Fagus sylvatica", tier=2, clue="smooth grey bark, and a floor too dark for anything else"),
        T("Walnut", "Juglans regia", tier=2, clue="poisons the soil around itself so rivals cannot grow"),
        T("Birch", "Betula pendula", tier=2, clue="peeling white bark; the first tree back after the ice")),
      C("Cucurbitales", "Cucurbitales", 95,
        T("Pumpkin", "Cucurbita pepo", tier=1, alt=("squash", "courgette", "zucchini"),
          clue="one of the three sisters, planted with maize and beans"),
        T("Cucumber", "Cucumis sativus", tier=1, clue="ninety-six per cent water, and technically a berry"),
        T("Watermelon", "Citrullus lanatus", tier=1, clue="came out of Africa; painted on Egyptian tomb walls")),
      C("Malpighiales", "Malpighiales", 100,
        T("Willow", "Salix alba", tier=2, clue="its bark gave the world aspirin"),
        T("Poplar", "Populus tremula", tier=3, alt=("aspen",),
          clue="flat leaf stalks make the whole tree shiver in no wind"),
        T("Cassava", "Manihot esculenta", tier=2, alt=("manioc", "tapioca"),
          clue="a root that must be soaked and cooked or it releases cyanide"),
        T("Rubber tree", "Hevea brasiliensis", tier=2, clue="smuggled out of Brazil in a crate of seeds"),
        T("Flax", "Linum usitatissimum", tier=3, alt=("linseed",),
          clue="the stem becomes linen, the seed becomes oil"))),
    C("Malvids", "Malvids", 110,
      C("Myrtales", "Myrtales", 100,
        T("Eucalyptus", "Eucalyptus globulus", tier=2, alt=("gum tree",),
          clue="oily leaves that invite the fire it needs to reseed"),
        T("Clove", "Syzygium aromaticum", tier=3, clue="the spice is an unopened flower bud, dried"),
        T("Pomegranate", "Punica granatum", tier=1, clue="the fruit of Persian gardens; hundreds of seeds in a leathery skin")),
      C("Sapindales", "Sapindales", 95,
        T("Orange", "Citrus sinensis", tier=1, alt=("citrus",),
          clue="every commercial one is a graft of the same few trees"),
        T("Mango", "Mangifera indica", tier=1, clue="grown in India for four thousand years; related to poison ivy"),
        T("Maple", "Acer saccharum", tier=1, clue="winged seeds that spin, and sap boiled forty to one"),
        T("Pistachio", "Pistacia vera", tier=2, clue="Iran and California argue over who grows the best")),
      C("Malvales", "Malvales", 95,
        T("Cotton", "Gossypium hirsutum", tier=1, clue="the fibre is a single hugely elongated seed hair"),
        T("Cacao", "Theobroma cacao", tier=1, alt=("cocoa", "chocolate"),
          clue="pods grow straight out of the trunk; the beans must ferment"),
        T("Baobab", "Adansonia digitata", tier=2, clue="stores water in a trunk you could park a car in")),
      C("Brassicales", "Brassicales", 95,
        T("Cabbage", "Brassica oleracea", tier=1, alt=("kale", "broccoli", "cauliflower"),
          clue="one species bred into broccoli, kale, sprouts and cauliflower"),
        T("Thale cress", "Arabidopsis thaliana", tier=3, alt=("arabidopsis",),
          clue="a roadside weed with a tiny genome; the lab rat of botany"),
        T("Mustard", "Sinapis alba", tier=2, clue="the heat only appears when the crushed seed meets water"),
        T("Papaya", "Carica papaya", tier=2, clue="its enzyme tenderises meat"))),
    gloss="roses, beans, oaks, cotton, citrus — most of the trees you can name")

ASTERIDS = C(
    "Asterids", "Asterids", 120,
    C("Ericales", "Ericales", 110,
      T("Blueberry", "Vaccinium corymbosum", tier=2, clue="needs soil acid enough to kill most crops"),
      T("Tea plant", "Camellia sinensis", tier=1, alt=("tea",),
        clue="green, oolong and black are the same leaf, oxidised differently"),
      T("Brazil nut", "Bertholletia excelsa", tier=3, clue="cannot be farmed; the tree needs wild bees and one rodent")),
    C("Lamiids", "Lamiids", 105,
      C("Solanales", "Solanales", 90,
        T("Tomato", "Solanum lycopersicum", tier=1, clue="Europe grew it as an ornament for two centuries, fearing it was poison"),
        T("Potato", "Solanum tuberosum", tier=1, clue="carried out of the Andes; the tuber is a swollen stem"),
        T("Chilli", "Capsicum annuum", tier=1, alt=("chili", "pepper", "capsicum"),
          clue="the heat is a chemical that birds cannot taste"),
        T("Tobacco", "Nicotiana tabacum", tier=2, clue="the alkaloid is an insecticide the plant makes for itself")),
      C("Lamiales", "Lamiales", 95,
        T("Olive", "Olea europaea", tier=1, clue="inedible off the tree; it must be cured in brine or lye"),
        T("Lavender", "Lavandula angustifolia", tier=2, clue="square stems, and an oil that calms bees and people"),
        T("Mint", "Mentha spicata", tier=1, clue="spreads by runners until it owns the whole bed"),
        T("Basil", "Ocimum basilicum", tier=2, clue="sacred in India, and the whole point of pesto"),
        T("Sesame", "Sesamum indicum", tier=2, clue="the pod springs open — hence the phrase")),
      C("Gentianales", "Gentianales", 95,
        T("Coffee", "Coffea arabica", tier=1, clue="first brewed in Yemen from a bean that is really a seed"),
        T("Oleander", "Nerium oleander", tier=3, clue="every part of this roadside shrub can stop a heart"))),
    C("Campanulids", "Campanulids", 105,
      C("Daisy family", "Asteraceae", 90,
        T("Sunflower", "Helianthus annuus", tier=1, clue="what looks like one flower is more than a thousand"),
        T("Lettuce", "Lactuca sativa", tier=1, clue="bolts to a bitter milky stalk the moment it gets hot"),
        T("Dandelion", "Taraxacum officinale", tier=2, clue="sets seed without pollination, so every one is a clone"),
        T("Chamomile", "Matricaria chamomilla", tier=2, clue="dried heads steeped for a tea that smells of apples"),
        rank="family"),
      C("Apiales", "Apiales", 90,
        T("Carrot", "Daucus carota", tier=1, clue="wild it is white and woody; orange was a Dutch selection"),
        T("Celery", "Apium graveolens", tier=2, clue="grown in trenches and blanched to take the bitterness out"),
        T("Parsley", "Petroselinum crispum", tier=2, clue="flat or curled, and the seed takes a month to germinate"))),
    gloss="fused petals — coffee, mint, tomatoes, sunflowers")

EUDICOTS = C(
    "Eudicots", "Eudicotyledons", 145,
    C("Ranunculales", "Ranunculales", 130,
      T("Poppy", "Papaver somniferum", tier=1, clue="the scored seed pod weeps the latex that becomes opium"),
      T("Buttercup", "Ranunculus acris", tier=2, clue="glossy petals that reflect yellow light under your chin")),
    C("Proteales", "Proteales", 125,
      T("Sacred lotus", "Nelumbo nucifera", tier=2, alt=("lotus",),
        clue="leaves so water-repellent that engineers copied the surface"),
      T("Plane tree", "Platanus orientalis", tier=2, alt=("sycamore", "chenar"),
        clue="peels its own bark in plates; the shade tree of Isfahan")),
    C("Core eudicots", "Gunneridae", 125,
      C("Caryophyllales", "Caryophyllales", 110,
        T("Saguaro cactus", "Carnegiea gigantea", tier=1, alt=("cactus", "saguaro"),
          clue="pleated to swell after rain; takes seventy years to grow an arm"),
        T("Spinach", "Spinacia oleracea", tier=2, clue="its iron content was famously exaggerated by a decimal point"),
        T("Quinoa", "Chenopodium quinoa", tier=2, clue="the seed must be rinsed of its bitter soapy coat"),
        T("Venus flytrap", "Dionaea muscipula", tier=1, clue="counts touches on its trigger hairs before it shuts"),
        T("Rhubarb", "Rheum rhabarbarum", tier=2, clue="the stalk is a pudding; the leaf is poison")),
      ASTERIDS,
      ROSIDS),
    gloss="three pollen pores — four fifths of all flowering plants")

ANGIOSPERMS = C(
    "Flowering plants", "Angiospermae", 190,
    T("Amborella", "Amborella trichopoda", tier=3,
      clue="a shrub on one Pacific island, sister to every other flower on earth"),
    C("Water lilies", "Nymphaeales", 175,
      T("Water lily", "Nymphaea alba", tier=2, clue="roots in the mud, leaves floating, flower open only by day")),
    C("Mesangiosperms", "Mesangiospermae", 170,
      C("Magnoliids", "Magnoliids", 160,
        T("Magnolia", "Magnolia grandiflora", tier=2,
          clue="older than bees, so it is built to be pollinated by beetles"),
        T("Avocado", "Persea americana", tier=1,
          clue="its fruit was built for a giant sloth that no longer exists"),
        T("Black pepper", "Piper nigrum", tier=2, alt=("pepper", "peppercorn"),
          clue="a climbing vine whose dried berry once cost more than gold"),
        T("Cinnamon", "Cinnamomum verum", tier=2, clue="the spice is the inner bark, rolled as it dries")),
      MONOCOTS,
      EUDICOTS),
    gloss="the flower, the fruit and the double fertilisation — 300,000 species in 150 million years")

GYMNOSPERMS = C(
    "Gymnosperms", "Acrogymnospermae", 330,
    C("Cycads and ginkgo", "Cycadophyta and Ginkgophyta", 310,
      T("Sago cycad", "Cycas revoluta", tier=2, alt=("cycad", "sago palm"),
        clue="looks like a palm, but its ancestors fed the dinosaurs"),
      T("Ginkgo", "Ginkgo biloba", tier=1, alt=("maidenhair tree",),
        clue="the last of its kind; four trees survived Hiroshima")),
    C("Conifers and gnetophytes", "Conifers and Gnetophyta", 310,
      T("Welwitschia", "Welwitschia mirabilis", tier=3,
        clue="two leaves, growing for a thousand years in the Namib"),
      C("Conifers", "Pinophyta", 300,
        C("Pine family", "Pinaceae", 200,
          T("Scots pine", "Pinus sylvestris", tier=2, alt=("pine",),
            clue="orange bark up top; the tree that came back after the glaciers"),
          T("Spruce", "Picea abies", tier=2, clue="the tree in the corner of the room every December"),
          T("Cedar of Lebanon", "Cedrus libani", tier=2, alt=("cedar",),
            clue="on a flag, and in the timbers of Solomon's temple"),
          rank="family"),
        C("Cypress line", "Cupressophyta", 220,
          T("Coast redwood", "Sequoia sempervirens", tier=1, alt=("redwood", "sequoia"),
            clue="the tallest living thing; drinks fog through its leaves"),
          T("Yew", "Taxus baccata", tier=2, clue="every part is poison except the red flesh; longbows were cut from it"),
          T("Monkey puzzle", "Araucaria araucana", tier=3, clue="spiral spikes and a Chilean accent"))),
      gloss="cones, needles and resin — the forests that came before flowers"),
    gloss="naked seeds, no flowers, no fruit")

LAND_PLANTS = C(
    "Land plants", "Embryophyta", 500,
    C("Bryophytes", "Bryophyta and relatives", 480,
      T("Sphagnum moss", "Sphagnum palustre", tier=2, alt=("moss", "peat moss"),
        clue="acidifies the bog it builds, and preserves whatever falls in"),
      T("Haircap moss", "Polytrichum commune", tier=3, clue="taller than a moss has any business being"),
      T("Liverwort", "Marchantia polymorpha", tier=3, clue="a flat green ribbon with cups of clones on its back"),
      gloss="no plumbing — they must stay small and stay damp"),
    C("Vascular plants", "Tracheophyta", 430,
      C("Clubmosses", "Lycopodiopsida", 400,
        T("Clubmoss", "Lycopodium clavatum", tier=3, alt=("club moss",),
          clue="a survivor of the coal forests, now ankle-high")),
      C("Euphyllophytes", "Euphyllophyta", 410,
        C("Ferns and horsetails", "Polypodiopsida", 380,
          T("Bracken", "Pteridium aquilinum", tier=2, alt=("fern", "bracken fern"),
            clue="unrolls a fiddlehead; one clone can cover a whole hillside"),
          T("Horsetail", "Equisetum arvense", tier=3, clue="jointed, gritty with silica, and unchanged since the Devonian"),
          gloss="spores, not seeds — the green understorey of the coal age"),
        C("Seed plants", "Spermatophyta", 350,
          GYMNOSPERMS,
          ANGIOSPERMS,
          gloss="the seed: an embryo packed with food and posted into the future")),
      gloss="tubes for water and stiffening for height — the invention of the tree"),
    rank="kingdom",
    gloss="the move onto dry land, about half a billion years ago")

PLANTS = C(
    "Plants and their relatives", "Archaeplastida", 1600,
    C("Red algae", "Rhodophyta", 1200,
      T("Nori", "Pyropia yezoensis", tier=2, alt=("laver", "seaweed"),
        clue="dried in sheets and wrapped around rice"),
      T("Coralline alga", "Corallina officinalis", tier=3, alt=("coralline algae",),
        clue="a seaweed that builds itself a skeleton of chalk"),
      gloss="the first lineage to keep a captured cyanobacterium and never let go"),
    C("Green plants", "Viridiplantae", 1100,
      C("Green algae", "Chlorophyta", 900,
        T("Sea lettuce", "Ulva lactuca", tier=3, alt=("ulva",),
          clue="bright green sheets two cells thick, in every rock pool"),
        T("Chlamydomonas", "Chlamydomonas reinhardtii", tier=3,
          clue="a green cell with two whips and an eyespot; a lab favourite"),
        T("Volvox", "Volvox carteri", tier=3,
          clue="a hollow rolling ball of cells — one of life's first colonies")),
      C("Streptophytes", "Streptophyta", 850,
        T("Stonewort", "Chara vulgaris", tier=3, clue="a pond alga that is closer to an oak than to seaweed"),
        LAND_PLANTS)),
    gloss="everything descended from the cell that swallowed a cyanobacterium")


# ══════════════════════════════════════════════════════════════════════════════
# FUNGI — closer to us than to anything green
# ══════════════════════════════════════════════════════════════════════════════

FUNGI = C(
    "Fungi", "Fungi", 1000,
    T("Chytrid fungus", "Batrachochytrium dendrobatidis", tier=3, alt=("chytrid",),
      clue="swims to its host; it is wiping out the world's frogs"),
    T("Black bread mould", "Rhizopus stolonifer", tier=3, alt=("bread mould", "bread mold"),
      clue="the grey fuzz on forgotten bread"),
    C("Dikarya", "Dikarya", 650,
      C("Sac fungi", "Ascomycota", 550,
        T("Brewer's yeast", "Saccharomyces cerevisiae", tier=1, alt=("yeast", "bakers yeast"),
          clue="one cell that gave us bread, beer, wine — and half of cell biology"),
        C("Filamentous sac fungi", "Pezizomycotina", 450,
          T("Penicillium", "Penicillium chrysogenum", tier=2, alt=("penicillin", "blue mould"),
            clue="the blue-green mould on a forgotten Petri dish in Paddington"),
          T("Morel", "Morchella esculenta", tier=2,
            clue="a honeycombed cap that nobody has managed to farm properly"),
          T("Black truffle", "Tuber melanosporum", tier=2, alt=("truffle",),
            clue="fruits underground and pays a pig to dig it up"),
          T("Zombie-ant fungus", "Ophiocordyceps unilateralis", tier=2, alt=("cordyceps",),
            clue="steers an ant to the right leaf, at the right height, then kills it"),
          T("Reindeer lichen", "Cladonia rangiferina", tier=2, alt=("lichen",),
            clue="not one organism — a fungus farming an alga inside itself")),
        gloss="spores fired from a sac; yeasts, moulds, truffles and most lichens"),
      C("Club fungi", "Basidiomycota", 500,
        C("Mushroom-formers", "Agaricomycetes", 300,
          T("Button mushroom", "Agaricus bisporus", tier=1, alt=("mushroom", "portobello"),
            clue="white, chestnut and portobello are one species at three ages"),
          T("Fly agaric", "Amanita muscaria", tier=1, alt=("amanita", "toadstool"),
            clue="the red-and-white toadstool of every illustrated fairy tale"),
          T("Shiitake", "Lentinula edodes", tier=2,
            clue="grown on logs of oak; the name means oak-tree mushroom"),
          T("Honey fungus", "Armillaria ostoyae", tier=3,
            clue="one individual in Oregon covers nine square kilometres")),
        T("Wheat rust", "Puccinia graminis", tier=3, alt=("rust fungus",),
          clue="the orange blight that has been ruining harvests since Rome"),
        gloss="spores on clubs under a cap — the mushrooms you would recognise"),
      gloss="the two lineages that make everything we call a mushroom"),
    rank="kingdom",
    gloss="feed by digesting the world outside themselves, then absorbing it")


# ══════════════════════════════════════════════════════════════════════════════
# ANIMALS · the invertebrate three-quarters
# ══════════════════════════════════════════════════════════════════════════════

CNIDARIA = C(
    "Cnidarians", "Cnidaria", 600,
    C("Anthozoans", "Anthozoa", 550,
      T("Staghorn coral", "Acropora cervicornis", tier=1, alt=("coral",),
        clue="an animal that farms algae in its own flesh and builds a reef"),
      T("Sea anemone", "Actinia equina", tier=1, clue="a stomach with tentacles, glued to a rock"),
      T("Sea fan", "Gorgonia ventalina", tier=3, alt=("gorgonian",),
        clue="a colony grown as a fan, set square across the current")),
    C("Medusozoans", "Medusozoa", 550,
      T("Moon jellyfish", "Aurelia aurita", tier=1, alt=("jellyfish", "jelly"),
        clue="ninety-five per cent water, four horseshoes for gonads, no brain"),
      T("Box jellyfish", "Chironex fleckeri", tier=2,
        clue="twenty-four eyes and a sting that can stop a heart in minutes"),
      T("Portuguese man o' war", "Physalia physalis", tier=2, alt=("man o war", "man of war"),
        clue="not one animal but a colony of four kinds, sailing"),
      T("Hydra", "Hydra vulgaris", tier=2,
        clue="a freshwater stalk that regrows any part and may not age")),
    gloss="stinging cells, radial symmetry, a body with one opening")

ARACHNIDS = C(
    "Arachnids", "Arachnida", 450,
    C("Spiders", "Araneae", 300,
      T("Garden spider", "Araneus diadematus", tier=1, alt=("orb weaver", "spider"),
        clue="rebuilds the whole orb web most mornings and eats the old silk"),
      T("Tarantula", "Brachypelma hamorii", tier=1,
        clue="flicks barbed hairs off its abdomen at whatever is bothering it"),
      T("Jumping spider", "Salticus scenicus", tier=2,
        clue="eight eyes, four of them excellent; stalks rather than webs"),
      T("Black widow", "Latrodectus mactans", tier=2,
        clue="a red hourglass, and venom fifteen times a rattlesnake's"),
      rank="order"),
    T("Emperor scorpion", "Pandinus imperator", tier=1, alt=("scorpion",),
      clue="glows blue-white under ultraviolet light, and nobody knows why"),
    C("Ticks and mites", "Acari", 400,
      T("Tick", "Ixodes ricinus", tier=1,
        clue="waits on a grass blade with its front legs out, for months if it must"),
      T("Dust mite", "Dermatophagoides pteronyssinus", tier=3,
        clue="eats your shed skin; there are millions in the mattress")),
    gloss="eight legs, no antennae, no wings — spiders, scorpions, ticks")

INSECTS = C(
    "Insects", "Insecta", 440,
    T("Dragonfly", "Anax imperator", tier=1,
      clue="hunts on the wing with a ninety-five per cent success rate"),
    T("Mayfly", "Ephemera danica", tier=2,
      clue="two years in the riverbed, one afternoon in the air"),
    C("Neopterans", "Neoptera", 390,
      C("Polyneopterans", "Polyneoptera", 340,
        C("Roaches and mantises", "Dictyoptera", 250,
          T("Praying mantis", "Mantis religiosa", tier=1, alt=("mantis",),
            clue="the only insect that can turn its head to look straight at you"),
          C("Cockroaches and termites", "Blattodea", 180,
            T("Cockroach", "Blattella germanica", tier=1,
              clue="lives a week without its head; dies of thirst, not of that"),
            T("Termite", "Macrotermes bellicosus", tier=1,
              clue="builds an air-conditioned tower and farms fungus inside it"))),
        C("Orthopterans", "Orthoptera", 250,
          T("Locust", "Schistocerca gregaria", tier=1, alt=("grasshopper",),
            clue="a solitary green insect that turns yellow and swarms when crowded"),
          T("Cricket", "Gryllus campestris", tier=2,
            clue="rubs one wing against the other; the rate tells you the temperature")),
        T("Stick insect", "Carausius morosus", tier=2, alt=("walking stick",),
          clue="a twig with legs; females can breed with no male at all"),
        T("Earwig", "Forficula auricularia", tier=2,
          clue="the pincers are for courtship, and it guards its eggs like a bird")),
      C("Eumetabolans", "Eumetabola", 380,
        C("Paraneopterans", "Paraneoptera", 330,
          C("True bugs", "Hemiptera", 300,
            T("Aphid", "Acyrthosiphon pisum", tier=2, alt=("greenfly",),
              clue="born pregnant, and milked by ants for sugar"),
            T("Cicada", "Magicicada septendecim", tier=1,
              clue="counts seventeen years underground, then emerges with everyone else"),
            T("Bedbug", "Cimex lectularius", tier=2,
              clue="hitchhikes in luggage and feeds while you sleep")),
          T("Head louse", "Pediculus humanus", tier=3, alt=("louse", "lice"),
            clue="its two forms split when we started wearing clothes")),
        C("Holometabolans", "Holometabola", 350,
          C("Beetles", "Coleoptera", 300,
            T("Ladybird", "Coccinella septempunctata", tier=1, alt=("ladybug",),
              clue="bleeds foul yellow blood from its knees when handled"),
            T("Dung beetle", "Scarabaeus sacer", tier=1, alt=("scarab",),
              clue="rolls its ball in a straight line by the light of the Milky Way"),
            T("Stag beetle", "Lucanus cervus", tier=2,
              clue="those enormous jaws are for wrestling, and cannot really bite"),
            T("Firefly", "Photinus pyralis", tier=1, alt=("lightning bug",),
              clue="each species flashes its own code; one female fakes another's"),
            T("Weevil", "Curculio nucum", tier=3,
              clue="a beetle with a long snout, drilling into a nut"),
            rank="order",
            gloss="a quarter of all named species on earth are beetles"),
          C("Ants, bees and wasps", "Hymenoptera", 300,
            T("Parasitoid wasp", "Nasonia vitripennis", tier=3, alt=("ichneumon",),
              clue="lays its eggs inside a living host; the sight shook Darwin's faith"),
            C("Stinging hymenopterans", "Aculeata", 190,
              C("Ants", "Formicidae", 140,
                T("Leafcutter ant", "Atta cephalotes", tier=1, alt=("ant",),
                  clue="cuts leaves it cannot eat, to feed a fungus that it can"),
                T("Army ant", "Eciton burchellii", tier=2,
                  clue="builds its nest out of its own living bodies"),
                rank="family"),
              C("Bees", "Anthophila", 120,
                T("Honeybee", "Apis mellifera", tier=1, alt=("bee",),
                  clue="dances a figure of eight to give the angle and the distance"),
                T("Bumblebee", "Bombus terrestris", tier=1,
                  clue="shivers its flight muscles to warm up, and buzzes pollen loose")),
              T("Paper wasp", "Polistes dominula", tier=2, alt=("wasp",),
                clue="chews wood into pulp and builds an open comb of it"))),
          C("Butterflies and moths", "Lepidoptera", 230,
            T("Micromoth", "Micropterix calthella", tier=3,
              clue="the oldest branch of moths; it still chews pollen with jaws"),
            C("Ditrysians", "Ditrysia", 150,
              C("Butterflies", "Papilionoidea", 110,
                T("Monarch butterfly", "Danaus plexippus", tier=1, alt=("monarch", "butterfly"),
                  clue="four generations to go north, one to fly the whole way back"),
                T("Swallowtail", "Papilio machaon", tier=2,
                  clue="the caterpillar rears up and everts an orange stink-horn")),
              C("Silkmoths and hawkmoths", "Bombycoidea", 90,
                T("Silkworm moth", "Bombyx mori", tier=1, alt=("silkworm", "silk moth"),
                  clue="domesticated for so long it can no longer fly or feed"),
                T("Hawkmoth", "Manduca sexta", tier=2, alt=("hawk moth", "sphinx moth"),
                  clue="hovers at a flower like a hummingbird, at dusk"))),
            rank="order"),
          C("Flies", "Diptera", 250,
            T("Mosquito", "Anopheles gambiae", tier=1,
              clue="only the female bites, and she is the deadliest animal alive"),
            C("Higher flies", "Brachycera", 190,
              T("Fruit fly", "Drosophila melanogaster", tier=1, alt=("drosophila",),
                clue="red eyes, ten days a generation, a century of genetics"),
              T("Housefly", "Musca domestica", tier=1,
                clue="tastes with its feet and vomits on its food to dissolve it")),
            rank="order"),
          T("Flea", "Ctenocephalides felis", tier=2,
            clue="jumps a hundred times its length using a pad of stored elastic"),
          gloss="complete metamorphosis: a larva, a pupa, and a rebuild in between")),
      gloss="wings that fold flat over the back — which let insects hide"),
    rank="class",
    gloss="six legs, three body parts, and more species than everything else combined")

ARTHROPODS = C(
    "Arthropods", "Arthropoda", 540,
    C("Chelicerates", "Chelicerata", 500,
      T("Horseshoe crab", "Limulus polyphemus", tier=1,
        clue="blue blood, drawn by the pharmaceutical industry to test for bacteria"),
      T("Sea spider", "Pycnogonum litorale", tier=3,
        clue="so thin that its gut runs down its legs"),
      ARACHNIDS),
    C("Mandibulates", "Mandibulata", 530,
      C("Myriapods", "Myriapoda", 480,
        T("Centipede", "Lithobius forficatus", tier=1,
          clue="one pair of legs per segment, and the front pair is venomous"),
        T("Millipede", "Julus scandinavius", tier=2,
          clue="two pairs of legs per segment, and a chemical defence, not a bite")),
      C("Pancrustaceans", "Pancrustacea", 510,
        C("Branchiopods", "Branchiopoda", 470,
          T("Brine shrimp", "Artemia salina", tier=2, alt=("sea monkey", "sea monkeys"),
            clue="sold as dust in a packet; add salt water and it hatches"),
          T("Water flea", "Daphnia pulex", tier=3, alt=("daphnia",),
            clue="transparent, so you can watch its heart beat under a lens")),
        C("Crustaceans", "Multicrustacea", 450,
          T("Barnacle", "Semibalanus balanoides", tier=2,
            clue="glues its head to a rock and kicks food into its mouth for life"),
          T("Copepod", "Calanus finmarchicus", tier=3,
            clue="probably the most numerous animal in the ocean"),
          C("Malacostracans", "Malacostraca", 430,
            C("Decapods", "Decapoda", 400,
              T("Lobster", "Homarus gammarus", tier=1,
                clue="tastes with its legs, and does not obviously die of old age"),
              T("Crab", "Cancer pagurus", tier=1,
                clue="the body plan evolved at least five separate times"),
              T("Prawn", "Palaemon serratus", tier=1, alt=("shrimp",),
                clue="swims backwards by flicking its tail under itself"),
              rank="order"),
            T("Krill", "Euphausia superba", tier=2,
              clue="a swarm can weigh more than every human alive"),
            T("Woodlouse", "Armadillidium vulgare", tier=2, alt=("pill bug", "roly poly", "slater"),
              clue="a crustacean that made it onto land, and still breathes like a fish"),
            T("Mantis shrimp", "Odontodactylus scyllarus", tier=2,
              clue="punches at the speed of a bullet, and boils the water doing it"))),
        C("Hexapods", "Hexapoda", 480,
          T("Springtail", "Folsomia candida", tier=3,
            clue="flicks a folded tail against the ground and vanishes"),
          INSECTS))),
    rank="phylum",
    gloss="jointed legs in a suit of armour that has to be shed to grow")

MOLLUSCS = C(
    "Molluscs", "Mollusca", 550,
    C("Cephalopods", "Cephalopoda", 480,
      T("Nautilus", "Nautilus pompilius", tier=2,
        clue="the last shelled one; pinhole eyes and ninety tentacles"),
      C("Soft cephalopods", "Coleoidea", 300,
        T("Octopus", "Octopus vulgaris", tier=1,
          clue="two thirds of its neurons are in its arms; it opens jars"),
        C("Ten-armed cephalopods", "Decapodiformes", 200,
          T("Squid", "Loligo vulgaris", tier=1,
            clue="jet-propelled, with the fastest nerve fibre in the animal kingdom"),
          T("Cuttlefish", "Sepia officinalis", tier=1,
            clue="runs colour across its skin like a screen — and is colour-blind"))),
      rank="class"),
    C("Gastropods", "Gastropoda", 500,
      T("Garden snail", "Cornu aspersum", tier=1, alt=("snail",),
        clue="rasps with a tongue of thousands of teeth, and is both sexes at once"),
      T("Slug", "Arion ater", tier=1,
        clue="a snail that gave up on the shell, and dries out for it"),
      T("Limpet", "Patella vulgata", tier=2,
        clue="grinds a scar into the rock to fit, and returns to it every tide"),
      T("Sea slug", "Chromodoris quadricolor", tier=2, alt=("nudibranch",),
        clue="steals stinging cells from what it eats and wears them"),
      rank="class"),
    C("Bivalves", "Bivalvia", 500,
      T("Oyster", "Ostrea edulis", tier=1,
        clue="filters two hundred litres a day and changes sex as it goes"),
      T("Mussel", "Mytilus edulis", tier=1,
        clue="holds on with threads of protein that set underwater"),
      T("Scallop", "Pecten maximus", tier=2,
        clue="dozens of blue eyes along the mantle, and it swims by clapping"),
      T("Giant clam", "Tridacna gigas", tier=2,
        clue="grows to two hundred kilos by farming algae in its own lips"),
      rank="class"),
    rank="phylum",
    gloss="a muscular foot, a rasping tongue and, usually, a shell")

SPIRALIA = C(
    "Spiralians", "Spiralia", 600,
    C("Flatworms", "Platyhelminthes", 560,
      T("Planarian", "Schmidtea mediterranea", tier=2, alt=("flatworm",),
        clue="cut it in half and you get two; cross-eyed if you cut the head"),
      T("Tapeworm", "Taenia solium", tier=2,
        clue="no mouth and no gut; it bathes in someone else's dinner"),
      rank="phylum"),
    C("Annelids", "Annelida", 560,
      T("Earthworm", "Lumbricus terrestris", tier=1, alt=("worm",),
        clue="Darwin's last book was about how much soil it moves"),
      T("Leech", "Hirudo medicinalis", tier=2,
        clue="anaesthetises the bite and keeps the blood from clotting"),
      T("Ragworm", "Hediste diversicolor", tier=3,
        clue="bristles down each side; dug out of estuary mud for bait"),
      T("Giant tube worm", "Riftia pachyptila", tier=2, alt=("tube worm",),
        clue="lives on volcanic vents with no mouth, fed by bacteria inside it"),
      rank="phylum"),
    MOLLUSCS,
    T("Brachiopod", "Lingula anatina", tier=3, alt=("lamp shell",),
      clue="a shell on a stalk, essentially unchanged for half a billion years"),
    T("Bdelloid rotifer", "Adineta vaga", tier=3, alt=("rotifer",),
      clue="no male has ever been found, and it survives being dried to dust"),
    gloss="worms, snails and their kin — the other half of the protostomes")

ECDYSOZOA = C(
    "Ecdysozoans", "Ecdysozoa", 590,
    C("Roundworms", "Nematoda", 500,
      T("C. elegans", "Caenorhabditis elegans", tier=2, alt=("c elegans", "nematode", "roundworm"),
        clue="959 cells, every one of them mapped, and a wiring diagram to match"),
      T("Hookworm", "Necator americanus", tier=3,
        clue="enters through the sole of a bare foot"),
      rank="phylum"),
    C("Panarthropods", "Panarthropoda", 570,
      T("Tardigrade", "Hypsibius dujardini", tier=1, alt=("water bear", "moss piglet"),
        clue="dries to a husk, takes a trip to space, and walks it off"),
      T("Velvet worm", "Euperipatoides rowelli", tier=3,
        clue="fires two jets of glue to pin its dinner down"),
      ARTHROPODS),
    gloss="animals that grow by shedding the whole skin — insects, crabs, worms")

DEUTEROSTOMES_INVERT = C(
    "Ambulacrarians", "Ambulacraria", 590,
    C("Echinoderms", "Echinodermata", 540,
      T("Starfish", "Asterias rubens", tier=1, alt=("sea star",),
        clue="pushes its stomach out through its mouth and digests the mussel in place"),
      T("Sea urchin", "Echinus esculentus", tier=1,
        clue="grazes with a five-toothed lantern that Aristotle described"),
      T("Sea cucumber", "Holothuria tubulosa", tier=2,
        clue="when frightened it throws out its own guts and grows new ones"),
      T("Brittle star", "Ophiothrix fragilis", tier=3,
        clue="arms that thrash like whips, and drop off if grabbed"),
      T("Feather star", "Antedon bifida", tier=3, alt=("crinoid", "sea lily"),
        clue="the oldest echinoderm design — a filter fan on a stalk"),
      rank="phylum",
      gloss="five-fold symmetry, tube feet, and a skeleton under the skin"),
    T("Acorn worm", "Saccoglossus kowalevskii", tier=3,
      clue="a burrowing worm with gill slits — which is why it matters"),
    gloss="the invertebrate half of our own branch of the animal kingdom")


# ══════════════════════════════════════════════════════════════════════════════
# FISH — four hundred million years of everything that swims
# ══════════════════════════════════════════════════════════════════════════════

PERCOMORPHS = C(
    "Percomorphs", "Percomorphaceae", 120,
    C("Pipefish and seahorses", "Syngnathiformes", 60,
      T("Seahorse", "Hippocampus hippocampus", tier=1,
        clue="the male carries the pregnancy, in a pouch")),
    C("Pufferfish and relatives", "Tetraodontiformes", 80,
      T("Pufferfish", "Takifugu rubripes", tier=1, alt=("fugu", "puffer fish"),
        clue="swallows water to double in size; licensed chefs only")),
    C("Ovalentarians", "Ovalentaria", 100,
      T("Clownfish", "Amphiprion ocellaris", tier=1, alt=("anemonefish",),
        clue="lives in the stinging anemone, and every one starts male"),
      T("Nile tilapia", "Oreochromis niloticus", tier=2, alt=("tilapia",),
        clue="broods its young in its mouth; farmed on every continent")),
    C("Pelagic percomorphs", "Pelagiaria", 90,
      T("Bluefin tuna", "Thunnus thynnus", tier=1, alt=("tuna",),
        clue="warm-blooded, never stops swimming, and sells for millions in Tokyo")),
    C("Carangarians", "Carangaria", 95,
      T("Swordfish", "Xiphias gladius", tier=2,
        clue="heats its own eyes and brain to hunt in cold deep water"),
      T("Flounder", "Platichthys flesus", tier=2, alt=("plaice", "flatfish"),
        clue="one eye migrates across the skull as the young fish tips over")),
    T("Anglerfish", "Melanocetus johnsonii", tier=1,
      clue="a lit lure over the mouth; the male fuses on as a parasite"),
    T("Mudskipper", "Periophthalmus barbarus", tier=2,
      clue="crosses the mudflat on its fins and breathes through wet skin"),
    gloss="spiny-rayed fish — the explosion that produced most fish alive")

RAY_FINS = C(
    "Ray-finned fish", "Actinopterygii", 400,
    C("Sturgeons and paddlefish", "Acipenseriformes", 200,
      T("Sturgeon", "Acipenser sturio", tier=2, alt=("beluga sturgeon", "caviar"),
        clue="armoured, ancient, slow to mature, and fished for its roe"),
      T("Paddlefish", "Polyodon spathula", tier=3,
        clue="sweeps a electroreceptive snout through the water for plankton")),
    C("Neopterygians", "Neopterygii", 330,
      C("Gars and bowfin", "Holostei", 280,
        T("Alligator gar", "Atractosteus spatula", tier=3, alt=("gar",),
          clue="a living fossil in a diamond of enamelled scales")),
      C("Teleosts", "Teleostei", 280,
        C("Eels and tarpon", "Elopomorpha", 250,
          T("European eel", "Anguilla anguilla", tier=1, alt=("eel",),
            clue="born in the Sargasso Sea; nobody has ever seen it spawn")),
        C("Bony tongues", "Osteoglossomorpha", 230,
          T("Arowana", "Osteoglossum bicirrhosum", tier=3,
            clue="leaps clear of the water to take insects off branches")),
        C("Clupeocephalans", "Clupeocephala", 240,
          T("Herring", "Clupea harengus", tier=1,
            clue="shoals in millions; salted and smoked, it built northern Europe"),
          C("Ostariophysans", "Ostariophysi", 200,
            C("Carps and minnows", "Cypriniformes", 150,
              T("Common carp", "Cyprinus carpio", tier=1, alt=("goldfish", "koi", "carp"),
                clue="the goldfish and the koi are both selections of it"),
              T("Zebrafish", "Danio rerio", tier=2,
                clue="a see-through embryo made it the lab's favourite vertebrate")),
            T("Piranha", "Pygocentrus nattereri", tier=1,
              clue="mostly eats fins and scales; the reputation is Roosevelt's fault"),
            T("Catfish", "Silurus glanis", tier=1, alt=("wels catfish",),
              clue="barbels for whiskers, and taste buds over its whole body"),
            T("Electric eel", "Electrophorus electricus", tier=1,
              clue="600 volts from three organs, and it is not an eel"),
            gloss="the freshwater fish — they hear through a chain of little bones"),
          C("Euteleosts", "Euteleostei", 230,
            C("Salmon and trout", "Salmoniformes", 40,
              T("Atlantic salmon", "Salmo salar", tier=1, alt=("salmon",),
                clue="navigates back to the smell of the stream it hatched in"),
              T("Brown trout", "Salmo trutta", tier=2, alt=("trout",),
                clue="the same species whether it stays in the burn or goes to sea")),
            T("Northern pike", "Esox lucius", tier=2, alt=("pike",),
              clue="an ambush torpedo lying still in the weed"),
            C("Spiny-rayed fish", "Acanthomorpha", 150,
              T("Atlantic cod", "Gadus morhua", tier=1, alt=("cod",),
                clue="a chin barbel and a white lateral line; fished nearly to nothing"),
              PERCOMORPHS)))),
      gloss="the modern fish: light bones, a swim bladder and protrusible jaws"),
    rank="class",
    gloss="fins held out on rays — 96 per cent of all fish species")

CARTILAGINOUS = C(
    "Cartilaginous fish", "Chondrichthyes", 420,
    C("Sharks and rays", "Elasmobranchii", 285,
      C("Sharks", "Selachimorpha", 200,
        T("Great white shark", "Carcharodon carcharias", tier=1, alt=("great white", "shark"),
          clue="warms its own muscles; smells blood but not from a mile off"),
        T("Whale shark", "Rhincodon typus", tier=1,
          clue="the biggest fish there is, and it eats the smallest things"),
        T("Hammerhead", "Sphyrna mokarran", tier=1, alt=("hammerhead shark",),
          clue="the head is a wing, and a spread of electrical sensors"),
        rank="order"),
      C("Rays", "Batoidea", 180,
        T("Manta ray", "Mobula birostris", tier=1, alt=("manta",),
          clue="seven metres across, and it somersaults through plankton"),
        T("Stingray", "Dasyatis pastinaca", tier=1,
          clue="buries itself in sand; the barb is defence, not hunting"))),
    T("Ratfish", "Chimaera monstrosa", tier=3, alt=("chimaera",),
      clue="a deep-water cousin of the sharks with a rabbit's face"),
    rank="class",
    gloss="no bone at all — a skeleton of cartilage, and skin made of teeth")

# ══════════════════════════════════════════════════════════════════════════════
# AMPHIBIANS, REPTILES, BIRDS
# ══════════════════════════════════════════════════════════════════════════════

AMPHIBIANS = C(
    "Amphibians", "Lissamphibia", 300,
    C("Frogs and toads", "Anura", 200,
      T("Common frog", "Rana temporaria", tier=1, alt=("frog",),
        clue="breathes through its skin, and overwinters in the mud of the pond"),
      T("Cane toad", "Rhinella marina", tier=1, alt=("toad",),
        clue="released to eat beetles in Queensland; ate everything else instead"),
      T("Poison dart frog", "Dendrobates tinctorius", tier=1,
        clue="gets its poison from its diet; captive-bred ones are harmless"),
      rank="order"),
    C("Salamanders and newts", "Caudata", 190,
      T("Axolotl", "Ambystoma mexicanum", tier=1,
        clue="never grows up, regrows limbs, and is nearly extinct in the wild"),
      T("Fire salamander", "Salamandra salamandra", tier=2, alt=("salamander",),
        clue="black and yellow, and folklore had it walking out of flames"),
      T("Japanese giant salamander", "Andrias japonicus", tier=2,
        clue="a metre and a half of wrinkled skin in a cold mountain stream"),
      T("Smooth newt", "Lissotriton vulgaris", tier=2, alt=("newt",),
        clue="grows a crest and dances underwater for a few weeks each spring"),
      rank="order"),
    T("Caecilian", "Ichthyophis glutinosus", tier=3,
      clue="a limbless burrowing amphibian; some young eat their mother's skin"),
    rank="class",
    gloss="wet skin, eggs with no shell — tied to fresh water for life")

SQUAMATES = C(
    "Lizards and snakes", "Squamata", 190,
    C("Geckos", "Gekkota", 100,
      T("Leopard gecko", "Eublepharis macularius", tier=2, alt=("gecko",),
        clue="sheds and eats its own skin; the tail is a food store"),
      T("Tokay gecko", "Gekko gecko", tier=3,
        clue="climbs glass on billions of hairs, using nothing but molecular attraction")),
    C("Iguanians", "Iguania", 160,
      T("Green iguana", "Iguana iguana", tier=1, alt=("iguana",),
        clue="a strict vegetarian that drops out of trees into rivers"),
      T("Chameleon", "Chamaeleo chamaeleon", tier=1,
        clue="colour is a mood and a temperature, not camouflage; eyes work separately"),
      T("Bearded dragon", "Pogona vitticeps", tier=2,
        clue="waves one arm to signal submission, and puffs a black beard")),
    C("Scincomorphs", "Scincomorpha", 150,
      T("Skink", "Scincus scincus", tier=2,
        clue="swims through dry sand as if it were water")),
    C("Anguimorphs", "Anguimorpha", 140,
      T("Komodo dragon", "Varanus komodoensis", tier=1, alt=("monitor lizard",),
        clue="three metres of venomous lizard on a handful of Indonesian islands"),
      T("Slow worm", "Anguis fragilis", tier=3,
        clue="a legless lizard, not a snake — it blinks and it can shed its tail")),
    C("Snakes", "Serpentes", 130,
      T("Reticulated python", "Malayopython reticulatus", tier=1, alt=("python",),
        clue="the longest snake there is; it constricts and swallows whole"),
      T("Boa constrictor", "Boa constrictor", tier=1, alt=("boa",),
        clue="gives birth to live young rather than laying"),
      T("King cobra", "Ophiophagus hannah", tier=1, alt=("cobra",),
        clue="eats other snakes, and is the only one that builds a nest"),
      T("Rattlesnake", "Crotalus atrox", tier=1,
        clue="adds a segment to the rattle at every moult, and senses your heat"),
      T("Black mamba", "Dendroaspis polylepis", tier=2,
        clue="the mouth inside is black; it can outrun a person over short ground"),
      T("Green anaconda", "Eunectes murinus", tier=1, alt=("anaconda",),
        clue="the heaviest snake, waiting half-submerged in the Llanos"),
      rank="suborder"),
    rank="order",
    gloss="scaly skin shed in one piece, and a jaw that can come apart")

BIRDS = C(
    "Birds", "Aves", 100,
    C("Ratites and tinamous", "Palaeognathae", 90,
      T("Ostrich", "Struthio camelus", tier=1,
        clue="two toes, an eye bigger than its brain, and a kick that kills"),
      T("Emu", "Dromaius novaehollandiae", tier=1,
        clue="Australia lost a war against these in 1932"),
      T("Kiwi", "Apteryx mantelli", tier=1,
        clue="nostrils at the tip of the bill, and an egg a quarter of its own weight"),
      T("Cassowary", "Casuarius casuarius", tier=2,
        clue="a bony helmet, a blue neck and a dagger on the inner toe"),
      T("Rhea", "Rhea americana", tier=3,
        clue="the pampas answer to the ostrich; the male raises the chicks"),
      gloss="flightless heavyweights, plus the tinamous that can still fly"),
    C("Neognaths", "Neognathae", 95,
      C("Fowl and waterfowl", "Galloanserae", 85,
        C("Landfowl", "Galliformes", 45,
          T("Chicken", "Gallus gallus", tier=1, alt=("junglefowl", "hen"),
            clue="descended from a shy jungle bird; now outnumbers us three to one"),
          T("Turkey", "Meleagris gallopavo", tier=1,
            clue="domesticated in Mexico, shipped to Europe, and misnamed for a country"),
          T("Peafowl", "Pavo cristatus", tier=1, alt=("peacock",),
            clue="the tail is the reason Darwin said the sight of a feather made him sick"),
          rank="order"),
        C("Waterfowl", "Anseriformes", 40,
          T("Mallard", "Anas platyrhynchos", tier=1, alt=("duck",),
            clue="every farmyard duck but the muscovy is this bird"),
          T("Greylag goose", "Anser anser", tier=1, alt=("goose",),
            clue="Lorenz's goslings followed him because he was the first thing they saw"),
          T("Mute swan", "Cygnus olor", tier=1, alt=("swan",),
            clue="in England the unmarked ones belong to the Crown"),
          rank="order")),
      C("Neoaves", "Neoaves", 68,
        C("Pigeons and allies", "Columbimorphae", 60,
          C("Pigeons", "Columbidae", 30,
            T("Rock pigeon", "Columba livia", tier=1, alt=("pigeon", "dove"),
              clue="navigates by magnetism and smell; feeds its young on milk"),
            T("Dodo", "Raphus cucullatus", tier=3, ext=1,
              clue="a giant ground pigeon that had never met anything that ate it"),
            rank="family")),
        C("Flamingos and grebes", "Mirandornithes", 50,
          T("Greater flamingo", "Phoenicopterus roseus", tier=1, alt=("flamingo",),
            clue="filters brine upside down, and is pink because of what it eats"),
          T("Great crested grebe", "Podiceps cristatus", tier=3, alt=("grebe",),
            clue="dances breast to breast with a beakful of weed"),
          gloss="two birds that look nothing alike and are each other's closest kin"),
        C("Swifts and hummingbirds", "Strisores", 62,
          T("Hummingbird", "Archilochus colubris", tier=1,
            clue="the only bird that can hover and fly backwards; heart at 1,200 a minute"),
          T("Common swift", "Apus apus", tier=2, alt=("swift",),
            clue="stays airborne for ten months at a stretch, and sleeps up there"),
          T("Nightjar", "Caprimulgus europaeus", tier=3,
            clue="churrs at dusk from a branch it is invisible against")),
        C("Cranes and rails", "Gruiformes", 55,
          T("Common crane", "Grus grus", tier=2, alt=("crane",),
            clue="dances, mates for life, and migrates in a bugling V")),
        C("Shorebirds", "Charadriiformes", 60,
          T("Herring gull", "Larus argentatus", tier=1, alt=("gull", "seagull"),
            clue="chicks peck the red spot on the parent's bill to be fed"),
          T("Atlantic puffin", "Fratercula arctica", tier=1, alt=("puffin",),
            clue="the bill is a summer costume; it carries a dozen fish crosswise"),
          rank="order"),
        C("Waterbirds", "Aequornithes", 62,
          T("Emperor penguin", "Aptenodytes forsteri", tier=1, alt=("penguin",),
            clue="the male holds the egg on his feet through an Antarctic winter"),
          T("Wandering albatross", "Diomedea exulans", tier=1, alt=("albatross",),
            clue="a three-and-a-half metre span, and it can sleep on the wing"),
          T("Grey heron", "Ardea cinerea", tier=2, alt=("heron",),
            clue="stands still in the shallows for as long as it takes"),
          T("White stork", "Ciconia ciconia", tier=2, alt=("stork",),
            clue="nests on chimneys, and one arrived in Germany with a Central African spear in it"),
          T("Great cormorant", "Phalacrocorax carbo", tier=2, alt=("cormorant",),
            clue="its feathers wet through on purpose, so it must hang them out to dry")),
        C("Raptors", "Accipitriformes", 55,
          T("Golden eagle", "Aquila chrysaetos", tier=1, alt=("eagle",),
            clue="can see a hare two miles off, and stoops at 150 miles an hour"),
          T("Griffon vulture", "Gyps fulvus", tier=2, alt=("vulture",),
            clue="soars all day without a wingbeat, and its stomach acid dissolves bone")),
        C("Owls", "Strigiformes", 55,
          T("Barn owl", "Tyto alba", tier=1, alt=("owl",),
            clue="hunts by ear alone; the wing edge is fringed to kill the sound"),
          T("Snowy owl", "Bubo scandiacus", tier=2,
            clue="hunts in daylight on the tundra, and follows the lemmings"),
          rank="order"),
        C("Kingfishers and woodpeckers", "Coraciimorphae", 60,
          T("Kingfisher", "Alcedo atthis", tier=1,
            clue="the blue is not pigment; the bill shape gave Japan a quieter train"),
          T("Hornbill", "Bucorvus leadbeateri", tier=2,
            clue="the female seals herself into the nest hole and is fed through a slit"),
          T("Toucan", "Ramphastos toco", tier=1,
            clue="the huge bill is nearly weightless, and radiates heat"),
          T("Woodpecker", "Dendrocopos major", tier=1,
            clue="a tongue that wraps around the skull, and a beak that never concusses")),
        C("Australaves", "Australaves", 62,
          T("Peregrine falcon", "Falco peregrinus", tier=1, alt=("falcon",),
            clue="the fastest animal alive, and its nostrils have baffles for the dive"),
          C("Parrots", "Psittaciformes", 45,
            T("African grey parrot", "Psittacus erithacus", tier=1, alt=("parrot",),
              clue="one of them learned to ask a question about itself"),
            T("Macaw", "Ara macao", tier=1,
              clue="eats clay at the riverbank to neutralise the poison in its diet"),
            T("Budgerigar", "Melopsittacus undulatus", tier=2, alt=("budgie", "parakeet"),
              clue="nomadic across the Australian interior, following the rain"),
            rank="order"),
          C("Passerines", "Passeriformes", 50,
            T("Superb lyrebird", "Menura novaehollandiae", tier=2, alt=("lyrebird",),
              clue="mimics chainsaws, camera shutters and other birds, perfectly"),
            C("Songbirds", "Passeri", 44,
              C("Crows and allies", "Corvoidea", 30,
                T("Carrion crow", "Corvus corone", tier=1, alt=("crow", "raven"),
                  clue="makes tools, holds grudges, and knows your face"),
                T("Magpie", "Pica pica", tier=1,
                  clue="one of the few animals that passes the mirror test"),
                T("Bird-of-paradise", "Paradisaea raggiana", tier=2,
                  clue="clears a stage on the forest floor and displays upside down")),
              C("Passeridans", "Passerida", 32,
                C("Warblers, tits and swallows", "Sylvioidea and Paridae", 25,
                  T("Blue tit", "Cyanistes caeruleus", tier=2,
                    clue="learned to open milk bottles, and taught the rest of Britain"),
                  T("Barn swallow", "Hirundo rustica", tier=1, alt=("swallow",),
                    clue="winters in South Africa and comes back to the same beam")),
                C("Thrushes and starlings", "Muscicapoidea", 25,
                  T("European robin", "Erithacus rubecula", tier=1, alt=("robin",),
                    clue="fiercely territorial, and it may see the magnetic field"),
                  T("Nightingale", "Luscinia megarhynchos", tier=2,
                    clue="a drab bird with a thousand-song repertoire, singing after dark"),
                  T("Common starling", "Sturnus vulgaris", tier=1, alt=("starling",),
                    clue="a hundred thousand of them turn together in a murmuration")),
                C("Finches and sparrows", "Passeroidea", 25,
                  T("House sparrow", "Passer domesticus", tier=1, alt=("sparrow",),
                    clue="followed farming out of the Middle East to every city on earth"),
                  T("Canary", "Serinus canaria", tier=2,
                    clue="taken down mines because it faints before you do"),
                  T("Zebra finch", "Taeniopygia guttata", tier=2,
                    clue="the songbird that taught neuroscience how learning a song works"),
                  T("Darwin's finch", "Geospiza fortis", tier=2, alt=("darwins finch", "ground finch"),
                    clue="beak depth measurably changes on Daphne Major after a drought"))),
              gloss="a voice box with muscles on both sides — the birds that sing"),
            rank="order",
            gloss="perching birds: three toes forward, one back, and 60% of all bird species")),
        gloss="every bird that is not a fowl, a duck or an ostrich"))),
    rank="class",
    gloss="feathered dinosaurs with a wishbone, air sacs and no teeth")

REPTILES = C(
    "Reptiles", "Sauropsida", 280,
    C("Lepidosaurs", "Lepidosauria", 250,
      T("Tuatara", "Sphenodon punctatus", tier=2,
        clue="the last of an order that is not a lizard; a third eye under the scalp"),
      SQUAMATES),
    C("Turtles and archosaurs", "Archelosauria", 260,
      C("Turtles", "Testudines", 210,
        T("Green sea turtle", "Chelonia mydas", tier=1, alt=("sea turtle", "turtle"),
          clue="returns across an ocean to the beach it hatched on"),
        T("Giant tortoise", "Chelonoidis niger", tier=1, alt=("tortoise",),
          clue="each island had its own shell shape, and Darwin nearly missed it"),
        T("Snapping turtle", "Chelydra serpentina", tier=2,
          clue="too big for its own shell, so it bites instead of hiding"),
        rank="order",
        gloss="a ribcage turned inside out and fused into a box"),
      C("Archosaurs", "Archosauria", 250,
        C("Crocodilians", "Crocodylia", 95,
          T("American alligator", "Alligator mississippiensis", tier=1, alt=("alligator",),
            clue="a broad snout that hides its teeth; it bellows and the water dances"),
          C("Crocodiles and gharials", "Longirostres", 60,
            T("Saltwater crocodile", "Crocodylus porosus", tier=1, alt=("crocodile", "croc"),
              clue="the largest living reptile, and it swims between islands"),
            T("Gharial", "Gavialis gangeticus", tier=2,
              clue="a snout like a pair of tongs, for nothing but fish")),
          rank="order"),
        C("Dinosaurs", "Dinosauria", 235,
          C("Bird-hipped dinosaurs", "Ornithischia", 210,
            T("Triceratops", "Triceratops horridus", tier=3, ext=1,
              clue="three horns and a frill, on the last day of the Cretaceous"),
            T("Stegosaurus", "Stegosaurus stenops", tier=3, ext=1,
              clue="plates along the back that were probably for display and heat")),
          C("Lizard-hipped dinosaurs", "Saurischia", 230,
            T("Diplodocus", "Diplodocus carnegii", tier=3, ext=1,
              clue="twenty-seven metres of neck, tail and hollow bone"),
            C("Theropods", "Theropoda", 220,
              T("Tyrannosaurus rex", "Tyrannosaurus rex", tier=3, ext=1, alt=("t rex", "trex", "t-rex"),
                clue="the bite could crush a car; the arms could not reach its own mouth"),
              C("Maniraptorans", "Maniraptora", 165,
                T("Velociraptor", "Velociraptor mongoliensis", tier=3, ext=1, alt=("raptor",),
                  clue="turkey-sized and feathered; the films took liberties"),
                C("Avialans", "Avialae", 160,
                  T("Archaeopteryx", "Archaeopteryx lithographica", tier=3, ext=1,
                    clue="feathers, wings, and also teeth and a bony tail"),
                  BIRDS)))),
          gloss="the only branch to survive the asteroid is the one with feathers"))),
    gloss="scales, a waterproof egg, and the two branches that own the land and the sky")
