# -*- coding: utf-8 -*-
"""
PHYLO — the candidate seed list.

Each row is  (common_name, scientific_name, prior, aliases)
  common_name  what the player types and reads. Must be a name a well-read
               non-biologist would actually produce unprompted.
  scientific_name  sent to the GBIF backbone matcher, which resolves synonyms
               and returns the authoritative kingdom→species lineage. If a name
               here is wrong or outdated, GBIF either corrects it or rejects it;
               gen_phylo.py logs every rejection rather than guessing.
  prior        1..5, my own guess at how nameable it is. Only a tie-breaker —
               the real salience number is English Wikipedia pageviews, fetched
               per organism by the harvester.
  aliases      extra strings the type-ahead should accept.

Nothing in this file is trusted as taxonomy. It is a list of *candidates*;
every lineage that ships comes from GBIF.
"""

SEED = []


def g(rows):
    SEED.extend(rows)


# ── MAMMALS ────────────────────────────────────────────────────────────────
g([
    ("Human", "Homo sapiens", 5, ["person", "people", "man"]),
    ("Chimpanzee", "Pan troglodytes", 5, ["chimp"]),
    ("Bonobo", "Pan paniscus", 4, ["pygmy chimpanzee"]),
    ("Western Gorilla", "Gorilla gorilla", 5, ["gorilla"]),
    ("Orangutan", "Pongo pygmaeus", 5, ["bornean orangutan"]),
    ("Gibbon", "Hylobates lar", 4, ["lar gibbon", "white-handed gibbon"]),
    ("Baboon", "Papio anubis", 4, ["olive baboon"]),
    ("Mandrill", "Mandrillus sphinx", 4, []),
    ("Rhesus Macaque", "Macaca mulatta", 4, ["macaque", "rhesus monkey"]),
    ("Japanese Macaque", "Macaca fuscata", 3, ["snow monkey"]),
    ("Capuchin Monkey", "Cebus capucinus", 4, ["capuchin"]),
    ("Howler Monkey", "Alouatta palliata", 3, []),
    ("Spider Monkey", "Ateles geoffroyi", 3, []),
    ("Marmoset", "Callithrix jacchus", 3, ["common marmoset"]),
    ("Proboscis Monkey", "Nasalis larvatus", 3, []),
    ("Ring-tailed Lemur", "Lemur catta", 4, ["lemur"]),
    ("Aye-aye", "Daubentonia madagascariensis", 3, []),
    ("Slow Loris", "Nycticebus coucang", 3, ["loris"]),
    ("Tarsier", "Tarsius tarsier", 3, []),

    ("Lion", "Panthera leo", 5, []),
    ("Tiger", "Panthera tigris", 5, []),
    ("Leopard", "Panthera pardus", 5, []),
    ("Jaguar", "Panthera onca", 5, []),
    ("Snow Leopard", "Panthera uncia", 4, []),
    ("Cheetah", "Acinonyx jubatus", 5, []),
    ("Cougar", "Puma concolor", 5, ["mountain lion", "puma"]),
    ("Lynx", "Lynx lynx", 4, ["eurasian lynx"]),
    ("Bobcat", "Lynx rufus", 4, []),
    ("Caracal", "Caracal caracal", 3, []),
    ("Ocelot", "Leopardus pardalis", 3, []),
    ("Serval", "Leptailurus serval", 3, []),
    ("Domestic Cat", "Felis catus", 5, ["cat", "house cat", "kitty"]),
    ("Wildcat", "Felis silvestris", 3, ["european wildcat"]),

    ("Grey Wolf", "Canis lupus", 5, ["wolf"]),
    ("Domestic Dog", "Canis familiaris", 5, ["dog", "puppy"]),
    ("Coyote", "Canis latrans", 4, []),
    ("Dingo", "Canis dingo", 3, []),
    ("Red Fox", "Vulpes vulpes", 5, ["fox"]),
    ("Arctic Fox", "Vulpes lagopus", 4, []),
    ("Fennec Fox", "Vulpes zerda", 3, []),
    ("African Wild Dog", "Lycaon pictus", 3, ["painted dog"]),
    ("Jackal", "Canis aureus", 3, ["golden jackal"]),
    ("Raccoon Dog", "Nyctereutes procyonoides", 2, ["tanuki"]),

    ("Brown Bear", "Ursus arctos", 5, ["grizzly bear", "grizzly"]),
    ("Polar Bear", "Ursus maritimus", 5, []),
    ("American Black Bear", "Ursus americanus", 4, ["black bear"]),
    ("Giant Panda", "Ailuropoda melanoleuca", 5, ["panda"]),
    ("Sloth Bear", "Melursus ursinus", 3, []),
    ("Spectacled Bear", "Tremarctos ornatus", 3, []),
    ("Red Panda", "Ailurus fulgens", 4, []),
    ("Raccoon", "Procyon lotor", 5, []),
    ("Coati", "Nasua nasua", 2, []),
    ("Meerkat", "Suricata suricatta", 4, []),
    ("Mongoose", "Herpestes edwardsii", 3, ["indian grey mongoose"]),
    ("Spotted Hyena", "Crocuta crocuta", 4, ["hyena"]),
    ("Badger", "Meles meles", 4, ["european badger"]),
    ("Honey Badger", "Mellivora capensis", 4, ["ratel"]),
    ("Wolverine", "Gulo gulo", 4, []),
    ("Otter", "Lutra lutra", 4, ["european otter"]),
    ("Sea Otter", "Enhydra lutris", 4, []),
    ("Stoat", "Mustela erminea", 3, ["ermine", "short-tailed weasel"]),
    ("Ferret", "Mustela furo", 4, []),
    ("Mink", "Neovison vison", 3, ["american mink"]),
    ("Pine Marten", "Martes martes", 3, ["marten"]),
    ("Skunk", "Mephitis mephitis", 4, ["striped skunk"]),

    ("Walrus", "Odobenus rosmarus", 4, []),
    ("Harbour Seal", "Phoca vitulina", 4, ["common seal", "harbor seal"]),
    ("Grey Seal", "Halichoerus grypus", 3, []),
    ("Leopard Seal", "Hydrurga leptonyx", 3, []),
    ("Elephant Seal", "Mirounga leonina", 3, ["southern elephant seal"]),
    ("California Sea Lion", "Zalophus californianus", 4, ["sea lion"]),

    ("Blue Whale", "Balaenoptera musculus", 5, []),
    ("Humpback Whale", "Megaptera novaeangliae", 5, []),
    ("Fin Whale", "Balaenoptera physalus", 3, []),
    ("Grey Whale", "Eschrichtius robustus", 3, []),
    ("Bowhead Whale", "Balaena mysticetus", 3, []),
    ("Sperm Whale", "Physeter macrocephalus", 5, []),
    ("Orca", "Orcinus orca", 5, ["killer whale"]),
    ("Bottlenose Dolphin", "Tursiops truncatus", 5, ["dolphin"]),
    ("Narwhal", "Monodon monoceros", 4, []),
    ("Beluga Whale", "Delphinapterus leucas", 4, ["beluga"]),
    ("Harbour Porpoise", "Phocoena phocoena", 3, ["porpoise"]),
    ("Amazon River Dolphin", "Inia geoffrensis", 3, ["pink river dolphin", "boto"]),

    ("African Bush Elephant", "Loxodonta africana", 5, ["african elephant", "elephant"]),
    ("Asian Elephant", "Elephas maximus", 5, []),
    ("Dugong", "Dugong dugon", 3, []),
    ("Manatee", "Trichechus manatus", 4, ["west indian manatee", "sea cow"]),
    ("Aardvark", "Orycteropus afer", 4, []),
    ("Rock Hyrax", "Procavia capensis", 2, ["hyrax", "dassie"]),

    ("Horse", "Equus caballus", 5, []),
    ("Donkey", "Equus asinus", 5, ["ass"]),
    ("Plains Zebra", "Equus quagga", 5, ["zebra"]),
    ("Przewalski's Horse", "Equus przewalskii", 2, []),
    ("White Rhinoceros", "Ceratotherium simum", 5, ["rhino", "rhinoceros"]),
    ("Black Rhinoceros", "Diceros bicornis", 4, []),
    ("Indian Rhinoceros", "Rhinoceros unicornis", 3, ["greater one-horned rhino"]),
    ("Malayan Tapir", "Tapirus indicus", 3, ["tapir"]),

    ("Domestic Pig", "Sus scrofa", 5, ["pig", "wild boar", "boar", "hog"]),
    ("Warthog", "Phacochoerus africanus", 4, []),
    ("Hippopotamus", "Hippopotamus amphibius", 5, ["hippo"]),
    ("Dromedary Camel", "Camelus dromedarius", 5, ["camel"]),
    ("Bactrian Camel", "Camelus bactrianus", 4, []),
    ("Llama", "Lama glama", 4, []),
    ("Alpaca", "Vicugna pacos", 4, []),
    ("Guanaco", "Lama guanicoe", 2, []),
    ("Giraffe", "Giraffa camelopardalis", 5, []),
    ("Okapi", "Okapia johnstoni", 3, []),
    ("Cattle", "Bos taurus", 5, ["cow", "bull", "ox"]),
    ("Zebu", "Bos indicus", 2, []),
    ("Yak", "Bos mutus", 4, []),
    ("American Bison", "Bison bison", 5, ["bison", "buffalo"]),
    ("European Bison", "Bison bonasus", 3, ["wisent"]),
    ("Water Buffalo", "Bubalus bubalis", 4, []),
    ("African Buffalo", "Syncerus caffer", 3, ["cape buffalo"]),
    ("Domestic Sheep", "Ovis aries", 5, ["sheep", "lamb", "ram"]),
    ("Bighorn Sheep", "Ovis canadensis", 3, []),
    ("Domestic Goat", "Capra hircus", 5, ["goat"]),
    ("Ibex", "Capra ibex", 3, ["alpine ibex"]),
    ("Musk Ox", "Ovibos moschatus", 3, ["muskox"]),
    ("Chamois", "Rupicapra rupicapra", 2, []),
    ("Impala", "Aepyceros melampus", 3, []),
    ("Springbok", "Antidorcas marsupialis", 3, []),
    ("Gazelle", "Eudorcas thomsonii", 4, ["thomson's gazelle"]),
    ("Wildebeest", "Connochaetes taurinus", 4, ["gnu", "blue wildebeest"]),
    ("Eland", "Taurotragus oryx", 2, ["common eland"]),
    ("Greater Kudu", "Tragelaphus strepsiceros", 3, ["kudu"]),
    ("Gemsbok", "Oryx gazella", 2, ["oryx"]),
    ("Saiga Antelope", "Saiga tatarica", 2, ["saiga"]),
    ("Pronghorn", "Antilocapra americana", 3, []),
    ("Red Deer", "Cervus elaphus", 4, ["deer", "stag"]),
    ("Elk", "Cervus canadensis", 4, ["wapiti"]),
    ("Moose", "Alces alces", 5, ["elk (european)"]),
    ("Reindeer", "Rangifer tarandus", 5, ["caribou"]),
    ("White-tailed Deer", "Odocoileus virginianus", 4, []),
    ("Roe Deer", "Capreolus capreolus", 3, []),
    ("Fallow Deer", "Dama dama", 3, []),
    ("Muntjac", "Muntiacus reevesi", 2, ["barking deer"]),

    ("Brown Rat", "Rattus norvegicus", 5, ["rat", "lab rat"]),
    ("Black Rat", "Rattus rattus", 4, []),
    ("House Mouse", "Mus musculus", 5, ["mouse", "lab mouse"]),
    ("Grey Squirrel", "Sciurus carolinensis", 5, ["squirrel", "gray squirrel"]),
    ("Red Squirrel", "Sciurus vulgaris", 4, []),
    ("Chipmunk", "Tamias striatus", 4, ["eastern chipmunk"]),
    ("Prairie Dog", "Cynomys ludovicianus", 4, ["black-tailed prairie dog"]),
    ("Marmot", "Marmota marmota", 3, ["alpine marmot"]),
    ("Groundhog", "Marmota monax", 4, ["woodchuck"]),
    ("Flying Squirrel", "Glaucomys volans", 3, ["southern flying squirrel"]),
    ("North American Beaver", "Castor canadensis", 5, ["beaver"]),
    ("Capybara", "Hydrochoerus hydrochaeris", 5, []),
    ("Guinea Pig", "Cavia porcellus", 5, ["cavy"]),
    ("Chinchilla", "Chinchilla lanigera", 4, []),
    ("Porcupine", "Hystrix cristata", 4, ["crested porcupine"]),
    ("North American Porcupine", "Erethizon dorsatum", 3, []),
    ("Naked Mole-rat", "Heterocephalus glaber", 3, []),
    ("Hamster", "Mesocricetus auratus", 4, ["golden hamster", "syrian hamster"]),
    ("Gerbil", "Meriones unguiculatus", 3, ["mongolian gerbil"]),
    ("Lemming", "Lemmus lemmus", 3, ["norway lemming"]),
    ("Muskrat", "Ondatra zibethicus", 3, []),
    ("Vole", "Microtus agrestis", 2, ["field vole"]),
    ("Dormouse", "Muscardinus avellanarius", 2, ["hazel dormouse"]),
    ("European Rabbit", "Oryctolagus cuniculus", 5, ["rabbit", "bunny"]),
    ("Brown Hare", "Lepus europaeus", 4, ["hare"]),
    ("Arctic Hare", "Lepus arcticus", 3, []),
    ("Pika", "Ochotona princeps", 2, ["american pika"]),

    ("Common Vampire Bat", "Desmodus rotundus", 4, ["vampire bat"]),
    ("Little Brown Bat", "Myotis lucifugus", 3, ["bat"]),
    ("Greater Horseshoe Bat", "Rhinolophus ferrumequinum", 2, ["horseshoe bat"]),
    ("Flying Fox", "Pteropus vampyrus", 4, ["fruit bat", "large flying fox"]),
    ("European Hedgehog", "Erinaceus europaeus", 4, ["hedgehog"]),
    ("European Mole", "Talpa europaea", 3, ["mole"]),
    ("Star-nosed Mole", "Condylura cristata", 3, []),
    ("Common Shrew", "Sorex araneus", 3, ["shrew"]),
    ("Nine-banded Armadillo", "Dasypus novemcinctus", 4, ["armadillo"]),
    ("Giant Anteater", "Myrmecophaga tridactyla", 4, ["anteater"]),
    ("Three-toed Sloth", "Bradypus variegatus", 5, ["sloth"]),
    ("Two-toed Sloth", "Choloepus didactylus", 3, []),
    ("Pangolin", "Manis pentadactyla", 4, ["chinese pangolin", "scaly anteater"]),

    ("Red Kangaroo", "Osphranter rufus", 5, ["kangaroo"]),
    ("Eastern Grey Kangaroo", "Macropus giganteus", 3, []),
    ("Wallaby", "Notamacropus rufogriseus", 4, ["red-necked wallaby"]),
    ("Koala", "Phascolarctos cinereus", 5, []),
    ("Common Wombat", "Vombatus ursinus", 4, ["wombat"]),
    ("Tasmanian Devil", "Sarcophilus harrisii", 4, []),
    ("Quokka", "Setonix brachyurus", 4, []),
    ("Sugar Glider", "Petaurus breviceps", 3, []),
    ("Virginia Opossum", "Didelphis virginiana", 4, ["opossum", "possum"]),
    ("Bilby", "Macrotis lagotis", 2, []),
    ("Platypus", "Ornithorhynchus anatinus", 5, ["duck-billed platypus"]),
    ("Short-beaked Echidna", "Tachyglossus aculeatus", 4, ["echidna", "spiny anteater"]),
])

# ── BIRDS ──────────────────────────────────────────────────────────────────
g([
    ("Chicken", "Gallus gallus", 5, ["hen", "rooster", "red junglefowl"]),
    ("Turkey", "Meleagris gallopavo", 5, ["wild turkey"]),
    ("Indian Peafowl", "Pavo cristatus", 5, ["peacock", "peahen"]),
    ("Common Pheasant", "Phasianus colchicus", 4, ["pheasant"]),
    ("Common Quail", "Coturnix coturnix", 3, ["quail"]),
    ("Grey Partridge", "Perdix perdix", 2, ["partridge"]),
    ("Mallard", "Anas platyrhynchos", 5, ["duck", "wild duck"]),
    ("Mute Swan", "Cygnus olor", 5, ["swan"]),
    ("Canada Goose", "Branta canadensis", 5, ["goose"]),
    ("Greylag Goose", "Anser anser", 3, []),
    ("Common Eider", "Somateria mollissima", 2, ["eider"]),
    ("Ostrich", "Struthio camelus", 5, ["common ostrich"]),
    ("Emu", "Dromaius novaehollandiae", 5, []),
    ("Southern Cassowary", "Casuarius casuarius", 4, ["cassowary"]),
    ("Kiwi", "Apteryx australis", 4, ["southern brown kiwi"]),
    ("Greater Rhea", "Rhea americana", 3, ["rhea"]),
    ("Emperor Penguin", "Aptenodytes forsteri", 5, ["penguin"]),
    ("King Penguin", "Aptenodytes patagonicus", 4, []),
    ("Adelie Penguin", "Pygoscelis adeliae", 3, []),
    ("Little Penguin", "Eudyptula minor", 3, ["fairy penguin"]),
    ("Galapagos Penguin", "Spheniscus mendiculus", 2, []),

    ("Bald Eagle", "Haliaeetus leucocephalus", 5, ["eagle"]),
    ("Golden Eagle", "Aquila chrysaetos", 4, []),
    ("Harpy Eagle", "Harpia harpyja", 3, []),
    ("Peregrine Falcon", "Falco peregrinus", 5, ["falcon", "peregrine"]),
    ("Common Kestrel", "Falco tinnunculus", 3, ["kestrel"]),
    ("Osprey", "Pandion haliaetus", 4, []),
    ("Red Kite", "Milvus milvus", 3, ["kite"]),
    ("Common Buzzard", "Buteo buteo", 3, ["buzzard"]),
    ("Red-tailed Hawk", "Buteo jamaicensis", 4, ["hawk"]),
    ("Northern Goshawk", "Accipiter gentilis", 3, ["goshawk"]),
    ("Andean Condor", "Vultur gryphus", 4, ["condor"]),
    ("California Condor", "Gymnogyps californianus", 3, []),
    ("Turkey Vulture", "Cathartes aura", 3, ["vulture"]),
    ("Griffon Vulture", "Gyps fulvus", 3, []),
    ("Secretarybird", "Sagittarius serpentarius", 3, []),
    ("Barn Owl", "Tyto alba", 5, ["owl"]),
    ("Snowy Owl", "Bubo scandiacus", 5, []),
    ("Eurasian Eagle-owl", "Bubo bubo", 3, ["eagle owl"]),
    ("Tawny Owl", "Strix aluco", 3, []),
    ("Great Horned Owl", "Bubo virginianus", 4, []),
    ("Burrowing Owl", "Athene cunicularia", 3, []),

    ("Rock Dove", "Columba livia", 5, ["pigeon", "rock pigeon"]),
    ("Wood Pigeon", "Columba palumbus", 3, []),
    ("Mourning Dove", "Zenaida macroura", 3, ["dove"]),
    ("Dodo", "Raphus cucullatus", 5, []),
    ("Budgerigar", "Melopsittacus undulatus", 4, ["budgie", "parakeet"]),
    ("African Grey Parrot", "Psittacus erithacus", 4, ["african gray parrot"]),
    ("Scarlet Macaw", "Ara macao", 4, ["macaw", "parrot"]),
    ("Blue-and-yellow Macaw", "Ara ararauna", 3, []),
    ("Cockatiel", "Nymphicus hollandicus", 4, []),
    ("Sulphur-crested Cockatoo", "Cacatua galerita", 4, ["cockatoo"]),
    ("Kea", "Nestor notabilis", 3, []),
    ("Kakapo", "Strigops habroptilus", 3, []),
    ("Lovebird", "Agapornis roseicollis", 2, ["rosy-faced lovebird"]),

    ("American Robin", "Turdus migratorius", 4, []),
    ("European Robin", "Erithacus rubecula", 4, ["robin"]),
    ("Common Blackbird", "Turdus merula", 4, ["blackbird"]),
    ("Song Thrush", "Turdus philomelos", 3, ["thrush"]),
    ("House Sparrow", "Passer domesticus", 5, ["sparrow"]),
    ("Common Starling", "Sturnus vulgaris", 4, ["starling"]),
    ("Barn Swallow", "Hirundo rustica", 4, ["swallow"]),
    ("Common Swift", "Apus apus", 3, ["swift"]),
    ("Blue Tit", "Cyanistes caeruleus", 3, []),
    ("Great Tit", "Parus major", 3, []),
    ("Northern Cardinal", "Cardinalis cardinalis", 4, ["cardinal"]),
    ("Blue Jay", "Cyanocitta cristata", 4, ["jay"]),
    ("Common Raven", "Corvus corax", 5, ["raven"]),
    ("Carrion Crow", "Corvus corone", 4, ["crow"]),
    ("American Crow", "Corvus brachyrhynchos", 4, []),
    ("Eurasian Magpie", "Pica pica", 4, ["magpie"]),
    ("Eurasian Jackdaw", "Corvus monedula", 3, ["jackdaw"]),
    ("Goldfinch", "Carduelis carduelis", 3, ["european goldfinch"]),
    ("Common Chaffinch", "Fringilla coelebs", 3, ["chaffinch"]),
    ("Canary", "Serinus canaria", 4, ["atlantic canary"]),
    ("Zebra Finch", "Taeniopygia guttata", 3, []),
    ("Darwin's Finch", "Geospiza fortis", 3, ["medium ground finch"]),
    ("Bird-of-paradise", "Paradisaea apoda", 3, ["greater bird-of-paradise"]),
    ("Lyrebird", "Menura novaehollandiae", 3, ["superb lyrebird"]),
    ("Northern Mockingbird", "Mimus polyglottos", 3, ["mockingbird"]),
    ("Common Nightingale", "Luscinia megarhynchos", 4, ["nightingale"]),
    ("Common Cuckoo", "Cuculus canorus", 4, ["cuckoo"]),
    ("Greater Roadrunner", "Geococcyx californianus", 4, ["roadrunner"]),
    ("Ruby-throated Hummingbird", "Archilochus colubris", 4, ["hummingbird"]),
    ("Bee Hummingbird", "Mellisuga helenae", 3, []),
    ("Belted Kingfisher", "Megaceryle alcyon", 2, []),
    ("Common Kingfisher", "Alcedo atthis", 4, ["kingfisher"]),
    ("Toco Toucan", "Ramphastos toco", 4, ["toucan"]),
    ("Great Hornbill", "Buceros bicornis", 3, ["hornbill"]),
    ("Hoopoe", "Upupa epops", 3, []),
    ("Great Spotted Woodpecker", "Dendrocopos major", 3, ["woodpecker"]),
    ("Pileated Woodpecker", "Dryocopus pileatus", 3, []),
    ("Woodpecker Finch", "Camarhynchus pallidus", 1, []),

    ("Greater Flamingo", "Phoenicopterus roseus", 5, ["flamingo"]),
    ("Grey Heron", "Ardea cinerea", 3, ["heron"]),
    ("Great Blue Heron", "Ardea herodias", 3, []),
    ("Great Egret", "Ardea alba", 3, ["egret"]),
    ("White Stork", "Ciconia ciconia", 4, ["stork"]),
    ("Marabou Stork", "Leptoptilos crumenifer", 2, []),
    ("Shoebill", "Balaeniceps rex", 4, []),
    ("Roseate Spoonbill", "Platalea ajaja", 3, ["spoonbill"]),
    ("Sacred Ibis", "Threskiornis aethiopicus", 3, ["ibis"]),
    ("Common Crane", "Grus grus", 3, ["crane"]),
    ("Sandhill Crane", "Antigone canadensis", 3, []),
    ("Great Cormorant", "Phalacrocorax carbo", 3, ["cormorant"]),
    ("Brown Pelican", "Pelecanus occidentalis", 4, ["pelican"]),
    ("Northern Gannet", "Morus bassanus", 3, ["gannet"]),
    ("Atlantic Puffin", "Fratercula arctica", 5, ["puffin"]),
    ("Herring Gull", "Larus argentatus", 4, ["seagull", "gull"]),
    ("Arctic Tern", "Sterna paradisaea", 4, ["tern"]),
    ("Wandering Albatross", "Diomedea exulans", 4, ["albatross"]),
    ("Frigatebird", "Fregata magnificens", 3, ["magnificent frigatebird"]),
    ("Blue-footed Booby", "Sula nebouxii", 4, ["booby"]),
    ("Great Auk", "Pinguinus impennis", 3, []),
    ("Eurasian Oystercatcher", "Haematopus ostralegus", 2, ["oystercatcher"]),
    ("Northern Lapwing", "Vanellus vanellus", 2, ["lapwing"]),
    ("Eurasian Curlew", "Numenius arquata", 2, ["curlew"]),
    ("Common Snipe", "Gallinago gallinago", 2, ["snipe"]),
    ("Eurasian Coot", "Fulica atra", 2, ["coot"]),
    ("Great Crested Grebe", "Podiceps cristatus", 2, ["grebe"]),
    ("Common Loon", "Gavia immer", 3, ["great northern diver", "loon"]),
    ("Whooper Swan", "Cygnus cygnus", 2, []),
])

# ── REPTILES ───────────────────────────────────────────────────────────────
g([
    ("Nile Crocodile", "Crocodylus niloticus", 5, ["crocodile"]),
    ("Saltwater Crocodile", "Crocodylus porosus", 4, []),
    ("American Alligator", "Alligator mississippiensis", 5, ["alligator", "gator"]),
    ("Chinese Alligator", "Alligator sinensis", 2, []),
    ("Gharial", "Gavialis gangeticus", 3, []),
    ("Spectacled Caiman", "Caiman crocodilus", 3, ["caiman"]),

    ("King Cobra", "Ophiophagus hannah", 5, []),
    ("Indian Cobra", "Naja naja", 4, ["cobra", "spectacled cobra"]),
    ("Black Mamba", "Dendroaspis polylepis", 5, ["mamba"]),
    ("Inland Taipan", "Oxyuranus microlepidotus", 3, ["taipan"]),
    ("Eastern Diamondback Rattlesnake", "Crotalus adamanteus", 4, ["rattlesnake"]),
    ("Western Diamondback Rattlesnake", "Crotalus atrox", 4, []),
    ("Sidewinder", "Crotalus cerastes", 3, []),
    ("Copperhead", "Agkistrodon contortrix", 3, []),
    ("Adder", "Vipera berus", 3, ["common european adder"]),
    ("Gaboon Viper", "Bitis gabonica", 3, []),
    ("Bushmaster", "Lachesis muta", 2, []),
    ("Reticulated Python", "Malayopython reticulatus", 4, ["python"]),
    ("Burmese Python", "Python bivittatus", 4, []),
    ("Ball Python", "Python regius", 4, ["royal python"]),
    ("Green Anaconda", "Eunectes murinus", 5, ["anaconda"]),
    ("Boa Constrictor", "Boa constrictor", 5, ["boa"]),
    ("Corn Snake", "Pantherophis guttatus", 3, []),
    ("Grass Snake", "Natrix natrix", 3, []),
    ("Garter Snake", "Thamnophis sirtalis", 3, ["common garter snake"]),
    ("Sea Krait", "Laticauda colubrina", 2, ["banded sea krait"]),

    ("Komodo Dragon", "Varanus komodoensis", 5, []),
    ("Nile Monitor", "Varanus niloticus", 2, ["monitor lizard"]),
    ("Green Iguana", "Iguana iguana", 5, ["iguana"]),
    ("Marine Iguana", "Amblyrhynchus cristatus", 4, []),
    ("Veiled Chameleon", "Chamaeleo calyptratus", 4, ["chameleon"]),
    ("Panther Chameleon", "Furcifer pardalis", 3, []),
    ("Tokay Gecko", "Gekko gecko", 3, ["gecko"]),
    ("Leopard Gecko", "Eublepharis macularius", 4, []),
    ("Common House Gecko", "Hemidactylus frenatus", 2, []),
    ("Bearded Dragon", "Pogona vitticeps", 4, []),
    ("Frilled Lizard", "Chlamydosaurus kingii", 4, ["frilled-neck lizard"]),
    ("Gila Monster", "Heloderma suspectum", 4, []),
    ("Basilisk Lizard", "Basiliscus plumifrons", 3, ["jesus christ lizard"]),
    ("Thorny Devil", "Moloch horridus", 3, []),
    ("Slow Worm", "Anguis fragilis", 2, []),
    ("Common Wall Lizard", "Podarcis muralis", 2, ["wall lizard"]),
    ("Tuatara", "Sphenodon punctatus", 3, []),

    ("Galapagos Tortoise", "Chelonoidis niger", 5, ["giant tortoise"]),
    ("Aldabra Giant Tortoise", "Aldabrachelys gigantea", 3, []),
    ("Leopard Tortoise", "Stigmochelys pardalis", 2, ["tortoise"]),
    ("Green Sea Turtle", "Chelonia mydas", 5, ["sea turtle", "turtle"]),
    ("Loggerhead Sea Turtle", "Caretta caretta", 4, ["loggerhead"]),
    ("Leatherback Sea Turtle", "Dermochelys coriacea", 4, ["leatherback"]),
    ("Hawksbill Sea Turtle", "Eretmochelys imbricata", 3, ["hawksbill"]),
    ("Red-eared Slider", "Trachemys scripta", 3, ["pond slider"]),
    ("Common Snapping Turtle", "Chelydra serpentina", 3, ["snapping turtle"]),
    ("Alligator Snapping Turtle", "Macrochelys temminckii", 3, []),
])

# ── AMPHIBIANS ─────────────────────────────────────────────────────────────
g([
    ("Common Frog", "Rana temporaria", 4, ["frog"]),
    ("American Bullfrog", "Lithobates catesbeianus", 4, ["bullfrog"]),
    ("African Clawed Frog", "Xenopus laevis", 3, ["xenopus"]),
    ("Poison Dart Frog", "Dendrobates tinctorius", 4, ["dyeing poison dart frog"]),
    ("Golden Poison Frog", "Phyllobates terribilis", 3, []),
    ("Red-eyed Tree Frog", "Agalychnis callidryas", 4, ["tree frog"]),
    ("Goliath Frog", "Conraua goliath", 3, []),
    ("Wood Frog", "Lithobates sylvaticus", 2, []),
    ("Glass Frog", "Hyalinobatrachium valerioi", 2, []),
    ("Common Toad", "Bufo bufo", 4, ["toad"]),
    ("Cane Toad", "Rhinella marina", 4, []),
    ("American Toad", "Anaxyrus americanus", 2, []),
    ("Fire Salamander", "Salamandra salamandra", 4, ["salamander"]),
    ("Axolotl", "Ambystoma mexicanum", 5, []),
    ("Tiger Salamander", "Ambystoma tigrinum", 3, []),
    ("Chinese Giant Salamander", "Andrias davidianus", 3, ["giant salamander"]),
    ("Hellbender", "Cryptobranchus alleganiensis", 3, []),
    ("Olm", "Proteus anguinus", 3, []),
    ("Smooth Newt", "Lissotriton vulgaris", 2, ["newt"]),
    ("Eastern Newt", "Notophthalmus viridescens", 2, []),
    ("Great Crested Newt", "Triturus cristatus", 2, []),
    ("Caecilian", "Ichthyophis glutinosus", 2, []),
    ("Surinam Toad", "Pipa pipa", 2, []),
])

# ── FISH ───────────────────────────────────────────────────────────────────
g([
    ("Great White Shark", "Carcharodon carcharias", 5, ["white shark", "shark"]),
    ("Whale Shark", "Rhincodon typus", 5, []),
    ("Basking Shark", "Cetorhinus maximus", 3, []),
    ("Tiger Shark", "Galeocerdo cuvier", 4, []),
    ("Bull Shark", "Carcharhinus leucas", 4, []),
    ("Hammerhead Shark", "Sphyrna mokarran", 4, ["great hammerhead", "hammerhead"]),
    ("Nurse Shark", "Ginglymostoma cirratum", 3, []),
    ("Blue Shark", "Prionace glauca", 3, []),
    ("Greenland Shark", "Somniosus microcephalus", 4, []),
    ("Goblin Shark", "Mitsukurina owstoni", 3, []),
    ("Manta Ray", "Mobula birostris", 4, ["giant manta ray", "manta"]),
    ("Stingray", "Dasyatis pastinaca", 4, ["common stingray"]),
    ("Electric Ray", "Torpedo torpedo", 2, []),
    ("Sawfish", "Pristis pristis", 3, ["largetooth sawfish"]),
    ("Little Skate", "Leucoraja erinacea", 2, ["skate"]),
    ("Sea Lamprey", "Petromyzon marinus", 3, ["lamprey"]),
    ("Hagfish", "Myxine glutinosa", 3, ["atlantic hagfish"]),

    ("Atlantic Salmon", "Salmo salar", 5, ["salmon"]),
    ("Sockeye Salmon", "Oncorhynchus nerka", 3, []),
    ("Rainbow Trout", "Oncorhynchus mykiss", 4, ["trout"]),
    ("Brown Trout", "Salmo trutta", 3, []),
    ("Atlantic Cod", "Gadus morhua", 5, ["cod"]),
    ("Haddock", "Melanogrammus aeglefinus", 3, []),
    ("Atlantic Herring", "Clupea harengus", 4, ["herring"]),
    ("European Anchovy", "Engraulis encrasicolus", 3, ["anchovy"]),
    ("European Sardine", "Sardina pilchardus", 3, ["sardine", "pilchard"]),
    ("Atlantic Bluefin Tuna", "Thunnus thynnus", 5, ["tuna", "bluefin"]),
    ("Skipjack Tuna", "Katsuwonus pelamis", 3, []),
    ("Atlantic Mackerel", "Scomber scombrus", 3, ["mackerel"]),
    ("Swordfish", "Xiphias gladius", 4, []),
    ("Atlantic Blue Marlin", "Makaira nigricans", 3, ["marlin"]),
    ("Atlantic Halibut", "Hippoglossus hippoglossus", 3, ["halibut"]),
    ("European Plaice", "Pleuronectes platessa", 2, ["plaice"]),
    ("Common Sole", "Solea solea", 2, ["dover sole", "sole"]),
    ("European Sea Bass", "Dicentrarchus labrax", 3, ["sea bass"]),
    ("Largemouth Bass", "Micropterus salmoides", 3, ["bass"]),
    ("Common Carp", "Cyprinus carpio", 4, ["carp"]),
    ("Goldfish", "Carassius auratus", 5, []),
    ("Koi", "Cyprinus rubrofuscus", 3, []),
    ("Zebrafish", "Danio rerio", 4, []),
    ("Guppy", "Poecilia reticulata", 3, []),
    ("Betta", "Betta splendens", 4, ["siamese fighting fish"]),
    ("Nile Tilapia", "Oreochromis niloticus", 3, ["tilapia"]),
    ("Clownfish", "Amphiprion ocellaris", 5, ["clown anemonefish", "nemo"]),
    ("Blue Tang", "Paracanthurus hepatus", 4, ["regal tang", "dory"]),
    ("Moorish Idol", "Zanclus cornutus", 2, []),
    ("Parrotfish", "Scarus psittacus", 3, []),
    ("Lionfish", "Pterois volitans", 4, ["red lionfish"]),
    ("Stonefish", "Synanceia verrucosa", 3, ["reef stonefish"]),
    ("Pufferfish", "Takifugu rubripes", 4, ["fugu", "japanese pufferfish"]),
    ("Porcupinefish", "Diodon hystrix", 2, []),
    ("Seahorse", "Hippocampus hippocampus", 5, ["short-snouted seahorse"]),
    ("Leafy Seadragon", "Phycodurus eques", 3, []),
    ("Pipefish", "Syngnathus acus", 2, ["greater pipefish"]),
    ("European Eel", "Anguilla anguilla", 4, ["eel"]),
    ("Moray Eel", "Muraena helena", 4, ["mediterranean moray", "moray"]),
    ("Electric Eel", "Electrophorus electricus", 5, []),
    ("Piranha", "Pygocentrus nattereri", 5, ["red-bellied piranha"]),
    ("Wels Catfish", "Silurus glanis", 3, ["catfish"]),
    ("Channel Catfish", "Ictalurus punctatus", 2, []),
    ("Northern Pike", "Esox lucius", 3, ["pike"]),
    ("Beluga Sturgeon", "Huso huso", 3, ["sturgeon"]),
    ("Paddlefish", "Polyodon spathula", 2, []),
    ("Coelacanth", "Latimeria chalumnae", 4, []),
    ("Australian Lungfish", "Neoceratodus forsteri", 3, ["lungfish"]),
    ("Mudskipper", "Periophthalmus barbarus", 3, ["atlantic mudskipper"]),
    ("Anglerfish", "Melanocetus johnsonii", 4, ["humpback anglerfish", "black seadevil"]),
    ("Ocean Sunfish", "Mola mola", 4, ["mola mola", "sunfish"]),
    ("Barracuda", "Sphyraena barracuda", 4, ["great barracuda"]),
    ("Remora", "Echeneis naucrates", 2, ["live sharksucker"]),
    ("Flying Fish", "Exocoetus volitans", 3, []),
    ("Archerfish", "Toxotes jaculatrix", 2, ["banded archerfish"]),
    ("Oarfish", "Regalecus glesne", 3, ["giant oarfish"]),
    ("Viperfish", "Chauliodus sloani", 2, ["sloane's viperfish"]),
    ("Lanternfish", "Myctophum punctatum", 1, []),
    ("Atlantic Wolffish", "Anarhichas lupus", 2, ["wolffish"]),
    ("Icefish", "Chaenocephalus aceratus", 2, ["blackfin icefish"]),
    ("Sea Bream", "Sparus aurata", 3, ["gilt-head bream"]),
    ("Red Snapper", "Lutjanus campechanus", 3, ["northern red snapper"]),
    ("Grouper", "Epinephelus marginatus", 3, ["dusky grouper"]),
    ("Mahi-mahi", "Coryphaena hippurus", 3, ["dolphinfish"]),
    ("Atlantic Menhaden", "Brevoortia tyrannus", 1, []),
    ("Sea Horse Pipefish", "Nerophis ophidion", 1, ["straightnose pipefish"]),
])

# ── INSECTS ────────────────────────────────────────────────────────────────
g([
    ("Western Honey Bee", "Apis mellifera", 5, ["honey bee", "honeybee", "bee"]),
    ("Buff-tailed Bumblebee", "Bombus terrestris", 4, ["bumblebee"]),
    ("Common Wasp", "Vespula vulgaris", 4, ["wasp", "yellowjacket"]),
    ("European Hornet", "Vespa crabro", 4, ["hornet"]),
    ("Asian Giant Hornet", "Vespa mandarinia", 4, ["murder hornet"]),
    ("Black Garden Ant", "Lasius niger", 3, ["ant"]),
    ("Leafcutter Ant", "Atta cephalotes", 4, []),
    ("Army Ant", "Eciton burchellii", 3, []),
    ("Red Imported Fire Ant", "Solenopsis invicta", 3, ["fire ant"]),
    ("Bullet Ant", "Paraponera clavata", 3, []),
    ("Carpenter Ant", "Camponotus pennsylvanicus", 2, []),
    ("Eastern Subterranean Termite", "Reticulitermes flavipes", 3, ["termite"]),

    ("Monarch Butterfly", "Danaus plexippus", 5, ["monarch"]),
    ("Cabbage White", "Pieris rapae", 3, ["small white butterfly"]),
    ("Painted Lady", "Vanessa cardui", 3, []),
    ("Red Admiral", "Vanessa atalanta", 3, []),
    ("Peacock Butterfly", "Aglais io", 3, []),
    ("Blue Morpho", "Morpho peleides", 4, ["morpho butterfly"]),
    ("Swallowtail Butterfly", "Papilio machaon", 4, ["old world swallowtail"]),
    ("Birdwing Butterfly", "Ornithoptera priamus", 2, ["common green birdwing"]),
    ("Death's-head Hawkmoth", "Acherontia atropos", 4, []),
    ("Luna Moth", "Actias luna", 4, []),
    ("Atlas Moth", "Attacus atlas", 4, []),
    ("Silk Moth", "Bombyx mori", 4, ["silkworm"]),
    ("Peppered Moth", "Biston betularia", 4, []),
    ("Gypsy Moth", "Lymantria dispar", 2, ["spongy moth"]),
    ("Hummingbird Hawk-moth", "Macroglossum stellatarum", 3, []),

    ("Seven-spot Ladybird", "Coccinella septempunctata", 4, ["ladybug", "ladybird"]),
    ("Stag Beetle", "Lucanus cervus", 4, []),
    ("Hercules Beetle", "Dynastes hercules", 4, []),
    ("Rhinoceros Beetle", "Oryctes nasicornis", 3, []),
    ("Goliath Beetle", "Goliathus goliatus", 3, []),
    ("Scarab Beetle", "Scarabaeus sacer", 4, ["sacred scarab", "dung beetle"]),
    ("Colorado Potato Beetle", "Leptinotarsa decemlineata", 2, []),
    ("Firefly", "Photinus pyralis", 4, ["lightning bug", "common eastern firefly"]),
    ("Weevil", "Curculio nucum", 2, ["nut weevil"]),
    ("Bombardier Beetle", "Brachinus crepitans", 2, []),
    ("Whirligig Beetle", "Gyrinus natator", 1, []),
    ("Death Watch Beetle", "Xestobium rufovillosum", 1, []),
    ("Diving Beetle", "Dytiscus marginalis", 2, ["great diving beetle"]),

    ("Common House Fly", "Musca domestica", 5, ["housefly", "fly"]),
    ("Fruit Fly", "Drosophila melanogaster", 5, ["drosophila"]),
    ("Mosquito", "Culex pipiens", 5, ["common house mosquito"]),
    ("Malaria Mosquito", "Anopheles gambiae", 4, []),
    ("Yellow Fever Mosquito", "Aedes aegypti", 4, []),
    ("Tsetse Fly", "Glossina morsitans", 3, []),
    ("Horsefly", "Tabanus bovinus", 2, []),
    ("Crane Fly", "Tipula paludosa", 2, ["daddy longlegs (fly)"]),
    ("Mayfly", "Ephemera danica", 3, ["green drake"]),
    ("Common Blue Damselfly", "Enallagma cyathigerum", 2, ["damselfly"]),
    ("Emperor Dragonfly", "Anax imperator", 4, ["dragonfly"]),
    ("Green Darner", "Anax junius", 2, []),
    ("Praying Mantis", "Mantis religiosa", 5, ["european mantis", "mantis"]),
    ("Orchid Mantis", "Hymenopus coronatus", 3, []),
    ("Desert Locust", "Schistocerca gregaria", 4, ["locust"]),
    ("Migratory Locust", "Locusta migratoria", 3, []),
    ("Field Cricket", "Gryllus campestris", 3, ["cricket"]),
    ("House Cricket", "Acheta domesticus", 2, []),
    ("Mole Cricket", "Gryllotalpa gryllotalpa", 2, []),
    ("Great Green Bush-cricket", "Tettigonia viridissima", 2, ["katydid"]),
    ("Common Green Grasshopper", "Omocestus viridulus", 2, ["grasshopper"]),
    ("Periodical Cicada", "Magicicada septendecim", 4, ["cicada"]),
    ("Common Stick Insect", "Carausius morosus", 3, ["stick insect", "walking stick"]),
    ("Leaf Insect", "Phyllium siccifolium", 2, []),
    ("Common Earwig", "Forficula auricularia", 3, ["earwig"]),
    ("German Cockroach", "Blattella germanica", 4, ["cockroach", "roach"]),
    ("American Cockroach", "Periplaneta americana", 4, []),
    ("Madagascar Hissing Cockroach", "Gromphadorhina portentosa", 3, []),
    ("Human Head Louse", "Pediculus humanus", 4, ["louse", "head lice"]),
    ("Common Bed Bug", "Cimex lectularius", 4, ["bed bug"]),
    ("Human Flea", "Pulex irritans", 3, ["flea"]),
    ("Cat Flea", "Ctenocephalides felis", 2, []),
    ("Green Peach Aphid", "Myzus persicae", 3, ["aphid", "greenfly"]),
    ("Common Green Lacewing", "Chrysoperla carnea", 2, ["lacewing"]),
    ("Water Boatman", "Corixa punctata", 2, []),
    ("Pond Skater", "Gerris lacustris", 2, ["water strider"]),
    ("Giant Water Bug", "Lethocerus americanus", 2, []),
    ("Shield Bug", "Palomena prasina", 2, ["green shield bug", "stink bug"]),
    ("Brown Marmorated Stink Bug", "Halyomorpha halys", 2, []),
    ("Silverfish", "Lepisma saccharinum", 3, []),
    ("Springtail", "Orchesella cincta", 1, []),
    ("Antlion", "Myrmeleon formicarius", 2, []),
    ("Caddisfly", "Phryganea grandis", 1, []),
    ("Cochineal Insect", "Dactylopius coccus", 2, ["cochineal"]),
])

# ── OTHER ARTHROPODS ───────────────────────────────────────────────────────
g([
    ("European Garden Spider", "Araneus diadematus", 4, ["garden spider", "orb weaver"]),
    ("Black Widow", "Latrodectus mactans", 5, ["southern black widow"]),
    ("Brown Recluse", "Loxosceles reclusa", 4, []),
    ("Sydney Funnel-web Spider", "Atrax robustus", 4, ["funnel-web spider"]),
    ("Goliath Birdeater", "Theraphosa blondi", 4, ["tarantula"]),
    ("Mexican Redknee Tarantula", "Brachypelma hamorii", 3, []),
    ("Jumping Spider", "Salticus scenicus", 4, ["zebra jumping spider"]),
    ("Wolf Spider", "Lycosa tarantula", 3, []),
    ("Brazilian Wandering Spider", "Phoneutria nigriventer", 3, []),
    ("House Spider", "Tegenaria domestica", 3, []),
    ("Emperor Scorpion", "Pandinus imperator", 4, ["scorpion"]),
    ("Deathstalker Scorpion", "Leiurus quinquestriatus", 3, []),
    ("Deer Tick", "Ixodes scapularis", 3, ["black-legged tick", "tick"]),
    ("Castor Bean Tick", "Ixodes ricinus", 2, ["sheep tick"]),
    ("House Dust Mite", "Dermatophagoides pteronyssinus", 3, ["dust mite"]),
    ("Varroa Mite", "Varroa destructor", 2, []),
    ("Harvestman", "Phalangium opilio", 2, ["daddy longlegs"]),
    ("Horseshoe Crab", "Limulus polyphemus", 4, ["atlantic horseshoe crab"]),

    ("European Lobster", "Homarus gammarus", 4, ["lobster"]),
    ("American Lobster", "Homarus americanus", 4, []),
    ("Spiny Lobster", "Palinurus elephas", 2, ["european spiny lobster"]),
    ("Edible Crab", "Cancer pagurus", 3, ["brown crab", "crab"]),
    ("Blue Crab", "Callinectes sapidus", 3, []),
    ("Japanese Spider Crab", "Macrocheira kaempferi", 4, ["giant spider crab"]),
    ("Coconut Crab", "Birgus latro", 4, []),
    ("Fiddler Crab", "Uca pugnax", 2, []),
    ("Hermit Crab", "Pagurus bernhardus", 4, ["common hermit crab"]),
    ("Common Shrimp", "Crangon crangon", 3, ["brown shrimp", "shrimp"]),
    ("Whiteleg Shrimp", "Litopenaeus vannamei", 2, ["prawn"]),
    ("Antarctic Krill", "Euphausia superba", 4, ["krill"]),
    ("Mantis Shrimp", "Odontodactylus scyllarus", 4, ["peacock mantis shrimp"]),
    ("Barnacle", "Semibalanus balanoides", 3, ["acorn barnacle"]),
    ("Goose Barnacle", "Lepas anatifera", 2, []),
    ("Water Flea", "Daphnia pulex", 3, ["daphnia"]),
    ("Brine Shrimp", "Artemia salina", 3, ["sea monkey"]),
    ("Common Woodlouse", "Oniscus asellus", 3, ["woodlouse", "pill bug", "roly poly"]),
    ("Sandhopper", "Talitrus saltator", 1, ["sand flea"]),
    ("Copepod", "Calanus finmarchicus", 2, []),
    ("Giant Isopod", "Bathynomus giganteus", 3, []),
    ("House Centipede", "Scutigera coleoptrata", 3, ["centipede"]),
    ("Giant Centipede", "Scolopendra gigantea", 3, ["amazonian giant centipede"]),
    ("Millipede", "Julus scandinavius", 3, []),
    ("Giant African Millipede", "Archispirostreptus gigas", 2, []),
])

# ── MOLLUSCS ───────────────────────────────────────────────────────────────
g([
    ("Common Octopus", "Octopus vulgaris", 5, ["octopus"]),
    ("Giant Pacific Octopus", "Enteroctopus dofleini", 4, []),
    ("Blue-ringed Octopus", "Hapalochlaena maculosa", 4, []),
    ("Mimic Octopus", "Thaumoctopus mimicus", 3, []),
    ("Giant Squid", "Architeuthis dux", 5, []),
    ("Colossal Squid", "Mesonychoteuthis hamiltoni", 4, []),
    ("European Squid", "Loligo vulgaris", 3, ["squid", "common squid"]),
    ("Humboldt Squid", "Dosidicus gigas", 3, []),
    ("Common Cuttlefish", "Sepia officinalis", 4, ["cuttlefish"]),
    ("Chambered Nautilus", "Nautilus pompilius", 4, ["nautilus"]),
    ("Garden Snail", "Cornu aspersum", 4, ["snail", "brown garden snail"]),
    ("Roman Snail", "Helix pomatia", 3, ["escargot", "edible snail"]),
    ("Giant African Land Snail", "Lissachatina fulica", 3, []),
    ("Great Pond Snail", "Lymnaea stagnalis", 2, ["pond snail"]),
    ("Cone Snail", "Conus geographus", 3, ["geography cone"]),
    ("Leopard Slug", "Limax maximus", 3, ["slug"]),
    ("Banana Slug", "Ariolimax columbianus", 3, []),
    ("Sea Slug", "Elysia chlorotica", 2, ["eastern emerald elysia"]),
    ("Nudibranch", "Glaucus atlanticus", 4, ["blue dragon", "blue sea slug"]),
    ("Sea Hare", "Aplysia californica", 3, ["california sea hare"]),
    ("Blue Mussel", "Mytilus edulis", 4, ["mussel"]),
    ("Pacific Oyster", "Magallana gigas", 4, ["oyster"]),
    ("European Flat Oyster", "Ostrea edulis", 3, []),
    ("Great Scallop", "Pecten maximus", 3, ["scallop"]),
    ("Giant Clam", "Tridacna gigas", 4, []),
    ("Hard Clam", "Mercenaria mercenaria", 2, ["quahog", "clam"]),
    ("Razor Clam", "Ensis magnus", 2, []),
    ("Ocean Quahog", "Arctica islandica", 3, []),
    ("Shipworm", "Teredo navalis", 2, []),
    ("Common Limpet", "Patella vulgata", 2, ["limpet"]),
    ("Common Periwinkle", "Littorina littorea", 2, ["periwinkle", "winkle"]),
    ("Abalone", "Haliotis rufescens", 3, ["red abalone"]),
    ("Queen Conch", "Aliger gigas", 3, ["conch"]),
    ("Chiton", "Chiton tuberculatus", 1, []),
])

# ── OTHER INVERTEBRATES ────────────────────────────────────────────────────
g([
    ("Moon Jellyfish", "Aurelia aurita", 5, ["jellyfish"]),
    ("Lion's Mane Jellyfish", "Cyanea capillata", 4, []),
    ("Box Jellyfish", "Chironex fleckeri", 4, ["sea wasp"]),
    ("Portuguese Man o' War", "Physalia physalis", 4, []),
    ("Immortal Jellyfish", "Turritopsis dohrnii", 3, []),
    ("Hydra", "Hydra vulgaris", 3, []),
    ("Sea Anemone", "Actinia equina", 4, ["beadlet anemone"]),
    ("Staghorn Coral", "Acropora cervicornis", 4, ["coral"]),
    ("Brain Coral", "Diploria labyrinthiformis", 3, ["grooved brain coral"]),
    ("Red Coral", "Corallium rubrum", 3, ["precious coral"]),
    ("Sea Fan", "Gorgonia ventalina", 2, ["common sea fan"]),
    ("Comb Jelly", "Mnemiopsis leidyi", 3, ["sea walnut", "ctenophore"]),
    ("Bath Sponge", "Spongia officinalis", 4, ["sea sponge", "sponge"]),
    ("Venus' Flower Basket", "Euplectella aspergillum", 2, ["glass sponge"]),

    ("Common Starfish", "Asterias rubens", 5, ["starfish", "sea star"]),
    ("Crown-of-thorns Starfish", "Acanthaster planci", 3, []),
    ("Sunflower Sea Star", "Pycnopodia helianthoides", 2, []),
    ("Purple Sea Urchin", "Strongylocentrotus purpuratus", 3, ["sea urchin"]),
    ("Edible Sea Urchin", "Echinus esculentus", 2, []),
    ("Sea Cucumber", "Holothuria tubulosa", 3, ["cotton-spinner"]),
    ("Brittle Star", "Ophiothrix fragilis", 2, ["common brittle star"]),
    ("Sea Lily", "Antedon bifida", 1, ["feather star"]),
    ("Sand Dollar", "Echinarachnius parma", 3, ["common sand dollar"]),

    ("Common Earthworm", "Lumbricus terrestris", 5, ["earthworm", "nightcrawler"]),
    ("Medicinal Leech", "Hirudo medicinalis", 4, ["leech"]),
    ("Giant Tube Worm", "Riftia pachyptila", 3, ["tube worm"]),
    ("Ragworm", "Hediste diversicolor", 1, []),
    ("Bootlace Worm", "Lineus longissimus", 2, ["ribbon worm"]),
    ("Tardigrade", "Hypsibius dujardini", 5, ["water bear", "moss piglet"]),
    ("Roundworm", "Caenorhabditis elegans", 4, ["c. elegans", "nematode"]),
    ("Human Roundworm", "Ascaris lumbricoides", 3, []),
    ("Hookworm", "Necator americanus", 2, []),
    ("Pinworm", "Enterobius vermicularis", 3, ["threadworm"]),
    ("Trichinella", "Trichinella spiralis", 2, []),
    ("Planarian", "Schmidtea mediterranea", 3, ["flatworm"]),
    ("Beef Tapeworm", "Taenia saginata", 3, ["tapeworm"]),
    ("Blood Fluke", "Schistosoma mansoni", 3, ["schistosome"]),
    ("Liver Fluke", "Fasciola hepatica", 2, []),
    ("Sea Squirt", "Ciona intestinalis", 3, ["tunicate", "vase tunicate"]),
    ("Lancelet", "Branchiostoma lanceolatum", 3, ["amphioxus"]),
    ("Acorn Worm", "Saccoglossus kowalevskii", 1, []),
    ("Velvet Worm", "Peripatus juliformis", 2, ["onychophoran"]),
    ("Peanut Worm", "Sipunculus nudus", 1, []),
    ("Bryozoan", "Membranipora membranacea", 1, ["sea mat", "moss animal"]),
    ("Lamp Shell", "Lingula anatina", 2, ["brachiopod"]),
    ("Rotifer", "Brachionus plicatilis", 2, []),
])

# ── PLANTS ─────────────────────────────────────────────────────────────────
g([
    ("Bread Wheat", "Triticum aestivum", 5, ["wheat"]),
    ("Rice", "Oryza sativa", 5, ["asian rice"]),
    ("Maize", "Zea mays", 5, ["corn", "sweetcorn"]),
    ("Barley", "Hordeum vulgare", 4, []),
    ("Oat", "Avena sativa", 4, ["oats"]),
    ("Rye", "Secale cereale", 3, []),
    ("Sorghum", "Sorghum bicolor", 3, []),
    ("Sugarcane", "Saccharum officinarum", 4, []),
    ("Bamboo", "Phyllostachys edulis", 5, ["moso bamboo"]),
    ("Ryegrass", "Lolium perenne", 2, ["perennial ryegrass", "grass"]),

    ("Potato", "Solanum tuberosum", 5, []),
    ("Tomato", "Solanum lycopersicum", 5, []),
    ("Aubergine", "Solanum melongena", 4, ["eggplant"]),
    ("Chili Pepper", "Capsicum annuum", 5, ["bell pepper", "pepper", "capsicum"]),
    ("Tobacco", "Nicotiana tabacum", 4, []),
    ("Deadly Nightshade", "Atropa belladonna", 4, ["belladonna"]),
    ("Petunia", "Petunia axillaris", 2, []),

    ("Soybean", "Glycine max", 4, ["soy", "soya"]),
    ("Common Bean", "Phaseolus vulgaris", 4, ["green bean", "kidney bean"]),
    ("Pea", "Pisum sativum", 5, ["garden pea"]),
    ("Chickpea", "Cicer arietinum", 4, ["garbanzo"]),
    ("Lentil", "Lens culinaris", 4, []),
    ("Peanut", "Arachis hypogaea", 5, ["groundnut"]),
    ("Alfalfa", "Medicago sativa", 3, ["lucerne"]),
    ("White Clover", "Trifolium repens", 3, ["clover"]),
    ("Liquorice", "Glycyrrhiza glabra", 3, ["licorice"]),
    ("Wisteria", "Wisteria sinensis", 3, ["chinese wisteria"]),
    ("Mimosa", "Mimosa pudica", 3, ["sensitive plant", "touch-me-not"]),
    ("Acacia", "Vachellia nilotica", 3, ["gum arabic tree"]),

    ("Apple", "Malus domestica", 5, []),
    ("Pear", "Pyrus communis", 4, []),
    ("Peach", "Prunus persica", 5, []),
    ("Cherry", "Prunus avium", 5, ["sweet cherry", "wild cherry"]),
    ("Plum", "Prunus domestica", 4, []),
    ("Apricot", "Prunus armeniaca", 4, []),
    ("Almond", "Prunus dulcis", 4, []),
    ("Strawberry", "Fragaria ananassa", 5, ["garden strawberry"]),
    ("Raspberry", "Rubus idaeus", 4, []),
    ("Blackberry", "Rubus fruticosus", 4, ["bramble"]),
    ("Dog Rose", "Rosa canina", 4, ["rose", "wild rose"]),
    ("Hawthorn", "Crataegus monogyna", 3, []),
    ("Rowan", "Sorbus aucuparia", 3, ["mountain ash"]),

    ("Orange", "Citrus sinensis", 5, ["sweet orange"]),
    ("Lemon", "Citrus limon", 5, []),
    ("Lime", "Citrus aurantiifolia", 4, ["key lime"]),
    ("Grapefruit", "Citrus paradisi", 4, []),
    ("Mango", "Mangifera indica", 5, []),
    ("Cashew", "Anacardium occidentale", 4, []),
    ("Pistachio", "Pistacia vera", 4, []),
    ("Grape Vine", "Vitis vinifera", 5, ["grape", "vine"]),
    ("Olive", "Olea europaea", 5, ["olive tree"]),
    ("Fig", "Ficus carica", 4, ["common fig"]),
    ("Pomegranate", "Punica granatum", 5, []),
    ("Date Palm", "Phoenix dactylifera", 4, ["dates"]),
    ("Coconut Palm", "Cocos nucifera", 5, ["coconut"]),
    ("Oil Palm", "Elaeis guineensis", 3, ["african oil palm"]),
    ("Banana", "Musa acuminata", 5, []),
    ("Pineapple", "Ananas comosus", 5, []),
    ("Avocado", "Persea americana", 5, []),
    ("Papaya", "Carica papaya", 4, []),
    ("Kiwifruit", "Actinidia deliciosa", 4, ["kiwi fruit"]),
    ("Watermelon", "Citrullus lanatus", 5, []),
    ("Cucumber", "Cucumis sativus", 5, []),
    ("Melon", "Cucumis melo", 4, ["cantaloupe", "honeydew"]),
    ("Pumpkin", "Cucurbita pepo", 5, ["courgette", "zucchini", "squash"]),
    ("Blueberry", "Vaccinium corymbosum", 4, ["highbush blueberry"]),
    ("Cranberry", "Vaccinium macrocarpon", 3, []),
    ("Durian", "Durio zibethinus", 4, []),
    ("Cocoa", "Theobroma cacao", 5, ["cacao", "chocolate tree"]),
    ("Coffee", "Coffea arabica", 5, ["arabica coffee"]),
    ("Tea", "Camellia sinensis", 5, ["tea plant"]),
    ("Vanilla", "Vanilla planifolia", 4, []),
    ("Black Pepper", "Piper nigrum", 4, ["peppercorn"]),
    ("Cinnamon", "Cinnamomum verum", 4, []),
    ("Saffron Crocus", "Crocus sativus", 4, ["saffron"]),
    ("Ginger", "Zingiber officinale", 5, []),
    ("Turmeric", "Curcuma longa", 4, []),
    ("Cardamom", "Elettaria cardamomum", 3, []),
    ("Nutmeg", "Myristica fragrans", 3, []),
    ("Clove", "Syzygium aromaticum", 3, []),

    ("Cabbage", "Brassica oleracea", 5, ["broccoli", "cauliflower", "kale", "brussels sprout"]),
    ("Turnip", "Brassica rapa", 3, ["bok choy"]),
    ("Rapeseed", "Brassica napus", 3, ["canola"]),
    ("Radish", "Raphanus sativus", 4, []),
    ("Thale Cress", "Arabidopsis thaliana", 4, ["arabidopsis"]),
    ("Mustard", "Sinapis alba", 3, ["white mustard"]),
    ("Carrot", "Daucus carota", 5, []),
    ("Celery", "Apium graveolens", 4, []),
    ("Parsley", "Petroselinum crispum", 4, []),
    ("Coriander", "Coriandrum sativum", 4, ["cilantro"]),
    ("Dill", "Anethum graveolens", 3, []),
    ("Fennel", "Foeniculum vulgare", 3, []),
    ("Hemlock", "Conium maculatum", 4, ["poison hemlock"]),
    ("Onion", "Allium cepa", 5, []),
    ("Garlic", "Allium sativum", 5, []),
    ("Leek", "Allium ampeloprasum", 3, []),
    ("Chive", "Allium schoenoprasum", 3, ["chives"]),
    ("Asparagus", "Asparagus officinalis", 4, []),
    ("Lettuce", "Lactuca sativa", 5, []),
    ("Sunflower", "Helianthus annuus", 5, []),
    ("Jerusalem Artichoke", "Helianthus tuberosus", 2, []),
    ("Globe Artichoke", "Cynara cardunculus", 3, ["artichoke"]),
    ("Daisy", "Bellis perennis", 4, ["common daisy"]),
    ("Dandelion", "Taraxacum officinale", 5, []),
    ("Chamomile", "Matricaria chamomilla", 3, []),
    ("Marigold", "Tagetes erecta", 3, ["mexican marigold"]),
    ("Chrysanthemum", "Chrysanthemum indicum", 3, []),
    ("Thistle", "Cirsium vulgare", 3, ["spear thistle"]),
    ("Basil", "Ocimum basilicum", 5, []),
    ("Mint", "Mentha spicata", 5, ["spearmint"]),
    ("Peppermint", "Mentha piperita", 4, []),
    ("Lavender", "Lavandula angustifolia", 5, []),
    ("Rosemary", "Salvia rosmarinus", 4, []),
    ("Sage", "Salvia officinalis", 4, []),
    ("Thyme", "Thymus vulgaris", 4, []),
    ("Oregano", "Origanum vulgare", 4, []),
    ("Sesame", "Sesamum indicum", 3, []),
    ("Sugar Beet", "Beta vulgaris", 4, ["beetroot", "beet", "chard"]),
    ("Spinach", "Spinacia oleracea", 4, []),
    ("Quinoa", "Chenopodium quinoa", 4, []),
    ("Buckwheat", "Fagopyrum esculentum", 3, []),
    ("Rhubarb", "Rheum rhabarbarum", 3, []),
    ("Cotton", "Gossypium hirsutum", 4, ["upland cotton"]),
    ("Cannabis", "Cannabis sativa", 5, ["hemp", "marijuana"]),
    ("Hop", "Humulus lupulus", 3, ["hops"]),
    ("Flax", "Linum usitatissimum", 3, ["linseed"]),
    ("Cassava", "Manihot esculenta", 4, ["manioc", "yuca"]),
    ("Poinsettia", "Euphorbia pulcherrima", 3, []),
    ("Rubber Tree", "Hevea brasiliensis", 3, []),
    ("Opium Poppy", "Papaver somniferum", 4, ["poppy"]),
    ("Common Poppy", "Papaver rhoeas", 3, ["field poppy", "corn poppy"]),
    ("Sweet Potato", "Ipomoea batatas", 4, []),
    ("Morning Glory", "Ipomoea purpurea", 3, []),
    ("Foxglove", "Digitalis purpurea", 4, []),
    ("Snapdragon", "Antirrhinum majus", 3, []),
    ("Sunflower Star Jasmine", "Jasminum officinale", 3, ["jasmine", "common jasmine"]),
    ("Lilac", "Syringa vulgaris", 4, []),
    ("Ash", "Fraxinus excelsior", 3, ["european ash"]),
    ("Heather", "Calluna vulgaris", 3, ["ling"]),
    ("Rhododendron", "Rhododendron ponticum", 3, []),
    ("Azalea", "Rhododendron indicum", 2, []),
    ("Camellia", "Camellia japonica", 3, []),
    ("Sundew", "Drosera rotundifolia", 3, ["round-leaved sundew"]),
    ("Venus Flytrap", "Dionaea muscipula", 5, []),
    ("Pitcher Plant", "Nepenthes rafflesiana", 4, []),
    ("Prickly Pear", "Opuntia ficus-indica", 4, ["cactus", "nopal"]),
    ("Saguaro", "Carnegiea gigantea", 4, []),
    ("Aloe Vera", "Aloe vera", 5, ["aloe"]),
    ("Agave", "Agave americana", 3, ["century plant"]),
    ("Tulip", "Tulipa gesneriana", 5, []),
    ("Daffodil", "Narcissus pseudonarcissus", 4, ["narcissus"]),
    ("Lily", "Lilium candidum", 4, ["madonna lily"]),
    ("Bluebell", "Hyacinthoides non-scripta", 3, ["common bluebell"]),
    ("Hyacinth", "Hyacinthus orientalis", 3, []),
    ("Iris", "Iris germanica", 3, ["bearded iris"]),
    ("Orchid", "Phalaenopsis amabilis", 4, ["moth orchid"]),
    ("Lady's Slipper Orchid", "Cypripedium calceolus", 2, []),
    ("Water Lily", "Nymphaea alba", 4, ["white water lily"]),
    ("Giant Water Lily", "Victoria amazonica", 3, []),
    ("Lotus", "Nelumbo nucifera", 4, ["sacred lotus"]),
    ("Duckweed", "Lemna minor", 2, ["common duckweed"]),
    ("Papyrus", "Cyperus papyrus", 3, []),
    ("Common Reed", "Phragmites australis", 2, ["reed"]),
    ("Cattail", "Typha latifolia", 3, ["bulrush"]),
    ("Titan Arum", "Amorphophallus titanum", 4, ["corpse flower"]),
    ("Rafflesia", "Rafflesia arnoldii", 4, ["corpse lily"]),
    ("Peace Lily", "Spathiphyllum wallisii", 3, []),
    ("Monstera", "Monstera deliciosa", 4, ["swiss cheese plant"]),
    ("Ivy", "Hedera helix", 4, ["common ivy", "english ivy"]),
    ("Mistletoe", "Viscum album", 4, ["european mistletoe"]),
    ("Holly", "Ilex aquifolium", 4, ["european holly"]),
    ("Sunflower Nettle", "Urtica dioica", 4, ["stinging nettle", "nettle"]),
    ("Hydrangea", "Hydrangea macrophylla", 3, []),
    ("Sunflower Buttercup", "Ranunculus acris", 2, ["meadow buttercup", "buttercup"]),
    ("Peony", "Paeonia lactiflora", 3, []),
    ("Magnolia", "Magnolia grandiflora", 4, ["southern magnolia"]),
    ("Avocado Bay Laurel", "Laurus nobilis", 3, ["bay laurel", "bay leaf"]),
    ("Sunflower Water Hyacinth", "Pontederia crassipes", 2, ["water hyacinth"]),

    ("English Oak", "Quercus robur", 5, ["oak", "oak tree"]),
    ("Red Oak", "Quercus rubra", 3, ["northern red oak"]),
    ("Cork Oak", "Quercus suber", 3, ["cork"]),
    ("Silver Birch", "Betula pendula", 4, ["birch"]),
    ("European Beech", "Fagus sylvatica", 4, ["beech"]),
    ("Sweet Chestnut", "Castanea sativa", 3, ["chestnut"]),
    ("Hazel", "Corylus avellana", 3, ["hazelnut"]),
    ("Walnut", "Juglans regia", 4, ["english walnut"]),
    ("Pecan", "Carya illinoinensis", 3, []),
    ("Sugar Maple", "Acer saccharum", 4, ["maple"]),
    ("Sycamore Maple", "Acer pseudoplatanus", 2, ["sycamore"]),
    ("Japanese Maple", "Acer palmatum", 3, []),
    ("Horse Chestnut", "Aesculus hippocastanum", 4, ["conker tree"]),
    ("Weeping Willow", "Salix babylonica", 4, ["willow"]),
    ("White Willow", "Salix alba", 3, []),
    ("Aspen", "Populus tremula", 3, ["european aspen"]),
    ("Quaking Aspen", "Populus tremuloides", 3, []),
    ("Eastern Cottonwood", "Populus deltoides", 2, ["cottonwood"]),
    ("Elm", "Ulmus glabra", 3, ["wych elm"]),
    ("Small-leaved Lime", "Tilia cordata", 2, ["linden", "lime tree"]),
    ("Baobab", "Adansonia digitata", 4, []),
    ("Banyan", "Ficus benghalensis", 3, ["indian banyan"]),
    ("Sacred Fig", "Ficus religiosa", 3, ["bodhi tree", "peepal"]),
    ("Eucalyptus", "Eucalyptus globulus", 4, ["blue gum", "gum tree"]),
    ("Mangrove", "Rhizophora mangle", 3, ["red mangrove"]),
    ("Teak", "Tectona grandis", 3, []),
    ("Mahogany", "Swietenia macrophylla", 3, ["big-leaf mahogany"]),
    ("Ebony", "Diospyros ebenum", 2, ["ceylon ebony"]),
    ("Balsa", "Ochroma pyramidale", 2, []),
    ("Kapok Tree", "Ceiba pentandra", 2, []),
    ("Jacaranda", "Jacaranda mimosifolia", 3, []),
    ("Plane Tree", "Platanus x acerifolia", 3, ["london plane"]),
    ("Neem", "Azadirachta indica", 3, []),
    ("Frankincense", "Boswellia sacra", 3, []),
    ("Myrrh", "Commiphora myrrha", 3, []),

    ("Scots Pine", "Pinus sylvestris", 4, ["pine", "pine tree"]),
    ("Eastern White Pine", "Pinus strobus", 3, []),
    ("Bristlecone Pine", "Pinus longaeva", 4, ["great basin bristlecone pine"]),
    ("Stone Pine", "Pinus pinea", 2, ["pine nut"]),
    ("Norway Spruce", "Picea abies", 4, ["spruce", "christmas tree"]),
    ("Sitka Spruce", "Picea sitchensis", 2, []),
    ("Silver Fir", "Abies alba", 3, ["fir"]),
    ("Douglas Fir", "Pseudotsuga menziesii", 3, []),
    ("European Larch", "Larix decidua", 2, ["larch"]),
    ("Cedar of Lebanon", "Cedrus libani", 3, ["cedar"]),
    ("Coast Redwood", "Sequoia sempervirens", 5, ["redwood"]),
    ("Giant Sequoia", "Sequoiadendron giganteum", 5, ["sequoia"]),
    ("Dawn Redwood", "Metasequoia glyptostroboides", 3, []),
    ("Bald Cypress", "Taxodium distichum", 2, []),
    ("Common Juniper", "Juniperus communis", 3, ["juniper"]),
    ("Yew", "Taxus baccata", 4, ["european yew"]),
    ("Monkey Puzzle", "Araucaria araucana", 4, []),
    ("Ginkgo", "Ginkgo biloba", 5, ["maidenhair tree"]),
    ("Welwitschia", "Welwitschia mirabilis", 3, []),
    ("Cycad", "Cycas revoluta", 3, ["sago palm"]),

    ("Bracken", "Pteridium aquilinum", 3, ["fern", "bracken fern"]),
    ("Male Fern", "Dryopteris filix-mas", 2, []),
    ("Maidenhair Fern", "Adiantum capillus-veneris", 2, []),
    ("Tree Fern", "Dicksonia antarctica", 3, ["soft tree fern"]),
    ("Horsetail", "Equisetum arvense", 3, ["field horsetail"]),
    ("Clubmoss", "Lycopodium clavatum", 2, ["stag's-horn clubmoss"]),
    ("Sphagnum Moss", "Sphagnum palustre", 3, ["peat moss", "bog moss"]),
    ("Common Haircap Moss", "Polytrichum commune", 2, ["moss"]),
    ("Liverwort", "Marchantia polymorpha", 3, ["common liverwort"]),
    ("Resurrection Plant", "Selaginella lepidophylla", 2, []),
])

# ── FUNGI ──────────────────────────────────────────────────────────────────
g([
    ("Button Mushroom", "Agaricus bisporus", 5, ["mushroom", "portobello", "cremini"]),
    ("Field Mushroom", "Agaricus campestris", 3, []),
    ("Fly Agaric", "Amanita muscaria", 5, ["toadstool"]),
    ("Death Cap", "Amanita phalloides", 5, []),
    ("Destroying Angel", "Amanita virosa", 3, []),
    ("Oyster Mushroom", "Pleurotus ostreatus", 4, []),
    ("Shiitake", "Lentinula edodes", 4, []),
    ("Enoki", "Flammulina velutipes", 3, ["velvet shank"]),
    ("Porcini", "Boletus edulis", 4, ["penny bun", "cep"]),
    ("Chanterelle", "Cantharellus cibarius", 4, []),
    ("Morel", "Morchella esculenta", 4, ["common morel"]),
    ("Black Truffle", "Tuber melanosporum", 5, ["truffle", "perigord truffle"]),
    ("White Truffle", "Tuber magnatum", 4, []),
    ("Puffball", "Lycoperdon perlatum", 3, ["common puffball"]),
    ("Giant Puffball", "Calvatia gigantea", 3, []),
    ("Stinkhorn", "Phallus impudicus", 3, ["common stinkhorn"]),
    ("Shaggy Ink Cap", "Coprinus comatus", 3, ["lawyer's wig"]),
    ("Honey Fungus", "Armillaria mellea", 3, ["honey mushroom"]),
    ("Turkey Tail", "Trametes versicolor", 3, []),
    ("Chicken of the Woods", "Laetiporus sulphureus", 3, []),
    ("Hen of the Woods", "Grifola frondosa", 3, ["maitake"]),
    ("Reishi", "Ganoderma lucidum", 3, ["lingzhi"]),
    ("Birch Polypore", "Fomitopsis betulina", 2, []),
    ("Tinder Fungus", "Fomes fomentarius", 2, ["hoof fungus"]),
    ("Lion's Mane Mushroom", "Hericium erinaceus", 3, []),
    ("Liberty Cap", "Psilocybe semilanceata", 4, ["magic mushroom"]),
    ("Jelly Ear", "Auricularia auricula-judae", 2, ["wood ear"]),
    ("Fairy Ring Mushroom", "Marasmius oreades", 2, []),
    ("Baker's Yeast", "Saccharomyces cerevisiae", 5, ["yeast", "brewer's yeast"]),
    ("Fission Yeast", "Schizosaccharomyces pombe", 2, []),
    ("Candida", "Candida albicans", 4, ["thrush fungus"]),
    ("Penicillium", "Penicillium chrysogenum", 4, ["penicillin mould"]),
    ("Blue Cheese Mould", "Penicillium roqueforti", 3, []),
    ("Black Bread Mould", "Rhizopus stolonifer", 2, ["bread mould"]),
    ("Aspergillus", "Aspergillus niger", 3, ["black mould"]),
    ("Koji Mould", "Aspergillus oryzae", 3, ["koji"]),
    ("Ergot", "Claviceps purpurea", 3, []),
    ("Athlete's Foot Fungus", "Trichophyton rubrum", 3, ["ringworm fungus"]),
    ("Cordyceps", "Ophiocordyceps unilateralis", 4, ["zombie-ant fungus"]),
    ("Caterpillar Fungus", "Ophiocordyceps sinensis", 3, []),
    ("Wheat Rust", "Puccinia graminis", 2, ["stem rust"]),
    ("Corn Smut", "Ustilago maydis", 2, ["huitlacoche"]),
    ("Dutch Elm Disease", "Ophiostoma ulmi", 2, []),
    ("Chytrid Fungus", "Batrachochytrium dendrobatidis", 3, []),
    ("Reindeer Lichen", "Cladonia rangiferina", 3, ["lichen"]),
    ("Oakmoss", "Evernia prunastri", 2, []),
    ("Bread Mould", "Neurospora crassa", 2, ["red bread mould"]),
])

# ── PROTISTS, ALGAE AND OTHER EUKARYOTES ───────────────────────────────────
g([
    ("Amoeba", "Amoeba proteus", 5, []),
    ("Paramecium", "Paramecium caudatum", 5, []),
    ("Euglena", "Euglena gracilis", 4, []),
    ("Slime Mould", "Physarum polycephalum", 4, ["blob", "slime mold"]),
    ("Dictyostelium", "Dictyostelium discoideum", 2, ["social amoeba"]),
    ("Malaria Parasite", "Plasmodium falciparum", 5, ["plasmodium"]),
    ("Toxoplasma", "Toxoplasma gondii", 4, []),
    ("Giardia", "Giardia lamblia", 3, []),
    ("Trypanosome", "Trypanosoma brucei", 3, ["sleeping sickness parasite"]),
    ("Leishmania", "Leishmania donovani", 2, []),
    ("Foraminifera", "Globigerina bulloides", 2, ["foram"]),
    ("Radiolarian", "Actinomma leptodermum", 1, []),
    ("Dinoflagellate", "Karenia brevis", 2, ["red tide alga"]),
    ("Diatom", "Thalassiosira pseudonana", 3, []),
    ("Coccolithophore", "Emiliania huxleyi", 2, []),
    ("Sea Lettuce", "Ulva lactuca", 3, ["green algae"]),
    ("Giant Kelp", "Macrocystis pyrifera", 4, ["kelp"]),
    ("Bladderwrack", "Fucus vesiculosus", 3, ["seaweed", "wrack"]),
    ("Nori", "Pyropia yezoensis", 3, ["laver"]),
    ("Irish Moss", "Chondrus crispus", 2, ["carrageen"]),
    ("Chlamydomonas", "Chlamydomonas reinhardtii", 3, []),
    ("Volvox", "Volvox carteri", 3, []),
    ("Spirogyra", "Spirogyra crassa", 2, ["pond scum"]),
    ("Stentor", "Stentor coeruleus", 2, []),
    ("Vorticella", "Vorticella campanula", 1, []),
    ("Water Mould", "Phytophthora infestans", 3, ["potato blight"]),
])

# ── BACTERIA AND ARCHAEA ───────────────────────────────────────────────────
g([
    ("Escherichia coli", "Escherichia coli", 5, ["e. coli", "e coli"]),
    ("Salmonella", "Salmonella enterica", 5, []),
    ("Cholera Bacterium", "Vibrio cholerae", 4, ["cholera"]),
    ("Plague Bacterium", "Yersinia pestis", 5, ["black death bacterium", "plague"]),
    ("Bubonic Plague Relative", "Yersinia enterocolitica", 1, []),
    ("Golden Staph", "Staphylococcus aureus", 5, ["staph", "mrsa"]),
    ("Strep Throat Bacterium", "Streptococcus pyogenes", 4, ["strep"]),
    ("Pneumococcus", "Streptococcus pneumoniae", 3, []),
    ("Tuberculosis Bacterium", "Mycobacterium tuberculosis", 5, ["tb", "tubercle bacillus"]),
    ("Leprosy Bacterium", "Mycobacterium leprae", 3, ["leprosy"]),
    ("Anthrax Bacterium", "Bacillus anthracis", 4, ["anthrax"]),
    ("Hay Bacillus", "Bacillus subtilis", 3, []),
    ("Botulism Bacterium", "Clostridium botulinum", 4, ["botulinum", "botox bacterium"]),
    ("Tetanus Bacterium", "Clostridium tetani", 3, ["tetanus"]),
    ("Yoghurt Bacterium", "Lactobacillus delbrueckii", 3, ["lactobacillus", "yogurt bacterium"]),
    ("Stomach Ulcer Bacterium", "Helicobacter pylori", 4, ["h. pylori"]),
    ("Gonorrhoea Bacterium", "Neisseria gonorrhoeae", 3, ["gonorrhea"]),
    ("Syphilis Bacterium", "Treponema pallidum", 4, ["syphilis"]),
    ("Lyme Disease Bacterium", "Borreliella burgdorferi", 3, ["borrelia", "lyme"]),
    ("Legionella", "Legionella pneumophila", 3, ["legionnaires' disease bacterium"]),
    ("Whooping Cough Bacterium", "Bordetella pertussis", 3, ["pertussis"]),
    ("Diphtheria Bacterium", "Corynebacterium diphtheriae", 3, ["diphtheria"]),
    ("Cyanobacterium", "Synechococcus elongatus", 3, ["blue-green alga"]),
    ("Spirulina", "Arthrospira platensis", 4, []),
    ("Nitrogen-fixing Rhizobium", "Rhizobium leguminosarum", 3, ["rhizobium"]),
    ("Agrobacterium", "Agrobacterium tumefaciens", 3, []),
    ("Deinococcus", "Deinococcus radiodurans", 3, ["conan the bacterium"]),
    ("Thermus", "Thermus aquaticus", 3, ["taq"]),
    ("Bioluminescent Vibrio", "Aliivibrio fischeri", 2, []),
    ("Streptomyces", "Streptomyces coelicolor", 2, []),
    ("Chlamydia", "Chlamydia trachomatis", 4, []),
    ("Mycoplasma", "Mycoplasma genitalium", 2, []),
    ("Listeria", "Listeria monocytogenes", 3, []),
    ("Pseudomonas", "Pseudomonas aeruginosa", 3, []),
    ("Methanogen", "Methanocaldococcus jannaschii", 2, ["methane archaeon"]),
    ("Halophilic Archaeon", "Halobacterium salinarum", 2, ["halobacterium"]),
    ("Sulfolobus", "Saccharolobus solfataricus", 2, ["sulfolobus"]),
    ("Pyrococcus", "Pyrococcus furiosus", 2, []),
    ("Methanobrevibacter", "Methanobrevibacter smithii", 2, ["gut archaeon"]),
    ("Thermoplasma", "Thermoplasma acidophilum", 1, []),
    ("Nitrosopumilus", "Nitrosopumilus maritimus", 1, []),
])


def dedupe(rows):
    """Two rows may resolve to the same organism; keep the first, highest prior."""
    seen, out = {}, []
    for r in rows:
        k = r[1].strip().lower()
        if k in seen:
            continue
        seen[k] = 1
        out.append(r)
    return out


SEED = dedupe(SEED)

if __name__ == "__main__":
    print("seed rows:", len(SEED))
    from collections import Counter
    print(Counter(r[2] for r in SEED))


