# -*- coding: utf-8 -*-
"""
PHYLO — the candidate seed list.

Each row is  (common_name, scientific_name, prior, aliases)
  common_name  what the player types and reads. Must be a name a well-read
               non-biologist would actually produce unprompted.
  scientific_name  sent to the GBIF backbone matcher, which resolves synonyms
               and returns the authoritative kingdom→species lineage. If a name
               here is wrong or outdated, GBIF either corrects it or rejects it;
               gen_phylo.py logs every rejection rather than guessing.
  prior        1..5, my own guess at how nameable it is. Only a tie-breaker —
               the real salience number is English Wikipedia pageviews, fetched
               per organism by the harvester.
  aliases      extra strings the type-ahead should accept.

Nothing in this file is trusted as taxonomy. It is a list of *candidates*;
every lineage that ships comes from GBIF.
"""

SEED = []


def g(rows):
    SEED.extend(rows)


# ── MAMMALS ────────────────────────────────────────────────────────────────
g([
    ("Human", "Homo sapiens", 5, ["person", "people", "man"]),
    ("Chimpanzee", "Pan troglodytes", 5, ["chimp"]),
    ("Bonobo", "Pan paniscus", 4, ["pygmy chimpanzee"]),
    ("Western Gorilla", "Gorilla gorilla", 5, ["gorilla"]),
    ("Orangutan", "Pongo pygmaeus", 5, ["bornean orangutan"]),
    ("Gibbon", "Hylobates lar", 4, ["lar gibbon", "white-handed gibbon"]),
    ("Baboon", "Papio anubis", 4, ["olive baboon"]),
    ("Mandrill", "Mandrillus sphinx", 4, []),
    ("Rhesus Macaque", "Macaca mulatta", 4, ["macaque", "rhesus monkey"]),
    ("Japanese Macaque", "Macaca fuscata", 3, ["snow monkey"]),
    ("Capuchin Monkey", "Cebus capucinus", 4, ["capuchin"]),
    ("Howler Monkey", "Alouatta palliata", 3, []),
    ("Spider Monkey", "Ateles geoffroyi", 3, []),
    ("Marmoset", "Callithrix jacchus", 3, ["common marmoset"]),
    ("Proboscis Monkey", "Nasalis larvatus", 3, []),
    ("Ring-tailed Lemur", "Lemur catta", 4, ["lemur"]),
    ("Aye-aye", "Daubentonia madagascariensis", 3, []),
    ("Slow Loris", "Nycticebus coucang", 3, ["loris"]),
    ("Tarsier", "Tarsius tarsier", 3, []),

    ("Lion", "Panthera leo", 5, []),
    ("Tiger", "Panthera tigris", 5, []),
    ("Leopard", "Panthera pardus", 5, []),
    ("Jaguar", "Panthera onca", 5, []),
    ("Snow Leopard", "Panthera uncia", 4, []),
    ("Cheetah", "Acinonyx jubatus", 5, []),
    ("Cougar", "Puma concolor", 5, ["mountain lion", "puma"]),
    ("Lynx", "Lynx lynx", 4, ["eurasian lynx"]),
    ("Bobcat", "Lynx rufus", 4, []),
    ("Caracal", "Caracal caracal", 3, []),
    ("Ocelot", "Leopardus pardalis", 3, []),
    ("Serval", "Leptailurus serval", 3, []),
    ("Domestic Cat", "Felis catus", 5, ["cat", "house cat", "kitty"]),
    ("Wildcat", "Felis silvestris", 3, ["european wildcat"]),

    ("Grey Wolf", "Canis lupus", 5, ["wolf"]),
    ("Domestic Dog", "Canis familiaris", 5, ["dog", "puppy"]),
    ("Coyote", "Canis latrans", 4, []),
    ("Dingo", "Canis dingo", 3, []),
    ("Red Fox", "Vulpes vulpes", 5, ["fox"]),
    ("Arctic Fox", "Vulpes lagopus", 4, []),
    ("Fennec Fox", "Vulpes zerda", 3, []),
    ("African Wild Dog", "Lycaon pictus", 3, ["painted dog"]),
    ("Jackal", "Canis aureus", 3, ["golden jackal"]),
    ("Raccoon Dog", "Nyctereutes procyonoides", 2, ["tanuki"]),

    ("Brown Bear", "Ursus arctos", 5, ["grizzly bear", "grizzly"]),
    ("Polar Bear", "Ursus maritimus", 5, []),
    ("American Black Bear", "Ursus americanus", 4, ["black bear"]),
    ("Giant Panda", "Ailuropoda melanoleuca", 5, ["panda"]),
    ("Sloth Bear", "Melursus ursinus", 3, []),
    ("Spectacled Bear", "Tremarctos ornatus", 3, []),
    ("Red Panda", "Ailurus fulgens", 4, []),
    ("Raccoon", "Procyon lotor", 5, []),
    ("Coati", "Nasua nasua", 2, []),
    ("Meerkat", "Suricata suricatta", 4, []),
    ("Mongoose", "Herpestes edwardsii", 3, ["indian grey mongoose"]),
    ("Spotted Hyena", "Crocuta crocuta", 4, ["hyena"]),
    ("Badger", "Meles meles", 4, ["european badger"]),
    ("Honey Badger", "Mellivora capensis", 4, ["ratel"]),
    ("Wolverine", "Gulo gulo", 4, []),
    ("Otter", "Lutra lutra", 4, ["european otter"]),
    ("Sea Otter", "Enhydra lutris", 4, []),
    ("Stoat", "Mustela erminea", 3, ["ermine", "short-tailed weasel"]),
    ("Ferret", "Mustela furo", 4, []),
    ("Mink", "Neovison vison", 3, ["american mink"]),
    ("Pine Marten", "Martes martes", 3, ["marten"]),
    ("Skunk", "Mephitis mephitis", 4, ["striped skunk"]),

    ("Walrus", "Odobenus rosmarus", 4, []),
    ("Harbour Seal", "Phoca vitulina", 4, ["common seal", "harbor seal"]),
    ("Grey Seal", "Halichoerus grypus", 3, []),
    ("Leopard Seal", "Hydrurga leptonyx", 3, []),
    ("Elephant Seal", "Mirounga leonina", 3, ["southern elephant seal"]),
    ("California Sea Lion", "Zalophus californianus", 4, ["sea lion"]),

    ("Blue Whale", "Balaenoptera musculus", 5, []),
    ("Humpback Whale", "Megaptera novaeangliae", 5, []),
    ("Fin Whale", "Balaenoptera physalus", 3, []),
    ("Grey Whale", "Eschrichtius robustus", 3, []),
    ("Bowhead Whale", "Balaena mysticetus", 3, []),
    ("Sperm Whale", "Physeter macrocephalus", 5, []),
    ("Orca", "Orcinus orca", 5, ["killer whale"]),
    ("Bottlenose Dolphin", "Tursiops truncatus", 5, ["dolphin"]),
    ("Narwhal", "Monodon monoceros", 4, []),
    ("Beluga Whale", "Delphinapterus leucas", 4, ["beluga"]),
    ("Harbour Porpoise", "Phocoena phocoena", 3, ["porpoise"]),
    ("Amazon River Dolphin", "Inia geoffrensis", 3, ["pink river dolphin", "boto"]),

    ("African Bush Elephant", "Loxodonta africana", 5, ["african elephant", "elephant"]),
    ("Asian Elephant", "Elephas maximus", 5, []),
    ("Dugong", "Dugong dugon", 3, []),
    ("Manatee", "Trichechus manatus", 4, ["west indian manatee", "sea cow"]),
    ("Aardvark", "Orycteropus afer", 4, []),
    ("Rock Hyrax", "Procavia capensis", 2, ["hyrax", "dassie"]),

    ("Horse", "Equus caballus", 5, []),
    ("Donkey", "Equus asinus", 5, ["ass"]),
    ("Plains Zebra", "Equus quagga", 5, ["zebra"]),
    ("Przewalski's Horse", "Equus przewalskii", 2, []),
    ("White Rhinoceros", "Ceratotherium simum", 5, ["rhino", "rhinoceros"]),
    ("Black Rhinoceros", "Diceros bicornis", 4, []),
    ("Indian Rhinoceros", "Rhinoceros unicornis", 3, ["greater one-horned rhino"]),
    ("Malayan Tapir", "Tapirus indicus", 3, ["tapir"]),

    ("Domestic Pig", "Sus scrofa", 5, ["pig", "wild boar", "boar", "hog"]),
    ("Warthog", "Phacochoerus africanus", 4, []),
    ("Hippopotamus", "Hippopotamus amphibius", 5, ["hippo"]),
    ("Dromedary Camel", "Camelus dromedarius", 5, ["camel"]),
    ("Bactrian Camel", "Camelus bactrianus", 4, []),
    ("Llama", "Lama glama", 4, []),
    ("Alpaca", "Vicugna pacos", 4, []),
    ("Guanaco", "Lama guanicoe", 2, []),
    ("Giraffe", "Giraffa camelopardalis", 5, []),
    ("Okapi", "Okapia johnstoni", 3, []),
    ("Cattle", "Bos taurus", 5, ["cow", "bull", "ox"]),
    ("Zebu", "Bos indicus", 2, []),
    ("Yak", "Bos mutus", 4, []),
    ("American Bison", "Bison bison", 5, ["bison", "buffalo"]),
    ("European Bison", "Bison bonasus", 3, ["wisent"]),
    ("Water Buffalo", "Bubalus bubalis", 4, []),
    ("African Buffalo", "Syncerus caffer", 3, ["cape buffalo"]),
    ("Domestic Sheep", "Ovis aries", 5, ["sheep", "lamb", "ram"]),
    ("Bighorn Sheep", "Ovis canadensis", 3, []),
    ("Domestic Goat", "Capra hircus", 5, ["goat"]),
    ("Ibex", "Capra ibex", 3, ["alpine ibex"]),
    ("Musk Ox", "Ovibos moschatus", 3, ["muskox"]),
    ("Chamois", "Rupicapra rupicapra", 2, []),
    ("Impala", "Aepyceros melampus", 3, []),
    ("Springbok", "Antidorcas marsupialis", 3, []),
    ("Gazelle", "Eudorcas thomsonii", 4, ["thomson's gazelle"]),
    ("Wildebeest", "Connochaetes taurinus", 4, ["gnu", "blue wildebeest"]),
    ("Eland", "Taurotragus oryx", 2, ["common eland"]),
    ("Greater Kudu", "Tragelaphus strepsiceros", 3, ["kudu"]),
    ("Gemsbok", "Oryx gazella", 2, ["oryx"]),
    ("Saiga Antelope", "Saiga tatarica", 2, ["saiga"]),
    ("Pronghorn", "Antilocapra americana", 3, []),
    ("Red Deer", "Cervus elaphus", 4, ["deer", "stag"]),
    ("Elk", "Cervus canadensis", 4, ["wapiti"]),
    ("Moose", "Alces alces", 5, ["elk (european)"]),
    ("Reindeer", "Rangifer tarandus", 5, ["caribou"]),
    ("White-tailed Deer", "Odocoileus virginianus", 4, []),
    ("Roe Deer", "Capreolus capreolus", 3, []),
    ("Fallow Deer", "Dama dama", 3, []),
    ("Muntjac", "Muntiacus reevesi", 2, ["barking deer"]),

    ("Brown Rat", "Rattus norvegicus", 5, ["rat", "lab rat"]),
    ("Black Rat", "Rattus rattus", 4, []),
    ("House Mouse", "Mus musculus", 5, ["mouse", "lab mouse"]),
    ("Grey Squirrel", "Sciurus carolinensis", 5, ["squirrel", "gray squirrel"]),
    ("Red Squirrel", "Sciurus vulgaris", 4, []),
    ("Chipmunk", "Tamias striatus", 4, ["eastern chipmunk"]),
    ("Prairie Dog", "Cynomys ludovicianus", 4, ["black-tailed prairie dog"]),
    ("Marmot", "Marmota marmota", 3, ["alpine marmot"]),
    ("Groundhog", "Marmota monax", 4, ["woodchuck"]),
    ("Flying Squirrel", "Glaucomys volans", 3, ["southern flying squirrel"]),
    ("North American Beaver", "Castor canadensis", 5, ["beaver"]),
    ("Capybara", "Hydrochoerus hydrochaeris", 5, []),
    ("Guinea Pig", "Cavia porcellus", 5, ["cavy"]),
    ("Chinchilla", "Chinchilla lanigera", 4, []),
    ("Porcupine", "Hystrix cristata", 4, ["crested porcupine"]),
    ("North American Porcupine", "Erethizon dorsatum", 3, []),
    ("Naked Mole-rat", "Heterocephalus glaber", 3, []),
    ("Hamster", "Mesocricetus auratus", 4, ["golden hamster", "syrian hamster"]),
    ("Gerbil", "Meriones unguiculatus", 3, ["mongolian gerbil"]),
    ("Lemming", "Lemmus lemmus", 3, ["norway lemming"]),
    ("Muskrat", "Ondatra zibethicus", 3, []),
    ("Vole", "Microtus agrestis", 2, ["field vole"]),
    ("Dormouse", "Muscardinus avellanarius", 2, ["hazel dormouse"]),
    ("European Rabbit", "Oryctolagus cuniculus", 5, ["rabbit", "bunny"]),
    ("Brown Hare", "Lepus europaeus", 4, ["hare"]),
    ("Arctic Hare", "Lepus arcticus", 3, []),
    ("Pika", "Ochotona princeps", 2, ["american pika"]),

    ("Common Vampire Bat", "Desmodus rotundus", 4, ["vampire bat"]),
    ("Little Brown Bat", "Myotis lucifugus", 3, ["bat"]),
    ("Greater Horseshoe Bat", "Rhinolophus ferrumequinum", 2, ["horseshoe bat"]),
    ("Flying Fox", "Pteropus vampyrus", 4, ["fruit bat", "large flying fox"]),
    ("European Hedgehog", "Erinaceus europaeus", 4, ["hedgehog"]),
    ("European Mole", "Talpa europaea", 3, ["mole"]),
    ("Star-nosed Mole", "Condylura cristata", 3, []),
    ("Common Shrew", "Sorex araneus", 3, ["shrew"]),
    ("Nine-banded Armadillo", "Dasypus novemcinctus", 4, ["armadillo"]),
    ("Giant Anteater", "Myrmecophaga tridactyla", 4, ["anteater"]),
    ("Three-toed Sloth", "Bradypus variegatus", 5, ["sloth"]),
    ("Two-toed Sloth", "Choloepus didactylus", 3, []),
    ("Pangolin", "Manis pentadactyla", 4, ["chinese pangolin", "scaly anteater"]),

    ("Red Kangaroo", "Osphranter rufus", 5, ["kangaroo"]),
    ("Eastern Grey Kangaroo", "Macropus giganteus", 3, []),
    ("Wallaby", "Notamacropus rufogriseus", 4, ["red-necked wallaby"]),
    ("Koala", "Phascolarctos cinereus", 5, []),
    ("Common Wombat", "Vombatus ursinus", 4, ["wombat"]),
    ("Tasmanian Devil", "Sarcophilus harrisii", 4, []),
    ("Quokka", "Setonix brachyurus", 4, []),
    ("Sugar Glider", "Petaurus breviceps", 3, []),
    ("Virginia Opossum", "Didelphis virginiana", 4, ["opossum", "possum"]),
    ("Bilby", "Macrotis lagotis", 2, []),
    ("Platypus", "Ornithorhynchus anatinus", 5, ["duck-billed platypus"]),
    ("Short-beaked Echidna", "Tachyglossus aculeatus", 4, ["echidna", "spiny anteater"]),
])

# ── BIRDS ──────────────────────────────────────────────────────────────────
g([
    ("Chicken", "Gallus gallus", 5, ["hen", "rooster", "red junglefowl"]),
    ("Turkey", "Meleagris gallopavo", 5, ["wild turkey"]),
    ("Indian Peafowl", "Pavo cristatus", 5, ["peacock", "peahen"]),
    ("Common Pheasant", "Phasianus colchicus", 4, ["pheasant"]),
    ("Common Quail", "Coturnix coturnix", 3, ["quail"]),
    ("Grey Partridge", "Perdix perdix", 2, ["partridge"]),
    ("Mallard", "Anas platyrhynchos", 5, ["duck", "wild duck"]),
    ("Mute Swan", "Cygnus olor", 5, ["swan"]),
    ("Canada Goose", "Branta canadensis", 5, ["goose"]),
    ("Greylag Goose", "Anser anser", 3, []),
    ("Common Eider", "Somateria mollissima", 2, ["eider"]),
    ("Ostrich", "Struthio camelus", 5, ["common ostrich"]),
    ("Emu", "Dromaius novaehollandiae", 5, []),
    ("Southern Cassowary", "Casuarius casuarius", 4, ["cassowary"]),
    ("Kiwi", "Apteryx australis", 4, ["southern brown kiwi"]),
    ("Greater Rhea", "Rhea americana", 3, ["rhea"]),
    ("Emperor Penguin", "Aptenodytes forsteri", 5, ["penguin"]),
    ("King Penguin", "Aptenodytes patagonicus", 4, []),
    ("Adelie Penguin", "Pygoscelis adeliae", 3, []),
    ("Little Penguin", "Eudyptula minor", 3, ["fairy penguin"]),
    ("Galapagos Penguin", "Spheniscus mendiculus", 2, []),

    ("Bald Eagle", "Haliaeetus leucocephalus", 5, ["eagle"]),
    ("Golden Eagle", "Aquila chrysaetos", 4, []),
    ("Harpy Eagle", "Harpia harpyja", 3, []),
    ("Peregrine Falcon", "Falco peregrinus", 5, ["falcon", "peregrine"]),
    ("Common Kestrel", "Falco tinnunculus", 3, ["kestrel"]),
    ("Osprey", "Pandion haliaetus", 4, []),
    ("Red Kite", "Milvus milvus", 3, ["kite"]),
    ("Common Buzzard", "Buteo buteo", 3, ["buzzard"]),
    ("Red-tailed Hawk", "Buteo jamaicensis", 4, ["hawk"]),
    ("Northern Goshawk", "Accipiter gentilis", 3, ["goshawk"]),
    ("Andean Condor", "Vultur gryphus", 4, ["condor"]),
    ("California Condor", "Gymnogyps californianus", 3, []),
    ("Turkey Vulture", "Cathartes aura", 3, ["vulture"]),
    ("Griffon Vulture", "Gyps fulvus", 3, []),
    ("Secretarybird", "Sagittarius serpentarius", 3, []),
    ("Barn Owl", "Tyto alba", 5, ["owl"]),
    ("Snowy Owl", "Bubo scandiacus", 5, []),
    ("Eurasian Eagle-owl", "Bubo bubo", 3, ["eagle owl"]),
    ("Tawny Owl", "Strix aluco", 3, []),
    ("Great Horned Owl", "Bubo virginianus", 4, []),
    ("Burrowing Owl", "Athene cunicularia", 3, []),

    ("Rock Dove", "Columba livia", 5, ["pigeon", "rock pigeon"]),
    ("Wood Pigeon", "Columba palumbus", 3, []),
    ("Mourning Dove", "Zenaida macroura", 3, ["dove"]),
    ("Dodo", "Raphus cucullatus", 5, []),
    ("Budgerigar", "Melopsittacus undulatus", 4, ["budgie", "parakeet"]),
    ("African Grey Parrot", "Psittacus erithacus", 4, ["african gray parrot"]),
    ("Scarlet Macaw", "Ara macao", 4, ["macaw", "parrot"]),
    ("Blue-and-yellow Macaw", "Ara ararauna", 3, []),
    ("Cockatiel", "Nymphicus hollandicus", 4, []),
    ("Sulphur-crested Cockatoo", "Cacatua galerita", 4, ["cockatoo"]),
    ("Kea", "Nestor notabilis", 3, []),
    ("Kakapo", "Strigops habroptilus", 3, []),
    ("Lovebird", "Agapornis roseicollis", 2, ["rosy-faced lovebird"]),

    ("American Robin", "Turdus migratorius", 4, []),
    ("European Robin", "Erithacus rubecula", 4, ["robin"]),
    ("Common Blackbird", "Turdus merula", 4, ["blackbird"]),
    ("Song Thrush", "Turdus philomelos", 3, ["thrush"]),
    ("House Sparrow", "Passer domesticus", 5, ["sparrow"]),
    ("Common Starling", "Sturnus vulgaris", 4, ["starling"]),
    ("Barn Swallow", "Hirundo rustica", 4, ["swallow"]),
    ("Common Swift", "Apus apus", 3, ["swift"]),
    ("Blue Tit", "Cyanistes caeruleus", 3, []),
    ("Great Tit", "Parus major", 3, []),
    ("Northern Cardinal", "Cardinalis cardinalis", 4, ["cardinal"]),
    ("Blue Jay", "Cyanocitta cristata", 4, ["jay"]),
    ("Common Raven", "Corvus corax", 5, ["raven"]),
    ("Carrion Crow", "Corvus corone", 4, ["crow"]),
    ("American Crow", "Corvus brachyrhynchos", 4, []),
    ("Eurasian Magpie", "Pica pica", 4, ["magpie"]),
    ("Eurasian Jackdaw", "Corvus monedula", 3, ["jackdaw"]),
    ("Goldfinch", "Carduelis carduelis", 3, ["european goldfinch"]),
    ("Common Chaffinch", "Fringilla coelebs", 3, ["chaffinch"]),
    ("Canary", "Serinus canaria", 4, ["atlantic canary"]),
    ("Zebra Finch", "Taeniopygia guttata", 3, []),
    ("Darwin's Finch", "Geospiza fortis", 3, ["medium ground finch"]),
    ("Bird-of-paradise", "Paradisaea apoda", 3, ["greater bird-of-paradise"]),
    ("Lyrebird", "Menura novaehollandiae", 3, ["superb lyrebird"]),
    ("Northern Mockingbird", "Mimus polyglottos", 3, ["mockingbird"]),
    ("Common Nightingale", "Luscinia megarhynchos", 4, ["nightingale"]),
    ("Common Cuckoo", "Cuculus canorus", 4, ["cuckoo"]),
    ("Greater Roadrunner", "Geococcyx californianus", 4, ["roadrunner"]),
    ("Ruby-throated Hummingbird", "Archilochus colubris", 4, ["hummingbird"]),
    ("Bee Hummingbird", "Mellisuga helenae", 3, []),
    ("Belted Kingfisher", "Megaceryle alcyon", 2, []),
    ("Common Kingfisher", "Alcedo atthis", 4, ["kingfisher"]),
    ("Toco Toucan", "Ramphastos toco", 4, ["toucan"]),
    ("Great Hornbill", "Buceros bicornis", 3, ["hornbill"]),
    ("Hoopoe", "Upupa epops", 3, []),
    ("Great Spotted Woodpecker", "Dendrocopos major", 3, ["woodpecker"]),
    ("Pileated Woodpecker", "Dryocopus pileatus", 3, []),
    ("Woodpecker Finch", "Camarhynchus pallidus", 1, []),

    ("Greater Flamingo", "Phoenicopterus roseus", 5, ["flamingo"]),
    ("Grey Heron", "Ardea cinerea", 3, ["heron"]),
    ("Great Blue Heron", "Ardea herodias", 3, []),
    ("Great Egret", "Ardea alba", 3, ["egret"]),
    ("White Stork", "Ciconia ciconia", 4, ["stork"]),
    ("Marabou Stork", "Leptoptilos crumenifer", 2, []),
    ("Shoebill", "Balaeniceps rex", 4, []),
    ("Roseate Spoonbill", "Platalea ajaja", 3, ["spoonbill"]),
    ("Sacred Ibis", "Threskiornis aethiopicus", 3, ["ibis"]),
    ("Common Crane", "Grus grus", 3, ["crane"]),
    ("Sandhill Crane", "Antigone canadensis", 3, []),
    ("Great Cormorant", "Phalacrocorax carbo", 3, ["cormorant"]),
    ("Brown Pelican", "Pelecanus occidentalis", 4, ["pelican"]),
    ("Northern Gannet", "Morus bassanus", 3, ["gannet"]),
    ("Atlantic Puffin", "Fratercula arctica", 5, ["puffin"]),
    ("Herring Gull", "Larus argentatus", 4, ["seagull", "gull"]),
    ("Arctic Tern", "Sterna paradisaea", 4, ["tern"]),
    ("Wandering Albatross", "Diomedea exulans", 4, ["albatross"]),
    ("Frigatebird", "Fregata magnificens", 3, ["magnificent frigatebird"]),
    ("Blue-footed Booby", "Sula nebouxii", 4, ["booby"]),
    ("Great Auk", "Pinguinus impennis", 3, []),
    ("Eurasian Oystercatcher", "Haematopus ostralegus", 2, ["oystercatcher"]),
    ("Northern Lapwing", "Vanellus vanellus", 2, ["lapwing"]),
    ("Eurasian Curlew", "Numenius arquata", 2, ["curlew"]),
    ("Common Snipe", "Gallinago gallinago", 2, ["snipe"]),
    ("Eurasian Coot", "Fulica atra", 2, ["coot"]),
    ("Great Crested Grebe", "Podiceps cristatus", 2, ["grebe"]),
    ("Common Loon", "Gavia immer", 3, ["great northern diver", "loon"]),
    ("Whooper Swan", "Cygnus cygnus", 2, []),
])

# ── REPTILES ───────────────────────────────────────────────────────────────
g([
    ("Nile Crocodile", "Crocodylus niloticus", 5, ["crocodile"]),
    ("Saltwater Crocodile", "Crocodylus porosus", 4, []),
    ("American Alligator", "Alligator mississippiensis", 5, ["alligator", "gator"]),
    ("Chinese Alligator", "Alligator sinensis", 2, []),
    ("Gharial", "Gavialis gangeticus", 3, []),
    ("Spectacled Caiman", "Caiman crocodilus", 3, ["caiman"]),

    ("King Cobra", "Ophiophagus hannah", 5, []),
    ("Indian Cobra", "Naja naja", 4, ["cobra", "spectacled cobra"]),
    ("Black Mamba", "Dendroaspis polylepis", 5, ["mamba"]),
    ("Inland Taipan", "Oxyuranus microlepidotus", 3, ["taipan"]),
    ("Eastern Diamondback Rattlesnake", "Crotalus adamanteus", 4, ["rattlesnake"]),
    ("Western Diamondback Rattlesnake", "Crotalus atrox", 4, []),
    ("Sidewinder", "Crotalus cerastes", 3, []),
    ("Copperhead", "Agkistrodon contortrix", 3, []),
    ("Adder", "Vipera berus", 3, ["common european adder"]),
    ("Gaboon Viper", "Bitis gabonica", 3, []),
    ("Bushmaster", "Lachesis muta", 2, []),
    ("Reticulated Python", "Malayopython reticulatus", 4, ["python"]),
    ("Burmese Python", "Python bivittatus", 4, []),
    ("Ball Python", "Python regius", 4, ["royal python"]),
    ("Green Anaconda", "Eunectes murinus", 5, ["anaconda"]),
    ("Boa Constrictor", "Boa constrictor", 5, ["boa"]),
    ("Corn Snake", "Pantherophis guttatus", 3, []),
    ("Grass Snake", "Natrix natrix", 3, []),
    ("Garter Snake", "Thamnophis sirtalis", 3, ["common garter snake"]),
    ("Sea Krait", "Laticauda colubrina", 2, ["banded sea krait"]),

    ("Komodo Dragon", "Varanus komodoensis", 5, []),
    ("Nile Monitor", "Varanus niloticus", 2, ["monitor lizard"]),
    ("Green Iguana", "Iguana iguana", 5, ["iguana"]),
    ("Marine Iguana", "Amblyrhynchus cristatus", 4, []),
    ("Veiled Chameleon", "Chamaeleo calyptratus", 4, ["chameleon"]),
    ("Panther Chameleon", "Furcifer pardalis", 3, []),
    ("Tokay Gecko", "Gekko gecko", 3, ["gecko"]),
    ("Leopard Gecko", "Eublepharis macularius", 4, []),
    ("Common House Gecko", "Hemidactylus frenatus", 2, []),
    ("Bearded Dragon", "Pogona vitticeps", 4, []),
    ("Frilled Lizard", "Chlamydosaurus kingii", 4, ["frilled-neck lizard"]),
    ("Gila Monster", "Heloderma suspectum", 4, []),
    ("Basilisk Lizard", "Basiliscus plumifrons", 3, ["jesus christ lizard"]),
    ("Thorny Devil", "Moloch horridus", 3, []),
    ("Slow Worm", "Anguis fragilis", 2, []),
    ("Common Wall Lizard", "Podarcis muralis", 2, ["wall lizard"]),
    ("Tuatara", "Sphenodon punctatus", 3, []),

    ("Galapagos Tortoise", "Chelonoidis niger", 5, ["giant tortoise"]),
    ("Aldabra Giant Tortoise", "Aldabrachelys gigantea", 3, []),
    ("Leopard Tortoise", "Stigmochelys pardalis", 2, ["tortoise"]),
    ("Green Sea Turtle", "Chelonia mydas", 5, ["sea turtle", "turtle"]),
    ("Loggerhead Sea Turtle", "Caretta caretta", 4, ["loggerhead"]),
    ("Leatherback Sea Turtle", "Dermochelys coriacea", 4, ["leatherback"]),
    ("Hawksbill Sea Turtle", "Eretmochelys imbricata", 3, ["hawksbill"]),
    ("Red-eared Slider", "Trachemys scripta", 3, ["pond slider"]),
    ("Common Snapping Turtle", "Chelydra serpentina", 3, ["snapping turtle"]),
    ("Alligator Snapping Turtle", "Macrochelys temminckii", 3, []),
])

# ── AMPHIBIANS ─────────────────────────────────────────────────────────────
g([
    ("Common Frog", "Rana temporaria", 4, ["frog"]),
    ("American Bullfrog", "Lithobates catesbeianus", 4, ["bullfrog"]),
    ("African Clawed Frog", "Xenopus laevis", 3, ["xenopus"]),
    ("Poison Dart Frog", "Dendrobates tinctorius", 4, ["dyeing poison dart frog"]),
    ("Golden Poison Frog", "Phyllobates terribilis", 3, []),
    ("Red-eyed Tree Frog", "Agalychnis callidryas", 4, ["tree frog"]),
    ("Goliath Frog", "Conraua goliath", 3, []),
    ("Wood Frog", "Lithobates sylvaticus", 2, []),
    ("Glass Frog", "Hyalinobatrachium valerioi", 2, []),
    ("Common Toad", "Bufo bufo", 4, ["toad"]),
    ("Cane Toad", "Rhinella marina", 4, []),
    ("American Toad", "Anaxyrus americanus", 2, []),
    ("Fire Salamander", "Salamandra salamandra", 4, ["salamander"]),
    ("Axolotl", "Ambystoma mexicanum", 5, []),
    ("Tiger Salamander", "Ambystoma tigrinum", 3, []),
    ("Chinese Giant Salamander", "Andrias davidianus", 3, ["giant salamander"]),
    ("Hellbender", "Cryptobranchus alleganiensis", 3, []),
    ("Olm", "Proteus anguinus", 3, []),
    ("Smooth Newt", "Lissotriton vulgaris", 2, ["newt"]),
    ("Eastern Newt", "Notophthalmus viridescens", 2, []),
    ("Great Crested Newt", "Triturus cristatus", 2, []),
    ("Caecilian", "Ichthyophis glutinosus", 2, []),
    ("Surinam Toad", "Pipa pipa", 2, []),
])
