#!/usr/bin/env python3
# =============================================================================
# SEMANTIC WING · STEP 6 — ship the HUMAN half of the link rule to the browser.
#
# sem_linkgraph.py documents the rule LINXICON is judged against:
#     u–v is a link  IFF  a human in SWOW answered one with the other
#                         (association count >= 2)
#                   OR    cos(u, v) >= TAU.
# The cosine half is answerable in the browser from AD_SEM (the quantised
# vectors) for ANY pair. The human half is not derivable from anything — it is
# data about what people said — so it has to ship too, or the runtime check
# would silently be "cosine only", which is not the rule.
#
# ENCODING. Canonicalise every association edge to (min,max), dedupe (SWOW is
# directed, the link rule is not), pack as key = min*N + max, sort, delta, LEB128
# varint, base64. Sorted deltas over ~90k keys spread across N^2 average ~1.5k,
# so nearly every delta is a 2-byte varint: the whole human association graph
# lands in a quarter of a megabyte, and the browser rebuilds it as one sorted
# Int32Array it can binary-search. No Set, no object churn, no GC pressure.
#
# Output: core/data/semlinks.js   -> window.AD_SEMLINKS
#         _build/sem/semlinks_report.txt
# =============================================================================
import base64
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SEM = os.path.join(HERE, "sem")
OUT = os.path.join(ROOT, "core", "data", "semlinks.js")
MINCOUNT = 2          # exactly the threshold sem_assoc.py / sem_linkgraph.py use
CHUNK = 270000        # base64 chars per string literal; keeps every file < 300 KB


def varint(n, buf):
    while n >= 0x80:
        buf.append((n & 0x7F) | 0x80)
        n >>= 7
    buf.append(n)


def main():
    vocab = open(os.path.join(SEM, "ship_vocab.txt"), encoding="utf-8").read().split()
    n = len(vocab)
    tau = float(open(os.path.join(SEM, "tau.txt")).read().strip())

    pairs = set()
    rows = 0
    with open(os.path.join(SEM, "assoc.tsv"), encoding="utf-8") as f:
        for line in f:
            a, b, c = line.split()
            a, b, c = int(a), int(b), int(c)
            rows += 1
            if c < MINCOUNT or a == b:
                continue
            pairs.add((a * n + b) if a < b else (b * n + a))

    keys = sorted(pairs)
    buf = bytearray()
    prev = 0
    for k in keys:
        varint(k - prev, buf)
        prev = k
    b64 = base64.b64encode(bytes(buf)).decode("ascii")

    parts = [b64[i:i + CHUNK] for i in range(0, len(b64), CHUNK)]
    # Every chunk must be a whole number of base64 quanta so it decodes alone.
    assert all(len(p) % 4 == 0 for p in parts[:-1]), "chunk not 4-aligned"

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("/* ===========================================================================\n"
                "   AD_SEMLINKS — the human half of the LINXICON link rule.\n"
                "   Source: Small World of Words English association norms (De Deyne, Navarro,\n"
                "     Perfors, Brysbaert & Storms 2019), via _build/sem_assoc.py.\n"
                "   An edge means: at least %d people answered one of these words with the\n"
                "   other. Undirected, deduped. Generated by _build/sem_pack_links.py.\n"
                "   key = min(u,v) * n + max(u,v), ids into AD_SEM.words; deltas, LEB128\n"
                "   varints, base64. Decode to a sorted Int32Array and binary-search it.\n"
                "   The other half of the rule is cos(u,v) >= tau, answered from AD_SEM.\n"
                "   =========================================================================== */\n"
                % MINCOUNT)
        f.write("window.AD_SEMLINKS = { n: %d, count: %d, tau: %.6f, bytes: %d, parts: [\n"
                % (n, len(keys), tau, len(buf)))
        for p in parts:
            f.write('"' + p + '",\n')
        f.write("] };\n")

    size = os.path.getsize(OUT)
    rep = ["assoc rows read            : %d" % rows,
           "undirected edges kept      : %d" % len(keys),
           "packed bytes               : %d" % len(buf),
           "base64 chars               : %d" % len(b64),
           "string literals            : %d" % len(parts),
           "semlinks.js bytes          : %d" % size,
           "mean bytes per edge        : %.2f" % (len(buf) / max(1, len(keys))),
           "tau carried through        : %.6f" % tau]
    txt = "\n".join(rep) + "\n"
    open(os.path.join(SEM, "semlinks_report.txt"), "w").write(txt)
    sys.stdout.write(txt)


if __name__ == "__main__":
    main()
