/* t_all.js — the cabinet smoke sweep. Run from the repo root:
     JSC=/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Helpers/jsc
     $JSC _build/harness.js -e 'load("_build/t_all.js")'

   WHY THIS EXISTS. THE DECIDER shipped broken for days without anyone noticing:
   core/data/trivia.js switched from verbose objects to packed rows, the reader
   was never updated, and the cabinet hit its own "the bank didn't load" guard
   and returned from its IIFE. No crash, no console error — just a polite error
   card where the game should be. Every cabinet has guards like that, and every
   cabinet's data is generated by a script that can drift away from it.

   So: for each cabinet, parse its REAL index.html, load exactly the scripts
   that page loads in the order it loads them, boot, and check four things:

     · the debug hook exists — missing means the module bailed out early, which
       is precisely the failure that is invisible from the outside;
     · nothing was written to console.error on the way up;
     · the page has readable text on it, not a blank <body>;
     · there is a main region for the shared chrome to hang off.

   The last three came from _build/t_smoke.js, an orphan that read a global
   `GAME` nobody set and so threw on line 6 for anything that just loaded it.
   Its checks were worth keeping and this sweep already pays the cost of booting
   every cabinet, so they moved here and the file went.

   This proves the cabinet BOOTS. It does not prove the game is any good.      */

var HOOKS = {
  atlas: "__AT", boxed: "__BX", chrono: "__CH", cluedrop: "__CD",
  connectrade: "__CT", decider: "__DC", flagle: "__FL", foodguessr: "__FG",
  geogrid: "__GG", globle: "__GL", lingua: "__LG", linxicon: "__LX",
  midi: "__MD", mini: "__MN", misaligned: "__MI", outline: "__OL",
  phylo: "__PH", pick5: "__P5",
  placeguessr: "__PG", quartets: "__QT", thirdle: "__TH", timeguessr: "__TG",
  tradle: "__TR", wordish: "__WD",
};

var ids = Object.keys(HOOKS).sort();
var broke = [];

ids.forEach(function (id) {
  H.reset();
  delete globalThis[HOOKS[id]];
  var errs = 0;
  var realError = console.error;
  console.error = function () { errs++; realError.apply(console, arguments); };

  var why = null;
  try {
    H.html("games/" + id + "/index.html");
    // Load exactly what the page loads, in page order. "../../core/x.js?v=12"
    // is repo-relative once the query and the climb are stripped.
    H.scripts.forEach(function (src) {
      var p = src.replace(/\?.*$/, "");
      p = p.indexOf("../../") === 0 ? p.slice(6) : "games/" + id + "/" + p;
      load(p);
    });
    H.boot();
  } catch (e) {
    why = String(e && e.message || e);
  }
  console.error = realError;

  var bad = [];
  if (typeof globalThis[HOOKS[id]] !== "object") {
    bad.push(why ? "THREW: " + why : "bailed out silently (no " + HOOKS[id] + ")");
  } else if (why) {
    bad.push("THREW after the hook was set: " + why);
  }
  if (errs) bad.push(errs + " console error" + (errs === 1 ? "" : "s") + " during boot");
  // Every cabinet renders well clear of this: the quietest opening screen is
  // OUTLINE at 41 characters, so 30 catches a blank page without being a
  // tripwire for a deliberately spare one.
  var seen = H.visible().join(" ").replace(/\s+/g, "");
  if (seen.length < 30) bad.push("page nearly empty after boot (“" + seen.slice(0, 60) + "”)");
  if (!H.maybe("main") && !H.maybe(".ac-main") && !H.maybe("#app")) bad.push("no main region");

  if (bad.length) broke.push(id + " — " + bad.join("; "));
  H.ok(!bad.length, id + (bad.length ? "  " + bad.join("; ") : ""));
});

H.section("summary");
if (broke.length) {
  print("  cabinets that do not come up clean:");
  broke.forEach(function (b) { print("    " + b); });
} else {
  print("  all " + ids.length + " cabinets boot clean");
}

H.done();
