/* t_all.js — the cabinet smoke sweep. Run from the repo root:
     JSC=/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Helpers/jsc
     $JSC _build/harness.js -e 'load("_build/t_all.js")'

   WHY THIS EXISTS. THE DECIDER shipped broken for days without anyone noticing:
   core/data/trivia.js switched from verbose objects to packed rows, the reader
   was never updated, and the cabinet hit its own "the bank didn't load" guard
   and returned from its IIFE. No crash, no console error — just a polite error
   card where the game should be. Every cabinet has guards like that, and every
   cabinet's data is generated by a script that can drift away from it.

   So: for each cabinet, parse its REAL index.html, load exactly the scripts
   that page loads in the order it loads them, boot, and check the debug hook
   exists. A hook that is missing means the module bailed out early — which is
   precisely the failure that is invisible from the outside.

   This proves the cabinet BOOTS. It does not prove the game is any good.      */

var HOOKS = {
  atlas: "__AT", boxed: "__BX", chrono: "__CH", cluedrop: "__CD",
  connectrade: "__CT", decider: "__DC", flagle: "__FL", foodguessr: "__FG",
  geogrid: "__GG", globle: "__GL", lingua: "__LG", linxicon: "__LX",
  midi: "__MD", mini: "__MN", outline: "__OL", phylo: "__PH", pick5: "__P5",
  placeguessr: "__PG", quartets: "__QT", thirdle: "__TH", timeguessr: "__TG",
  tradle: "__TR", wordish: "__WD",
};

var ids = Object.keys(HOOKS).sort();
var broke = [];

ids.forEach(function (id) {
  H.reset();
  delete globalThis[HOOKS[id]];
  var errs = 0;
  var realError = console.error;
  console.error = function () { errs++; realError.apply(console, arguments); };

  var why = null;
  try {
    H.html("games/" + id + "/index.html");
    // Load exactly what the page loads, in page order. "../../core/x.js?v=12"
    // is repo-relative once the query and the climb are stripped.
    H.scripts.forEach(function (src) {
      var p = src.replace(/\?.*$/, "");
      p = p.indexOf("../../") === 0 ? p.slice(6) : "games/" + id + "/" + p;
      load(p);
    });
    H.boot();
  } catch (e) {
    why = String(e && e.message || e);
  }
  console.error = realError;

  var up = typeof globalThis[HOOKS[id]] === "object";
  if (!up) broke.push(id + (why ? " — threw: " + why : " — bailed out silently"));
  H.ok(up, id + (why ? "  THREW: " + why : "") +
           (errs ? "  (" + errs + " console errors)" : ""));
});

H.section("summary");
if (broke.length) {
  print("  cabinets that do not boot:");
  broke.forEach(function (b) { print("    " + b); });
} else {
  print("  all " + ids.length + " cabinets boot");
}

H.done();
