# -*- coding: utf-8 -*-
"""
trivia_bank.py -- the hand-authored question bank behind THE DECIDER.

RULES I HELD MYSELF TO WHILE WRITING THIS
  * Every answer is a settled fact that a reference work would agree with and
    that was still true in January 2026. No incumbents, no current champions,
    no "biggest company", no populations, no live records -- anything whose
    answer moves was left out rather than guessed.
  * The three wrong options are plausible (same kind of thing, same register)
    but unambiguously wrong. No "all of the above", no near-synonyms of the
    answer, no two options that could both be defended.
  * `note` is the payoff line shown after the reveal -- one sentence, the thing
    you actually want to know. It never just restates the answer.
  * diff 1 = nearly everyone; 2 = easy for a strong player; 3 = solid pub-quiz
    middle; 4 = they will miss some of these; 5 = genuinely hard.
  * Where a fact is disputed or version-dependent, it is NOT here.

Edit this file, then run  python3 _build/gen_trivia.py
"""

CATS = {
    "general": {"label": "GENERAL KNOWLEDGE", "icon": "\U0001F3B2"},
    "geo":     {"label": "GEOGRAPHY",         "icon": "\U0001F30D"},
    "history": {"label": "HISTORY",           "icon": "\U0001F3DB"},
    "science": {"label": "SCIENCE",           "icon": "\U0001F9EA"},
    "film":    {"label": "FILM & TV",         "icon": "\U0001F3AC"},
    "music":   {"label": "MUSIC",             "icon": "\U0001F3B5"},
    "lit":     {"label": "LITERATURE",        "icon": "\U0001F4D6"},
    "food":    {"label": "FOOD & DRINK",      "icon": "\U0001F372"},
    "sport":   {"label": "SPORT",             "icon": "⚽"},
    "ai":      {"label": "AI & TECH",         "icon": "\U0001F916"},
    "art":     {"label": "ART",               "icon": "\U0001F3A8"},
    "words":   {"label": "LANGUAGE & WORDS",  "icon": "\U0001F524"},
    "persia":  {"label": "IRAN & PERSIA",     "icon": "\U0001F1EE\U0001F1F7"},
    "jewish":  {"label": "JEWISH LIFE",       "icon": "✡"},
    "cities":  {"label": "THEIR FOUR CITIES", "icon": "\U0001F5FA"},
}


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "wrong": (w1, w2, w3), "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = []

# ══ GENERAL KNOWLEDGE ══════════════════════════════════════════════════════
BANK += [
    Q("general", 1, "How many squares are there on a standard chessboard?",
      "64", "32", "81", "100",
      "Eight by eight. The 32 is the number of squares of each colour."),
    Q("general", 1, "Which zodiac sign is represented by a pair of scales?",
      "Libra", "Aries", "Virgo", "Capricorn",
      "The only zodiac sign symbolised by an object rather than a creature."),
    Q("general", 1, "Which colour appears at the top of a rainbow?",
      "Red", "Violet", "Blue", "Green",
      "Red is refracted least, so it sits on the outer, upper edge of the arc."),
    Q("general", 1, "In the Greek alphabet, which letter comes last?",
      "Omega", "Alpha", "Sigma", "Psi",
      "Hence 'the alpha and the omega' -- the first and the last."),
    Q("general", 1, "What is the currency of Japan?",
      "Yen", "Won", "Yuan", "Ringgit",
      "The won is Korean, the yuan Chinese, the ringgit Malaysian."),
    Q("general", 2, "Which Roman numeral represents 50?",
      "L", "C", "D", "X",
      "C is 100, D is 500, X is 10."),
    Q("general", 2, "In the Chinese zodiac, which animal starts the twelve-year cycle?",
      "Rat", "Ox", "Dragon", "Tiger",
      "The rat is said to have hitched a ride on the ox and jumped off first."),
    Q("general", 2, "Vexillology is the study of what?",
      "Flags", "Coins", "Stamps", "Caves",
      "From the Latin 'vexillum', a Roman military standard."),
    Q("general", 2, "How many points does a snooker ball score if it is the black?",
      "7", "6", "8", "5",
      "Yellow 2, green 3, brown 4, blue 5, pink 6, black 7."),
    Q("general", 2, "What does the abbreviation 'e.g.' stand for?",
      "Exempli gratia", "Ergo gratia", "Exempli generalis", "Et grata",
      "Latin for 'for the sake of example' -- unlike 'i.e.', id est, 'that is'."),
    Q("general", 3, "What is the collective noun for a group of crows?",
      "A murder", "A parliament", "A murmuration", "A charm",
      "A parliament is owls, a murmuration starlings, a charm goldfinches."),
    Q("general", 3, "Numismatics is the collecting and study of what?",
      "Coins", "Stamps", "Postcards", "Maps",
      "Stamp collecting is philately -- a word coined in 1864 from Greek."),
    Q("general", 3, "Which is the only letter of the alphabet that appears in no US state name?",
      "Q", "Z", "X", "J",
      "Z is in Arizona, X in Texas, J in New Jersey. Q is nowhere."),
    Q("general", 3, "In heraldry, which colour is 'gules'?",
      "Red", "Blue", "Green", "Black",
      "Azure is blue, vert green, sable black, or gold and argent silver."),
    Q("general", 3, "How many dots are there in total on a pair of standard six-sided dice?",
      "42", "36", "48", "21",
      "Each die carries 21 pips, because 1+2+3+4+5+6 = 21."),
    Q("general", 3, "How many hearts does an octopus have?",
      "Three", "One", "Two", "Eight",
      "Two pump blood through the gills, one through the rest of the body."),
    Q("general", 4, "What is the name of the dot over a lower-case 'i'?",
      "A tittle", "A serif", "A cedilla", "A macron",
      "Hence 'to a T' -- originally 'to a tittle', meaning to the last detail."),
    Q("general", 4, "In Norse myth, what is the name of Odin's eight-legged horse?",
      "Sleipnir", "Fenrir", "Gungnir", "Draupnir",
      "Fenrir is the wolf, Gungnir the spear, Draupnir the ring."),
    Q("general", 4, "Which two metals are alloyed to make bronze?",
      "Copper and tin", "Copper and zinc", "Iron and carbon", "Tin and lead",
      "Copper and zinc gives brass; iron and carbon gives steel."),
    Q("general", 4, "What is the plastic or metal sheath on the end of a shoelace called?",
      "An aglet", "A ferrule", "A grommet", "A chape",
      "A ferrule is the metal band on a tool handle; a grommet is an eyelet."),
    Q("general", 4, "A 'baker's dozen' is thirteen. What was the practice originally meant to avoid?",
      "Penalties for selling underweight bread", "Wasting a spare loaf",
      "Paying tax on the twelfth", "Splitting a dozen between two customers",
      "Medieval English law punished short-weight loaves harshly, so bakers added one."),
    Q("general", 5, "In bell-ringing, what is a 'peal' required to exceed?",
      "5,000 changes", "1,000 changes", "500 changes", "10,000 changes",
      "A full peal is at least 5,000 changes and takes roughly three hours."),
    Q("general", 5, "What is the term for the study of the shapes and origins of place names?",
      "Toponymy", "Onomastics", "Etymology", "Cartology",
      "Onomastics is names in general; toponymy is the branch about places."),
    Q("general", 5, "Which SI base unit is defined using the caesium-133 atom?",
      "The second", "The metre", "The kelvin", "The mole",
      "9,192,631,770 oscillations of that transition define one second."),
    Q("general", 2, "What is the largest planet in the Solar System?",
      "Jupiter", "Saturn", "Neptune", "Uranus",
      "Jupiter has more than twice the mass of every other planet combined."),
    Q("general", 3, "Which family of birds can hover in place and fly deliberately backwards?",
      "Hummingbirds", "Kingfishers", "Swifts", "Wrens",
      "A figure-of-eight wing stroke generates lift on both the forward and back sweep."),
    Q("general", 2, "In a standard deck of cards, which suit is ranked highest in bridge?",
      "Spades", "Hearts", "Diamonds", "Clubs",
      "Bridge ranks the suits clubs, diamonds, hearts, spades -- spades top."),
    Q("general", 3, "What is the name for a word or phrase that means the opposite of itself, such as 'cleave'?",
      "A contronym", "A homonym", "An antonym", "A metonym",
      "'Cleave' means both to split apart and to cling to."),
    Q("general", 4, "How many keys does a standard modern grand piano have?",
      "88", "84", "92", "76",
      "Fifty-two white and thirty-six black, spanning A0 to C8."),
    Q("general", 5, "A 'lustrum' in Roman reckoning was a period of how long?",
      "Five years", "Ten years", "Three years", "A hundred years",
      "It marked the census and its purification rite, held every five years."),
    Q("general", 3, "Which planet is closest in size to Earth?",
      "Venus", "Mars", "Mercury", "Neptune",
      "Venus has about 95% of Earth's diameter; Mars only about 53%."),
    Q("general", 2, "How many time zones does the contiguous United States use?",
      "Four", "Three", "Five", "Six",
      "Eastern, Central, Mountain and Pacific; Alaska and Hawaii add more."),
    Q("general", 4, "Which of these is a genuine typographic name for the '#' symbol?",
      "Octothorpe", "Obelisk", "Pilcrow", "Interpunct",
      "A pilcrow is the paragraph mark, an obelisk the dagger, an interpunct the mid-dot."),
    Q("general", 5, "In falconry, what is a young bird taken from the nest for training called?",
      "An eyas", "A haggard", "A passager", "A tiercel",
      "A haggard is caught as an adult; a tiercel is a male peregrine."),
    Q("general", 1, "What does a sommelier specialise in?",
      "Wine", "Cheese", "Tea", "Bread",
      "From Old French for the court official who handled provisions and pack animals."),
    Q("general", 1, "How many minutes are there in a full day?",
      "1,440", "1,200", "1,240", "1,800",
      "Twenty-four hours of sixty minutes each."),
    Q("general", 3, "Which of these is the only US state whose name begins with two vowels?",
      "Iowa", "Ohio", "Utah", "Oregon",
      "Ohio, Utah and Oregon all start with a single vowel; Iowa opens with I and o."),
    Q("general", 4, "The Nobel Prizes are awarded in Stockholm, except for one. Which?",
      "The Peace Prize", "The Prize in Literature", "The Prize in Physics", "The Prize in Economics",
      "Nobel's will sent the Peace Prize to Oslo; nobody is quite sure why."),
    Q("general", 2, "What is the imaginary line at 0 degrees longitude called?",
      "The Prime Meridian", "The Equator", "The Tropic of Cancer", "The International Date Line",
      "Fixed at Greenwich by an international conference in 1884."),
    Q("general", 5, "In printing, how many points are there in a pica?",
      "12", "10", "16", "6",
      "Six picas make an inch, so a pica is a sixth of an inch."),
]

# ══ GEOGRAPHY ══════════════════════════════════════════════════════════════
BANK += [
    Q("geo", 1, "What is the capital of Canada?",
      "Ottawa", "Toronto", "Vancouver", "Montreal",
      "Chosen in 1857 as a compromise between Toronto and Quebec City."),
    Q("geo", 1, "Which ocean lies between Africa and Australia?",
      "The Indian Ocean", "The Pacific Ocean", "The Atlantic Ocean", "The Southern Ocean",
      "The only ocean named after a country."),
    Q("geo", 1, "Mount Kilimanjaro stands in which country?",
      "Tanzania", "Kenya", "Uganda", "Ethiopia",
      "Its Uhuru Peak is Africa's highest point at 5,895 m."),
    Q("geo", 1, "Which is the longest river in South America?",
      "The Amazon", "The Paraná", "The Orinoco", "The Magdalena",
      "It also carries more water than the next seven largest rivers combined."),
    Q("geo", 2, "What is the capital of New Zealand?",
      "Wellington", "Auckland", "Christchurch", "Dunedin",
      "Auckland is much bigger; Wellington got the capital in 1865 for being central."),
    Q("geo", 2, "Which country is entirely surrounded by South Africa?",
      "Lesotho", "Eswatini", "Botswana", "Zimbabwe",
      "Eswatini is nearly enclosed too, but it also borders Mozambique."),
    Q("geo", 2, "The Strait of Gibraltar separates Spain from which country?",
      "Morocco", "Algeria", "Tunisia", "Libya",
      "At its narrowest the crossing is about 13 km."),
    Q("geo", 2, "Which African country was once known as Abyssinia?",
      "Ethiopia", "Eritrea", "Sudan", "Somalia",
      "One of only two African states never colonised, along with Liberia."),
    Q("geo", 2, "Which US state has the largest area?",
      "Alaska", "Texas", "California", "Montana",
      "Alaska is more than twice the size of Texas."),
    Q("geo", 2, "Lake Titicaca sits on the border of Peru and which other country?",
      "Bolivia", "Chile", "Ecuador", "Brazil",
      "At 3,812 m it is the highest large navigable lake in the world."),
    Q("geo", 2, "Baku is the capital of which country?",
      "Azerbaijan", "Armenia", "Georgia", "Turkmenistan",
      "It sits on the Caspian, some 28 m below sea level."),
    Q("geo", 3, "Which two countries share the world's longest land border?",
      "Canada and the USA", "Russia and China", "Argentina and Chile", "Kazakhstan and Russia",
      "About 8,891 km, including the Alaska stretch."),
    Q("geo", 3, "The Atacama Desert lies mostly in which country?",
      "Chile", "Peru", "Bolivia", "Argentina",
      "Parts of it have gone decades without measurable rain."),
    Q("geo", 3, "Which capital city stands on the river Vltava?",
      "Prague", "Budapest", "Vienna", "Bratislava",
      "Budapest and Bratislava are on the Danube; Vienna too."),
    Q("geo", 3, "Which country has the only national flag that is neither square nor rectangular?",
      "Nepal", "Switzerland", "Bhutan", "Qatar",
      "Two stacked pennants. Switzerland and the Vatican are square, not odd-shaped."),
    Q("geo", 3, "Which strait separates Asia from North America?",
      "The Bering Strait", "The Torres Strait", "The Strait of Malacca", "The Bosphorus",
      "About 82 km wide, with two islands in the middle split between Russia and the USA."),
    Q("geo", 3, "Which country has the longest coastline in the world?",
      "Canada", "Russia", "Indonesia", "Australia",
      "Roughly 202,000 km, thanks to the Arctic archipelago."),
    Q("geo", 3, "Istanbul straddles which strait?",
      "The Bosphorus", "The Dardanelles", "The Strait of Hormuz", "The Kerch Strait",
      "The Dardanelles is the other Turkish strait, further southwest."),
    Q("geo", 3, "Which mountain range is conventionally taken as the boundary between Europe and Asia?",
      "The Urals", "The Caucasus", "The Carpathians", "The Altai",
      "The Caucasus is often used for the southern stretch of the same boundary."),
    Q("geo", 3, "What is the smallest country in the world by area?",
      "Vatican City", "Monaco", "Nauru", "San Marino",
      "About 0.49 km2 -- Monaco, the runner-up, is four times larger."),
    Q("geo", 4, "Which is the deepest lake in the world?",
      "Lake Baikal", "Lake Tanganyika", "The Caspian Sea", "Lake Superior",
      "1,642 m deep, and it holds roughly a fifth of the world's unfrozen fresh water."),
    Q("geo", 4, "Tashkent is the capital of which country?",
      "Uzbekistan", "Kazakhstan", "Turkmenistan", "Kyrgyzstan",
      "Central Asia's largest city, largely rebuilt after the 1966 earthquake."),
    Q("geo", 4, "Which of these is the world's northernmost capital city?",
      "Reykjavík", "Helsinki", "Oslo", "Stockholm",
      "At about 64 degrees north, some 4 degrees further north than Oslo."),
    Q("geo", 4, "What is the largest island in the Mediterranean?",
      "Sicily", "Sardinia", "Cyprus", "Crete",
      "About 25,700 km2; Sardinia is second at around 24,000."),
    Q("geo", 4, "Which country was formerly called Upper Volta?",
      "Burkina Faso", "Mali", "Niger", "Benin",
      "Renamed in 1984; the new name means roughly 'land of upright people'."),
    Q("geo", 4, "The Darién Gap interrupts the Pan-American Highway between which two countries?",
      "Panama and Colombia", "Costa Rica and Panama", "Colombia and Ecuador", "Mexico and Guatemala",
      "About 100 km of roadless rainforest and swamp."),
    Q("geo", 4, "Angel Falls, the world's tallest uninterrupted waterfall, is in which country?",
      "Venezuela", "Brazil", "Colombia", "Guyana",
      "A drop of 979 m from the Auyán-tepui plateau."),
    Q("geo", 4, "Which country's territory includes the Svalbard archipelago?",
      "Norway", "Denmark", "Russia", "Iceland",
      "Sovereign Norwegian since a 1920 treaty that also lets other signatories operate there."),
    Q("geo", 5, "Point Nemo, the spot in the ocean furthest from any land, lies in which ocean?",
      "The Pacific", "The Atlantic", "The Indian Ocean", "The Southern Ocean",
      "The nearest land is about 2,690 km away; the nearest humans are often on the ISS."),
    Q("geo", 5, "What is the capital of Bhutan?",
      "Thimphu", "Paro", "Punakha", "Gangtok",
      "Paro has the airport; Punakha was the old winter capital."),
    Q("geo", 5, "Which two countries are 'doubly landlocked', bordered only by other landlocked countries?",
      "Liechtenstein and Uzbekistan", "Nepal and Bhutan", "Austria and Hungary", "Mongolia and Laos",
      "Uzbekistan's neighbours include Afghanistan, itself landlocked."),
    Q("geo", 5, "The Danube empties into which sea?",
      "The Black Sea", "The Adriatic", "The Aegean", "The Caspian",
      "Through a large delta shared by Romania and Ukraine."),
    Q("geo", 3, "Which country contains the world's largest coral reef system?",
      "Australia", "Indonesia", "The Philippines", "Belize",
      "The Great Barrier Reef runs some 2,300 km along the Queensland coast."),
    Q("geo", 5, "Lake Chad borders Chad, Cameroon, Niger and which fourth country?",
      "Nigeria", "Sudan", "Mali", "Libya",
      "The lake has shrunk drastically since the 1960s, which is why the shares shift."),
    Q("geo", 3, "Which sea is bounded entirely by ocean currents rather than land?",
      "The Sargasso Sea", "The Caspian Sea", "The Coral Sea", "The Bering Sea",
      "Ringed by the North Atlantic Gyre, and named for its floating sargassum weed."),
    Q("geo", 4, "Which African capital sits at the confluence of the Blue and White Nile?",
      "Khartoum", "Cairo", "Juba", "Addis Ababa",
      "The name is often read as 'elephant's trunk', for the shape of the confluence."),
    Q("geo", 2, "Which is the largest of the Great Lakes by surface area?",
      "Lake Superior", "Lake Michigan", "Lake Huron", "Lake Erie",
      "The largest freshwater lake in the world by surface area."),
    Q("geo", 4, "Which country lies immediately south of Egypt?",
      "Sudan", "Libya", "Chad", "Eritrea",
      "The border runs along the 22nd parallel, apart from the disputed Hala'ib Triangle."),
    Q("geo", 5, "Kaliningrad, a Russian exclave, is wedged between which two countries?",
      "Poland and Lithuania", "Latvia and Belarus", "Belarus and Poland", "Estonia and Latvia",
      "Formerly Königsberg, and the home town of Immanuel Kant."),
    Q("geo", 3, "The Panama Canal connects the Atlantic to which ocean?",
      "The Pacific", "The Indian Ocean", "The Arctic Ocean", "The Southern Ocean",
      "Because of the isthmus's shape, ships transit roughly northwest to southeast."),
]

# ---END---
