# -*- coding: utf-8 -*-
"""
trivia_bank.py -- the hand-authored question bank behind THE DECIDER.

RULES I HELD MYSELF TO WHILE WRITING THIS
  * Every answer is a settled fact that a reference work would agree with and
    that was still true in January 2026. No incumbents, no current champions,
    no "biggest company", no populations, no live records -- anything whose
    answer moves was left out rather than guessed.
  * The three wrong options are plausible (same kind of thing, same register)
    but unambiguously wrong. No "all of the above", no near-synonyms of the
    answer, no two options that could both be defended.
  * `note` is the payoff line shown after the reveal -- one sentence, the thing
    you actually want to know. It never just restates the answer.
  * diff 1 = nearly everyone; 2 = easy for a strong player; 3 = solid pub-quiz
    middle; 4 = they will miss some of these; 5 = genuinely hard.
  * Where a fact is disputed or version-dependent, it is NOT here.

Edit this file, then run  python3 _build/gen_trivia.py
"""

CATS = {
    "general": {"label": "GENERAL KNOWLEDGE", "icon": "\U0001F3B2"},
    "geo":     {"label": "GEOGRAPHY",         "icon": "\U0001F30D"},
    "history": {"label": "HISTORY",           "icon": "\U0001F3DB"},
    "science": {"label": "SCIENCE",           "icon": "\U0001F9EA"},
    "film":    {"label": "FILM & TV",         "icon": "\U0001F3AC"},
    "music":   {"label": "MUSIC",             "icon": "\U0001F3B5"},
    "lit":     {"label": "LITERATURE",        "icon": "\U0001F4D6"},
    "food":    {"label": "FOOD & DRINK",      "icon": "\U0001F372"},
    "sport":   {"label": "SPORT",             "icon": "⚽"},
    "ai":      {"label": "AI & TECH",         "icon": "\U0001F916"},
    "art":     {"label": "ART",               "icon": "\U0001F3A8"},
    "words":   {"label": "LANGUAGE & WORDS",  "icon": "\U0001F524"},
    "persia":  {"label": "IRAN & PERSIA",     "icon": "\U0001F1EE\U0001F1F7"},
    "jewish":  {"label": "JEWISH LIFE",       "icon": "✡"},
    "cities":  {"label": "THEIR FOUR CITIES", "icon": "\U0001F5FA"},
}


def Q(cat, diff, q, a, w1, w2, w3, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "wrong": (w1, w2, w3), "note": note}


def N(cat, diff, q, a, unit, note):
    return {"cat": cat, "diff": diff, "q": q, "a": a, "unit": unit,
            "note": note, "numeric": True}


BANK = []

# ══ GENERAL KNOWLEDGE ══════════════════════════════════════════════════════
BANK += [
    Q("general", 1, "How many squares are there on a standard chessboard?",
      "64", "32", "81", "100",
      "Eight by eight. The 32 is the number of squares of each colour."),
    Q("general", 1, "Which zodiac sign is represented by a pair of scales?",
      "Libra", "Aries", "Virgo", "Capricorn",
      "The only zodiac sign symbolised by an object rather than a creature."),
    Q("general", 1, "Which colour appears at the top of a rainbow?",
      "Red", "Violet", "Blue", "Green",
      "Red is refracted least, so it sits on the outer, upper edge of the arc."),
    Q("general", 1, "In the Greek alphabet, which letter comes last?",
      "Omega", "Alpha", "Sigma", "Psi",
      "Hence 'the alpha and the omega' -- the first and the last."),
    Q("general", 1, "What is the currency of Japan?",
      "Yen", "Won", "Yuan", "Ringgit",
      "The won is Korean, the yuan Chinese, the ringgit Malaysian."),
    Q("general", 2, "Which Roman numeral represents 50?",
      "L", "C", "D", "X",
      "C is 100, D is 500, X is 10."),
    Q("general", 2, "In the Chinese zodiac, which animal starts the twelve-year cycle?",
      "Rat", "Ox", "Dragon", "Tiger",
      "The rat is said to have hitched a ride on the ox and jumped off first."),
    Q("general", 2, "Vexillology is the study of what?",
      "Flags", "Coins", "Stamps", "Caves",
      "From the Latin 'vexillum', a Roman military standard."),
    Q("general", 2, "How many points does a snooker ball score if it is the black?",
      "7", "6", "8", "5",
      "Yellow 2, green 3, brown 4, blue 5, pink 6, black 7."),
    Q("general", 2, "What does the abbreviation 'e.g.' stand for?",
      "Exempli gratia", "Ergo gratia", "Exempli generalis", "Et grata",
      "Latin for 'for the sake of example' -- unlike 'i.e.', id est, 'that is'."),
    Q("general", 3, "What is the collective noun for a group of crows?",
      "A murder", "A parliament", "A murmuration", "A charm",
      "A parliament is owls, a murmuration starlings, a charm goldfinches."),
    Q("general", 3, "Numismatics is the collecting and study of what?",
      "Coins", "Stamps", "Postcards", "Maps",
      "Stamp collecting is philately -- a word coined in 1864 from Greek."),
    Q("general", 3, "Which is the only letter of the alphabet that appears in no US state name?",
      "Q", "Z", "X", "J",
      "Z is in Arizona, X in Texas, J in New Jersey. Q is nowhere."),
    Q("general", 3, "In heraldry, which colour is 'gules'?",
      "Red", "Blue", "Green", "Black",
      "Azure is blue, vert green, sable black, or gold and argent silver."),
    Q("general", 3, "How many dots are there in total on a pair of standard six-sided dice?",
      "42", "36", "48", "21",
      "Each die carries 21 pips, because 1+2+3+4+5+6 = 21."),
    Q("general", 3, "How many hearts does an octopus have?",
      "Three", "One", "Two", "Eight",
      "Two pump blood through the gills, one through the rest of the body."),
    Q("general", 4, "What is the name of the dot over a lower-case 'i'?",
      "A tittle", "A serif", "A cedilla", "A macron",
      "Hence 'to a T' -- originally 'to a tittle', meaning to the last detail."),
    Q("general", 4, "In Norse myth, what is the name of Odin's eight-legged horse?",
      "Sleipnir", "Fenrir", "Gungnir", "Draupnir",
      "Fenrir is the wolf, Gungnir the spear, Draupnir the ring."),
    Q("general", 4, "Which two metals are alloyed to make bronze?",
      "Copper and tin", "Copper and zinc", "Iron and carbon", "Tin and lead",
      "Copper and zinc gives brass; iron and carbon gives steel."),
    Q("general", 4, "What is the plastic or metal sheath on the end of a shoelace called?",
      "An aglet", "A ferrule", "A grommet", "A chape",
      "A ferrule is the metal band on a tool handle; a grommet is an eyelet."),
    Q("general", 4, "A 'baker's dozen' is thirteen. What was the practice originally meant to avoid?",
      "Penalties for selling underweight bread", "Wasting a spare loaf",
      "Paying tax on the twelfth", "Splitting a dozen between two customers",
      "Medieval English law punished short-weight loaves harshly, so bakers added one."),
    Q("general", 5, "In bell-ringing, what is a 'peal' required to exceed?",
      "5,000 changes", "1,000 changes", "500 changes", "10,000 changes",
      "A full peal is at least 5,000 changes and takes roughly three hours."),
    Q("general", 5, "What is the term for the study of the shapes and origins of place names?",
      "Toponymy", "Onomastics", "Etymology", "Cartology",
      "Onomastics is names in general; toponymy is the branch about places."),
    Q("general", 5, "Which SI base unit is defined using the caesium-133 atom?",
      "The second", "The metre", "The kelvin", "The mole",
      "9,192,631,770 oscillations of that transition define one second."),
    Q("general", 2, "What is the largest planet in the Solar System?",
      "Jupiter", "Saturn", "Neptune", "Uranus",
      "Jupiter has more than twice the mass of every other planet combined."),
    Q("general", 3, "Which family of birds can hover in place and fly deliberately backwards?",
      "Hummingbirds", "Kingfishers", "Swifts", "Wrens",
      "A figure-of-eight wing stroke generates lift on both the forward and back sweep."),
    Q("general", 2, "In a standard deck of cards, which suit is ranked highest in bridge?",
      "Spades", "Hearts", "Diamonds", "Clubs",
      "Bridge ranks the suits clubs, diamonds, hearts, spades -- spades top."),
    Q("general", 3, "What is the name for a word or phrase that means the opposite of itself, such as 'cleave'?",
      "A contronym", "A homonym", "An antonym", "A metonym",
      "'Cleave' means both to split apart and to cling to."),
    Q("general", 4, "How many keys does a standard modern grand piano have?",
      "88", "84", "92", "76",
      "Fifty-two white and thirty-six black, spanning A0 to C8."),
    Q("general", 5, "A 'lustrum' in Roman reckoning was a period of how long?",
      "Five years", "Ten years", "Three years", "A hundred years",
      "It marked the census and its purification rite, held every five years."),
    Q("general", 3, "Which planet is closest in size to Earth?",
      "Venus", "Mars", "Mercury", "Neptune",
      "Venus has about 95% of Earth's diameter; Mars only about 53%."),
    Q("general", 2, "How many time zones does the contiguous United States use?",
      "Four", "Three", "Five", "Six",
      "Eastern, Central, Mountain and Pacific; Alaska and Hawaii add more."),
    Q("general", 4, "Which of these is a genuine typographic name for the '#' symbol?",
      "Octothorpe", "Obelisk", "Pilcrow", "Interpunct",
      "A pilcrow is the paragraph mark, an obelisk the dagger, an interpunct the mid-dot."),
    Q("general", 5, "In falconry, what is a young bird taken from the nest for training called?",
      "An eyas", "A haggard", "A passager", "A tiercel",
      "A haggard is caught as an adult; a tiercel is a male peregrine."),
    Q("general", 1, "What does a sommelier specialise in?",
      "Wine", "Cheese", "Tea", "Bread",
      "From Old French for the court official who handled provisions and pack animals."),
    Q("general", 1, "How many minutes are there in a full day?",
      "1,440", "1,200", "1,240", "1,800",
      "Twenty-four hours of sixty minutes each."),
    Q("general", 3, "Which of these is the only US state whose name begins with two vowels?",
      "Iowa", "Ohio", "Utah", "Oregon",
      "Ohio, Utah and Oregon all start with a single vowel; Iowa opens with I and o."),
    Q("general", 4, "The Nobel Prizes are awarded in Stockholm, except for one. Which?",
      "The Peace Prize", "The Prize in Literature", "The Prize in Physics", "The Prize in Economics",
      "Nobel's will sent the Peace Prize to Oslo; nobody is quite sure why."),
    Q("general", 2, "What is the imaginary line at 0 degrees longitude called?",
      "The Prime Meridian", "The Equator", "The Tropic of Cancer", "The International Date Line",
      "Fixed at Greenwich by an international conference in 1884."),
    Q("general", 5, "In printing, how many points are there in a pica?",
      "12", "10", "16", "6",
      "Six picas make an inch, so a pica is a sixth of an inch."),
]

# ══ GEOGRAPHY ══════════════════════════════════════════════════════════════
BANK += [
    Q("geo", 1, "What is the capital of Canada?",
      "Ottawa", "Toronto", "Vancouver", "Montreal",
      "Chosen in 1857 as a compromise between Toronto and Quebec City."),
    Q("geo", 1, "Which ocean lies between Africa and Australia?",
      "The Indian Ocean", "The Pacific Ocean", "The Atlantic Ocean", "The Southern Ocean",
      "The only ocean named after a country."),
    Q("geo", 1, "Mount Kilimanjaro stands in which country?",
      "Tanzania", "Kenya", "Uganda", "Ethiopia",
      "Its Uhuru Peak is Africa's highest point at 5,895 m."),
    Q("geo", 1, "Which is the longest river in South America?",
      "The Amazon", "The Paraná", "The Orinoco", "The Magdalena",
      "It also carries more water than the next seven largest rivers combined."),
    Q("geo", 2, "What is the capital of New Zealand?",
      "Wellington", "Auckland", "Christchurch", "Dunedin",
      "Auckland is much bigger; Wellington got the capital in 1865 for being central."),
    Q("geo", 2, "Which country is entirely surrounded by South Africa?",
      "Lesotho", "Eswatini", "Botswana", "Zimbabwe",
      "Eswatini is nearly enclosed too, but it also borders Mozambique."),
    Q("geo", 2, "The Strait of Gibraltar separates Spain from which country?",
      "Morocco", "Algeria", "Tunisia", "Libya",
      "At its narrowest the crossing is about 13 km."),
    Q("geo", 2, "Which African country was once known as Abyssinia?",
      "Ethiopia", "Eritrea", "Sudan", "Somalia",
      "One of only two African states never colonised, along with Liberia."),
    Q("geo", 2, "Which US state has the largest area?",
      "Alaska", "Texas", "California", "Montana",
      "Alaska is more than twice the size of Texas."),
    Q("geo", 2, "Lake Titicaca sits on the border of Peru and which other country?",
      "Bolivia", "Chile", "Ecuador", "Brazil",
      "At 3,812 m it is the highest large navigable lake in the world."),
    Q("geo", 2, "Baku is the capital of which country?",
      "Azerbaijan", "Armenia", "Georgia", "Turkmenistan",
      "It sits on the Caspian, some 28 m below sea level."),
    Q("geo", 3, "Which two countries share the world's longest land border?",
      "Canada and the USA", "Russia and China", "Argentina and Chile", "Kazakhstan and Russia",
      "About 8,891 km, including the Alaska stretch."),
    Q("geo", 3, "The Atacama Desert lies mostly in which country?",
      "Chile", "Peru", "Bolivia", "Argentina",
      "Parts of it have gone decades without measurable rain."),
    Q("geo", 3, "Which capital city stands on the river Vltava?",
      "Prague", "Budapest", "Vienna", "Bratislava",
      "Budapest and Bratislava are on the Danube; Vienna too."),
    Q("geo", 3, "Which country has the only national flag that is neither square nor rectangular?",
      "Nepal", "Switzerland", "Bhutan", "Qatar",
      "Two stacked pennants. Switzerland and the Vatican are square, not odd-shaped."),
    Q("geo", 3, "Which strait separates Asia from North America?",
      "The Bering Strait", "The Torres Strait", "The Strait of Malacca", "The Bosphorus",
      "About 82 km wide, with two islands in the middle split between Russia and the USA."),
    Q("geo", 3, "Which country has the longest coastline in the world?",
      "Canada", "Russia", "Indonesia", "Australia",
      "Roughly 202,000 km, thanks to the Arctic archipelago."),
    Q("geo", 3, "Istanbul straddles which strait?",
      "The Bosphorus", "The Dardanelles", "The Strait of Hormuz", "The Kerch Strait",
      "The Dardanelles is the other Turkish strait, further southwest."),
    Q("geo", 3, "Which mountain range is conventionally taken as the boundary between Europe and Asia?",
      "The Urals", "The Caucasus", "The Carpathians", "The Altai",
      "The Caucasus is often used for the southern stretch of the same boundary."),
    Q("geo", 3, "What is the smallest country in the world by area?",
      "Vatican City", "Monaco", "Nauru", "San Marino",
      "About 0.49 km2 -- Monaco, the runner-up, is four times larger."),
    Q("geo", 4, "Which is the deepest lake in the world?",
      "Lake Baikal", "Lake Tanganyika", "The Caspian Sea", "Lake Superior",
      "1,642 m deep, and it holds roughly a fifth of the world's unfrozen fresh water."),
    Q("geo", 4, "Tashkent is the capital of which country?",
      "Uzbekistan", "Kazakhstan", "Turkmenistan", "Kyrgyzstan",
      "Central Asia's largest city, largely rebuilt after the 1966 earthquake."),
    Q("geo", 4, "Which of these is the world's northernmost capital city?",
      "Reykjavík", "Helsinki", "Oslo", "Stockholm",
      "At about 64 degrees north, some 4 degrees further north than Oslo."),
    Q("geo", 4, "What is the largest island in the Mediterranean?",
      "Sicily", "Sardinia", "Cyprus", "Crete",
      "About 25,700 km2; Sardinia is second at around 24,000."),
    Q("geo", 4, "Which country was formerly called Upper Volta?",
      "Burkina Faso", "Mali", "Niger", "Benin",
      "Renamed in 1984; the new name means roughly 'land of upright people'."),
    Q("geo", 4, "The Darién Gap interrupts the Pan-American Highway between which two countries?",
      "Panama and Colombia", "Costa Rica and Panama", "Colombia and Ecuador", "Mexico and Guatemala",
      "About 100 km of roadless rainforest and swamp."),
    Q("geo", 4, "Angel Falls, the world's tallest uninterrupted waterfall, is in which country?",
      "Venezuela", "Brazil", "Colombia", "Guyana",
      "A drop of 979 m from the Auyán-tepui plateau."),
    Q("geo", 4, "Which country's territory includes the Svalbard archipelago?",
      "Norway", "Denmark", "Russia", "Iceland",
      "Sovereign Norwegian since a 1920 treaty that also lets other signatories operate there."),
    Q("geo", 5, "Point Nemo, the spot in the ocean furthest from any land, lies in which ocean?",
      "The Pacific", "The Atlantic", "The Indian Ocean", "The Southern Ocean",
      "The nearest land is about 2,690 km away; the nearest humans are often on the ISS."),
    Q("geo", 5, "What is the capital of Bhutan?",
      "Thimphu", "Paro", "Punakha", "Gangtok",
      "Paro has the airport; Punakha was the old winter capital."),
    Q("geo", 5, "Which two countries are 'doubly landlocked', bordered only by other landlocked countries?",
      "Liechtenstein and Uzbekistan", "Nepal and Bhutan", "Austria and Hungary", "Mongolia and Laos",
      "Uzbekistan's neighbours include Afghanistan, itself landlocked."),
    Q("geo", 5, "The Danube empties into which sea?",
      "The Black Sea", "The Adriatic", "The Aegean", "The Caspian",
      "Through a large delta shared by Romania and Ukraine."),
    Q("geo", 3, "Which country contains the world's largest coral reef system?",
      "Australia", "Indonesia", "The Philippines", "Belize",
      "The Great Barrier Reef runs some 2,300 km along the Queensland coast."),
    Q("geo", 5, "Lake Chad borders Chad, Cameroon, Niger and which fourth country?",
      "Nigeria", "Sudan", "Mali", "Libya",
      "The lake has shrunk drastically since the 1960s, which is why the shares shift."),
    Q("geo", 3, "Which sea is bounded entirely by ocean currents rather than land?",
      "The Sargasso Sea", "The Caspian Sea", "The Coral Sea", "The Bering Sea",
      "Ringed by the North Atlantic Gyre, and named for its floating sargassum weed."),
    Q("geo", 4, "Which African capital sits at the confluence of the Blue and White Nile?",
      "Khartoum", "Cairo", "Juba", "Addis Ababa",
      "The name is often read as 'elephant's trunk', for the shape of the confluence."),
    Q("geo", 2, "Which is the largest of the Great Lakes by surface area?",
      "Lake Superior", "Lake Michigan", "Lake Huron", "Lake Erie",
      "The largest freshwater lake in the world by surface area."),
    Q("geo", 4, "Which country lies immediately south of Egypt?",
      "Sudan", "Libya", "Chad", "Eritrea",
      "The border runs along the 22nd parallel, apart from the disputed Hala'ib Triangle."),
    Q("geo", 5, "Kaliningrad, a Russian exclave, is wedged between which two countries?",
      "Poland and Lithuania", "Latvia and Belarus", "Belarus and Poland", "Estonia and Latvia",
      "Formerly Königsberg, and the home town of Immanuel Kant."),
    Q("geo", 3, "The Panama Canal connects the Atlantic to which ocean?",
      "The Pacific", "The Indian Ocean", "The Arctic Ocean", "The Southern Ocean",
      "Because of the isthmus's shape, ships transit roughly northwest to southeast."),
]

# ══ HISTORY ════════════════════════════════════════════════════════════════
BANK += [
    Q("history", 1, "Who was the first person to set foot on the Moon?",
      "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins",
      "Aldrin followed him about twenty minutes later; Collins stayed in orbit."),
    Q("history", 1, "The Titanic was steaming towards which city when it sank?",
      "New York", "Boston", "Halifax", "Philadelphia",
      "It had left Southampton four days earlier on its maiden voyage."),
    Q("history", 1, "Which English king had six wives?",
      "Henry VIII", "Henry VII", "Edward VI", "Charles II",
      "Two were beheaded, two divorced, one died in childbirth, one outlived him."),
    Q("history", 1, "Apartheid was the official policy of which country?",
      "South Africa", "Rhodesia", "Namibia", "Angola",
      "Formally in force from 1948 until the early 1990s."),
    Q("history", 2, "Which civilisation built Machu Picchu?",
      "The Inca", "The Aztec", "The Maya", "The Olmec",
      "Built in the 15th century and never found by the Spanish."),
    Q("history", 2, "Who was the first Emperor of Rome?",
      "Augustus", "Julius Caesar", "Nero", "Tiberius",
      "Caesar was never emperor -- he was dictator; Augustus was his heir."),
    Q("history", 2, "The Magna Carta was sealed in which year?",
      "1215", "1066", "1314", "1485",
      "At Runnymede, by King John, under pressure from rebel barons."),
    Q("history", 2, "On which island was Napoleon Bonaparte born?",
      "Corsica", "Sardinia", "Elba", "Sicily",
      "Elba was his first place of exile; St Helena was the second."),
    Q("history", 2, "Which empire was ruled from Constantinople for a thousand years after Rome fell?",
      "The Byzantine Empire", "The Ottoman Empire", "The Holy Roman Empire", "The Sasanian Empire",
      "The Ottomans took the city in 1453 and ruled from it afterwards."),
    Q("history", 2, "Who was assassinated in Sarajevo in June 1914?",
      "Archduke Franz Ferdinand", "Tsar Nicholas II", "King Alexander I", "Kaiser Wilhelm II",
      "Gavrilo Princip's shots set off the July Crisis and then the First World War."),
    Q("history", 2, "Which country did the United States buy Alaska from in 1867?",
      "Russia", "Canada", "Britain", "Denmark",
      "$7.2 million, about two cents an acre, and it was mocked as 'Seward's Folly'."),
    Q("history", 3, "The Treaty of Versailles was signed in which year?",
      "1919", "1918", "1920", "1921",
      "The armistice was 1918; the treaty came the following June."),
    Q("history", 3, "Which 1815 battle ended Napoleon's rule for good?",
      "Waterloo", "Austerlitz", "Leipzig", "Borodino",
      "Austerlitz, nine years earlier, had been his greatest victory."),
    Q("history", 3, "Who was the last Tsar of Russia?",
      "Nicholas II", "Alexander III", "Peter III", "Paul I",
      "Alexander III was his father; the dynasty ended in 1917."),
    Q("history", 3, "The Rosetta Stone was the key to reading which writing system?",
      "Egyptian hieroglyphs", "Cuneiform", "Linear B", "Old Persian",
      "It carries the same decree in hieroglyphs, Demotic and Greek."),
    Q("history", 3, "Which Roman town was buried by Vesuvius in AD 79 alongside Herculaneum?",
      "Pompeii", "Ostia", "Capua", "Cumae",
      "Pliny the Younger's letters describe the eruption from across the bay."),
    Q("history", 3, "Who was British Prime Minister when Britain declared war on Germany in 1939?",
      "Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Stanley Baldwin",
      "Churchill replaced him in May 1940, after the Norway debate."),
    Q("history", 3, "The Hundred Years' War was fought between England and which country?",
      "France", "Spain", "Scotland", "The Netherlands",
      "It ran, on and off, from 1337 to 1453 -- so 116 years."),
    Q("history", 3, "Which US President completed the Louisiana Purchase?",
      "Thomas Jefferson", "George Washington", "James Madison", "James Monroe",
      "It doubled the size of the country for about $15 million in 1803."),
    Q("history", 3, "In which year did India become independent?",
      "1947", "1945", "1949", "1950",
      "Partition came at the same moment; the republic was declared in 1950."),
    Q("history", 4, "The 1494 Treaty of Tordesillas divided the newly found world between which two powers?",
      "Spain and Portugal", "Spain and France", "Portugal and England", "France and the Netherlands",
      "It is why Brazil speaks Portuguese and the rest of South America Spanish."),
    Q("history", 4, "Who was the first woman to be awarded a Nobel Prize?",
      "Marie Curie", "Bertha von Suttner", "Selma Lagerlöf", "Irène Joliot-Curie",
      "Physics, 1903; she later won Chemistry too, the only person with both."),
    Q("history", 4, "The Defenestration of Prague in 1618 helped set off which war?",
      "The Thirty Years' War", "The Seven Years' War", "The War of the Spanish Succession", "The Hussite Wars",
      "Two regents were thrown from a castle window and survived the fall."),
    Q("history", 4, "Which dynasty ruled China immediately before the Qing?",
      "The Ming", "The Song", "The Yuan", "The Han",
      "The Ming fell in 1644; the Yuan were the Mongol dynasty before them."),
    Q("history", 4, "Finland declared independence in 1917 from which country?",
      "Russia", "Sweden", "Germany", "Denmark",
      "It had been a Grand Duchy of the Russian Empire since 1809."),
    Q("history", 4, "Who led the Carthaginian army that crossed the Alps with elephants?",
      "Hannibal", "Hasdrubal", "Hamilcar", "Scipio",
      "Hamilcar was his father; Scipio was the Roman who eventually beat him."),
    Q("history", 4, "In which decade did the Suez Canal open?",
      "The 1860s", "The 1850s", "The 1870s", "The 1880s",
      "November 1869, after ten years of construction under Ferdinand de Lesseps."),
    Q("history", 4, "The Bayeux Tapestry depicts which event?",
      "The Norman conquest of England", "The First Crusade", "The Battle of Agincourt", "The Wars of the Roses",
      "It is embroidery, not tapestry, and it is about 70 metres long."),
    Q("history", 4, "Who was the first President of the Republic of Turkey?",
      "Mustafa Kemal Atatürk", "İsmet İnönü", "Enver Pasha", "Mehmed VI",
      "İnönü succeeded him in 1938; Mehmed VI was the last Ottoman sultan."),
    Q("history", 4, "The Boxer Rebellion of 1899-1901 took place in which country?",
      "China", "Japan", "Korea", "Vietnam",
      "An eight-nation alliance intervened against the anti-foreign uprising."),
    Q("history", 5, "Which Byzantine emperor had Roman law codified in the 6th century?",
      "Justinian I", "Constantine I", "Theodosius I", "Basil II",
      "The Corpus Juris Civilis underlies much of European civil law."),
    Q("history", 5, "Which Mughal emperor had the Taj Mahal built?",
      "Shah Jahan", "Akbar", "Aurangzeb", "Babur",
      "For his wife Mumtaz Mahal; Aurangzeb, his son, later deposed him."),
    Q("history", 5, "At the Battle of Lepanto in 1571 the Ottoman fleet was defeated by which alliance?",
      "The Holy League", "The Hanseatic League", "The Delian League", "The League of Cambrai",
      "A Spanish-Venetian-Papal coalition; Cervantes was wounded in the fighting."),
    Q("history", 5, "Which country was the first to grant women the vote in national elections?",
      "New Zealand", "Australia", "Finland", "Norway",
      "1893. Finland was first to let women stand for parliament as well, in 1906."),
    Q("history", 5, "Mansa Musa ruled which medieval West African empire?",
      "Mali", "Songhai", "Ghana", "Kanem-Bornu",
      "His 1324 pilgrimage to Mecca reportedly destabilised Egypt's gold price."),
    Q("history", 5, "Which Roman emperor issued the Edict of Milan, legalising Christian worship?",
      "Constantine I", "Theodosius I", "Diocletian", "Nero",
      "313 AD. Theodosius made Christianity the state religion seventy years later."),
    Q("history", 5, "Whose expedition completed the first circumnavigation of the globe?",
      "Ferdinand Magellan's", "Francis Drake's", "James Cook's", "Christopher Columbus's",
      "Magellan died in the Philippines; Juan Sebastián Elcano brought the ship home."),
    Q("history", 5, "Which Egyptian ruler was the last active monarch of the Ptolemaic kingdom?",
      "Cleopatra VII", "Nefertiti", "Hatshepsut", "Berenice IV",
      "She was Macedonian Greek by descent, not Egyptian."),
    Q("history", 5, "Which 1919 conference created the League of Nations?",
      "The Paris Peace Conference", "The Congress of Vienna", "The Yalta Conference", "The Hague Convention",
      "The United States never joined the League its own president had proposed."),
    Q("history", 3, "Which two Japanese cities were struck by atomic bombs in 1945?",
      "Hiroshima and Nagasaki", "Hiroshima and Kokura", "Nagasaki and Kyoto", "Yokohama and Kobe",
      "Kokura was the original second target but was obscured by cloud."),
    Q("history", 4, "The Berlin Airlift supplied West Berlin during a blockade in which years?",
      "1948-49", "1945-46", "1953-54", "1961-62",
      "Around 280,000 flights kept two million people supplied for eleven months."),
    Q("history", 5, "Which ancient wonder stood on the island of Pharos?",
      "The Lighthouse of Alexandria", "The Colossus of Rhodes", "The Temple of Artemis", "The Mausoleum at Halicarnassus",
      "It stood for roughly 1,600 years before earthquakes brought it down."),
    Q("history", 2, "The Cuban Missile Crisis took place in which decade?",
      "The 1960s", "The 1950s", "The 1970s", "The 1940s",
      "October 1962, and it lasted thirteen days."),
    Q("history", 4, "Which country's 1974 'Carnation Revolution' ended a long dictatorship almost bloodlessly?",
      "Portugal", "Spain", "Greece", "Chile",
      "It also triggered the independence of Angola, Mozambique and Guinea-Bissau."),
    Q("history", 5, "The Rosetta Stone is written in three scripts. Which language does the Greek section record?",
      "Ancient Greek", "Coptic", "Latin", "Aramaic",
      "Greek was the administrative language of Ptolemaic Egypt, which is why it helped."),
]

# ══ SCIENCE ════════════════════════════════════════════════════════════════
BANK += [
    Q("science", 1, "What is the chemical symbol for gold?",
      "Au", "Ag", "Go", "Gd",
      "From Latin 'aurum'. Ag is silver, Gd gadolinium."),
    Q("science", 1, "Which planet is known as the Red Planet?",
      "Mars", "Venus", "Mercury", "Jupiter",
      "Iron oxide dust in its soil gives it the colour."),
    Q("science", 1, "Which gas do plants take in from the air for photosynthesis?",
      "Carbon dioxide", "Oxygen", "Nitrogen", "Methane",
      "They release oxygen as the by-product."),
    Q("science", 1, "What is the largest organ of the human body?",
      "The skin", "The liver", "The lungs", "The brain",
      "About two square metres of it on an average adult."),
    Q("science", 1, "How many chambers does the human heart have?",
      "Four", "Two", "Three", "Six",
      "Two atria and two ventricles; fish have two chambers."),
    Q("science", 1, "Which is the hardest naturally occurring mineral?",
      "Diamond", "Quartz", "Corundum", "Topaz",
      "Ten on the Mohs scale; corundum, at nine, is next."),
    Q("science", 2, "Which cells carry oxygen around the human body?",
      "Red blood cells", "White blood cells", "Platelets", "Plasma cells",
      "White cells fight infection; platelets clot."),
    Q("science", 2, "What is the most abundant gas in Earth's atmosphere?",
      "Nitrogen", "Oxygen", "Carbon dioxide", "Argon",
      "About 78% nitrogen to 21% oxygen; argon is a distant third."),
    Q("science", 2, "What does DNA stand for?",
      "Deoxyribonucleic acid", "Dinucleic acid", "Deoxyribose nuclear acid", "Diribonucleic acid",
      "RNA is the same without the 'deoxy' -- it keeps the extra oxygen."),
    Q("science", 2, "Which vitamin does the skin make when exposed to sunlight?",
      "Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K",
      "Technically a hormone precursor rather than a true dietary vitamin."),
    Q("science", 2, "What is the SI unit of force?",
      "The newton", "The joule", "The watt", "The pascal",
      "One newton accelerates one kilogram at one metre per second squared."),
    Q("science", 2, "What is the chemical formula of table salt?",
      "NaCl", "KCl", "NaHCO3", "CaCO3",
      "KCl is a salt substitute; NaHCO3 is bicarbonate of soda."),
    Q("science", 2, "Which human bone is the longest?",
      "The femur", "The tibia", "The humerus", "The fibula",
      "Roughly a quarter of an adult's height."),
    Q("science", 2, "Which acid does the human stomach produce to digest food?",
      "Hydrochloric acid", "Sulfuric acid", "Acetic acid", "Citric acid",
      "It keeps stomach contents at a pH of about 1.5 to 3.5."),
    Q("science", 3, "Which part of the brain governs balance and fine coordination?",
      "The cerebellum", "The cerebrum", "The medulla", "The hippocampus",
      "It holds over half the brain's neurons in about a tenth of its volume."),
    Q("science", 3, "What is the pH of pure water at 25 degrees Celsius?",
      "7", "0", "14", "1",
      "Neutral by definition -- equal concentrations of H+ and OH-."),
    Q("science", 3, "Who worked out the three laws of planetary motion?",
      "Johannes Kepler", "Nicolaus Copernicus", "Galileo Galilei", "Isaac Newton",
      "He used Tycho Brahe's observations of Mars to find the elliptical orbit."),
    Q("science", 3, "What is it called when a liquid turns to gas below its boiling point?",
      "Evaporation", "Condensation", "Sublimation", "Deposition",
      "Sublimation is solid straight to gas, as with dry ice."),
    Q("science", 3, "Which organelle is called the powerhouse of the cell?",
      "The mitochondrion", "The ribosome", "The nucleus", "The Golgi apparatus",
      "It has its own DNA, inherited only from your mother."),
    Q("science", 3, "Which is the least dense metal in the periodic table?",
      "Lithium", "Beryllium", "Sodium", "Aluminium",
      "It floats on water -- while reacting with it."),
    Q("science", 3, "Which is the smallest bone in the human body?",
      "The stapes", "The malleus", "The incus", "The hyoid",
      "One of the three middle-ear bones; about three millimetres long."),
    Q("science", 3, "Which effect splits white light into a spectrum as it passes through a prism?",
      "Dispersion", "Diffraction", "Reflection", "Polarisation",
      "Different wavelengths bend by different amounts, so the colours fan out."),
    Q("science", 4, "What is the most abundant element in the universe?",
      "Hydrogen", "Helium", "Oxygen", "Carbon",
      "About three quarters of all ordinary matter by mass."),
    Q("science", 4, "What is the boundary around a black hole beyond which nothing can escape?",
      "The event horizon", "The ergosphere", "The photon sphere", "The singularity",
      "The singularity is the centre; the photon sphere is where light can orbit."),
    Q("science", 4, "Which two particles found in the atomic nucleus are made of quarks?",
      "Protons and neutrons", "Electrons and positrons", "Photons and gluons", "Neutrinos and muons",
      "Three quarks each: uud for a proton, udd for a neutron."),
    Q("science", 4, "Which gas law says pressure and volume are inversely proportional at fixed temperature?",
      "Boyle's law", "Charles's law", "Avogadro's law", "Dalton's law",
      "Charles's law is the volume-temperature one."),
    Q("science", 4, "Who arranged the first widely accepted periodic table and predicted missing elements?",
      "Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Robert Boyle",
      "He left gaps, and gallium and germanium later turned up to fill them."),
    Q("science", 4, "Which planet spins almost on its side, tipped about 98 degrees?",
      "Uranus", "Neptune", "Venus", "Saturn",
      "Probably knocked over by a giant impact early in the Solar System."),
    Q("science", 4, "What does a Geiger counter detect?",
      "Ionising radiation", "Sound intensity", "Magnetic flux", "Air pressure",
      "A gas-filled tube: each ionising particle triggers an audible pulse."),
    Q("science", 4, "What is the dating of events by counting tree rings called?",
      "Dendrochronology", "Palynology", "Stratigraphy", "Radiometry",
      "Palynology is pollen; overlapping ring series stretch back thousands of years."),
    Q("science", 4, "Which blood type is the universal donor for red cell transfusions?",
      "O negative", "AB positive", "A negative", "O positive",
      "AB positive is the universal recipient -- the mirror image."),
    Q("science", 5, "Which noble gas takes its name from the Greek for 'lazy' or 'inactive'?",
      "Argon", "Neon", "Krypton", "Xenon",
      "Neon means 'new', krypton 'hidden', xenon 'stranger'."),
    Q("science", 5, "Which physicist formulated the uncertainty principle?",
      "Werner Heisenberg", "Erwin Schrödinger", "Niels Bohr", "Max Born",
      "1927. You cannot pin down position and momentum together beyond a fixed limit."),
    Q("science", 5, "The Krebs cycle takes place in which part of a eukaryotic cell?",
      "The mitochondrial matrix", "The cytoplasm", "The nucleus", "The endoplasmic reticulum",
      "Glycolysis, the step before it, happens out in the cytoplasm."),
    Q("science", 5, "Whose 'last theorem' did Andrew Wiles prove in the 1990s?",
      "Pierre de Fermat's", "Leonhard Euler's", "Carl Friedrich Gauss's", "Bernhard Riemann's",
      "It had stood unproved for over 350 years."),
    Q("science", 5, "Which enzyme unwinds the DNA double helix during replication?",
      "Helicase", "Polymerase", "Ligase", "Primase",
      "Polymerase then builds the new strand; ligase stitches the pieces together."),
    Q("science", 5, "What is the point in an orbit nearest to the Sun called?",
      "Perihelion", "Aphelion", "Perigee", "Apogee",
      "Perigee and apogee are the equivalents for an orbit around the Earth."),
    Q("science", 5, "Which scientist measured the charge on a single electron with an oil-drop experiment?",
      "Robert Millikan", "J. J. Thomson", "Ernest Rutherford", "Niels Bohr",
      "Thomson had identified the electron; Millikan pinned down its charge."),
    Q("science", 5, "Which particle, proposed in 1930 to save conservation of energy in beta decay, was not detected until 1956?",
      "The neutrino", "The positron", "The muon", "The pion",
      "Pauli suggested it apologetically, calling it a 'desperate remedy'."),
    Q("science", 3, "Which subatomic particle carries a negative electric charge?",
      "The electron", "The proton", "The neutron", "The photon",
      "Protons are positive, neutrons neutral, photons chargeless."),
    Q("science", 5, "What is the term for animals that generate their own body heat internally?",
      "Endothermic", "Ectothermic", "Poikilothermic", "Mesothermic",
      "Ectotherms take their heat from the environment -- the old 'cold-blooded'."),
    Q("science", 4, "Which comet last appeared in 1986 and returns roughly every 76 years?",
      "Halley's Comet", "Hale-Bopp", "Comet Encke", "Comet Hyakutake",
      "Edmond Halley predicted its return; he did not live to see it confirmed."),
    Q("science", 5, "Which layer of the atmosphere contains most of the ozone layer?",
      "The stratosphere", "The troposphere", "The mesosphere", "The thermosphere",
      "Weather happens in the troposphere below; jets cruise at the boundary."),
    Q("science", 2, "What does 'RNA' stand for?",
      "Ribonucleic acid", "Radionucleic acid", "Ribose nuclear acid", "Reduced nucleic acid",
      "Messenger RNA carries the instruction from DNA out to the ribosome."),
    Q("science", 4, "Roughly how fast does light travel in a vacuum?",
      "300,000 km per second", "30,000 km per second", "3,000,000 km per second", "3,000 km per second",
      "299,792,458 metres per second, exactly -- the metre is defined from it."),
]

# ---END---
