#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
xw_clues.py -- the hand-authored clue bank for core/data/crosswords.js.

Keyed by ANSWER, so a re-fill of the grids does not invalidate the writing: any answer
the filler produces that already has a clue is covered, and gen_crosswords.py lists the
ones that are not (in _build/xw_need_clues.txt).

House style, borrowed from the NYT Mini:
  * short -- a phrase, not a sentence; no final period
  * concrete and everyday; no trivia that needs a search engine
  * no proper nouns in the ANSWER, and only durable ones in the clue
  * "___" marks a fill-in-the-blank
  * "e.g." / "for one" / ", say" mark a definition-by-example
  * a question mark marks a pun or a deliberate misdirection
  * nothing dated to a single decade; nothing that will read as stale in five years
  * the clue never contains its own answer, or any other answer in the same puzzle

A value may be a LIST of clues; an answer used in more than one puzzle then gets a
different clue each time rather than reading as copy-paste.

MIDI_META gives the titled/themed midis their title and theme note.
"""

CLUES = {
    # ---- 3 letters -------------------------------------------------------------
    "ACE": ["Serve that never comes back", "Card above a king"],
    "ACT": ["Part of a play", "Behave"],
    "ADD": "Total up",
    "ADS": "Interruptions in a podcast",
    "AGE": ["It's only a number, they say", "Get older"],
    "AID": "Lend a hand",
    "AIM": "Point a camera",
    "AIR": ["What a flat tyre needs", "Broadcast"],
    "ALL": "The whole lot",
    "AND": "Word joining two names",
    "ANT": "Picnic pest",
    "ANY": "Take your pick",
    "APT": "Fitting",
    "ARC": "Rainbow's shape",
    "ARM": ["Limb with an elbow", "Supply with weapons"],
    "ART": "What a gallery hangs",
    "ASH": "What the fire leaves behind",
    "ASK": "Put a question",
    "ATE": "Had dinner",
    "BAD": "Not good",
    "BAG": "Grocery carrier",
    "BAT": ["Cave flier", "Slugger's stick"],
    "BAY": "Curve in the coastline",
    "BEE": "Buzzing pollinator",
    "BET": "Wager",
    "BID": "Auction offer",
    "BIG": "Large",
    "BIN": "Where the recycling goes",
    "BIT": "A little",
    "BOW": ["Violinist's stick", "Bend at the waist"],
    "BOX": "Cardboard container",
    "BOY": "Young lad",
    "BUG": ["Beetle, e.g.", "Glitch in the code"],
    "BUS": "It stops at a stop",
    "BUT": "However",
    "BUY": "Purchase",
    "BYE": "See ya",
    "CAB": "Yellow ride",
    "CAN": "Soup container",
    "CAP": "Baseball hat",
    "CAR": "Thing in a driveway",
    "CAT": "Lap warmer",
    "COD": "Fish in fish and chips",
    "COW": "Milk source",
    "CRY": "Let the tears out",
    "CUP": "Mug's cousin",
    "CUT": "Snip",
    "DAD": "Father",
    "DAM": "Beaver's project",
    "DAY": "Sunrise to sunset",
    "DID": "Went ahead and done it",
    "DIG": "Work with a shovel",
    "DOG": "Loyal companion",
    "DOT": "Full stop, in a web address",
    "DRY": "Like the Sahara",
    "DUE": "Expected",
    "DUO": "Pair",
    "EAR": "Corn unit, or a listener",
    "EAT": "Have lunch",
    "EGG": "Breakfast oval",
    "END": "Finish line",
    "ERA": "Long stretch of history",
    "EYE": "Hole in a needle",
    "FAN": ["Supporter in the stands", "It cools a room"],
    "FAR": "A long way off",
    "FAT": "Butter's makeup",
    "FED": "Gave dinner to",
    "FEE": "Charge for service",
    "FEW": "Not many",
    "FIG": "Fruit in a Newton",
    "FIT": ["In good shape", "The right size"],
    "FIX": "Repair",
    "FLY": "Take to the sky",
    "FOG": "Low cloud on the road",
    "FOR": "In favour of",
    "FOX": "Bushy-tailed prowler",
    "FUN": "A good time",
    "FUR": "Cat's coat",
    "GAP": "Space between two teeth",
    "GAS": "What you fill the tank with",
    "GEL": "Hair goop",
    "GEM": "Stone in a ring",
    "GET": "Obtain",
    "GIG": "One night's work for a band",
    "GOD": "Deity",
    "GOT": "Received",
    "GUY": "Fellow",
    "GYM": "Where the treadmills are",
    "HAD": "Possessed",
    "HAM": "Deli meat",
    "HAS": "Owns",
    "HAT": "Head topper",
    "HER": "Belonging to a woman",
    "HIM": "That fellow",
    "HIP": "Joint above the thigh",
    "HIS": "Belonging to a man",
    "HIT": "Chart-topper",
    "HOP": "Little jump",
    "HOT": "Like fresh coffee",
    "HOW": "In what way",
    "HUB": "Centre of the wheel",
    "ICE": "Rink surface",
    "ILL": "Under the weather",
    "INK": "What a pen runs out of",
    "INN": "Small roadside hotel",
    "ITS": "Possessive with no apostrophe",
    "JAM": "Toast topper, or a traffic mess",
    "JAR": "Pickle holder",
    "JET": "Fast plane",
    "JOB": "Day work",
    "JOY": "Pure delight",
    "KEY": ["It opens a lock", "Legend on a map"],
    "KID": "Young goat, or a young person",
    "KIT": "Set of tools",
    "LAB": "Room with beakers",
    "LAP": "One circuit of the track",
    "LAW": "What Parliament passes",
    "LAY": "Put down",
    "LED": "Showed the way",
    "LEG": "Part of a journey, or of a table",
    "LET": "Allow",
    "LIP": "Mug's rim",
    "LOG": ["Firewood piece", "Keep a record"],
    "LOT": "A great deal",
    "LOW": "Near the ground",
    "MAD": "Furious",
    "MAN": "Grown fellow",
    "MAP": "Fold-out guide",
    "MAT": "Wipe your feet on it",
    "MAY": "Month of flowers",
    "MEN": "Grown fellows",
    "MET": "Ran into",
    "MID": "Halfway through",
    "MIN": "Sixty seconds, on a label",
    "MIX": "Stir together",
    "MOM": "Mum, over there",
    "NEW": "Fresh out of the box",
    "NOR": "Neither's partner",
    "NOT": "Negative word",
    "NUT": "Bolt's partner",
    "OAK": "Acorn tree",
    "ODD": "Not divisible by two",
    "OFF": "Switched the other way",
    "OIL": "Olive or engine",
    "OLD": "Been around a while",
    "ONE": "Single",
    "OPT": "Choose",
    "OUR": "Belonging to us",
    "OUT": "Not in",
    "OWN": "Have to your name",
    "PAD": "Notepad",
    "PAL": "Buddy",
    "PAN": "Skillet",
    "PAR": "Golf standard",
    "PAT": "Gentle tap",
    "PAY": "Settle the bill",
    "PEN": "Ink holder",
    "PER": "For each",
    "PET": "Cat or dog",
    "PIC": "Snapshot, informally",
    "PIE": "Slice of dessert",
    "PIG": "Farm oinker",
    "PIN": "Sharp little fastener",
    "PIT": ["Peach centre", "Where the race cars stop"],
    "POP": "Balloon sound",
    "POT": "It goes on the stove",
    "PRO": "Not an amateur",
    "PUB": "Place for a pint",
    "PUT": "Place",
    "RAN": "Sprinted",
    "RAP": "Sharp knock",
    "RAT": "Sewer dweller",
    "RAW": "Uncooked",
    "RAY": "Beam of light",
    "RED": "Stop sign colour",
    "RID": "Free of",
    "RIM": "Edge of a glass",
    "RIP": "Tear",
    "ROD": "Fishing pole",
    "ROW": ["Line of seats", "Use the oars"],
    "RUG": "Floor covering",
    "RUN": "Jog fast",
    "SAD": "Blue",
    "SAP": "Maple syrup source",
    "SAT": "Took a seat",
    "SAW": "Toothy tool",
    "SAY": "Speak",
    "SEA": "Salty expanse",
    "SEE": "Take a look",
    "SET": "Ready, ___, go",
    "SHE": "Pronoun for Misha",
    "SHY": "Bashful",
    "SIN": "Moral slip",
    "SIR": "Polite address to a gentleman",
    "SIT": "Take a chair",
    "SIX": "Half a dozen",
    "SKI": "Head down the slope",
    "SKY": "The blue above",
    "SON": "Male child",
    "SPA": "Place for a massage",
    "SPY": "One who watches quietly",
    "SUB": "Sandwich, or a boat that dives",
    "SUM": "Total",
    "SUN": "The star we orbit",
    "TAB": "Bar bill",
    "TAG": "You're it!",
    "TAN": "Colour from a beach day",
    "TAP": "Light knock, or a faucet",
    "TAR": "Black road goo",
    "TAX": "April obligation",
    "TEA": "Earl Grey, e.g.",
    "TEE": "Golf ball's perch",
    "TEN": "Perfect score",
    "THE": "Commonest word in English",
    "TIE": "Game with no winner",
    "TIN": "Metal for a can",
    "TIP": "Extra for the server",
    "TOE": "Digit in a sock",
    "TON": "Two thousand pounds",
    "TOO": "Also",
    "TOP": "Highest point",
    "TOY": "Playroom item",
    "TRY": "Give it a shot",
    "TUB": "Where the bubble bath goes",
    "TWO": "A pair's count",
    "USE": "Put to work",
    "VAN": "Delivery vehicle",
    "WAX": "Candle stuff",
    "WAY": "Route",
    "WEB": "Spider's work",
    "WED": "Get married",
    "WET": "Soaked",
    "WHO": "Question about identity",
    "WHY": "Question about reason",
    "WIN": "Come first",
    "WOW": "That's amazing!",
    "YES": "Affirmative",
    "YET": "So far",
    "YOU": "The one reading this",
    "ZIP": "Nothing at all",
    "ZOO": "Where the lions live",

    # ---- 4 letters -------------------------------------------------------------
    "ACES": "Serves that can't be returned",
    "ACID": "Vinegar, chemically",
    "ACRE": "Field measure",
    "ACTS": "Divisions of a drama",
    "AGED": "Grown older, as cheese",
    "AGES": "Takes forever",
    "AIDE": "Assistant",
    "AIMS": "Goals",
    "ALSO": "In addition",
    "AREA": "Length times width",
    "ARMS": "What a hug uses",
    "ARTS": "Liberal ___",
    "ATOM": "Smallest bit of an element",
    "AUNT": "Mum's sister",
    "AUTO": "Vehicle, for short",
    "AWAY": "Not at home",
    "BABY": "Newborn",
    "BACK": "Opposite of front",
    "BAND": "Four with guitars",
    "BANG": "Loud noise",
    "BANK": "Where the money sits",
    "BARE": "Uncovered",
    "BARN": "Red farm building",
    "BASE": "Bottom support",
    "BATH": "Long soak",
    "BEAD": "Necklace bit",
    "BEAM": "Ray, or a wide smile",
    "BEAN": "Coffee starts as one",
    "BEAR": ["Woods wanderer", "Put up with"],
    "BEAT": "Rhythm unit",
    "BEDS": "Bedroom furniture",
    "BEEF": "Steak source",
    "BEER": "Pint at the pub",
    "BELL": "It rings",
    "BELT": "Trouser holder-upper",
    "BEND": "Curve in the road",
    "BENT": "No longer straight",
    "BEST": "Top of the class",
    "BIKE": "Two-wheeler",
    "BILL": "What arrives at the end of a meal",
    "BIND": "Tie up",
    "BIRD": "Robin or wren",
    "BITE": "Quick mouthful",
    "BITS": "Small pieces",
    "BLUE": "Sky colour",
    "BOAT": "It floats",
    "BODY": "Head to toe",
    "BOLD": "Daring, or a heavy typeface",
    "BOLT": "It comes with a nut",
    "BOND": "Close connection",
    "BONE": "Skeleton piece",
    "BOOK": "Thing with chapters",
    "BOOM": "Distant thunder sound",
    "BOOT": "Ankle-covering shoe",
    "BORN": "Newly arrived",
    "BOSS": "The one in charge",
    "BOTH": "The two of them",
    "BOWL": "Cereal holder",
    "BRAN": "Fibre in cereal",
    "BUCK": "Male deer",
    "BULB": "It goes in a lamp",
    "BULK": "Sold in large quantity",
    "BULL": "Rodeo beast",
    "BUMP": "Small rise in the road",
    "BURN": "What a candle does",
    "BUSY": "Run off your feet",
    "CAFE": "Place for a flat white",
    "CAGE": "Hamster's home",
    "CAKE": "Birthday dessert",
    "CALL": "Ring up",
    "CALM": "Unruffled",
    "CAME": "Turned up",
    "CAMP": "Tents in a field",
    "CAMPS": "Summer getaways for kids",
    "CANE": "Walking stick",
    "CAPE": "Superhero's back flap",
    "CAPS": "Baseball headwear",
    "CARD": "It comes with a birthday gift",
    "CARE": "Give a hoot",
    "CARS": "What a garage holds",
    "CART": "Shopping trolley",
    "CASE": "Detective's assignment",
    "CASH": "Notes and coins",
    "CAST": "Everyone in the play",
    "CATS": "Nine-lived pets",
    "CAVE": "Bat's home",
    "CELL": "Building block of life",
    "CENT": "Penny",
    "CHAP": "Fellow, in Britain",
    "CHAT": "Little talk",
    "CHEF": "One in the kitchen whites",
    "CHIP": "Crisp, over there",
    "CITE": "Quote a source",
    "CITY": "Big built-up place",
    "CLAN": "Extended family group",
    "CLIP": "Short bit of video",
    "CLUB": "Group you join",
    "CLUE": "Hint for a solver",
    "COAL": "Black fuel",
    "COAT": "Winter layer",
    "COATS": "Winter wear",
    "CODE": "Secret writing",
    "COIL": "Loop of wire",
    "COIN": "Pocket money",
    "COLD": "Like the Arctic",
    "COME": "Arrive",
    "CONE": "Ice cream holder",
    "COOK": "Make dinner",
    "COOL": "Mildly cold",
    "COPE": "Manage somehow",
    "COPY": "Duplicate",
    "CORD": "Length of flex",
    "CORE": "Apple's centre",
    "CORK": "Bottle stopper",
    "CORN": "Cob crop",
    "COST": "Price tag",
    "COVE": "Sheltered little bay",
    "CREW": "Boat's team",
    "CROP": "What the farmer harvests",
    "CROW": "Black cawing bird",
    "CUBE": "Six-sided solid",
    "CURE": "Fix for an illness",
    "CUTE": "Adorable",
    "CUTS": "Trims",
    "DAMP": "A little wet",
    "DARE": "Double ___",
    "DARK": "Lights out",
    "DASH": "Short sprint, or a punctuation mark",
    "DATA": "Numbers to crunch",
    "DATE": "Day on a calendar",
    "DAWN": "First light",
    "DAYS": "Weeks are made of them",
    "DEAL": "Bargain",
    "DEAN": "College official",
    "DEAR": "Beloved",
    "DEBT": "Money owed",
    "DECK": "Cards, all together",
    "DEED": "Something done",
    "DEEP": "Far down",
    "DEER": "Woodland grazer",
    "DENY": "Refuse flatly",
    "DESK": "Where the laptop sits",
    "DIAL": "Old phone's face",
    "DICE": "Cubes for a board game",
    "DIET": "Eating plan",
    "DISH": "Plate, or a recipe",
    "DIVE": "Head into the pool",
    "DOCK": "Where the boat ties up",
    "DOES": "Carries out",
    "DOLL": "Toy figure",
    "DOME": "Rounded roof",
    "DONE": "Finished",
    "DOOR": "You knock on it",
    "DOSE": "Amount of medicine",
    "DOTS": "Ellipsis parts",
    "DOWN": "Toward the floor",
    "DRAG": "Pull along",
    "DRAW": "Sketch",
    "DREW": "Sketched",
    "DROP": "Bit of rain",
    "DRUM": "Kit piece you hit",
    "DUCK": "Pond paddler",
    "DUES": "Membership payments",
    "DULL": "Not sharp, not fun",
    "DUSK": "Just before dark",
    "DUST": "What a cloth removes",
    "DUTY": "Obligation",
    "EACH": "Every one",
    "EARN": "Work for it",
    "EARS": "Corn parts, or listeners",
    "EASE": "Comfort",
    "EAST": "Where the sun comes up",
    "EASY": "No trouble at all",
    "ECHO": "Sound bouncing back",
    "EDGE": "Rim of the cliff",
    "EDIT": "Tidy up a draft",
    "EGGS": "Dozen in a carton",
    "ELSE": "Otherwise",
    "ENDS": "Finishes",
    "EPIC": "Long adventure tale",
    "EURO": "Money in Madrid",
    "EVEN": "Divisible by two",
    "EVER": "At any time",
    "EVIL": "Wicked",
    "EXAM": "Big test",
    "EXIT": "Way out",
    "EXPO": "Big trade show",
    "EYED": "Looked over",
    "EYES": "They can go sore",
    "FACE": "Front of the head",
    "FACT": "Something true",
    "FADE": "Slowly disappear",
    "FAIL": "Not pass",
    "FAIR": "Just, or a funfair",
    "FAKE": "Not genuine",
    "FALL": "Autumn",
    "FAME": "Being widely known",
    "FANS": "People in the stands",
    "FARE": "Bus ticket price",
    "FARM": "Where the crops are",
    "FAST": "Quick",
    "FATE": "What's meant to be",
    "FEAR": "Dread",
    "FEAT": "Impressive achievement",
    "FEED": "Give dinner to",
    "FEEL": "Sense by touch",
    "FEES": "Charges on a bill",
    "FEET": "Twelve inches, twice",
    "FELL": "Took a tumble",
    "FELT": "Sensed",
    "FILE": "Folder's contents",
    "FILL": "Top up",
    "FILM": "Movie",
    "FIND": "Come across",
    "FINE": "Perfectly all right",
    "FIRE": "Campfire",
    "FIRM": "Solid, or a business",
    "FISH": "Angler's catch",
    "FIST": "Closed hand",
    "FITS": "Is the right size",
    "FIVE": "Fingers on a hand",
    "FLAG": "It flies on a pole",
    "FLAT": "Level",
    "FLEE": "Run for it",
    "FLEW": "Went by air",
    "FLIP": "Turn over",
    "FLOW": "Move like a river",
    "FOAM": "Bubbles on a latte",
    "FOIL": "Kitchen wrap",
    "FOLD": "Crease in half",
    "FOLK": "Ordinary people",
    "FOND": "Warmly attached",
    "FONT": "Helvetica, for one",
    "FOOD": "What's for dinner",
    "FOOL": "Silly one",
    "FOOT": "Twelve inches",
    "FORK": "Table utensil",
    "FORM": "Paperwork to fill in",
    "FORT": "Walled stronghold",
    "FOUR": "Legs on a chair",
    "FREE": "Costing nothing",
    "FROG": "Lily pad hopper",
    "FUEL": "What the tank holds",
    "FULL": "No room left",
    "FUND": "Pot of money",
    "GAIN": "Put on, as weight",
    "GAME": "Match",
    "GANG": "Group that runs together",
    "GATE": "Garden entrance",
    "GAVE": "Handed over",
    "GEAR": "Kit for a trip",
    "GEMS": "Ring stones",
    "GIFT": "Wrapped surprise",
    "GIRL": "Young lass",
    "GIVE": "Hand over",
    "GLAD": "Pleased",
    "GLUE": "Sticky stuff",
    "GOAL": "What the striker scores",
    "GOAT": "Cliff-climbing bleater",
    "GOES": "Departs",
    "GOLD": "First-place metal",
    "GOLF": "Game of eighteen holes",
    "GONE": "No longer here",
    "GOOD": "Not bad at all",
    "GRAB": "Snatch",
    "GRAM": "Metric weight",
    "GREW": "Got bigger",
    "GREY": "Colour of a rain cloud",
    "GRID": "Crossing lines",
    "GRIP": "Firm hold",
    "GROW": "Get bigger",
    "GULF": "Big bay",
    "HAIR": "What a brush is for",
    "HALF": "Fifty per cent",
    "HALL": "Corridor",
    "HAND": "Five fingers",
    "HANG": "Suspend",
    "HARD": "Tough going",
    "HARM": "Damage",
    "HARP": "Angel's instrument",
    "HATE": "Can't stand",
    "HATS": "Head toppers",
    "HAVE": "Possess",
    "HEAD": "Where the hat goes",
    "HEAL": "Get better",
    "HEAR": "Catch a sound",
    "HEAT": "Warmth",
    "HELD": "Kept a grip on",
    "HELP": "Lend a hand",
    "HERB": "Basil, e.g.",
    "HERE": "Present!",
    "HERO": "One who saves the day",
    "HIDE": "Keep out of sight",
    "HIGH": "Up above",
    "HILL": "Small rise",
    "HINT": "Nudge in the right direction",
    "HIRE": "Take on for a job",
    "HITS": "Chart favourites",
    "HOLD": "Keep in your hands",
    "HOLE": "Gap in a sock",
    "HOME": "Where you hang your hat",
    "HOOK": "Coat hanger on a wall",
    "HOPE": "Wish for the best",
    "HORN": "Trumpet, or a car's honker",
    "HOSE": "Garden watering tube",
    "HOST": "Party thrower",
    "HOUR": "Sixty minutes",
    "HUGE": "Enormous",
    "HUNT": "Search hard",
    "HURT": "Cause pain",
    "ICON": "Little picture on a screen",
    "IDEA": "Light bulb moment",
    "IDLE": "Doing nothing",
    "INCH": "Twelfth of a foot",
    "INFO": "Details, briefly",
    "INNS": "Small roadside hotels",
    "IRON": "Metal, or a wrinkle remover",
    "ISLE": "Bit of land in a lake",
    "ITEM": "One thing on a list",
    "JADE": "Green stone",
    "JAIL": "Lock-up",
    "JAZZ": "Music with improvisation",
    "JEEP": "Rugged four-wheeler",
    "JOBS": "Positions on offer",
    "JOIN": "Become a member",
    "JOKE": "Something with a punchline",
    "JUMP": "Leap",
    "JUNE": "Month after May",
    "JURY": "Twelve in a box",
    "JUST": "Only",
    "KEEN": "Very enthusiastic",
    "KEEP": "Hold on to",
    "KEPT": "Held on to",
    "KEYS": "Ring of metal openers",
    "KICK": "Boot the ball",
    "KIDS": "The little ones",
    "KIND": "Type, or thoughtful",
    "KISS": "Peck on the cheek",
    "KITE": "Thing on a string",
    "KITS": "Sets of parts",
    "KNEE": "Joint that bends",
    "KNEW": "Was aware of",
    "KNIT": "Work with wool",
    "KNOW": "Be certain of",
    "LACE": "Delicate fabric",
    "LACK": "Be short of",
    "LADY": "Woman",
    "LAID": "Put down",
    "LAKE": "Inland water",
    "LAMB": "Spring farm arrival",
    "LAMP": "Bedside light",
    "LAND": "Touch down",
    "LANE": "Narrow road",
    "LAST": "Final",
    "LATE": "Behind schedule",
    "LAWN": "Grass to mow",
    "LAWS": "Rules with teeth",
    "LAZY": "Not inclined to move",
    "LEAD": "Go first",
    "LEAF": "It falls in autumn",
    "LEAK": "Slow drip",
    "LEAN": "Tilt",
    "LEAP": "Big jump",
    "LEFT": "Opposite of right",
    "LEGS": "A table has four",
    "LENS": "Glass in a camera",
    "LESS": "Fewer",
    "LETS": "Permits",
    "LIES": "Untruths",
    "LIFE": "Birth to death",
    "LIFT": "Raise up",
    "LIKE": "Be fond of",
    "LIME": "Green citrus",
    "LINE": "Queue",
    "LINK": "Chain piece",
    "LION": "Big cat with a mane",
    "LIPS": "Mouth's border",
    "LIST": "Things written in order",
    "LIVE": "Not recorded",
    "LOAD": "What the truck carries",
    "LOAN": "Money to be paid back",
    "LOCK": "Key's counterpart",
    "LOGO": "Brand mark",
    "LONE": "All by itself",
    "LONG": "Not short",
    "LOOK": "Have a glance",
    "LOOP": "Circle of rope",
    "LOSE": "Fail to win",
    "LOSS": "Defeat",
    "LOST": "Can't find the way",
    "LOTS": "Plenty",
    "LOUD": "Turn it down!",
    "LOVE": "Deep affection",
    "LUCK": "Fortune",
    "MADE": "Built",
    "MAID": "Household helper",
    "MAIL": "What the postman brings",
    "MAIN": "Chief",
    "MAKE": "Build",
    "MALE": "Not female",
    "MALL": "Shops under one roof",
    "MANY": "A great number",
    "MAPS": "Atlas contents",
    "MARK": "Small stain",
    "MASK": "Face cover",
    "MASS": "Amount of matter",
    "MATE": "Friend, in Australia",
    "MATH": "Numbers class",
    "MEAL": "Breakfast, lunch or dinner",
    "MEAN": "Unkind, or the average",
    "MEAT": "Butcher's stock",
    "MEET": "Get together",
    "MELT": "Turn to liquid",
    "MENU": "List of dishes",
    "MERE": "Nothing more than",
    "MESH": "Netting",
    "MESS": "Disaster area",
    "MICE": "Cheese nibblers",
    "MILD": "Not spicy",
    "MILE": "Sixteen hundred metres, roughly",
    "MILK": "Cereal's partner",
    "MILL": "Where the flour is ground",
    "MIND": "What thinks",
    "MINE": "Belonging to me",
    "MINI": "Small version",
    "MINT": "Herb in a mojito",
    "MISS": "Fail to catch",
    "MOOD": "How you're feeling",
    "MOON": "It waxes and wanes",
    "MORE": "Additional",
    "MOSS": "Green carpet on a rock",
    "MOST": "The largest part",
    "MOVE": "Change position",
    "MUCH": "A great deal",
    "MUST": "Have to",
    "MYTH": "Old story, or a false belief",
    "NAIL": "Hammer's target",
    "NAME": "What you're called",
    "NAVY": "Fleet, or a dark blue",
    "NEAR": "Close by",
    "NEAT": "Tidy",
    "NECK": "Head's support",
    "NEED": "Must have",
    "NEON": "Bright sign gas",
    "NEST": "Twiggy home",
    "NETS": "What goalkeepers guard",
    "NEWS": "What's happening",
    "NEXT": "Following",
    "NICE": "Pleasant",
    "NINE": "Cats' lives count",
    "NODE": "Point in a network",
    "NONE": "Not a single one",
    "NOON": "Middle of the day",
    "NOSE": "Smeller",
    "NOTE": "Short message",
    "NOVA": "Star that suddenly brightens",
    "OAKS": "Acorn trees",
    "OATS": "Porridge grain",
    "OBEY": "Do as told",
    "ODDS": "Chances",
    "OKAY": "Fine by me",
    "ONCE": "A single time",
    "ONES": "Digits before twos",
    "ONLY": "Nothing but",
    "ONTO": "Up on top of",
    "OPEN": "Not shut",
    "ORAL": "Spoken, not written",
    "OVAL": "Egg shape",
    "OVEN": "Where the roast goes",
    "OVENS": "Bakery fixtures",
    "OVER": "Finished",
    "OWES": "Has to pay back",
    "OWNS": "Has to their name",
    "PACE": "Walking speed",
    "PACK": "Fill the suitcase",
    "PAGE": "Sheet in a book",
    "PAID": "Settled up",
    "PAIN": "Ache",
    "PAIR": "Two of a kind",
    "PALE": "Washed out",
    "PALM": "Beach tree, or part of a hand",
    "PARK": "Green space in a city",
    "PART": "Piece of a whole",
    "PASS": "Go by",
    "PAST": "Days gone by",
    "PATH": "Walking track",
    "PAWS": "Cat's feet",
    "PEAK": "Mountain top",
    "PEAR": "Fruit shaped like a teardrop",
    "PEAS": "Green pods' contents",
    "PECK": "Bird's quick bite",
    "PEER": "Look closely",
    "PENS": "Ink holders",
    "PEST": "Nuisance",
    "PETS": "Household animals",
    "PICK": "Choose",
    "PICS": "Snapshots, informally",
    "PIER": "Walkway over the water",
    "PIES": "Bakery rounds",
    "PIGS": "Sty dwellers",
    "PILE": "Heap",
    "PILL": "Tablet to swallow",
    "PINE": "Evergreen tree",
    "PINK": "Colour of candy floss",
    "PINS": "Sewing sharps",
    "PIPE": "Plumber's tube",
    "PLAN": "Way forward",
    "PLAY": "What children do",
    "PLOT": "Story's arc",
    "PLUG": "Wall socket's partner",
    "PLUS": "Added to",
    "POEM": "Verse",
    "POET": "Verse writer",
    "POLE": "Flag's post",
    "POLL": "Survey of opinion",
    "POND": "Duck's water",
    "PONY": "Small horse",
    "POOL": "Place for a swim",
    "POOR": "Short of money",
    "PORE": "Tiny skin opening",
    "PORT": "Harbour",
    "POSE": "Hold still for a photo",
    "POST": "Send by mail",
    "POUR": "Tip out the milk",
    "PRAY": "Speak to the heavens",
    "PREP": "Get ready",
    "PROP": "Thing an actor holds",
    "PULL": "Tug",
    "PUMP": "It moves water",
    "PURE": "Nothing added",
    "PUSH": "Shove",
    "QUIT": "Give up",
    "QUIZ": "Short test",
    "RACE": "Sprint to the line",
    "RACK": "Shelf for coats",
    "RAIL": "Train track piece",
    "RAIN": "Wet weather",
    "RAMP": "Slope up to a door",
    "RANK": "Position in an order",
    "RARE": "Hardly ever seen",
    "RATE": "Speed, or a charge",
    "RATS": "Sewer dwellers",
    "READ": "Get through a book",
    "REAL": "Genuine",
    "REAP": "Bring in the harvest",
    "REAR": "Back end",
    "REED": "Clarinet part",
    "REEF": "Coral ridge",
    "RELY": "Depend",
    "RENT": "Monthly payment to a landlord",
    "REST": "Take five",
    "RICE": "Grain in a risotto",
    "RICH": "Loaded",
    "RIDE": "Go by bike",
    "RING": "Circle for a finger",
    "RIPE": "Ready to eat",
    "RISE": "Go up",
    "RISK": "Chance of trouble",
    "ROAD": "Route with tarmac",
    "ROBE": "Bathroom wrap",
    "ROCK": "Stone",
    "ROLE": "Part in a play",
    "ROLL": "Bread bun",
    "ROOF": "Top of the house",
    "ROOM": "Space with four walls",
    "ROOT": "Underground part of a plant",
    "ROPE": "Thick cord",
    "ROSE": "Valentine's flower",
    "ROWS": "Lines of seats",
    "RUGS": "Floor coverings",
    "RUIN": "Wreck",
    "RULE": "Regulation",
    "RUSH": "Hurry",
    "RUST": "Orange metal decay",
    "SAFE": "Out of harm's way",
    "SAID": "Uttered",
    "SAIL": "Catch the wind",
    "SAKE": "For heaven's ___",
    "SALE": "Half-price event",
    "SALT": "Shaker filler",
    "SAME": "Identical",
    "SAND": "Beach stuff",
    "SANE": "Of sound mind",
    "SAVE": "Put aside for later",
    "SAYS": "States",
    "SCAN": "Read quickly",
    "SEAL": "Beach barker, or to close up",
    "SEAS": "Salty expanses",
    "SEAT": "Chair",
    "SEED": "What you plant",
    "SEEK": "Search for",
    "SEEM": "Appear",
    "SEEN": "Laid eyes on",
    "SELF": "Your own person",
    "SELL": "Trade for money",
    "SEMI": "Half, as a prefix",
    "SEND": "Ship off",
    "SENT": "Dispatched",
    "SETS": "Tennis match parts",
    "SHED": "Garden hut",
    "SHIP": "Ocean vessel",
    "SHOE": "Foot's cover",
    "SHOP": "Store",
    "SHOT": "Attempt at goal",
    "SHOW": "Programme",
    "SHUT": "Closed",
    "SIDE": "Fries, e.g.",
    "SIGN": "Notice on a post",
    "SILK": "Smooth luxurious fabric",
    "SING": "Carry a tune",
    "SINK": "Kitchen basin",
    "SITE": "Building plot",
    "SITS": "Takes a chair",
    "SIZE": "Small, medium or large",
    "SKIN": "Body's largest organ",
    "SLAM": "Close hard",
    "SLIP": "Lose your footing",
    "SLOT": "Coin's opening",
    "SLOW": "Not quick",
    "SNAP": "Break sharply",
    "SNOW": "Winter's white fall",
    "SOAP": "It goes with water",
    "SOFA": "Living room seat",
    "SOFT": "Like a pillow",
    "SOIL": "Garden dirt",
    "SOLD": "No longer available",
    "SOLE": "Bottom of a shoe",
    "SOLO": "All on your own",
    "SOME": "A few",
    "SONG": "Tune with words",
    "SOON": "Before long",
    "SORE": "Aching",
    "SORT": "Kind",
    "SOUL": "Inner spirit",
    "SOUP": "Bowl of broth",
    "SOUR": "Like a lemon",
    "SPAN": "Reach from end to end",
    "SPIN": "Turn round fast",
    "SPOT": "Small mark",
    "STAR": "Twinkler",
    "STAY": "Remain",
    "STEM": "Flower's stalk",
    "STEP": "Stair",
    "STIR": "Give the pot a turn",
    "STOP": "Halt",
    "SUCH": "Of that kind",
    "SUIT": "Jacket and trousers",
    "SURE": "Certain",
    "SWAN": "Graceful white bird",
    "SWIM": "Do lengths",
    "TAGS": "Price labels",
    "TAIL": "Dog's wagger",
    "TAKE": "Grab hold of",
    "TALE": "Story",
    "TALK": "Have a word",
    "TALL": "High up",
    "TANK": "Fish's home",
    "TANKS": "Fish homes",
    "TAPE": "Sticky roll",
    "TASK": "Job to do",
    "TEAL": "Blue-green",
    "TEAM": "Eleven on a pitch",
    "TEAR": "Rip",
    "TELL": "Let in on it",
    "TEND": "Look after",
    "TENT": "Camper's shelter",
    "TERM": "Word or phrase",
    "TEST": "Exam",
    "TEXT": "Words on the page",
    "THAN": "Comparison word",
    "THAT": "Not this",
    "THEM": "Those people",
    "THEN": "At that time",
    "THIN": "Not thick",
    "THIS": "Not that",
    "THUS": "Therefore",
    "TIDE": "The sea's rise and fall",
    "TIED": "Knotted",
    "TIER": "Layer of a cake",
    "TIES": "Knots",
    "TILE": "Bathroom square",
    "TILL": "Shop's cash drawer",
    "TIME": "What a clock shows",
    "TINY": "Very small",
    "TIPS": "Handy hints",
    "TIRE": "Wear out",
    "TOES": "Digits in socks",
    "TOLD": "Let in on it",
    "TOLL": "Bridge charge",
    "TOMB": "Burial chamber",
    "TONE": "Shade of colour",
    "TONS": "A great many",
    "TOOK": "Grabbed",
    "TOOL": "Hammer, e.g.",
    "TOPS": "Beats",
    "TORN": "Ripped",
    "TORT": "Legal wrong",
    "TOUR": "Trip with stops",
    "TOWN": "Smaller than a city",
    "TOYS": "Playroom items",
    "TRAP": "Snare",
    "TRAY": "Cafeteria carrier",
    "TREE": "Oak or elm",
    "TREK": "Long hike",
    "TRIM": "Cut back",
    "TRIO": "Group of three",
    "TRIP": "Journey",
    "TRUE": "Not false",
    "TUBE": "Hollow cylinder",
    "TUNE": "Melody",
    "TURN": "Your go",
    "TWIN": "Sibling born the same day",
    "TYPE": "Sort, or to key in",
    "UGLY": "Not easy on the eye",
    "UNDO": "Reverse it",
    "UNIT": "One of a set",
    "UPON": "Once ___ a time",
    "URGE": "Strong impulse",
    "USED": "Second-hand",
    "USER": "One at the keyboard",
    "USES": "Puts to work",
    "VAST": "Enormous",
    "VERY": "Extremely",
    "VIEW": "What you see from the window",
    "VOID": "Empty space",
    "VOLT": "Electrical unit",
    "VOTE": "Mark the ballot",
    "WAGE": "Weekly pay",
    "WAIT": "Hang on",
    "WAKE": "Get up",
    "WALK": "Go on foot",
    "WALL": "Room's side",
    "WANT": "Wish for",
    "WARD": "Hospital section",
    "WARM": "Nicely heated",
    "WASH": "Clean with water",
    "WAVE": "Hello from a distance",
    "WAYS": "Routes",
    "WEAK": "Not strong",
    "WEAR": "Have on",
    "WEED": "Unwanted plant",
    "WEEK": "Seven days",
    "WELL": "Water source",
    "WENT": "Departed",
    "WERE": "Existed, plurally",
    "WEST": "Where the sun sets",
    "WHAT": "Question word",
    "WHEN": "At what time",
    "WHOM": "Formal object pronoun",
    "WIDE": "Broad",
    "WIFE": "Married woman",
    "WILD": "Untamed",
    "WILL": "Shall",
    "WIND": "Breeze, stronger",
    "WINE": "Red or white",
    "WING": "Bird's flier",
    "WINS": "Comes first",
    "WIRE": "Metal thread",
    "WISE": "Full of good sense",
    "WISH": "Hope for",
    "WOOD": "Log's material",
    "WOOL": "Sheep's coat",
    "WORD": "Unit of a sentence",
    "WORK": "The day job",
    "WORM": "Soil wriggler",
    "WORN": "Threadbare",
    "YARD": "Three feet",
    "YARN": "Knitter's supply",
    "YEAR": "Twelve months",
    "ZERO": "Nothing",
    "ZINC": "Galvanising metal",
    "ZONE": "Marked-off area",
    "ZOOM": "Move in close",

    # ---- 5 letters -------------------------------------------------------------
    "ABOVE": "Higher than",
    "ABOUT": "Roughly",
    "ACRES": "Field measures",
    "ACTOR": "One on the stage",
    "ACUTE": "Sharp, as an angle under 90 degrees",
    "ADOPT": "Take on as your own",
    "ADULT": "Grown-up",
    "AGAIN": "One more time",
    "AGENT": "One who acts for you",
    "AGILE": "Quick on one's feet",
    "AGREE": "See eye to eye",
    "AHEAD": "Out in front",
    "ALARM": "It goes off at six",
    "ALBUM": "Collection of songs",
    "ALERT": "On the lookout",
    "ALGAE": "Pond scum",
    "ALIEN": "Little green visitor",
    "ALIVE": "Still kicking",
    "ALLOW": "Let happen",
    "ALONE": "By yourself",
    "ALONG": "Beside the way",
    "ALTER": "Change",
    "AMBER": "Traffic light between",
    "AMEND": "Change, as a constitution",
    "AMINO": "___ acid",
    "AMONG": "In the middle of",
    "ANGEL": "Winged helper",
    "ANGER": "Hot temper",
    "ANGLE": "Forty-five degrees, e.g.",
    "ANGRY": "Seeing red",
    "ANIME": "Japanese animation style",
    "APART": "Separated",
    "APPLE": "Fruit for the teacher",
    "APRON": "Cook's cover-up",
    "AREAS": "Regions on a map",
    "ARENA": "Concert venue",
    "ARGUE": "Have words",
    "ARISE": "Come up",
    "ARMED": "Carrying a weapon",
    "AROMA": "Smell of fresh bread",
    "AROSE": "Got out of bed",
    "ARRAY": "Impressive display",
    "ARROW": "It flies from a bow",
    "ASIDE": "Whispered to the audience",
    "ASHES": "Fireplace leftovers",
    "ASKED": "Popped the question",
    "ASSET": "Something valuable on the books",
    "ATLAS": "Book of maps",
    "ATOMS": "Tiny building blocks",
    "ATTIC": "Storage space up top",
    "AUDIO": "Sound track",
    "AWAKE": "Not asleep",
    "AWARD": "Prize",
    "AWARE": "Clued in",
    "BACON": "Breakfast strips",
    "BADGE": "Sheriff's star",
    "BAKER": "One who works with dough",
    "BANDS": "Groups with guitars",
    "BASIC": "Nothing fancy",
    "BASIN": "Sink",
    "BATCH": "One tray of cookies",
    "BEACH": "Sandy strip",
    "BEADS": "Necklace bits",
    "BEANS": "What's on toast, in Britain",
    "BEARD": "Face fuzz",
    "BEARS": "Woodland wanderers",
    "BEAST": "Big wild animal",
    "BEATS": "Rhythms in a bar",
    "BEGAN": "Got going",
    "BEGIN": "Get going",
    "BEGUN": "Under way",
    "BEING": "Creature",
    "BELOW": "Underneath",
    "BENCH": "Park seat",
    "BIRDS": "Robins and wrens",
    "BIRTH": "Arrival of a baby",
    "BLADE": "Knife's edge",
    "BLAME": "Point the finger at",
    "BLAND": "Needs more salt",
    "BLANK": "Empty space to fill",
    "BLAST": "Big explosion",
    "BLEND": "Mix smoothly",
    "BLIND": "Unable to see",
    "BLOCK": "Wooden cube for a toddler",
    "BLOOM": "What a flower does",
    "BOARD": "Chess surface",
    "BOAST": "Show off in words",
    "BOATS": "Things that float",
    "BONES": "Skeleton pieces",
    "BONUS": "Extra on top",
    "BOOKS": "Shelf's contents",
    "BOOST": "Give a lift",
    "BOOTH": "Cafe seat with a table",
    "BOOTS": "Wellies, e.g.",
    "BOUND": "Tied up, or a leap",
    "BOXES": "Cardboard containers",
    "BRAIN": "Thinking organ",
    "BRAKE": "Pedal that stops",
    "BRAND": "Maker's name",
    "BRASS": "Trumpet's metal",
    "BREAD": "Loaf",
    "BREAK": "Take five",
    "BREED": "Type of dog",
    "BRICK": "Wall unit",
    "BRIDE": "One in white at a wedding",
    "BRIEF": "Not long",
    "BRING": "Fetch along",
    "BROAD": "Wide",
    "BROKE": "Out of money",
    "BROOM": "Sweeper",
    "BROWN": "Colour of chocolate",
    "BRUSH": "Painter's tool",
    "BUILD": "Put together",
    "BUILT": "Constructed",
    "BUNCH": "Grapes come in one",
    "BURNT": "Left in too long",
    "BUYER": "One at the other end of a sale",
    "CABIN": "Log hut in the woods",
    "CABLE": "Thick wire",
    "CAMEL": "Desert humpback",
    "CANAL": "Man-made waterway",
    "CANDY": "Sweets, in America",
    "CANOE": "Paddle craft",
    "CARDS": "Deck's contents",
    "CARED": "Was concerned",
    "CARGO": "What a freighter carries",
    "CARRY": "Take along",
    "CASES": "Matters for a detective",
    "CATCH": "Grab in the air",
    "CAUSE": "Reason behind it",
    "CEDAR": "Fragrant wood",
    "CELLO": "Big string instrument",
    "CENTS": "Pennies",
    "CHAIN": "Links in a row",
    "CHAIR": "Thing you sit on",
    "CHALK": "Blackboard stick",
    "CHARM": "Winning appeal",
    "CHART": "Graph",
    "CHASE": "Run after",
    "CHEAP": "Costs very little",
    "CHECK": "Look over",
    "CHESS": "Game of kings and pawns",
    "CHEST": "Ribs' home, or a trunk",
    "CHIEF": "Head honcho",
    "CHILD": "Youngster",
    "CHILL": "Cool down",
    "CHIPS": "Fries, in Britain",
    "CIVIC": "To do with the town",
    "CIVIL": "Politely restrained",
    "CLAIM": "Say it's yours",
    "CLASS": "Group of pupils",
    "CLEAN": "Spotless",
    "CLEAR": "Easy to see through",
    "CLERK": "Office worker",
    "CLICK": "Mouse sound",
    "CLIFF": "Sheer drop",
    "CLIMB": "Go up",
    "CLOAK": "Long cape",
    "CLOCK": "Wall timekeeper",
    "CLONE": "Exact copy",
    "CLOSE": "Shut",
    "CLOTH": "Fabric piece",
    "CLOUD": "Where your files live now",
    "COACH": "One who trains the team",
    "COAST": "Where the land meets the sea",
    "COATS": "Winter wear",
    "COINS": "Pocket change",
    "COLOR": "Red or blue, e.g.",
    "COMES": "Turns up",
    "COMIC": "Funny one",
    "CORAL": "Reef builder",
    "COUNT": "One, two, three ...",
    "COURT": "Where tennis is played",
    "COVER": "Book's front",
    "CRACK": "Thin split",
    "CRAFT": "Skill with the hands",
    "CRANE": "Long-necked bird, or a lifting machine",
    "CRASH": "Sound of dropped dishes",
    "CRAZY": "Out of your mind",
    "CREAM": "Top of the milk",
    "CREEK": "Small stream",
    "CREPT": "Moved quietly",
    "CRIME": "What a detective solves",
    "CROPS": "Fields' yield",
    "CROSS": "Go over",
    "CROWD": "Full house",
    "CROWN": "Head of a monarch's outfit",
    "CRUSH": "Squash flat",
    "CURVE": "Bend in the road",
    "CYCLE": "Ride a bike",
    "DAILY": "Every day",
    "DAIRY": "Milk section",
    "DANCE": "Move to the beat",
    "DATES": "Days on a calendar",
    "DEALT": "Handed out the cards",
    "DEBUT": "First appearance",
    "DECAY": "Slowly rot",
    "DECOR": "Interior look",
    "DELAY": "Hold-up",
    "DENSE": "Thick, in both senses",
    "DEPTH": "How far down",
    "DEPOT": "Bus station",
    "DEVIL": "Horned troublemaker",
    "DIARY": "Where the secrets go",
    "DIRTY": "Needs a wash",
    "DITCH": "Roadside trench",
    "DIVER": "Pool plunger",
    "DOING": "In the middle of it",
    "DOUBT": "Not be sure",
    "DOZEN": "Baker's count",
    "DRAFT": "First version",
    "DRAMA": "Theatre, or a fuss",
    "DRAWN": "Sketched",
    "DREAM": "Night-time film in your head",
    "DRESS": "Frock",
    "DRIED": "Water taken out",
    "DRILL": "It makes holes",
    "DRINK": "Have a sip",
    "DRIVE": "Ambition, or a road",
    "DROPS": "Bits of rain",
    "DRUMS": "Kit pieces you hit",
    "EAGER": "Raring to go",
    "EAGLE": "Bald bird of prey",
    "EARLY": "Ahead of schedule",
    "EARTH": "Third rock from the sun",
    "EATEN": "Consumed",
    "EDGES": "Rims",
    "EDITS": "Tweaks to a draft",
    "EIGHT": "Legs on a spider",
    "ELDER": "Older one",
    "ELECT": "Vote in",
    "ELITE": "Cream of the crop",
    "EMPTY": "Nothing inside",
    "ENEMY": "The other side",
    "ENJOY": "Have a good time",
    "ENTER": "Go in",
    "ENTRY": "Way in",
    "EQUAL": "The same as",
    "ERASE": "Wipe the whiteboard",
    "ERROR": "Boo-boo",
    "EUROS": "Cash in Lisbon",
    "EVENT": "Something on the calendar",
    "EVERY": "Each and all",
    "EXACT": "Down to the last detail",
    "EXIST": "Be real",
    "EXTRA": "Movie background player",
    "FACES": "Fronts of heads",
    "FAINT": "Barely there",
    "FAITH": "Firm belief",
    "FALSE": "Not true",
    "FANCY": "Posh",
    "FARMS": "Rural spreads",
    "FAULT": "Whose mistake it was",
    "FAVOR": "Kind turn",
    "FEAST": "Enormous meal",
    "FENCE": "Garden boundary",
    "FEVER": "Raised temperature",
    "FEWER": "Not as many",
    "FIELD": "Where the crops grow",
    "FIFTH": "After fourth",
    "FIFTY": "Half a hundred",
    "FIGHT": "Scrap",
    "FINAL": "Last of all",
    "FINDS": "Comes across",
    "FIRST": "Before all others",
    "FIXED": "Repaired",
    "FLAME": "Candle's tip",
    "FLASH": "Quick burst of light",
    "FLEET": "Group of ships",
    "FLOAT": "Sit on the water",
    "FLOOD": "Too much water",
    "FLOOR": "What you stand on",
    "FLORA": "Plant life",
    "FLOUR": "Baker's white powder",
    "FLUID": "Liquid",
    "FOCUS": "Sharpen the lens",
    "FOLKS": "Ordinary people",
    "FORCE": "Push or pull",
    "FORMS": "Paperwork",
    "FORTH": "Onward",
    "FOUND": "Came across",
    "FRAME": "What holds the picture",
    "FRESH": "Just picked",
    "FROST": "Morning white on the grass",
    "FRUIT": "Apples and pears",
    "FULLY": "Completely",
    "FUNDS": "Money set aside",
    "FUNNY": "Good for a laugh",
    "GAMES": "Matches",
    "GENRE": "Horror or comedy",
    "GHOST": "Sheet with two eyeholes",
    "GIANT": "Huge one",
    "GIFTS": "Wrapped surprises",
    "GIVEN": "Handed over",
    "GIVES": "Hands over",
    "GLASS": "Window material",
    "GLOBE": "Desk model of the world",
    "GLORY": "Great renown",
    "GOALS": "What strikers score",
    "GOING": "On the way",
    "GOODS": "Things for sale",
    "GRACE": "Elegance of movement",
    "GRADE": "Mark on a paper",
    "GRAIN": "Wheat, e.g.",
    "GRAND": "A thousand bucks",
    "GRAPH": "Chart with axes",
    "GRASS": "Lawn's cover",
    "GRAVE": "Deadly serious",
    "GREAT": "Terrific",
    "GREEN": "Colour of a lawn",
    "GRILL": "Barbecue rack",
    "GROSS": "Really unpleasant",
    "GROUP": "Set of people",
    "GROVE": "Small stand of trees",
    "GROWN": "Fully developed",
    "GUARD": "One on watch",
    "GUESS": "Take a stab at it",
    "GUEST": "One at your table",
    "GUIDE": "One who leads the tour",
    "HABIT": "Hard thing to break",
    "HANDS": "Ten fingers, in two groups",
    "HANDY": "Useful to have",
    "HAPPY": "Full of cheer",
    "HARSH": "Rough and unkind",
    "HASTE": "Rush",
    "HAVEN": "Safe place",
    "HEADS": "Coin's other side",
    "HEARD": "Caught the sound of",
    "HEART": "It beats",
    "HEAVY": "Hard to lift",
    "HELLO": "Greeting at the door",
    "HENCE": "Therefore",
    "HERBS": "Basil and thyme",
    "HOBBY": "Weekend pursuit",
    "HOLES": "Eighteen on a golf course",
    "HOMES": "Places on the market",
    "HONEY": "Bee product",
    "HONOR": "Hold in high respect",
    "HOPES": "Wishes",
    "HORSE": "Derby runner",
    "HOSTS": "Party throwers",
    "HOTEL": "Place with room service",
    "HOURS": "Sixty-minute stretches",
    "HOUSE": "Two-storey dwelling",
    "HUMAN": "To err is ___",
    "HUMOR": "What a comic needs",
    "HURRY": "Get a move on",
    "IDEAL": "Perfect",
    "IDEAS": "Light bulb moments",
    "IMAGE": "Picture",
    "INDEX": "At the back of the book",
    "INNER": "Further in",
    "INPUT": "What you feed a machine",
    "IONIC": "Column style with scrolls",
    "IRONS": "Golf clubs, or wrinkle removers",
    "ISLES": "Bits of land in a lake",
    "ISSUE": "Magazine number, or a problem",
    "ITEMS": "Things on a list",
    "JEANS": "Denim trousers",
    "JOINT": "Where two bones meet",
    "JOKES": "Things with punchlines",
    "JUICE": "Breakfast squeeze",
    "KEEPS": "Holds on to",
    "KINDS": "Types",
    "KNEES": "Joints that bend",
    "KNIFE": "Fork's partner",
    "KNOWN": "Recognised",
    "KNOWS": "Is certain of",
    "LABEL": "Tag on a jar",
    "LABOR": "Hard work",
    "LADEN": "Heavily loaded",
    "LAKES": "Inland waters",
    "LANDS": "Touches down",
    "LARGE": "Big size",
    "LASER": "Focused beam",
    "LASTS": "Endures",
    "LATER": "Further on",
    "LATEX": "Glove material",
    "LAUGH": "React to a joke",
    "LAYER": "One level of a cake",
    "LEARN": "Pick up a skill",
    "LEASE": "Renter's contract",
    "LEAST": "Smallest amount",
    "LEAVE": "Head out",
    "LEMON": "Sour fruit, or a bad car",
    "LEVEL": "Perfectly flat",
    "LIGHT": "What a lamp gives",
    "LIKED": "Was fond of",
    "LIKES": "Is fond of",
    "LIMIT": "How far you can go",
    "LINEN": "Crisp summer fabric",
    "LINES": "Queues",
    "LIVED": "Made a home",
    "LIVER": "Organ that filters",
    "LIVES": "Cats have nine",
    "LOADS": "Plenty",
    "LOCAL": "From round here",
    "LODGE": "Ski chalet",
    "LOGIC": "Sound reasoning",
    "LOOKS": "Glances",
    "LOOSE": "Not tight",
    "LOVED": "Held dear",
    "LOVER": "Sweetheart",
    "LOVES": "Adores",
    "LOWER": "Bring down",
    "LOYAL": "Faithful",
    "LUCKY": "Fortune's favourite",
    "LUNCH": "Midday meal",
    "LYING": "Not telling the truth",
    "MAGIC": "Sleight of hand",
    "MAKER": "One who builds it",
    "MAKES": "Builds",
    "MALES": "Not females",
    "MANIA": "Craze",
    "MAPLE": "Syrup tree",
    "MARCH": "Walk in step",
    "MARKS": "Small stains",
    "MATCH": "Game, or a little fire stick",
    "MAYBE": "Could go either way",
    "MEALS": "Breakfast, lunch and dinner",
    "MEANS": "Signifies",
    "MEANT": "Intended",
    "MEDAL": "What a winner wears",
    "MEDIA": "The press",
    "MEETS": "Gets together with",
    "MENUS": "Lists of dishes",
    "MERCY": "Kindness to the defeated",
    "MERGE": "Join into one",
    "METAL": "Iron or tin",
    "METER": "Parking charge box",
    "METRO": "Underground, in Paris",
    "MIGHT": "Strength",
    "MINDS": "Thinking organs",
    "MINOR": "Not major",
    "MIXED": "Stirred together",
    "MODEL": "Small version of a thing",
    "MODES": "Ways of doing it",
    "MONEY": "What's in the wallet",
    "MONTH": "Thirty days, roughly",
    "MORAL": "Point of the story",
    "MOTEL": "Roadside stop for the night",
    "MOTOR": "Engine",
    "MOUNT": "Climb up on",
    "MOUSE": "Cheese nibbler",
    "MOUTH": "Where the food goes in",
    "MOVED": "Shifted",
    "MOVES": "Shifts",
    "MOVIE": "Film",
    "MUSIC": "What the band makes",
    "NAMED": "Given a title",
    "NAMES": "What people are called",
    "NASAL": "Through the nose",
    "NAVAL": "To do with the fleet",
    "NEEDS": "Must-haves",
    "NERVE": "Cheek, or a body's wire",
    "NEVER": "Not once",
    "NEWLY": "Just recently",
    "NIGHT": "Dark hours",
    "NINTH": "Inning when it's decided",
    "NOBLE": "High-minded",
    "NOISE": "Racket",
    "NOTED": "Well known",
    "NOTES": "Jottings",
    "NOVEL": "Book with chapters",
    "NURSE": "One in scrubs",
    "OCCUR": "Take place",
    "OCEAN": "Vast blue expanse",
    "OFFER": "Put on the table",
    "OFTEN": "Many times",
    "OLDER": "Further along in years",
    "OLIVE": "Martini garnish",
    "ONION": "It makes you cry",
    "ONSET": "Beginning",
    "OPENS": "Unlocks",
    "OPERA": "Aida, for one",
    "OPTIC": "To do with sight",
    "ORBIT": "Path around a planet",
    "ORDER": "Tidy arrangement",
    "ORGAN": "Church instrument",
    "OTHER": "The remaining one",
    "OUNCE": "Sixteenth of a pound",
    "OUTER": "Further out",
    "OWNED": "Had to their name",
    "OWNER": "One with the title deeds",
    "PAINT": "What a brush spreads",
    "PAIRS": "Twosomes",
    "PANDA": "Bamboo eater",
    "PANEL": "Flat board, or an expert group",
    "PANTS": "Trousers, in America",
    "PAPER": "Newsprint",
    "PARKS": "Green spaces",
    "PARTS": "Pieces",
    "PARTY": "Do with balloons",
    "PASTE": "Thick spread",
    "PATCH": "Bit sewn over a hole",
    "PATHS": "Walking tracks",
    "PATIO": "Paved bit of garden",
    "PEACE": "No more war",
    "PEACH": "Fuzzy stone fruit",
    "PEARL": "Oyster's treasure",
    "PENNY": "Copper coin",
    "PETAL": "Flower's leaf",
    "PHASE": "Stage of the moon",
    "PHONE": "It rings in your pocket",
    "PHOTO": "Snapshot",
    "PIANO": "Eighty-eight keys",
    "PIECE": "Bit of the whole",
    "PILOT": "One in the cockpit",
    "PITCH": "Football field",
    "PIVOT": "Change direction",
    "PIXEL": "Tiny screen dot",
    "PIZZA": "Round with toppings",
    "PLACE": "Spot",
    "PLAIN": "Nothing added",
    "PLANE": "It has wings",
    "PLANS": "Ways forward",
    "PLANT": "Something in a pot",
    "PLATE": "Dinner round",
    "PLAYS": "Stage works",
    "PLAZA": "Public square",
    "PLEAS": "Urgent requests",
    "POEMS": "Verses",
    "POETS": "Verse writers",
    "POINT": "Sharp end",
    "POLAR": "To do with the ice caps",
    "PONDS": "Duck waters",
    "PORTS": "Harbours",
    "POUND": "Sixteen ounces",
    "POWER": "What the grid supplies",
    "PRESS": "Push down",
    "PRICE": "What it costs",
    "PRIDE": "Lions' group, or self-regard",
    "PRINT": "Put on paper",
    "PRIOR": "Earlier",
    "PRIZE": "What the winner takes",
    "PROBE": "Investigate",
    "PROOF": "Evidence that settles it",
    "PROUD": "Pleased with yourself",
    "PROVE": "Show beyond doubt",
    "PULSE": "Beat at the wrist",
    "PUNCH": "Fruit drink, or a jab",
    "PUPIL": "One at a desk, or part of an eye",
    "QUEEN": "She wears the crown",
    "QUEST": "Long search",
    "QUICK": "Fast",
    "QUIET": "Shh!",
    "QUITE": "Rather",
    "QUOTE": "Words in inverted commas",
    "RADAR": "It sweeps the sky",
    "RADIO": "Dashboard music box",
    "RAISE": "Lift up",
    "RALLY": "Long tennis exchange",
    "RANCH": "Cattle spread",
    "RANGE": "Mountains in a row",
    "RAPID": "Very quick",
    "RATED": "Given a score",
    "RATES": "Charges",
    "RATIO": "Three to one, e.g.",
    "REACH": "Stretch out for",
    "READS": "Gets through a book",
    "READY": "All set",
    "REALM": "Kingdom",
    "REBEL": "One who won't fall in line",
    "RECAP": "Quick summary",
    "REEDS": "Riverbank grasses",
    "REEFS": "Coral ridges",
    "REFER": "Point toward",
    "REHAB": "Recovery programme",
    "RELAX": "Put your feet up",
    "RELAY": "Race with a baton",
    "RENEW": "Extend a subscription",
    "RESET": "Start over",
    "RETRO": "Deliberately old-fashioned",
    "REUSE": "Recycle's neighbour",
    "RHINO": "Horned heavyweight",
    "RIDER": "One in the saddle",
    "RIDGE": "Long crest of a hill",
    "RIGHT": "Correct",
    "RINGS": "Circles for fingers",
    "RISES": "Goes up",
    "RISKS": "Chances of trouble",
    "RIVER": "Flowing water",
    "ROADS": "Routes with tarmac",
    "ROBOT": "Machine that does the chores",
    "ROCKS": "Stones",
    "ROLES": "Parts in a play",
    "ROLLS": "Bread buns",
    "ROOMS": "Spaces with four walls",
    "ROOTS": "Underground plant parts",
    "ROSES": "Valentine's flowers",
    "ROUGH": "Not smooth",
    "ROUND": "Circular",
    "ROUTE": "Way to get there",
    "ROVER": "Machine exploring a planet",
    "ROYAL": "Fit for a queen",
    "RUGBY": "Game with an oval ball",
    "RULES": "Regulations",
    "RURAL": "Out in the country",
    "SAINT": "Very good person indeed",
    "SALAD": "Bowl of leaves",
    "SALES": "Half-price events",
    "SALON": "Where the haircut happens",
    "SANDY": "Like a beach",
    "SAUCE": "What goes on the pasta",
    "SAVED": "Put aside for later",
    "SCALE": "Bathroom truth-teller",
    "SCANS": "Reads quickly",
    "SCARE": "Give a fright",
    "SCARF": "Neck warmer",
    "SCENE": "Setting of a shot",
    "SCENT": "What a perfume gives",
    "SCOOP": "Exclusive story",
    "SCORE": "Twenty, or the final tally",
    "SCOUT": "One who goes ahead to look",
    "SCRAP": "Little bit left over",
    "SCREW": "Twisty fastener",
    "SCRUB": "Clean hard",
    "SEATS": "Places to sit",
    "SEEDS": "What you plant",
    "SEEKS": "Searches for",
    "SEEMS": "Appears",
    "SELLS": "Moves merchandise",
    "SENSE": "Sight or smell",
    "SERVE": "Start the tennis point",
    "SEVEN": "Days in a week",
    "SHADE": "Out of the sun",
    "SHAFT": "Elevator's vertical space",
    "SHAKE": "Give it a good rattle",
    "SHAPE": "Circle or square",
    "SHARE": "Give a piece to others",
    "SHARP": "Keen-edged",
    "SHEEP": "Woolly grazer",
    "SHEET": "What goes on a bed",
    "SHELF": "Where the books sit",
    "SHELL": "What a snail carries",
    "SHIFT": "Move over",
    "SHINE": "Give off light",
    "SHIRT": "It has a collar",
    "SHOCK": "Nasty surprise",
    "SHOES": "Pair for the feet",
    "SHOOT": "Fire away",
    "SHOPS": "Places to buy things",
    "SHORE": "Where the waves end",
    "SHORT": "Not tall",
    "SHOTS": "Attempts at goal",
    "SHOWN": "Displayed",
    "SHOWS": "Programmes",
    "SIDES": "Left and right",
    "SIGHT": "One of the five senses",
    "SIGNS": "Notices on posts",
    "SINCE": "From then on",
    "SIXTH": "After fifth",
    "SIZES": "Small, medium and large",
    "SKILL": "What practice builds",
    "SKIRT": "Below-the-waist garment",
    "SLEEP": "Nightly shutdown",
    "SLEPT": "Was out cold",
    "SLICE": "Cut of cake",
    "SLIDE": "Playground chute",
    "SLOTS": "Coin openings",
    "SMALL": "Little",
    "SMART": "Bright",
    "SMELL": "What a nose does",
    "SMILE": "Say cheese!",
    "SMOKE": "What rises from a fire",
    "SNAKE": "Legless slitherer",
    "SOCKS": "They go in shoes",
    "SOLAR": "Powered by the sun",
    "SOLID": "Not liquid or gas",
    "SOLVE": "Crack the puzzle",
    "SONGS": "Tunes with words",
    "SOUND": "What ears pick up",
    "SOUTH": "Down the compass",
    "SPACE": "Room to move",
    "SPARE": "Extra one, just in case",
    "SPEAK": "Say something",
    "SPEED": "How fast",
    "SPELL": "Put the letters in order",
    "SPEND": "Part with money",
    "SPICE": "Cinnamon, e.g.",
    "SPINE": "Backbone",
    "SPOKE": "Wheel part, or talked",
    "SPORT": "Football, e.g.",
    "SPOTS": "Small marks",
    "SPRAY": "Fine mist",
    "SQUAD": "Team's full list",
    "STACK": "Pancake pile",
    "STAFF": "The people who work there",
    "STAGE": "Where the actors stand",
    "STAIR": "One step of many",
    "STAMP": "It goes on the envelope",
    "STAND": "Get to your feet",
    "STARS": "Night sky dots",
    "START": "Get going",
    "STATE": "Say it plainly",
    "STEAM": "What the kettle gives off",
    "STEEL": "Strong alloy",
    "STEPS": "Stairs",
    "STICK": "Twig",
    "STILL": "Not moving",
    "STOCK": "What's on the shelves",
    "STOLE": "Took without asking",
    "STONE": "Rock",
    "STOOD": "Got to their feet",
    "STOPS": "Halts",
    "STORE": "Shop",
    "STORM": "Thunder and lightning",
    "STORY": "Tale",
    "STOVE": "Where the pot goes",
    "STRAP": "Backpack part",
    "STRAW": "Sipping tube",
    "STRIP": "Long narrow piece",
    "STUDS": "Wall framing pieces",
    "STUDY": "Hit the books",
    "STUFF": "Odds and ends",
    "STUNT": "Risky move in a film",
    "STYLE": "Way of doing it with flair",
    "SUGAR": "Sweetener in the bowl",
    "SUITE": "Set of rooms",
    "SUITS": "Jackets and trousers",
    "SUPER": "Terrific",
    "SWEET": "Sugary",
    "SWING": "Playground seat on ropes",
    "SWORD": "Knight's blade",
    "TABLE": "It has four legs",
    "TAKEN": "Already spoken for",
    "TAKES": "Grabs hold of",
    "TALES": "Stories",
    "TALKS": "Has a word",
    "TANKS": "Fish homes",
    "TAROT": "Fortune-telling cards",
    "TASTE": "Sense on the tongue",
    "TEACH": "Pass on what you know",
    "TEAMS": "Sides in a league",
    "TEARS": "What crying produces",
    "TEETH": "What a dentist checks",
    "TERMS": "Contract conditions",
    "TESTS": "Quizzes",
    "THANK": "Say cheers to",
    "THEFT": "Taking what isn't yours",
    "THEME": "Unifying idea",
    "THERE": "Over yonder",
    "THESE": "The nearby ones",
    "THICK": "Not thin",
    "THING": "Object",
    "THINK": "Use your head",
    "THIRD": "After second",
    "THOSE": "The far ones",
    "THREE": "Sides of a triangle",
    "THROW": "Chuck it",
    "TIDAL": "Of the sea's rise and fall",
    "TIGER": "Striped big cat",
    "TIGHT": "Hard to squeeze into",
    "TILES": "Bathroom squares",
    "TIMER": "Kitchen countdown",
    "TIMES": "Multiplied by",
    "TIRED": "Ready for bed",
    "TIRES": "Things you rotate on a car",
    "TITLE": "Name of a book",
    "TODAY": "Neither yesterday nor tomorrow",
    "TONER": "Printer refill",
    "TONES": "Shades of colour",
    "TOOLS": "Shed contents",
    "TOOTH": "One of thirty-two",
    "TOPIC": "What it's about",
    "TOTAL": "Sum",
    "TOUCH": "Feel with a finger",
    "TOUGH": "Hard going",
    "TOWEL": "Poolside must",
    "TOWER": "Tall narrow building",
    "TOWNS": "Smaller than cities",
    "TOXIC": "Poisonous",
    "TRACE": "Faint sign left behind",
    "TRACK": "Where the runners run",
    "TRADE": "Swap",
    "TRAIL": "Path through the woods",
    "TRAIN": "It runs on rails",
    "TREAT": "Little reward",
    "TREES": "What a forest is made of",
    "TREND": "Way things are heading",
    "TRIAL": "Court hearing",
    "TRIBE": "Group with shared roots",
    "TRICK": "Sleight of hand",
    "TRIED": "Gave it a go",
    "TRIES": "Attempts",
    "TRIPS": "Journeys",
    "TROOP": "Group of scouts",
    "TRUCK": "Lorry",
    "TRULY": "Honestly",
    "TRUNK": "Elephant's nose",
    "TRUST": "Believe in",
    "TRUTH": "What's actually so",
    "TUNER": "Guitar pitch helper",
    "TURNS": "Takes a corner",
    "TWICE": "On two occasions",
    "TWINS": "Two born the same day",
    "TWIST": "Turn sharply",
    "TYPES": "Sorts",
    "ULTRA": "Extreme, as a marathon",
    "UNCLE": "Mum's brother",
    "UNDER": "Below",
    "UNION": "Workers' organisation",
    "UNITE": "Come together",
    "UNITS": "Apartment building count",
    "UNTIL": "Up to the time of",
    "UPPER": "Further up",
    "URBAN": "Of the city",
    "URGES": "Strong impulses",
    "USAGE": "How it's used",
    "USERS": "People on an app",
    "USUAL": "The regular one",
    "UTTER": "Complete, or to say aloud",
    "VALID": "Holds up",
    "VALUE": "What it's worth",
    "VALVE": "It controls the flow",
    "VENUE": "Where the gig happens",
    "VIDEO": "Moving pictures",
    "VILLA": "Holiday house with a pool",
    "VINYL": "Records' material",
    "VIRUS": "Cause of a cold",
    "VISIT": "Drop in on",
    "VITAL": "Absolutely necessary",
    "VOCAL": "Outspoken",
    "VOICE": "What a singer uses",
    "VOTED": "Marked the ballot",
    "VOTES": "Ballots cast",
    "WAGES": "Weekly pay",
    "WAGON": "Cart on four wheels",
    "WAIST": "Where the belt goes",
    "WASTE": "Throw away",
    "WATCH": "Wrist timepiece",
    "WATER": "H2O",
    "WAVES": "What surfers ride",
    "WEEKS": "Sets of seven days",
    "WHALE": "Ocean giant",
    "WHEAT": "Bread grain",
    "WHEEL": "Round thing that turns",
    "WHERE": "In what place",
    "WHICH": "What one",
    "WHILE": "During",
    "WHITE": "Snow's colour",
    "WHOLE": "All of it",
    "WHOSE": "Belonging to which one",
    "WIDER": "Less narrow",
    "WIDTH": "How broad",
    "WINDS": "Strong breezes",
    "WINES": "Reds and whites",
    "WINGS": "What a bird flaps",
    "WIRED": "Buzzing with energy",
    "WOMAN": "Grown-up girl",
    "WOMEN": "Grown-up girls",
    "WOODS": "Small forest",
    "WORDS": "Sentence pieces",
    "WORKS": "Does the job",
    "WORLD": "The whole globe",
    "WORRY": "Fret",
    "WORSE": "Less good",
    "WORST": "Least good of all",
    "WORTH": "What it fetches",
    "WOULD": "Might well",
    "WRITE": "Put pen to paper",
    "WRONG": "Not correct",
    "WROTE": "Put pen to paper, once",
    "YARDS": "Three-foot lengths",
    "YIELD": "Give way",
    "YOUNG": "Not old",
    "YOURS": "Belonging to you",
    "YOUTH": "Early years",
}

# ---- the longer fill the 7x7 midis need -------------------------------------
CLUES.update({
    # 3-4 letters the midi grids reach for that the mini pool did not
    "AHA": "Cry when the penny drops",
    "ALE": "Pub pint",
    "ARE": "Exist, plurally",
    "AWE": "Wonder mixed with a little fear",
    "AWED": "Struck with wonder",
    "BED": "Where the duvet goes",
    "DEN": "Cosy little room",
    "DIM": "Not bright",
    "EEL": "Slippery swimmer",
    "ELF": "Pointy-eared helper",
    "ELK": "Big antlered deer",
    "ERR": "Slip up",
    "GAG": "Joke",
    "LOO": "Bathroom, in Britain",
    "NUN": "One in a habit",
    "PLUM": "Purple stone fruit",
    "POPE": "Man in the white cassock",
    "RYE": "Bread grain, or a whiskey",
    "SANG": "Carried a tune",
    "SCAT": "Jazz singing without words",
    "SLAB": "Thick flat piece",
    "SLUR": "Speak unclearly",
    "STUB": "Ticket remnant",
    "VET": "Animal doctor",
    "VIA": "By way of",
    "WAN": "Pale and washed out",
    "WAS": "Used to be",
    "WHAM": "Sound of a hard hit",
    "YEN": "Money in Tokyo",
    "ALAS": "Sadly ...",
    "AXIS": "Line a globe spins on",
    "CANON": "Accepted body of work",
    "CHILI": "Spicy bowl",
    "LOCH": "Scottish lake",
    "NICHE": "Snug little spot",
    "PAPA": "Dad",
    "PESTS": "Nuisances",
    "PLEA": "Urgent request",
    "SEDAN": "Four-door car",
    "SCAMS": "Cons",
    "HARDY": "Tough, weather-wise",
    "FRANKS": "Hot dogs",

    # 6 letters
    "ACCENT": "Way of speaking that gives you away",
    "ACHING": "Sore all over",
    "ACTORS": "The cast",
    "AGENDA": "Meeting's running order",
    "AGENTS": "Ones who act on your behalf",
    "ALBINO": "Lacking pigment",
    "ALMOND": "Nut in marzipan",
    "ALPINE": "Of high mountains",
    "ANTICS": "Silly goings-on",
    "APIECE": "For each one",
    "ARCADE": "Room full of coin-op cabinets",
    "ARISES": "Comes up",
    "AROUSE": "Stir up",
    "ARMOUR": "Knight's metal suit",
    "ARREST": "Take into custody",
    "ARTIST": "One with a paintbrush",
    "ASSESS": "Size up",
    "ASSIST": "Help out",
    "ATTIRE": "What you're wearing",
    "AVERSE": "Not keen",
    "BARELY": "Only just",
    "BARLEY": "Grain in a beer",
    "BEAUTY": "Great looks",
    "BEFORE": "Ahead in time",
    "BEHIND": "At the back",
    "BETTER": "Improved",
    "BOTTLE": "It has a neck and a cap",
    "BOTTOM": "Lowest part",
    "BRANCH": "Tree limb",
    "BREATH": "In and out",
    "BRIDGE": "It crosses the river",
    "BRIGHT": "Full of light",
    "BUDGET": "Spending plan",
    "BUTTER": "Toast spread",
    "BUTTON": "Shirt fastener",
    "CAMERA": "It takes the photo",
    "CANDLE": "Wick in wax",
    "CANNOT": "Is unable to",
    "CARBON": "Element in a diamond",
    "CARPET": "Wall-to-wall floor covering",
    "CASTLE": "Fortress with a moat",
    "CENTRE": "Middle",
    "CHANCE": "Roll of the dice",
    "CHANGE": "Coins in your pocket",
    "CHEESE": "Say it for the camera",
    "CHERRY": "Fruit on the sundae",
    "CHOICE": "Option",
    "CHURCH": "Building with a steeple",
    "CIRCLE": "Round shape",
    "CIRCUS": "Big top show",
    "CLOSET": "Where the coats hang",
    "COATED": "Given a layer",
    "COFFEE": "Morning brew",
    "COLUMN": "Pillar",
    "COMEDY": "Genre with laughs",
    "COMMON": "Not rare",
    "CORNER": "Where two walls meet",
    "CORNY": "Groan-worthy, as a joke",
    "COTTON": "T-shirt fabric",
    "COUNTY": "Region of a state",
    "COUPLE": "Two together",
    "COURSE": "Set of classes",
    "COUSIN": "Aunt's child",
    "CREATE": "Bring into being",
    "CREDIT": "Praise where it's due",
    "DANGER": "Peril",
    "DECADE": "Ten years",
    "DEGREE": "What graduation brings",
    "DESERT": "Sandy expanse",
    "DESIRE": "Strong wish",
    "DINNER": "Evening meal",
    "DOCTOR": "One in a white coat",
    "DOLLAR": "Hundred cents",
    "DOUBLE": "Twice as much",
    "DRAWER": "It slides out of a desk",
    "DRIVER": "One at the wheel",
    "EASILY": "Without trouble",
    "EDITOR": "One who cuts the copy",
    "EFFECT": "Result",
    "EIGHTH": "After seventh",
    "ELDERS": "Older ones",
    "ELDEST": "Oldest of all",
    "ELOPED": "Married in secret",
    "ELUDES": "Slips away from",
    "EMERGE": "Come out",
    "EMPIRE": "Ruled-over lands",
    "ENCORE": "One more song!",
    "ENDING": "How the story finishes",
    "ENERGY": "Get-up-and-go",
    "ENGINE": "What's under the bonnet",
    "ENOUGH": "No more needed",
    "ENTERS": "Goes in",
    "ESCAPE": "Get away",
    "ESCORT": "Go along with",
    "EXPECT": "Anticipate",
    "FAMILY": "Parents and children",
    "FATHER": "Dad",
    "FEMALE": "Not male",
    "FIGURE": "Number, or a shape",
    "FINGER": "Digit on a hand",
    "FINISH": "Cross the line",
    "FISHES": "Angles for supper",
    "FLIGHT": "Trip by air",
    "FLOWER": "Bloom in a vase",
    "FOREST": "Lots of trees",
    "FRIEND": "Pal",
    "FRINGE": "Edge, or a haircut",
    "FROZEN": "Solid with cold",
    "GARDEN": "Where you grow things",
    "GEISHA": "Traditional Japanese entertainer",
    "GENTLY": "With a soft touch",
    "GOLDEN": "Like a good retriever",
    "GROUND": "What you walk on",
    "GRUNTS": "Low noises of effort",
    "GUITAR": "Six-stringed instrument",
    "HANDLE": "What you grip",
    "HAPPEN": "Take place",
    "HEIFER": "Young cow",
    "HEIGHT": "How tall",
    "HINGES": "Door swingers",
    "HONEST": "Truthful",
    "HOUSES": "Homes on a street",
    "HUNGRY": "Ready for dinner",
    "IGNITE": "Set alight",
    "IGUANA": "Big lizard",
    "IMPACT": "Collision",
    "INGEST": "Swallow",
    "INSANE": "Out of one's mind",
    "INSECT": "Six-legged crawler",
    "INSIDE": "Indoors",
    "INTACT": "Not a scratch on it",
    "ISLAND": "Land with water all round",
    "ITSELF": "On its own",
    "JACKET": "Light coat",
    "JUNGLE": "Dense tropical forest",
    "LADDER": "Rungs to climb",
    "LADIES": "Women",
    "LAGOON": "Shallow water beside the sea",
    "LANDED": "Touched down",
    "LATHER": "Soap suds",
    "LATTER": "The second of two",
    "LAUNCH": "Send off",
    "LEADER": "One out in front",
    "LEGEND": "Old story, or a map key",
    "LEMONS": "Sour fruits",
    "LENDER": "One who gives a loan",
    "LETTER": "It comes in an envelope",
    "LISTEN": "Lend an ear",
    "LITTLE": "Small",
    "LONELY": "Wanting company",
    "LONGER": "More drawn out",
    "MAKING": "Building",
    "MANNER": "Way of behaving",
    "MANTIS": "Praying insect",
    "MARINE": "Of the sea",
    "MARKET": "Stalls in a square",
    "MASTER": "Expert",
    "MEADOW": "Grassy field",
    "MEAGRE": "Barely enough",
    "MEMORY": "What a photo brings back",
    "METHOD": "Way of doing it",
    "MIDDLE": "Halfway point",
    "MINUTE": "Sixty seconds",
    "MIRROR": "It shows you your face",
    "MOMENT": "Instant",
    "MONKEY": "Tree-swinging primate",
    "MONTHS": "Twelve in a year",
    "MOROSE": "Sunk in gloom",
    "MOTHER": "Mum",
    "MUSEUM": "Where the exhibits are",
    "NATURE": "The great outdoors",
    "NEGATE": "Cancel out",
    "NICKEL": "Five-cent coin",
    "NOTING": "Taking note of",
    "NUGGET": "Little lump of gold",
    "NUMBER": "Seven, e.g.",
    "OPENER": "Bottle tool",
    "ORANGE": "Fruit, or a colour",
    "ORCHID": "Elegant houseplant",
    "ORDERS": "Instructions",
    "ORIGIN": "Where it started",
    "OTHERS": "The rest",
    "OXYGEN": "What we breathe",
    "PALACE": "Where a monarch lives",
    "PANELS": "Flat boards",
    "PARDON": "Say again?",
    "PARENT": "Mum or dad",
    "PAROLE": "Early release",
    "PARSON": "Country clergyman",
    "PAUPER": "Very poor person",
    "PENCIL": "It needs sharpening",
    "PEPPER": "Salt's partner",
    "PERSON": "Individual",
    "PICKLE": "Jar of brine, or a fix",
    "PIERCE": "Make a hole in",
    "PIGEON": "City bird",
    "PILLOW": "Head rest",
    "PLANET": "Saturn, e.g.",
    "PLENTY": "More than enough",
    "POCKET": "Where the keys go",
    "POINTS": "Sharp ends",
    "POTATO": "Spud",
    "POUNCE": "Spring at the prey",
    "PUZZLE": "Brain teaser",
    "RABBIT": "Long-eared hopper",
    "RANGES": "Mountain chains",
    "READER": "One with a book",
    "REASON": "The why of it",
    "RECIPE": "Cooking instructions",
    "RECORD": "Vinyl disc",
    "REGION": "Part of a country",
    "RELICS": "Objects from long ago",
    "REMOTE": "Far off, or a channel changer",
    "REPAIR": "Fix",
    "RESCUE": "Save from danger",
    "RETINA": "Back of the eye",
    "RETURN": "Come back",
    "RIBBON": "Gift wrap trim",
    "RIDING": "On horseback",
    "ROTTEN": "Gone off",
    "SAFELY": "Without harm",
    "SAFER": "Less risky",
    "SALARY": "Yearly pay",
    "SCALES": "Fish's covering",
    "SEASON": "Spring, e.g.",
    "SECOND": "After first",
    "SECRET": "Don't tell anyone",
    "SEWING": "Work with a needle",
    "SHADOW": "It follows you on a sunny day",
    "SILVER": "Second-place metal",
    "SIMPLE": "Easy as pie",
    "SINGER": "One at the mic",
    "SINGLE": "Just one",
    "SIPHON": "Draw off with a tube",
    "SISTER": "Female sibling",
    "SKIRTS": "Below-the-waist garments",
    "SMOOTH": "No bumps at all",
    "SPIDER": "Eight-legged weaver",
    "SPIRIT": "Ghost, or good cheer",
    "SPRING": "Season of buds",
    "SQUARE": "Four equal sides",
    "STEER": "Guide the wheel",
    "STRAND": "Single hair",
    "STREET": "Road with houses",
    "STRING": "Bit of twine",
    "SUMMER": "Season of the beach",
    "SUNDAY": "Day of rest",
    "SWITCH": "Flick it for light",
    "TALENT": "Natural gift",
    "TEMPLE": "Place of worship",
    "TENANT": "One who pays the rent",
    "TENDED": "Looked after",
    "TENNIS": "Game with a net and a serve",
    "TENTS": "Campers' shelters",
    "THENCE": "From that place",
    "THINGS": "Objects",
    "THIRST": "Need for water",
    "THORAX": "Middle bit of an insect",
    "THREAD": "Needle's partner",
    "TICKET": "It gets you in",
    "TIMBER": "Wood for building",
    "TISSUE": "For a runny nose",
    "TOMATO": "Salad red",
    "TONGUE": "Taster in the mouth",
    "TRADER": "One who buys and sells",
    "TRIPOD": "Three-legged stand",
    "TROOPS": "Soldiers",
    "TUNNEL": "Passage under the hill",
    "TURTLE": "Shelled swimmer",
    "TYRANT": "Cruel ruler",
    "UNEVEN": "Bumpy",
    "UNLESS": "Except if",
    "UPDATE": "Bring up to date",
    "VALLEY": "Low ground between hills",
    "VELVET": "Soft plush fabric",
    "VIOLIN": "Instrument played with a bow",
    "WAITER": "One who brings the food",
    "WALNUT": "Nut with a wrinkly shell",
    "WAVING": "Saying hello from afar",
    "WEAVE": "Work at the loom",
    "WINDOW": "Glass in a wall",
    "WINNER": "First past the post",
    "WINTER": "Season of the heavy coat",
    "WONDER": "Marvel",
    "WOODEN": "Made of timber",
    "YELLOW": "Colour of a lemon",

    # 7 letters
    "ABILITY": "What you can do",
    "ACREAGE": "How much land",
    "AILMENT": "Something that ails you",
    "AMATEUR": "Not a professional",
    "ANIMALS": "Zoo residents",
    "ANOTHER": "One more",
    "ARRIVED": "Turned up",
    "ARTISTE": "Performer, grandly",
    "AVERAGE": "Middling",
    "BALANCE": "What a tightrope needs",
    "BARRIER": "Thing in the way",
    "BATTERY": "It powers the torch",
    "BEDROOM": "Where the bed is",
    "BROADEN": "Widen",
    "CAPTIVE": "Held prisoner",
    "CEILING": "What's above your head indoors",
    "CHAPTER": "Book division",
    "CHIMING": "Ringing out, as a clock",
    "CLASSIC": "Never goes out of style",
    "CONDEMN": "Denounce",
    "CONSOLE": "Comfort, or a games box",
    "CULTURE": "Arts and customs",
    "CURTAIN": "It goes up at the theatre",
    "DIALECT": "Regional way of speaking",
    "DIAMOND": "Hardest gem",
    "DIOXIDE": "Carbon ___",
    "DRIVERS": "Ones at the wheel",
    "EARLIER": "Before now",
    "ENDINGS": "How stories finish",
    "EVENING": "After dusk",
    "FACTORY": "Where things get made",
    "FANTASY": "Daydream genre",
    "FERTILE": "Good for growing",
    "FINGERS": "Digits on a hand",
    "FISHING": "Casting a line",
    "FLOWERS": "What a bouquet is made of",
    "FREEDOM": "Being able to choose",
    "GENERAL": "Broad, not specific",
    "GRINDER": "Coffee bean crusher",
    "HOLIDAY": "Time off",
    "ILLEGAL": "Against the law",
    "IMAGINE": "Picture it",
    "INDUCED": "Brought on",
    "INSECTS": "Six-legged crawlers",
    "JOURNAL": "Where you write the day down",
    "KITCHEN": "Room with the hob",
    "LANTERN": "Portable light",
    "LEATHER": "Hide made into a jacket",
    "LOCATED": "Pinned down",
    "MACHINE": "Engine-driven device",
    "MEETING": "Diary filler",
    "MINUTES": "Notes from a meeting",
    "MONIKER": "Name, informally",
    "MORNING": "Before noon",
    "MUSICAL": "Show with songs",
    "NATURAL": "Not artificial",
    "NOTHING": "Zilch",
    "OPINION": "What you think",
    "ORIGINS": "Where things began",
    "OUTSIDE": "Out of doors",
    "OVERRUN": "Go past the time",
    "PACKAGE": "Parcel",
    "PARTNER": "The other half",
    "PATIENT": "One the doctor sees",
    "PENSIVE": "Deep in thought",
    "PERFECT": "Not a flaw in it",
    "PICTURE": "What hangs on the wall",
    "POPULAR": "Widely liked",
    "POSTERS": "Wall prints",
    "PRESENT": "Gift, or here",
    "PRINTER": "It puts ink on paper",
    "PROBLEM": "Puzzler",
    "PUNCHED": "Threw a jab at",
    "PUNGENT": "Sharply smelly",
    "READERS": "Ones with books",
    "RUNNING": "Out for a jog",
    "SAMURAI": "Japanese warrior of old",
    "SCATTER": "Spread about",
    "SCIENCE": "Lab subject",
    "SCREAMS": "Shrieks",
    "SENSORS": "They detect things",
    "SERPENT": "Slitherer, poetically",
    "SHINING": "Giving off light",
    "SLANDER": "Spoken lie that does damage",
    "SNOWING": "Coming down white",
    "SORTING": "Putting in order",
    "SPIDERS": "Eight-legged weavers",
    "STARRED": "Was the lead in",
    "STARRY": "Full of night lights",
    "STELLAR": "Outstanding",
    "STRANDS": "Single hairs",
    "STUMBLE": "Trip over",
    "SURFACE": "Top layer",
    "TEACHER": "One at the whiteboard",
    "TERMITE": "Wood-eating insect",
    "THUNDER": "Lightning's rumble",
    "TONIGHT": "This evening",
    "TRADING": "Buying and selling",
    "TRANSIT": "Getting from A to B",
    "TRAVELS": "Goes places",
    "TROPICS": "Hot band round the equator",
    "TRUSTEE": "One who looks after a fund",
    "VILLAGE": "Smaller than a town",
    "VINTAGE": "From a good old year",
    "WEATHER": "Rain or shine",
    "WEDDING": "Day of the big dress",
    "WHALING": "Hunting the biggest game at sea",
    "WRONGED": "Treated unfairly",
})

# midis that carry a title and a light theme
MIDI_META = {}
