# -*- coding: utf-8 -*-
"""Clue bank chunk: 6-letter words, batch 1."""
CLUES = {
    "RACING": ["Competing for first place", "Heart-pounding, as a pulse"],
    "PLANTS": ["Things you water", "Undercover cops in a crowd"],
    "KIDNAP": ["Take hostage", "Snatch, in a ransom plot"],
    "ARABIA": ["Lawrence of ___", "Peninsula east of the Red Sea"],
    "VIEWED": ["Regarded, as a proposal", "Seen, in web-traffic terms"],
    "PANAMA": ["Its canal opened in 1914", "Hat named for the wrong country?"],
    "PLACED": ["Put in position", "Finished in the top three"],
    "SCOFFS": ["Sneers audibly", "Reacts to a tall tale, maybe"],
    "AFRAID": ["Chicken, so to speak", "Reluctant to look under the bed"],
    "PLAYED": ["Took the field", "Feigned, as innocence"],
    "FUSION": ["Jazz-rock blend", "What powers the sun"],
    "SHIRTS": ["Items on hangers", "Skins' opponents in pickup ball"],
    "PARISH": ["Vicar's territory", "Louisiana's answer to a county"],
    "COUPON": ["Money-off slip", "What the thrifty clip"],
    "FORCES": ["Compels, as a confession", "Gravity and friction, for two"],
    "UPBEAT": ["Sunny in outlook", "Cheery, or a conductor's cue"],
    "TURNED": ["Changed direction", "Went sour, as milk"],
    "BISHOP": ["Diagonal mover on a board", "One who wears a mitre"],
    "DREAMT": ["Had visions while asleep", "Pictured things during a nap"],
    "ISSUED": ["Handed out officially", "Put into circulation, as stamps"],
    "PASSED": ["Got a C or better", "Went by, as time"],
    "FLORAL": ["Rose-patterned", "Like a busy wallpaper print"],
    "STATED": ["Said outright", "Put on the record"],
    "ADULTS": ["Full-price ticket holders", "Grown-ups in the room"],
    "GUILTY": ["Verdict that ends a trial", "Feeling after the last biscuit"],
    "TABLET": ["Pill you swallow", "Moses came down with two"],
    "MORGUE": ["Toe-tag venue", "Where a coroner works"],
    "SERVED": ["Brought to the table", "Started the tennis point"],
    "DINING": ["Having a proper sit-down meal", "Word before room or car"],
    "LOOKED": ["Cast a glance", "Gave the once-over"],
    "MOSCOW": ["Red Square's city", "Kremlin's home"],
    "LOGGED": ["Recorded in a journal", "___ on, as to an account"],
    "NEARLY": ["Just about", "Within a whisker of"],
    "AFFORD": ["Be able to buy", "Have the means for"],
    "GAMING": ["Console hobby", "Working the system, in a way"],
    "FASTER": ["Quicker off the mark", "How the tortoise wasn't"],
    "DALLAS": ["Cowboys' city", "Big D of Texas"],
    "SPOKEN": ["Uttered out loud", "Delivered by mouth, not by pen"],
    "REDEEM": ["Cash in, as a voucher", "Win back one's good name"],
    "SHARED": ["Split, as a bill", "Posted for friends to see"],
    "SOUNDS": ["What a mic picks up", "Sirens and slams, collectively"],
    "REGIME": ["Ruling government", "One that gets toppled"],
    "DEPEND": ["Rely, with 'on'", "Hinge, as on a condition"],
    "FORCED": ["Made to do it", "Strained, as a laugh"],
    "FAILED": ["Flunked the exam", "Came up short"],
    "HERBAL": ["Like chamomile tea", "Caffeine-free, as an infusion"],
    "ASSETS": ["Left side of a balance sheet", "Frozen things, in sanctions news"],
    "LAWYER": ["Courtroom pro", "One you call before you talk"],
    "MADRID": ["Spain's capital", "Home of the Prado"],
    "MARGIN": ["Blank strip on a page", "Gap between profit and cost"],
    "GRATIS": ["On the house", "For nothing at all"],
    "NORMAN": ["Like the 1066 invaders", "Arch style in old English churches"],
    "MURPHY": ["Whose law says it will go wrong", "Fold-away bed name"],
    "STARVE": ["Go without food", "Deprive of fuel, as a fire"],
    "MANIAC": ["Wild-eyed sort", "Reckless driver, informally"],
    "COMICS": ["Superhero reading", "Sunday paper section"],
    "ACCUSE": ["Point the finger at", "Level a charge against"],
    "DANISH": ["Pastry with fruit filling", "From Copenhagen"],
    "ATOMIC": ["Nuclear, in a way", "Like a clock that keeps perfect time"],
    "ARABIC": ["Language of the Quran", "Numerals we use daily"],
    "HUNTER": ["Stalker of deer", "Gatherer's partner"],
    "WRITER": ["Novelist or poet", "One with a block, sometimes"],
    "ENGAGE": ["Draw into conversation", "Get the gears to mesh"],
    "GENDER": ["Masculine or feminine, in grammar", "What der, die and das mark"],
    "BRONZE": ["Third-place metal", "Copper and tin, alloyed"],
    "SPOUSE": ["Wedded partner", "The one you file jointly with"],
    "EXOTIC": ["Strikingly foreign", "Like a pet that needs a permit"],
    "AGREED": ["'Fine by me'", "Settled on, as terms"],
    "SOCCER": ["World Cup sport", "The beautiful game, to Americans"],
    "SALMON": ["Fish that swims upstream", "Pinkish orange shade"],
    "WEAPON": ["Arsenal item", "Secret ___ (hidden advantage)"],
    "BURDEN": ["Heavy load to carry", "What the beast of it bears"],
    "PROPER": ["Correct and fitting", "Noun type that takes a capital"],
    "INCHES": ["Twelve to a foot", "Creeps forward bit by bit"],
    "SHARES": ["Stock market units", "Splits with a friend"],
    "REALTY": ["Property, in legal terms", "Land and buildings as a business"],
    "COLORS": ["Crayon box contents", "Primary trio, plus the rest"],
    "AUTUMN": ["Season of falling leaves", "When the clocks go back"],
    "TOILET": ["Loo, more formally", "Fixture with a cistern"],
    "DRIVES": ["Golf tee shots", "Ambitions, or hard disks"],
    "DEALER": ["One who hands out cards", "Car lot operator"],
    "NEWTON": ["Unit of force", "Apple-inspired physicist"],
    "MILLER": ["One who grinds grain", "Baker's supplier, in a village"],
    "WHILST": ["During, in British usage", "At the same time as, to a Brit"],
    "CAUSED": ["Brought about", "Set in motion, as trouble"],
    "FRAMES": ["Picture surrounds", "Bowling has ten"],
    "PROMPT": ["Right on time", "What you type into a chatbot"],
    "INDEED": ["'Quite so'", "Emphatic yes"],
    "EASIER": ["Less of a struggle", "Downhill, compared to up"],
    "ADDING": ["Putting in extra", "What a plus sign says to do"],
    "MOSTLY": ["By and large", "Nine times out of ten"],
    "PRINTS": ["Gallery reproductions", "What a detective dusts for"],
    "SUITES": ["Hotel's priciest rooms", "Bach wrote them for cello"],
    "VICTOR": ["Winner of the contest", "One who takes the spoils"],
    "ATTACH": ["Fasten securely", "Add a file to an email"],
    "SEEING": ["'___ is believing'", "Taking in with the eyes"],
    "HUDSON": ["New York river", "Bay in northern Canada"],
    "DIVINE": ["Fit for the gods", "Guess by intuition"],
    "MESSED": ["Fouled up, informally", "Made a hash of things, with 'up'"],
    "DIALOG": ["Box that pops up on screen", "Script's spoken part, US-style"],
    "PIECES": ["Jigsaw bits", "What a chessboard holds"],
    "SHIELD": ["Riot police carry them", "What a knight hides behind"],
    "PRAGUE": ["Czech capital", "City on the Vltava"],
    "TRENDS": ["Fashion currents", "What analysts spot in data"],
    "PICKUP": ["Flatbed truck", "Casual game at the park"],
    "CHROME": ["Shiny bumper finish", "Bright metal trim on a hot rod"],
    "CHARTS": ["Bar graphs and pie slices", "Where a hit song climbs"],
    "LAMBDA": ["Eleventh Greek letter", "Symbol for wavelength in physics"],
    "LIGHTS": ["Stadium illuminators", "Traffic trio: red, amber, green"],
    "BELONG": ["Fit in with the group", "Be a member"],
    "NEWEST": ["Most recent", "Latest off the line"],
    "STRAIN": ["Muscle injury from overdoing it", "Variant of a virus"],
    "HEBREW": ["Language of the Torah", "Right-to-left script of Israel"],
    "ADJUST": ["Fine-tune the setting", "Get used to a new normal"],
    "RAISED": ["Brought up", "Hiked, as the rent"],
    "SOVIET": ["Bygone union member", "Cold War adjective"],
    "TREATY": ["Signed peace deal", "What ends a war on paper"],
    "VIENNA": ["Waltz city", "Austria's capital"],
    "ALBUMS": ["Vinyl collection", "Where photos or tracks are kept"],
    "CHEATS": ["Codes for infinite lives", "Ones who peek at answers"],
    "GUESTS": ["Party arrivals", "Ones on the list"],
    "HOSTED": ["Threw the party", "Put up for the night"],
    "CHAPEL": ["Small place of worship", "Sistine ___"],
    "TRACKS": ["Album cuts", "What a train runs on"],
    "GRANTS": ["Research funding awards", "Wishes, if you're a genie"],
    "RADIUS": ["Half a diameter", "Bone in the forearm"],
    "STUART": ["Royal house before Hanover", "Dynasty of Charles I"],
    "MONROE": ["Marilyn of Hollywood", "Doctrine-naming president"],
    "CRAFTS": ["Arts' partner", "Glue-gun pursuits"],
    "STYLES": ["Fashion varieties", "Does one's hair"],
    "DENVER": ["Mile-High City", "Colorado's capital"],
    "FILLED": ["Topped up to the brim", "Occupied, as a vacancy"],
    "PRAISE": ["Words of approval", "What a good review heaps on"],
    "VENICE": ["City of canals", "Where gondolas glide"],
    "CABLES": ["TV hookups", "Bridge suspension strands"],
    "KILLED": ["Put an end to", "Cut, as the engine"],
    "BORDER": ["Line on a map", "Where passports get stamped"],
    "STARTS": ["Gets going", "Jumps, as at a loud bang"],
    "CAUSES": ["Charitable ones get donations", "Brings about"],
    "ABSENT": ["Not in class", "Marked missing on the roll"],
    "OPENED": ["Unsealed the envelope", "Cut the ribbon"],
    "BUBBLE": ["Soap sphere", "What a market does before it bursts"],
    "SCORES": ["Tallies on the board", "Twenties, in old counting"],
    "VESSEL": ["Ship or boat", "Blood ___ (artery, say)"],
    "EDITED": ["Cut for length", "Blue-pencilled"],
    "LINKED": ["Joined together", "Arm in arm, in a way"],
    "SCROLL": ["Document kept in a tube", "What a mouse wheel does"],
    "BEGINS": ["Gets underway", "Opens, as a show"],
    "RELATE": ["Connect with emotionally", "Tell, as a story"],
    "ALERTS": ["Phone buzzes and pings", "Weather warnings"],
    "RETAIN": ["Hold on to, as water", "Keep on the payroll"],
    "LEAVES": ["Rake bait in October", "Heads out the door"],
    "CHECKS": ["Ticks on a list", "Verifies twice over"],
    "TESTED": ["Tried out in a lab", "Put through its paces"],
    "ANCHOR": ["Ship's brake", "One who reads the news"],
    "AMBUSH": ["Surprise attack", "Lie in wait for"],
    "PARADE": ["Float procession", "Rain on someone's ___"],
    "SHOWED": ["Turned up, as at a party", "Put on display"],
    "LIMITS": ["Speed signs post them", "Boundaries not to cross"],
    "AVENGE": ["Get even for", "Settle a score for a wrong"],
    "STYLUS": ["Tablet pen", "Needle on a record player"],
    "RACKET": ["Tennis swatter", "Din, or a shady scheme"],
    "CATTLE": ["Herd on a ranch", "What a cowhand drives"],
    "ROBBED": ["Held up at gunpoint", "Cheated of a win, in fan-speak"],
    "POTTER": ["One at the wheel with clay", "Ceramics maker, or a boy wizard"],
    "RELOAD": ["Refresh the browser page", "Put more ammo in"],
    "KUWAIT": ["Gulf state", "Country freed in 1991"],
    "EATING": ["Having a meal", "What the acid does to metal"],
    "STRUCK": ["Hit with force", "Walked out, as workers"],
    "BRIDAL": ["Like a white gown", "___ shower"],
    "STOCKS": ["Wall Street buys", "Old punishment with a wooden frame"],
    "TRIBAL": ["Like clan loyalties", "Such as a totem or a drumbeat"],
    "REBATE": ["Money back after purchase", "Mail-in refund"],
    "DETECT": ["Pick up on a faint trace", "Sniff out a clue"],
    "NIGHTS": ["Arabian ___ (tale collection)", "Dark stretches"],
    "SAVING": ["Putting money aside", "Daylight ___ time"],
    "HELPED": ["Lent a hand", "Pitched in"],
    "IMMUNE": ["Safe from infection", "Not affected, as by criticism"],
    "LATVIA": ["Baltic country", "Riga's nation"],
    "BANDIT": ["Masked robber", "One-armed ___ (slot machine)"],
    "CELTIC": ["Like Gaelic languages", "Glasgow club, or a knotwork style"],
    "ADVISE": ["Give counsel to", "Tell what you'd do"],
    "SHOWER": ["Morning rinse", "Brief spell of rain"],
    "HOORAY": ["Cheer of delight", "Cry when the goal goes in"],
    "REVEAL": ["Big moment on a makeover show", "Let the secret out"],
    "SEEMED": ["Gave the impression", "Looked to be the case"],
    "WATSON": ["Holmes's chronicler", "'Elementary, my dear ___'"],
    "STRICT": ["Not letting anything slide", "Like a no-nonsense teacher"],
    "FINDER": ["One who comes across something", "'Losers weepers' partner"],
    "INLINE": ["Like some roller skates", "In a straight row"],
    "GRUDGE": ["Long-held resentment", "What you bear for years"],
    "STEADY": ["Not wobbling", "Slow and ___ wins the race"],
    "THEMES": ["Party dress-up topics", "Recurring motifs"],
    "CLUMSY": ["All thumbs", "Prone to knocking things over"],
    "GENEVA": ["Swiss city on a lake", "Where the conventions were signed"],
    "ASKING": ["Putting the question", "___ price (what the seller wants)"],
    "BLOCKS": ["City distances", "Toddler's toy tower pieces"],
    "INTAKE": ["Amount consumed", "New cohort at a college"],
    "ASSURE": ["Put someone's mind at rest", "Promise confidently"],
    "SODIUM": ["Salt's other half", "Element number 11"],
    "PAYING": ["Settling the bill", "Turning a profit, with 'off'"],
    "SULTAN": ["Ottoman ruler", "Muslim monarch of old"],
    "CRISIS": ["Emergency of the first order", "Midlife ___"],
    "DECENT": ["Pretty good", "Fair-minded and fine"],
    "HEADER": ["Football goal off the brow", "Top of a page"],
}
