# -*- coding: utf-8 -*-
"""Clue bank chunk: 7-letter words, batch 1."""
CLUES = {
    "ACTIONS": ["Deeds, not words", "They speak louder than words"],
    "BEEPING": ["Making a car-horn sound", "What a smoke alarm does at 3 a.m."],
    "MARKETS": ["Stalls-and-bustle places", "Bulls and bears frequent them"],
    "YELLING": ["Hollering loudly", "Using an outdoor voice indoors"],
    "SUPPOSE": ["Assume, for argument's sake", "Let's say, hypothetically"],
    "INVOLVE": ["Bring into the mix", "Entail, as a task"],
    "PERHAPS": ["Maybe, maybe not", "It could happen"],
    "PERSONS": ["People, in legalese", "Missing ___ report"],
    "SCREECH": ["Sound an owl makes", "Brakes losing an argument"],
    "OUTLINE": ["Rough plan", "Silhouette's edge"],
    "FACTORS": ["3 and 5, for 15", "Things to weigh up in a decision"],
    "HOLLAND": ["Tulip country, loosely", "Home of Gouda and canals"],
    "CHUCKLE": ["Quiet laugh", "What a dad joke earns, at best"],
    "CAREFUL": ["Taking pains", "Not one to spill the milk"],
    "MINIMAL": ["Bare-bones", "Just enough and no more"],
    "LOTTERY": ["Numbers game with a jackpot", "Long-odds hope, weekly"],
    "LICENCE": ["Permit, in Britain", "Poetic ___"],
    "HALLWAY": ["Corridor at home", "Where the coat hooks live"],
    "CONSULT": ["Seek advice from", "Check with an expert"],
    "QUICKLY": ["Like a flash", "Before you know it"],
    "DOLLARS": ["Greenbacks", "Loonies and bucks, e.g."],
    "DRIVING": ["Behind the wheel", "Like heavy rain"],
    "TURKISH": ["___ delight", "Of Ankara and Istanbul"],
    "QUANTUM": ["Kind of leap", "Physics of the very small"],
    "SECONDS": ["Another helping", "Sixty make a minute"],
    "STRETCH": ["Morning yawn's partner", "Limber up before a run"],
    "CRICKET": ["Bat-and-ball game with tea breaks", "Chirper in the grass"],
    "GROWING": ["Getting taller", "On the up, as a business"],
    "PANTING": ["Out of breath", "How a dog cools off"],
    "HEARING": ["Court session without a jury", "One of the five senses"],
    "OLYMPIC": ["Of the Games every four years", "___ torch relay"],
    "RAINBOW": ["Arc after a shower", "Seven-colour sky show"],
    "DECLINE": ["Say no, politely", "Downward slide"],
    "ISRAELI": ["Of Tel Aviv", "Shekel spender"],
    "EFFORTS": ["Best-laid attempts", "What one puts in"],
    "JAMAICA": ["Reggae's birthplace", "Island of Blue Mountain coffee"],
    "NURSING": ["Bedside profession", "Cradling a drink slowly"],
    "COVERED": ["Insured, as damage", "Under a lid"],
    "DISPUTE": ["Argue against", "Contested point"],
    "FINDING": ["Research result", "What a study reports"],
    "ADVERSE": ["Unfavourable", "Kind of side effect"],
    "EXCERPT": ["Passage lifted from a book", "Snippet quoted in a review"],
    "AFFAIRS": ["Current ___", "Goings-on of state"],
    "TOWARDS": ["In the direction of", "Approaching, as midnight"],
    "PERFUME": ["Scent in a small bottle", "Duty-free counter buy"],
    "SUGGEST": ["Float an idea", "Put forward, as a plan"],
    "CHARGES": ["Bills for services", "Ones in a nanny's care"],
    "RESTORE": ["Bring back to former glory", "Undo the damage to"],
    "REASONS": ["The whys behind it", "Rhyme's partner, in a phrase"],
    "TALKING": ["Chatting away", "___ point (issue to raise)"],
    "CREATOR": ["Maker of a hit show", "One with a channel, nowadays"],
    "PASSAGE": ["Narrow way through", "Bit of a book"],
    "QUARTER": ["Coin with an eagle", "Fifteen minutes"],
    "HEADSET": ["Gamer's gear", "Call-centre wear"],
    "OAKLAND": ["Bay Area city east of the bridge", "California port near Berkeley"],
    "MISSING": ["Not where it should be", "Absent without trace"],
    "LUNATIC": ["Wild-eyed sort", "Moonstruck one, by etymology"],
    "LOGICAL": ["Sound in reasoning", "Spock-like"],
    "EXTRACT": ["Vanilla ___", "Pull out, as a tooth"],
    "PAYABLE": ["Due, on a bill", "Accounts ___"],
    "OPENING": ["Gap in a fence", "Chess start"],
    "RECIPES": ["Cookbook contents", "Instructions with a bake time"],
    "COUNTER": ["Kitchen work surface", "Argue back"],
    "FOLLOWS": ["Comes after", "Tails, as a detective"],
    "RAILWAY": ["Train network, in Britain", "Sleepers lie under it"],
    "MISTAKE": ["Honest slip-up", "Wrong turn, figuratively"],
    "VILLAIN": ["Panto boo magnet", "The one the hero fights"],
    "MINERAL": ["Quartz or gypsum", "Vitamin's shelf-mate"],
    "FORTUNE": ["Cookie message", "Small ___ (a tidy sum)"],
    "PARKING": ["Meter's business", "___ ticket"],
    "STADIUM": ["Roaring bowl on match day", "Big venue with tiered seats"],
    "BROTHER": ["Sibling, maybe", "Big ___ is watching"],
    "COSTUME": ["Halloween getup", "Fancy-dress outfit"],
    "OBJECTS": ["Things on a shelf", "Raises a legal protest"],
    "NORFOLK": ["English county with the Broads", "Virginia naval city"],
    "ARTWORK": ["Gallery hanging", "Album cover, essentially"],
    "ETHICAL": ["Above board", "Of right and wrong"],
    "NEUTRAL": ["Switzerland's stance", "Gear between reverse and first"],
    "APPEARS": ["Seems to be", "Shows up on cue"],
    "DECIDED": ["Made up one's mind", "Clear-cut, as an advantage"],
    "DESIGNS": ["Blueprints", "Has ___ on (is scheming)"],
    "BINDING": ["Book's spine", "Legally enforceable"],
    "WINNING": ["In the lead", "Charming, as a smile"],
    "VIOLENT": ["Rough and forceful", "Like a nasty storm"],
    "COTTAGE": ["Cheese with curds", "Thatched country home"],
    "ANYMORE": ["Any longer", "No longer, informally"],
    "CREDITS": ["Rolling names at a film's end", "Ones a student earns"],
    "CLEARLY": ["Plain as day", "Without a doubt"],
    "RESOLVE": ["Firmness of purpose", "Sort out, as a dispute"],
    "FLIGHTS": ["Departures board list", "Stairs, in sets"],
    "EXPERTS": ["Panel of pundits", "Ones who know their stuff"],
    "NIGERIA": ["Africa's most populous nation", "Lagos is its largest city"],
    "EXACTLY": ["Precisely!", "You said it"],
    "ANYBODY": ["Just anyone", "Anyone at all"],
    "OPTIMAL": ["Best possible", "As good as it gets"],
    "NATIONS": ["United ___", "Countries, formally"],
    "GASPING": ["Short of air", "Reacting to a plot twist"],
    "SOBBING": ["Crying hard", "In floods of tears"],
    "SPEAKER": ["House leader", "One at the podium"],
    "OFFICES": ["Cubicle homes", "Places with water coolers"],
    "MANAGED": ["Pulled it off", "Ran, as a shop"],
    "ELEGANT": ["Chic and refined", "Like a neat proof"],
}
