# -*- coding: utf-8 -*-
"""
xwx_clues_flavour.py -- the light personal seasoning, per CONTRACT section 7.

Rules I am following:
  * roughly 1 clue in 15 across the whole pool, never a whole themed grid
  * NOTHING here needs inside knowledge to solve -- every one of these is a
    clue a stranger could get.  The flavour is in the *choice* of reference,
    not in privileged information.
  * the four cities (Cambridge/Boston, London, Edinburgh, Houston), AI safety
    and governance, Persian culture, Jewish culture and Israel, football
  * no Shahnameh lore (they don't know it and it has its own cabinet)
  * no workplace, no real colleagues, no romance-clich voice

Keyed by ANSWER, exactly like the main bank.  The generator draws from here at a
capped rate so the seasoning stays a seasoning.
"""
FLAVOUR = {
    # ---- the four cities ----------------------------------------------------
    "RIVER": ["The Charles, to Cambridge", "The Thames, for one"],
    "CHARLES": ["River between Boston and Cambridge"],
    "BRIDGE": ["Cam crossing that named a city", "Tower ___, on the Thames"],
    "SQUARE": ["Harvard ___", "Trafalgar ___"],
    "HARVARD": ["Cambridge university with a crimson colour"],
    "BOSTON": ["City where the Tea Party wasn't a party"],
    "LONDON": ["City of black cabs and red buses"],
    "TEXAS": ["Lone Star State"],
    "HOUSTON": ["___, we have a problem"],
    "TUBE": ["London Underground, informally", "Mind the gap network"],
    "CAB": ["Black one, in London"],
    "MIND": ["___ the gap"],
    "GAP": ["Mind the ___"],
    "HILL": ["Beacon ___, in Boston", "Arthur's Seat is one, sort of"],
    "CASTLE": ["It sits on a dead volcano in Edinburgh"],
    "SCOTS": ["Edinburgh residents, mostly"],
    "SCOTLAND": ["Where Hogmanay is a public holiday"],
    "KILT": ["Pleated Highland wear"],
    "TARTAN": ["Checked cloth of a Scottish clan"],
    "HAGGIS": ["Burns Night centrepiece"],
    "FRINGE": ["Edinburgh's August festival"],
    "CLOSE": ["Narrow Edinburgh alley", "Nearly"],
    "LOCH": ["Scottish lake"],
    "FIRTH": ["Scottish estuary, as of Forth"],
    "OYSTER": ["Card that taps you onto the Tube", "Pearl producer"],
    "SUBWAY": ["Boston's is the oldest in America"],
    "TRAIN": ["What the Red Line runs"],
    "LINE": ["Red, Green, Orange or Blue, in Boston"],
    "GREEN": ["Boston T line, or a Fenway colour"],
    "PARK": ["Fenway ___", "Hyde ___"],
    "COMMON": ["Boston's is the oldest public park in America"],
    "TEA": ["What Boston harbour got a lot of in 1773"],
    "HUB": ["Boston's old nickname, with 'the'"],
    "SNOW": ["What a New England February delivers"],
    "AUTUMN": ["When New England leaves turn"],
    "RAIN": ["What Scotland does best"],
    "HUMID": ["Like a Houston August"],
    "RODEO": ["Houston hosts the world's biggest one"],
    "OIL": ["Houston's original business"],
    "SPACE": ["What Houston's centre is named for"],
    "BRISKET": ["Slow-smoked Texas barbecue cut"],
    "TACO": ["Breakfast staple in Texas"],
    "QUEUE": ["What Britons form and Americans stand in"],
    "PINT": ["What a British pub sells by the"],
    "PUB": ["Where a round gets bought"],
    "BREXIT": ["2016 British vote, in one coined word"],
    "THAMES": ["London's river"],
    "SOHO": ["London district, or a New York one"],
    "CAMDEN": ["London market borough"],
    "CHELSEA": ["London borough with a football club"],
    "ARSENAL": ["North London club, or a weapons store"],
    "UNITED": ["Manchester club with the red shirts", "Joined together"],
    # ---- football / soccer --------------------------------------------------
    "PITCH": ["Where the match is played", "Sales spiel"],
    "GOAL": ["What the net is for", "Something to aim at"],
    "OFFSIDE": ["Flag-raising football offence"],
    "PENALTY": ["Spot kick from twelve yards"],
    "STRIKER": ["The one paid to score"],
    "KEEPER": ["Only player allowed to use hands", "Worth holding on to"],
    "DERBY": ["Match between local rivals"],
    "SQUAD": ["The whole playing group"],
    "TREBLE": ["Three trophies in one season", "Triple"],
    "LEAGUE": ["Premier ___"],
    "CORNER": ["Kick from the flag", "Where two walls meet"],
    "HEADER": ["Goal scored with the forehead"],
    "DRIBBLE": ["Take the ball past a defender"],
    "REFEREE": ["The one with the whistle"],
    "EXTRA": ["___ time, after ninety minutes"],
    "STOPPAGE": ["___ time, added at the end"],
    "TACKLE": ["Win the ball back", "Take on a hard job"],
    "CROSS": ["Ball swung into the box", "Annoyed, in Britain"],
    "SHIRT": ["It carries the squad number"],
    "STADIUM": ["Where eighty thousand sing"],
    "MATCH": ["Ninety minutes of it", "Strike-anywhere stick"],
    "TROPHY": ["What the winners lift"],
    "DRAW": ["One-all, say", "Sketch"],
    "KICK": ["Free ___", "Buzz"],
    "TREBLES": ["Trio of trophies"],
    # ---- AI safety, governance, evals --------------------------------------
    "SAFETY": ["What the AI research field puts before capability"],
    "ALIGN": ["Bring into agreement, as goals with values"],
    "MODEL": ["What gets trained, then evaluated", "Pose for a painter"],
    "TRAIN": ["Teach a system by example"],
    "COMPUTE": ["The chips-and-power input to a big AI run", "Work out"],
    "EVAL": ["Test suite, to an AI researcher"],
    "AUDIT": ["Inspection a regulator orders"],
    "POLICY": ["What a government paper proposes", "Insurance document"],
    "GOVERN": ["Hold the reins of state"],
    "RISK": ["What a safety case tries to bound", "Chance of loss"],
    "SANDBOX": ["Contained place to test something risky"],
    "BENCHMARK": ["Standard test everyone reports against"],
    "AGENT": ["Software that acts on your behalf", "Booking go-between"],
    "PROMPT": ["What you type at a chatbot", "On time"],
    "TOKEN": ["Chunk of text a model reads", "Gesture without substance"],
    "NEURAL": ["Of nerves, or of a network"],
    "LAYER": ["Level in a deep network", "Add another jumper"],
    "SCALE": ["What the laws in AI describe", "Climb"],
    "TREATY": ["What states sign to bind themselves"],
    "CHARTER": ["Founding document of an institution"],
    "OVERSIGHT": ["Supervision, or a mistake -- both"],
    "REDTEAM": ["Group paid to attack your own system"],
    "GUARDRAIL": ["Limit built in to stop a bad outcome"],
    "TRANSPARENT": ["Able to be seen straight through"],
    "CONSENT": ["What data use is supposed to have"],
    "PRIVACY": ["What a data law is meant to protect"],
    "ROBUST": ["Holding up under stress"],
    "SUMMIT": ["Where leaders meet, or a peak"],
    "PARLIAMENT": ["Where a bill becomes law in Britain"],
    "CHIPS": ["Export-controlled silicon", "Fish and ___"],
    "SILICON": ["Element the chips are cut from"],
    # ---- Persian culture (no Shahnameh) ------------------------------------
    "SAFFRON": ["Costliest spice by weight"],
    "TAHDIG": ["Crisp rice crust from the bottom of the pot"],
    "KEBAB": ["Grilled meat on a skewer"],
    "PISTACHIO": ["Green nut Iran is famous for"],
    "POMEGRANATE": ["Seed-packed fruit of a Persian garden"],
    "NOWRUZ": ["Persian new year, at the spring equinox"],
    "BAZAAR": ["Covered market, from Persian"],
    "KIOSK": ["Little street booth, from Persian"],
    "DIVAN": ["Low couch, or a book of collected poems"],
    "SHAWL": ["Wrap for the shoulders, from Persian"],
    "TULIP": ["Cup-shaped spring bulb, named via Persian"],
    "LILAC": ["Pale purple bloom, from a Persian word"],
    "JULEP": ["Mint drink whose name came from Persian"],
    "CANDY": ["Sweet whose name came from Persian for sugar"],
    "MUSK": ["Heavy perfume note, from Persian"],
    "CARPET": ["Persian export you don't step on lightly"],
    "RUG": ["Smaller than a carpet"],
    "TEHRAN": ["Iran's capital"],
    "PERSIA": ["Iran's older name"],
    "FARSI": ["Language written in a Perso-Arabic script"],
    "WALNUT": ["Nut ground into a Persian stew"],
    "MINT": ["Herb in a Persian yoghurt dish", "Where coins are made"],
    "YOGHURT": ["Cultured dairy served alongside rice"],
    "ROSE": ["Flower whose water flavours Persian sweets"],
    "SUMAC": ["Tart red spice dusted over kebabs"],
    "CARDAMOM": ["Pod that perfumes Persian tea"],
    "GARDEN": ["Walled Persian paradise, originally"],
    "POET": ["Hafez, for one"],
    "NIGHTINGALE": ["Bird of a thousand Persian poems"],
    # ---- Jewish culture and Israel -----------------------------------------
    "BAGEL": ["Boiled then baked ring"],
    "LATKE": ["Fried potato pancake of Hanukkah"],
    "CHALLAH": ["Braided loaf for Friday night"],
    "MATZO": ["Unleavened Passover bread"],
    "SEDER": ["Passover meal with a set order"],
    "SHABBAT": ["Friday-sunset to Saturday-night rest"],
    "SUKKAH": ["Temporary hut built for a harvest festival"],
    "MENORAH": ["Branched candelabrum"],
    "DREIDEL": ["Spinning top with Hebrew letters"],
    "HEBREW": ["Language read right to left"],
    "YIDDISH": ["Language that gave English 'schlep'"],
    "SCHLEP": ["Haul something a long, annoying way"],
    "KVETCH": ["Complain, in borrowed Yiddish"],
    "MENSCH": ["Thoroughly decent person"],
    "CHUTZPAH": ["Nerve, in borrowed Yiddish"],
    "KOSHER": ["Fit to eat, by religious law", "Above board"],
    "RABBI": ["Teacher who leads a congregation"],
    "TORAH": ["Scroll read in a synagogue"],
    "PURIM": ["Costumes-and-pastry spring festival"],
    "HUMMUS": ["Chickpea dip"],
    "FALAFEL": ["Fried chickpea ball in a pitta"],
    "SHAKSHUKA": ["Eggs poached in a spiced tomato pan"],
    "TAHINI": ["Sesame paste in the dip"],
    "PITA": ["Pocket bread"],
    "JERUSALEM": ["City on a hill, three times over"],
    "ISRAEL": ["Country on the eastern Mediterranean"],
    "HAIFA": ["Israeli port on a mountainside"],
    "OLIVE": ["Tree of the Levant", "Martini garnish"],
    "DESERT": ["The Negev, for one", "Abandon"],
    "SALT": ["What makes the Dead Sea float you", "Season"],
}
CLUES = {}
