# -*- coding: utf-8 -*-
"""Clue bank chunk: 7-letter words, batch 0."""
CLUES = {
    "CONTACT": ["Get in touch with", "Lens that sits on the eye"],
    "SERVICE": ["Tennis stroke that starts a point", "Church ceremony"],
    "PRODUCT": ["What 6 times 7 gives you", "Item on a shelf"],
    "SUPPORT": ["Back up, as a cause", "What a bracket provides"],
    "MESSAGE": ["Text you fire off", "Moral of a story"],
    "THROUGH": ["Done with it, informally", "By way of; via"],
    "PRIVACY": ["What a curtain protects", "Phone setting that guards your data"],
    "COMPANY": ["Firm you work for", "Guests you have over"],
    "JANUARY": ["Resolution month", "When the ball drops"],
    "PROGRAM": ["Theater handout listing the cast", "Software bundle"],
    "BECAUSE": ["Answer to a toddler's endless why", "For the reason that"],
    "ADDRESS": ["Envelope line", "Speak to a crowd"],
    "SUBJECT": ["Topic of an essay", "Line at the top of an email"],
    "BETWEEN": ["Sandwiched", "Amid two things"],
    "SPECIAL": ["Diner's dish of the day", "Not like the others"],
    "PROJECT": ["Weekend job around the house", "Throw an image on a wall"],
    "VERSION": ["Software release number", "One side of a story"],
    "SECTION": ["Part of a newspaper", "Slice of the orchestra"],
    "NETWORK": ["Schmooze at a mixer", "TV broadcaster"],
    "WITHOUT": ["Lacking; sans", "Not having any of it"],
    "CURRENT": ["Up to date", "What a river has"],
    "CONTROL": ["Remote in your hand", "Keep in check"],
    "HISTORY": ["School subject full of dates", "It repeats itself, they say"],
    "ACCOUNT": ["Bank holding", "Eyewitness version of events"],
    "DIGITAL": ["Not analog", "Of clocks with numerals, not hands"],
    "PROFILE": ["Side view of a face", "Page you set up on a social app"],
    "QUALITY": ["High-end, as goods", "Trait of character"],
    "CONTENT": ["Perfectly happy", "What a creator uploads"],
    "COUNTRY": ["Nation on a map", "Genre with fiddles and heartbreak"],
    "PRIVATE": ["Lowest army rank", "For your eyes only"],
    "COMPARE": ["Hold up side by side", "Weigh two options"],
    "INCLUDE": ["Add to the guest list", "Leave nobody out"],
    "COLLEGE": ["Where you pick a major", "Electoral ___"],
    "ARTICLE": ["A, an or the", "Magazine piece"],
    "PROVIDE": ["Supply, as a meal", "Come up with what's needed"],
    "PROCESS": ["Series of steps to follow", "Handle the paperwork for"],
    "ENGLISH": ["Language of Shakespeare", "Spin on a cue ball"],
    "GALLERY": ["Where the paintings hang", "Crowd watching a golf putt"],
    "LIBRARY": ["Place with a quiet rule", "Your collection of e-books"],
    "MEDICAL": ["Of doctors and clinics", "Bill you dread after a hospital stay"],
    "COMMENT": ["Weigh in below the line", "Passing remark"],
    "AGAINST": ["Opposed to", "Leaning on, as a ladder"],
    "PAYMENT": ["Money that changes hands", "Monthly bill settling"],
    "STUDENT": ["One with homework", "Learner's permit holder, perhaps"],
    "AMERICA": ["Land of the free, in song", "Vespucci's namesake"],
    "EXAMPLE": ["Case in point", "Model to follow"],
    "RELEASE": ["Let go of the rope", "New album drop"],
    "SIMILAR": ["Much the same", "Like, but not identical"],
    "MILLION": ["Seven-figure sum", "Lottery jackpot unit"],
    "WELCOME": ["Doormat greeting", "Glad to see you"],
    "CENTRAL": ["Right in the middle", "Main, as an idea"],
    "COUNCIL": ["Town's governing body", "Ones who decide on planning permission"],
    "ARCHIVE": ["Store old files away", "Where the back issues live"],
    "SOCIETY": ["The public at large", "Club with members and dues"],
    "EDITION": ["Printing of a book", "Sunday paper's fat one"],
    "ALREADY": ["By this time", "Sooner than expected"],
    "SEVERAL": ["More than a couple", "Three or four, roughly"],
    "DISPLAY": ["Show off proudly", "Shop window arrangement"],
    "WRITTEN": ["Put down on paper", "Kind of exam, as opposed to oral"],
    "FEDERAL": ["Nationwide, in the U.S.", "Of the national government"],
    "FINANCE": ["Bankroll a purchase", "World of stocks and bonds"],
    "PERCENT": ["Figure with a % sign", "Hundredth part"],
    "GERMANY": ["Country of Goethe and Bach", "Where the autobahn runs"],
    "VARIOUS": ["Assorted, as reasons", "Of several different kinds"],
    "RECEIVE": ["Get in the mail", "Catch a pass"],
    "MICHAEL": ["Jordan or Jackson, on court or stage", "Archangel of the Bible"],
    "FLORIDA": ["The Sunshine State", "Where the Keys are"],
    "LICENSE": ["Card the officer asks for", "Permission, formally granted"],
    "KINGDOM": ["Realm with a throne", "Animal or plant grouping"],
    "THOUGHT": ["Idea that crossed your mind", "Believed, in the past"],
    "STORAGE": ["What an attic is good for", "Unit you rent for your clutter"],
    "SUMMARY": ["Short version", "The gist of it"],
    "WESTERN": ["Film with cowboys", "Of the sunset direction"],
    "OVERALL": ["All things considered", "Taken as a whole"],
    "SOMEONE": ["A certain person", "Anybody at all"],
    "BELIEVE": ["Take on faith", "Have confidence in"],
    "CERTAIN": ["Sure as can be", "Not to be doubted"],
    "JEWELRY": ["Necklaces and rings", "What a velvet box holds"],
    "BRITISH": ["Of Blighty", "Like tea at four, stereotypically"],
    "TUESDAY": ["Day after Monday", "Pancake day, in Britain"],
    "CAPITAL": ["Paris, to France", "Big letter"],
    "ENGLAND": ["Home of the Three Lions", "Country whose capital is London"],
    "AIRPORT": ["Where flights depart", "Place with a duty-free shop"],
    "FOREIGN": ["From another country", "Not domestic"],
    "CHANNEL": ["What you flip through on TV", "Strait between two lands"],
    "PRIMARY": ["Of first importance", "Red, blue or yellow"],
    "PURPOSE": ["Reason for being", "The point of it all"],
    "FEATURE": ["Headline article", "Highlight of the new phone"],
    "CHICAGO": ["Windy City", "Musical with 'All That Jazz'"],
    "REGULAR": ["Like clockwork", "Bar patron who always comes in"],
    "STATION": ["Where the train stops", "Radio dial spot"],
    "IMPROVE": ["Get better", "Raise your game"],
    "DISEASE": ["What a vaccine prevents", "Heart trouble, e.g."],
    "COMMAND": ["Sit or stay, to a dog", "Take charge of"],
    "WILLIAM": ["Shakespeare's first name", "Prince who married Kate"],
    "EXPRESS": ["Say out loud", "Train that skips stops"],
    "SUCCESS": ["Sweet smell of it", "Hitting the mark"],
    "MAXIMUM": ["The very most", "Speed limit, e.g."],
    "FORWARD": ["Striker on a pitch", "Pass the email along"],
    "CATALOG": ["Wish book from the mail", "List systematically"],
    "TRAFFIC": ["Rush hour crawl", "Deal in illicit goods"],
    "IRELAND": ["Emerald Isle", "Home of Joyce and Yeats"],
    "INSTEAD": ["In place of that", "Rather than"],
    "FITNESS": ["Gym-goer's goal", "Being in good shape"],
    "CHINESE": ["Takeaway option", "Language with tones"],
    "DEVELOP": ["Grow over time", "Bring a photo out in the darkroom"],
    "SESSION": ["Therapy hour", "Parliament's sitting period"],
    "CENTURY": ["Hundred years", "Batsman's hundred runs"],
    "PACIFIC": ["Ocean west of Chile", "Peaceful, poetically"],
    "VEHICLE": ["Car or truck", "Means to an end, figuratively"],
    "DEFAULT": ["Setting out of the box", "Fail to pay the loan"],
    "REQUIRE": ["Call for, as a rule", "Insist on as a must"],
    "OUTDOOR": ["Of the great open air", "Like a patio grill"],
    "PROTEIN": ["What a shake may be full of", "Muscle-building nutrient"],
    "GRANDPA": ["Old man of the family", "One who spoils you rotten, maybe"],
    "FACULTY": ["Teaching staff", "Mental power"],
    "MISSION": ["Apollo 11, for one", "Job you accept"],
    "SWEETIE": ["Honey or dear", "Term for a loved one"],
    "RICHARD": ["Lionheart king", "Nixon or Burton"],
    "VIRTUAL": ["Almost, but not quite, actual", "Reality you need a headset for"],
    "MINIMUM": ["Bare bones amount", "Wage floor"],
    "VARIETY": ["Spice of life", "A mixed bag of things"],
    "DESKTOP": ["Computer that stays put", "Screen with your icons on it"],
    "RESPECT": ["Aretha's demand", "Look up to"],
    "UNKNOWN": ["Anonymous, on a caller ID", "Yet to be discovered"],
    "GEORGIA": ["Peach State", "O'Keeffe of American art"],
    "BENEFIT": ["Charity gala", "Perk of the job"],
    "FICTION": ["Novels and such", "Truth is stranger than it"],
    "COMPLEX": ["Not simple at all", "Group of buildings together"],
    "SPANISH": ["Language of Cervantes", "Omelette with potato in it"],
    "ECONOMY": ["Cheap seats on a plane", "Nation's financial health"],
    "HELPFUL": ["Ready to lend a hand", "Like a good hint"],
    "RUSSIAN": ["Language of Tolstoy", "Nesting doll's origin"],
    "AFRICAN": ["Of the second-largest continent", "Like a safari animal"],
    "JUSTICE": ["Supreme Court figure", "Fairness under the law"],
    "CONNECT": ["Join the dots", "Hit it off with someone"],
    "ADVANCE": ["Move forward", "Payment before the work"],
    "AUCTION": ["Going, going, gone event", "Where the gavel falls"],
    "CORRECT": ["Right on the money", "Fix the typos in"],
    "FASHION": ["Milan runway world", "Manner or way"],
    "MONITOR": ["Track over time", "Screen on your desk"],
    "DISCUSS": ["Talk it over", "Hash out at a meeting"],
    "INITIAL": ["First of all", "Letter you sign a box with"],
    "CONTEXT": ["Words around the quote", "Taken out of it, unfairly"],
    "INSTALL": ["Set up the new software", "Put in, as a boiler"],
    "APPAREL": ["Clothing on a rack", "Wardrobe stock"],
    "SURGERY": ["Operation in a theatre", "Where a British doctor sees you"],
    "BROUGHT": ["Carried along", "Fetched, in the past"],
    "HIMSELF": ["The man, alone", "He did it all by ___"],
    "ARIZONA": ["Grand Canyon State", "Where Phoenix is"],
    "KEYWORD": ["Term you type in a search box", "Tag for finding an article"],
    "ITALIAN": ["Language of opera", "Like pasta or pesto"],
    "PREMIUM": ["Insurance payment", "Top shelf, quality-wise"],
    "UPGRADE": ["Move to business class", "Better version of the app"],
    "EASTERN": ["Of the sunrise side", "Time zone in New York"],
    "THERAPY": ["Talking cure", "What a couch is for, in a cliche"],
    "SERIOUS": ["No joking around", "Grave in tone"],
    "DEFENSE": ["Line protecting the goal, in the U.S.", "Lawyer's case for the accused"],
    "PROTECT": ["Keep from harm", "Guard the queen"],
    "PREVENT": ["Stop before it starts", "Head off at the pass"],
    "ELEMENT": ["Iron or gold, on a table", "Part of a whole"],
    "HOUSTON": ["Texas city where NASA listens", "Space center metropolis"],
    "RESERVE": ["Book a table", "Set aside for later"],
    "PLASTIC": ["Credit card material", "Not the real thing"],
    "PRODUCE": ["Grocery aisle greens", "Bring about"],
    "FAILURE": ["Total flop", "Not an option, they say"],
    "WEEKEND": ["Saturday and Sunday", "When you finally lie in"],
    "ONTARIO": ["Province of Toronto", "Great Lake bordering New York"],
    "JACKSON": ["Face on the $20 bill", "Pollock of the paint splatters"],
    "SEATTLE": ["Home of the Space Needle", "City of grunge and rain"],
    "PATTERN": ["Repeating design", "Sewing guide"],
    "SPONSOR": ["Logo on the shirt", "One who funds the team"],
    "INDIANA": ["Jones of the movies", "State of the Hoosiers"],
    "NUCLEAR": ["Of the atom's core", "Family of the traditional sort"],
    "PROMOTE": ["Move up the ranks", "Push the new record"],
    "TOURISM": ["Industry of holidaymakers", "What sells postcards"],
    "GRAPHIC": ["Vivid, as detail", "Chart on a slide"],
    "ATLANTA": ["Georgia's capital", "Where the 1996 Games were held"],
    "ENLARGE": ["Blow up, as a photo", "Make bigger"],
    "REVENUE": ["Money coming in", "Top line of the accounts"],
    "MEASURE": ["Take the dimensions of", "Bill before parliament"],
    "EXPLORE": ["Poke around", "Set off for parts unknown"],
    "CONCEPT": ["The big idea", "Rough notion behind a design"],
    "REALITY": ["Life as it actually is", "TV genre with no script"],
    "BILLION": ["Thousand million", "Sum a tech founder dreams of"],
    "GUNSHOT": ["Starter's signal at a race", "Bang heard in a thriller"],
    "TORONTO": ["Canada's largest city", "Where the CN Tower stands"],
    "PERFORM": ["Take the stage", "Carry out a task"],
    "HEALTHY": ["In fine fettle", "Like a salad, we hope"],
    "CONDUCT": ["Lead the orchestra", "Behaviour, on a school report"],
    "EXTREME": ["Way over the top", "Sport with a lot of adrenaline"],
    "CONTAIN": ["Hold within", "Stop an outbreak from spreading"],
    "CRYSTAL": ["Clear as can be", "Quartz formation"],
    "ACADEMY": ["Where the Oscars come from", "School of a fancy sort"],
    "DYNAMIC": ["Full of energy", "How a duo interacts"],
    "INSTANT": ["Split second", "Coffee that just needs water"],
    "AUSTRIA": ["Mozart's homeland", "Country of the Vienna waltz"],
    "UTILITY": ["Water or power company", "Handy, as a knife"],
    "PREVIEW": ["Sneak look", "Trailer before the film"],
    "DESPITE": ["Notwithstanding", "In the face of"],
    "PHOENIX": ["Bird that rises from ashes", "Arizona's capital"],
    "COMFORT": ["Console a mourner", "What a soft chair offers"],
    "ALABAMA": ["Deep South state", "Sweet home, in a song"],
    "ACHIEVE": ["Pull off, as a goal", "Reach at last"],
    "CIRCUIT": ["Loop of a track", "Board inside a gadget"],
    "REMOVAL": ["Taking away", "Van hired for a house move"],
    "OPTICAL": ["Of the eyes", "Illusion of a tricky sort"],
    "ORLANDO": ["Florida theme park hub", "Woolf novel of a shifting hero"],
    "COMRADE": ["Fellow soldier", "Term of address in old Moscow"],
    "ADVISOR": ["One who guides a student", "Consultant of a sort"],
    "GENERIC": ["Off-brand, at the pharmacy", "Lacking any distinction"],
    "COMPACT": ["Small and neat", "Powder case in a handbag"],
    "ATTEMPT": ["Have a go at it", "Try, try again"],
    "STEPHEN": ["King of horror novels", "Hawking of physics"],
    "CLIMATE": ["Weather over decades", "Mood of the workplace"],
}
