# -*- coding: utf-8 -*-
"""
xwx_clues_alt.py -- extra clues for the answers that recur most.

The first big generation run produced grids where END appeared 61 times and every
one of those 61 read "Finish line".  A pool that large only feels hand-made if
the glue words are re-clued, so this file gives the 200-odd most-reused answers
four to seven clues each, in deliberately different registers: plain definition,
wordplay with a question mark, fill-in-the-blank, definition-by-example,
misdirection.  The generator rotates through them.

Every clue here is checked by xwx_validate.clue_conflict, so none of them
contains its own answer.
"""
CLUES = {
    # ---- 3 letters ---------------------------------------------------------
    "END": ["Tail of the film", "Wrap up", "Rope's far bit", "Purpose, as in means to an ___",
            "Where the credits roll", "Defender's job on a rugby line"],
    "ONE": ["Loneliest number, in song", "Ace, numerically", "Number on a lottery ball",
            "The first of them all", "___-way street"],
    "YES": ["The answer a proposal hopes for", "Nod, in a word", "Aye",
            "What the referendum ballot offers first", "Agreement, spoken"],
    "SET": ["Group of tennis games", "Film location", "Harden, as jelly", "Fixed and unmoving",
            "Collection of matching china", "Put down carefully"],
    "ALE": ["Bitter's cousin", "What a cask holds", "Brew from a hand pump",
            "Real ___, to a British drinker"],
    "SEE": ["Get the point", "Meet up with", "Consult, as a doctor",
            "Understand at last", "Witness"],
    "NEW": ["Just off the press", "Brand ___", "Never used", "Unfamiliar",
            "What a resolution makes of a year"],
    "TEA": ["Four o'clock ritual", "Leaf in a pot", "Light evening meal, in Britain",
            "Gossip, in current slang", "What Boston harbour got a lot of in 1773"],
    "ATE": ["Cleared the plate", "Consumed", "Devoured", "Took a bite, and then some"],
    "TEN": ["Digits on two hands", "Bowling pin count", "Commandments count",
            "Top mark for a dive", "A very attractive person, informally"],
    "PER": ["Miles ___ hour", "Apiece", "According to, in legalese", "For every one"],
    "RED": ["Colour of a Man United shirt", "Hot, as a chilli", "In the ___, losing money",
            "Ripe tomato's hue", "Wine that isn't white"],
    "ARE": ["Belong to the living, plurally", "Verb for you and me",
            "How ___ you?", "Form of 'to be'"],
    "EYE": ["Storm's calm centre", "Look over carefully", "What a needle has",
            "Potato bud", "Private ___"],
    "SEA": ["Where the tide belongs", "Dead or Red one", "Lots of, as in a ___ of faces",
            "The Aegean, for one"],
    "BEE": ["Spelling contest", "Hive dweller", "Busy as a ___",
            "Quilting gathering"],
    "ERR": ["Get it wrong", "Miss the mark", "To ___ is human", "Blunder"],
    "YEN": ["Strong craving", "Currency without a decimal point", "Longing"],
    "YET": ["Nevertheless", "Up to now", "Still, in a sentence", "But even so"],
    "TRY": ["Have a go", "Five points in rugby", "Put on trial", "Attempt"],
    "PET": ["Stroke gently", "Favourite, as a project", "Goldfish, e.g.",
            "___ peeve"],
    "LED": ["Was out in front", "Guided", "Took the first turn on the dance floor",
            "Went first"],
    "DEN": ["Bear's winter quarters", "Study with a soft chair", "Lion's home",
            "Thieves' hideout, in a phrase"],
    "ART": ["Skill raised to a craft", "What hangs at the Tate",
            "Fine ___", "State of the ___"],
    "TWO": ["Company, before three is a crowd", "Even prime",
            "Number of halves in a match", "It takes ___ to tango"],
    "LET": ["Rent out, in Britain", "Serve that gets replayed", "Permit",
            "Give way to"],
    "DRY": ["Wipe with a towel", "Without a drop of rain", "Wit that keeps a straight face",
            "Not sweet, as a wine"],
    "ASH": ["Tree with pale hard wood", "Grey residue", "Cricket urn contents, notionally",
            "What a volcano throws up"],
    "ARM": ["Branch of the service", "Sleeve filler", "Chair's side rest"],
    "AHA": ["Sudden-insight sound", "Gotcha!", "Cry of dawning realisation"],
    "OPT": ["Make a choice", "___ out", "Decide in favour", "Go for"],
    "ADS": ["Billboard content", "Skippable bits before the video",
            "Classified section", "What a jingle sells"],
    "SKY": ["Where the kite goes", "Blue overhead", "The ___'s the limit",
            "Cloud's address"],
    "MET": ["Bumped into", "Satisfied, as a condition", "Came face to face with"],
    "ACT": ["Pretend", "One of five in a Shakespeare play", "Do something at last",
            "Piece of legislation"],
    "WED": ["Tie the knot", "Join in marriage", "Say I do"],
    "NOT": ["Far from it", "Word that flips a meaning", "Nope, formally"],
    "MEN": ["Chess pieces, collectively", "Blokes", "Crew, of old",
            "Best ___ at a wedding"],
    "HAS": ["Possesses", "Is holding", "Must, when followed by 'to'"],
    "ALL": ["Every last one", "Score in a tied game", "Once and for ___",
            "The full amount"],
    "ACE": ["Nail an exam", "Top pilot", "Brilliant, in British slang",
            "Highest card in the pack"],
    "THE": ["Definite article", "Word before almost anything", "It precedes a noun"],
    "PEN": ["Writer's tool", "Small enclosure for pigs", "Compose a letter",
            "Mightier than the sword, they say"],
    "GET": ["Fetch", "Take the joke", "Come to have", "Catch, as a train"],
    "ELK": ["Wapiti", "Moose relative", "Antlered wanderer of the north"],
    "EEL": ["It writhes in a river", "Jellied dish of old London",
            "Fish shaped like a rope"],
    "EAT": ["Tuck in", "Corrode, as acid does", "Take a meal",
            "Consume, in a phrase about words"],
    "SAW": ["Laid eyes on", "Old saying", "Carpenter's cutter", "Witnessed"],
    "GEM": ["Cut and polished stone", "Real find", "Sparkler in a setting",
            "Something precious, figuratively"],
    "BED": ["Flower patch", "Where the duvet lives", "Riverbottom",
            "Turn in for the night, with 'go to'"],
    "APT": ["Well chosen", "Likely to", "On the nose", "Quick to learn"],
    "ANT": ["Colony worker", "Farm insect in a plastic box", "It carries crumbs home"],
    "WET": ["Straight out of the rain", "Not yet dry, as paint",
            "Feeble, in British insult", "Dampen"],
    "WAS": ["Existed once", "Past tense of is", "Used to be, singularly"],
    "USE": ["Make the most of", "Employ", "Purpose, as in no ___ crying",
            "Consume, as fuel"],
    "RAY": ["Sunbeam", "Flat fish that glides", "Note after doh", "Thin line of light"],
    "GEL": ["Come together, as a team", "Hair styling goo", "Set into a soft solid"],
    "ARC": ["Curved path", "Story's shape", "Part of a circle", "Welder's flash"],
    "ADD": ["Chuck in", "Sum up", "Say further", "Do the plus sign's work"],
    "TOE": ["Sock's occupant", "___ the line", "Little piggy, in a rhyme",
            "Foot's front digit"],
    "ODD": ["Peculiar", "Not one of a pair", "Three or five, e.g.",
            "Strange, in a mildly worrying way"],
    "INN": ["Coaching stop of old", "Pub with rooms", "Where a traveller beds down"],
    "DOT": ["Small round mark", "Point in Morse code", "Speck",
            "On the ___, exactly on time"],
    "BET": ["Have a flutter", "Stake on the outcome", "Sure thing, informally",
            "Put money on it"],
    "AWE": ["Reverent amazement", "Shock and ___", "Stun into silence"],
    "ANY": ["Some at all", "Whichever you like", "___ minute now"],
    "AND": ["Plus", "Conjunction that joins", "Word in most band names"],
    "SPY": ["Watch in secret", "Cold War operative", "Catch sight of",
            "One who reports back quietly"],
    "PIN": ["Bowling target", "Fix in place", "Sewing sharp",
            "Number that guards a card"],
    "PAT": ["Reassuring touch", "Butter portion", "Too neat, as an answer",
            "Stand ___, stay put"],
    "TUB": ["Bath", "Ice cream container", "Wide shallow vessel"],
    "TAB": ["Bill at the bar", "Browser page", "Little pull on a can",
            "Keep ___s on"],
    "RYE": ["Dark bread grain", "Whiskey from a mash bill", "Sandwich bread with caraway"],
    "PAR": ["What the scorecard expects", "On a ___ with, equal to",
            "Below ___, under the weather"],
    "MOM": ["Parent in Houston", "Family cook, often", "Word for mother in America"],
    "ICE": ["Chill a drink", "Rink surface", "Cubes in a glass",
            "What breaks between strangers"],
    "EGG": ["What the hen laid", "Urge on, with 'on'", "Breakfast in a shell"],
    "TON": ["Great weight", "Loads of, informally", "Hundred, in cricket slang"],
    "TAR": ["Road surfacing goo", "Sticky black stuff", "Old sailor, informally"],
    "TAP": ["Turn on the water", "Gentle knock", "Dance in metal shoes",
            "Listen in on a line"],
    "RAP": ["Sharp knock", "Rhymed verse over a beat", "Take the ___, get blamed"],
    "LEG": ["Stage of a relay", "Table support", "Stretch of a journey",
            "Trouser filler"],
    "LAB": ["Room with fume hoods", "Retriever, informally", "Where the experiment runs"],
    "BYE": ["Free pass to the next round", "Cheerio", "Farewell, briefly"],
    "ROW": ["Line of seats", "Blazing argument", "Pull the oars",
            "What a boat needs two of"],
    "RAW": ["Straight from the fridge", "Unprocessed", "Sore and red",
            "Bitterly cold, as wind"],
    "POT": ["Pan's deeper cousin", "Total in the middle of the poker table",
            "Sink a snooker ball", "Where the plant grows"],
    "LAY": ["Set down", "Song, poetically", "Put the table in order, with 'the table'"],
    "LAP": ["Circuit of the track", "Where the cat sits", "Drink like a dog",
            "Overtake by a full circuit"],
    "ITS": ["Belonging to it", "Possessive that trips people up"],
    "DAM": ["Hoover, for one", "Hold back the river", "Beaver's engineering"],
    "CAP": ["Bottle top", "Set an upper limit", "Peaked hat",
            "Appearance for the national side"],
    "CAB": ["Hail one on the street", "Lorry's front", "Taxi"],
    "AIR": ["Give it a listen, on radio", "Put on television", "What tyres need",
            "Melody, in old music"],
    "SUB": ["Stand-in", "Long sandwich", "Boat that dives", "Bring on a fresh player"],
    "SON": ["Boy of the family", "Term of address from an older man",
            "Father's male child"],
    "SAY": ["Have a voice in it", "Utter", "Roughly, as in ___ fifty",
            "Get a word in"],
    "PUB": ["Local, in Britain", "Where the quiz night happens",
            "Building with a hand pump"],
    "PRO": ["Paid player", "In favour", "Expert, informally", "One of two column headings"],
    "POP": ["Balloon's end", "Chart music", "Nip out briefly", "Fizzy drink, in Britain"],
    "PIT": ["Stone in a cherry", "Where the crew changes tyres", "Coal mine",
            "Set against, with 'against'"],
    "MIN": ["Short unit on a cooking label", "Least, on a dial"],
    "GAP": ["Space between", "Missing piece of knowledge", "___ year"],
    "FEE": ["Charge for the service", "Entry price", "What the lawyer bills"],
    "EAR": ["Where the earring goes", "Corn on the cob unit",
            "Have an ___ for music", "Listener"],
    "DAD": ["Family driver, traditionally", "Papa", "One half of the parents"],
    "CUP": ["Trophy with handles", "What the tea goes in", "Bra measurement",
            "World ___"],
    # ---- 4 letters ---------------------------------------------------------
    "AREA": ["Patch of ground", "Square footage", "Neighbourhood",
            "Field of expertise", "Penalty ___, on a pitch"],
    "IDEA": ["Brainwave", "Plan taking shape", "The whole point of it",
            "Notion", "What a lightbulb signals in a cartoon"],
    "IRON": ["Golf club with a flat face", "Press the shirts", "Ferrous element",
            "Pump ___, at the gym", "Strong, as a will"],
    "ACES": ["Four in a deck", "Sails through the test",
            "Unreturnable serves", "Top pilots"],
    "ONES": ["Digits in binary, half of them", "Loved ___", "Singles, in a till"],
    "ALAS": ["More's the pity", "Woe is me", "Regrettably"],
    "ELSE": ["Or ___!", "Besides that", "Anything ___?", "In addition to this"],
    "ORAL": ["By word of mouth", "Exam with no writing", "Of the mouth",
            "Tradition passed down in speech"],
    "ONTO": ["Wise to", "Up on the roof, say", "Aware of what you're doing"],
    "ALSO": ["What's more", "Too", "Into the bargain"],
    "ACRE": ["Farm measure", "Just over 4,000 square metres", "Chunk of land"],
    "OVEN": ["Where the cake rises", "Kitchen appliance with a door",
            "Hot as an ___", "Roasting box"],
    "ICON": ["Tappable square on a phone", "Legend of the field",
            "Painted saint on wood", "Symbol on a screen"],
    "ITEM": ["Line on the agenda", "Thing in a basket", "Couple, in gossip",
            "Entry on a receipt"],
    "TEST": ["Trial run", "Cricket match over five days", "Try out",
            "Put through its paces"],
    "AGES": ["Donkey's years", "Grows older", "An eternity, informally"],
    "URGE": ["Push someone to act", "Sudden want", "Encourage strongly"],
    "TREE": ["Family diagram", "Thing with rings inside", "Oak, e.g.",
            "Bark's owner"],
    "ONCE": ["One time only", "___ upon a time", "As soon as",
            "Formerly"],
    "ACID": ["Sharp, as a remark", "Opposite of a base", "Lemon juice, chemically"],
    "USES": ["Puts to good purpose", "Applications", "Employs"],
    "NEST": ["Twiggy cradle", "Settle in snugly", "___ egg, savings"],
    "EVER": ["At any time at all", "Always, in a vow", "Forever, shortened"],
    "AURA": ["Atmosphere someone gives off", "Glow around a figure",
            "Feeling a place gives you"],
    "WERE": ["Used to be, plurally", "Past tense of are"],
    "USED": ["Pre-owned", "Exploited", "Second hand", "Made the most of"],
    "ATOM": ["Building block of matter", "Splitting it releases energy",
            "Smallest unit of an element"],
    "TEND": ["Mind the garden", "Be inclined to", "Care for the sick"],
    "PEST": ["Aphid, to a gardener", "Nuisance", "Something a farmer sprays for"],
    "ECHO": ["Repeat back", "Sound off a canyon wall", "Faint reminder of the past"],
    "AROSE": ["Came about", "Got up", "Presented itself, as a problem"],
    "TONE": ["Shade of a colour", "Manner of speaking", "Firm up, as muscle"],
    "GEAR": ["Kit and tackle", "Cog in a box", "Shift into a higher one"],
    "EVEN": ["Level out", "Divisible by two", "Get ___, take revenge",
            "Smooth, as ground"],
    "TAGS": ["Price labels", "Names in code", "Marks with a label"],
    "SEND": ["Post off", "Dispatch", "Put in the mail"],
    "NEON": ["Sign gas", "Bright to the point of glaring", "Element number ten"],
    "NEAR": ["Within reach", "Approach", "A ___ miss"],
    "EDIT": ["Cut for length", "Revise a draft", "Make changes to a file"],
    "OPEN": ["Unlocked", "Golf major", "Frank and honest", "Prise the lid off"],
    "RATE": ["Charge per unit", "Judge out of ten", "Speed of change",
            "Deserve, in British usage"],
    "RARE": ["Hardly ever seen", "Cooked barely at all", "Precious and scarce"],
    "SALE": ["Rails of red tickets", "Transaction", "Half-price time of year"],
    "EASE": ["Effortlessness", "Loosen slowly", "Comfort", "At ___, relaxed"],
    "OVAL": ["Running-track shape", "Rugby ball outline", "Elongated round"],
    # ---- 5 letters ---------------------------------------------------------
    "ARENA": ["Where the gladiators went", "Sphere of activity",
            "Big indoor venue", "Political ___"],
    "ALERT": ["Sharp and awake", "Warning message", "Tip off",
            "Red ___"],
    "TENOR": ["General drift of a speech", "Voice above baritone",
            "Sax pitched below alto"],
    "ARISE": ["Crop up", "Get to your feet", "Occur, as an issue"],
    "IDEAL": ["Couldn't be better", "Standard worth aiming at", "Just right"],
    "EATEN": ["Polished off", "Devoured already", "Gone from the plate"],
    "UNITE": ["Join forces", "Bring together", "Merge into one"],
    "RESET": ["Start again from scratch", "Put the clock right",
            "Hold the button down to do this"],
    "IDEAS": ["Suggestions in a meeting", "What a brainstorm produces",
            "Notions"],
    "ERASE": ["Rub out", "Delete for good", "Wipe clean"],
    "SCENE": ["Chunk of a screenplay", "Make a ___, cause a fuss",
            "Setting laid out", "Crime location"],
    "LINEN": ["Cool summer cloth", "Bed sheets, collectively",
            "Fabric that wrinkles proudly"],
    "ELITE": ["Top tier", "Select few", "Best of the best"],
    "ASIDE": ["Remark to the audience", "Off to one side",
            "Put ___, save for later"],
    "ALIEN": ["Utterly unfamiliar", "Visitor from far off", "Foreign"],
    "TONER": ["Cartridge powder", "Skincare step after cleansing"],
    "THREE": ["Sides of a triangle", "Crowd, after two", "Points for a win"],
    "OCEAN": ["Pacific, e.g.", "Vast salt water", "Deep blue"],
    "LEAVE": ["Clear off", "Time off work", "Abandon", "Set out"],
    "EATER": ["Diner", "Fussy ___", "One at the table"],
    "ALIVE": ["Breathing", "Buzzing with energy", "Not dead yet"],
    "ERROR": ["Slip in the code", "Fielder's mistake", "Wrong turn",
            "Trial and ___"],
    "DATES": ["Squishy sweet fruits", "Calendar entries",
            "Goes out with"],
    "AREAS": ["Districts", "Fields of study", "Zones on a map"],
    "TONES": ["Shades", "Firms up", "Colours of a palette"],
    "ITEMS": ["Shopping list contents", "Points to cover"],
    "ASSET": ["Plus on the balance sheet", "Something you'd hate to lose",
            "Valuable resource"],
    "AORTA": ["Big vessel from the heart", "Largest artery"],
    "ANIME": ["Animation from Japan", "Style with very large eyes"],
    "ACTS": ["Behaves", "Parts of a play", "Performs on stage"],
    "USER": ["One with an account", "Person at the keyboard", "End ___"],
    "UNITS": ["Metres and grams, e.g.", "Flats in a block", "Army sections"],
    "ULTRA": ["Beyond extreme", "Race far longer than a marathon", "Way past normal"],
    "TREAT": ["Handle with care", "Small indulgence", "Trick or ___",
            "See to, medically"],
    "STONE": ["British weight of fourteen pounds", "Pip in a peach",
            "Throw one, in a saying", "Rock"],
    "OPENS": ["Unseals", "Starts the innings", "Prises the lid off"],
    "ONSET": ["First sign of it", "Start of an illness", "Beginning"],
    "PADRE": ["Chaplain to the troops", "Priest, informally"],
    "AROMA": ["Waft from the kitchen", "Bouquet of a wine", "Rich smell"],
    "WEAVE": ["Thread over and under", "Duck and dodge through traffic",
            "Pattern of a fabric"],
    "UTTER": ["Say out loud", "Absolute", "Total, as nonsense"],
    "TENSE": ["Strung tight", "Past, present or future", "On edge"],
    "STOVE": ["Hob", "Where the kettle sits", "Cooking range"],
    "STORE": ["Keep for later", "Shop", "Stockpile", "Set ___ by, value"],
    "RATED": ["Given stars", "Assessed", "Thought highly of, in Britain"],
    "OPERA": ["Soap ___", "Sung drama", "Carmen, for one"],
    "MANIA": ["Craze that sweeps through", "Obsessive enthusiasm"],
    "LEASE": ["Tenant's paperwork", "Rent out long-term", "New ___ of life"],
    "EVENT": ["Big occasion", "Item in the diary", "One race in a meet"],
    "ANGLE": ["Right one is ninety degrees", "Point of view",
            "Fish with a rod", "Slant on a story"],
    "AGREE": ["Reach terms", "Say the same thing", "Match up"],
    "RENEW": ["Sign on for another year", "Refresh", "Take out again"],
    "RENAL": ["To do with kidneys", "Of the organ that filters blood"],
    "IRONS": ["Presses flat", "Clubs in a golf bag", "Shackles, of old"],
    "AGED": ["Matured in a barrel", "Grown old", "Left to mellow"],
    "TONGA": ["Kingdom in the South Pacific", "Polynesian island nation"],
    "EURO": ["Money in Dublin", "Currency of the eurozone", "Cash in Lisbon"],
    "TACO": ["Filled tortilla", "Tuesday special, in America"],
    "OLIVE": ["Drab green", "Tree of the Mediterranean", "Tapenade base"],
    "HERE": ["In this very spot", "Present, at roll call", "Not there"],
    "SHE": ["Pronoun for a woman", "Her, in the nominative"],
    "ARTS": ["Humanities, broadly", "Martial ___", "Painting and sculpture, jointly"],
}
