# -*- coding: utf-8 -*-
"""Clue bank chunk: 5-letter words, batch 1."""
CLUES = {
    "ISAAC": ["Newton of gravity fame", "Asimov who wrote about robots"],
    "OXIDE": ["Rust, chemically speaking", "Iron and oxygen compound"],
    "FACED": ["Squared up to a problem", "Turned to look at"],
    "BLINK": ["Lose the staring contest", "Quick shut of the eyes"],
    "TAMIL": ["Language spoken in Chennai", "Tongue of southern India"],
    "FUZZY": ["Like a peach's skin", "Out of focus"],
    "FORGE": ["Blacksmith's workplace", "Fake a signature"],
    "AUTOS": ["Detroit assembly output", "Sedans and estate cars"],
    "BARKS": ["Sounds from the kennel", "Outer layers on tree trunks"],
    "BRAVE": ["Not afraid of the dark", "Atlanta baseball player"],
    "AWFUL": ["Truly terrible", "Two stars out of ten"],
    "DARCY": ["Austen's brooding love interest", "Proud suitor of Elizabeth Bennet"],
    "TAPES": ["Cassettes of old", "Records for later viewing"],
    "ZONES": ["Regions on a map", "Time divisions of the globe"],
    "RACES": ["Sprints and marathons", "Runs at top speed"],
    "GROAN": ["Reaction to a bad pun", "Sound of a stubbed toe"],
    "KNOCK": ["Rap at the door", "Criticise, informally"],
    "AMIGO": ["Friend, in Spanish", "Buddy south of the border"],
    "QUILT": ["Patchwork bedcover", "Stitched blanket from scraps"],
    "MAMBO": ["Cuban ballroom dance", "Dance craze of the 1950s"],
    "CHOIR": ["Group in the church loft", "Sopranos and altos, together"],
    "BLOND": ["Fair-haired", "Hair shade from a bottle, often"],
    "BURST": ["Pop like a balloon", "Sudden flurry of activity"],
    "DOWRY": ["Bride's family payment", "Marriage gift of old"],
    "FIBRE": ["Roughage, in Britain", "What bran is full of"],
    "DAISY": ["Lawn flower in a chain", "Bloom with a yellow centre"],
    "LEEDS": ["West Yorkshire city", "City between Manchester and York"],
    "CRUDE": ["Oil straight from the well", "Rough and unrefined"],
    "SHUSH": ["Librarian's request", "Tell to be quiet"],
    "BURNS": ["Scottish poet Robert", "Sensations from a hot stove"],
    "PUMPS": ["Heels for the office", "Moves liquid along"],
    "ALLAH": ["God, in Islam", "Name invoked in the Quran"],
    "MARSH": ["Boggy ground", "Wetland thick with reeds"],
    "OPIUM": ["Poppy-derived drug", "Its wars shook old China"],
    "THETA": ["Greek letter after eta", "Angle symbol in trigonometry"],
    "STAKE": ["Share in a business", "Vampire hunter's tool"],
    "ARBOR": ["Shady garden structure", "Ann ___, Michigan"],
    "RIFLE": ["Search through roughly", "Long-barrelled gun"],
    "DOGGY": ["Bag for restaurant leftovers", "Puppy, to a toddler"],
    "CYBER": ["Online, as a prefix", "___ Monday bargains"],
    "OASIS": ["Desert watering hole", "Britpop band from Manchester"],
    "TONIC": ["Gin's partner", "Bracing pick-me-up"],
    "ROMEO": ["Shakespeare's lovestruck teen", "R, in the NATO alphabet"],
    "HONKS": ["Sounds in a traffic jam", "Noises from a gaggle"],
    "CUBAN": ["Havana native", "Kind of cigar, famously"],
    "MACHO": ["Aggressively masculine", "All swagger and bravado"],
    "FROZE": ["Stopped dead on the spot", "Turned to ice"],
    "DYING": ["Fading fast", "Desperately eager"],
    "MOURN": ["Wear black for", "Feel the loss of"],
    "QUACK": ["Duck's remark", "Doctor with no diploma"],
    "SKATE": ["Glide across the ice", "Flat fish on a French menu"],
    "FRANC": ["Old Paris currency", "Swiss money"],
    "ANNOY": ["Get under one's skin", "Pester relentlessly"],
    "ARSON": ["Fire-setting crime", "Insurance investigator's suspicion"],
    "CAPRI": ["Italian island near Naples", "___ pants, ending mid-calf"],
    "PADRE": ["Military chaplain", "Father, in Spanish"],
    "SCOLD": ["Tell off sharply", "Give a talking-to"],
    "COUPE": ["Two-door car", "Sporty body style"],
    "BENIN": ["West African nation", "Neighbour of Togo and Nigeria"],
    "PATSY": ["Easy mark for a con", "One set up to take the blame"],
    "SQUAT": ["Gym move with a barbell", "Crouch down low"],
    "MANIC": ["Frantically busy", "Wildly overexcited"],
    "SIXTY": ["Minutes in an hour", "Common speed limit"],
    "SPARK": ["Bit of flying ember", "Set off, as a debate"],
    "SPIKE": ["Sudden jump in prices", "Volleyball smash"],
    "TONGA": ["South Pacific kingdom", "Nation of some 170 islands"],
    "ACIDS": ["Low-pH liquids", "Vinegar and lemon juice"],
    "LIBYA": ["North African nation", "Tripoli's country"],
    "CHAOS": ["Utter disorder", "Theory with a butterfly effect"],
    "FLANK": ["Side of an army", "Cut of beef for grilling"],
    "BASES": ["Diamond's four stations", "Acids' counterparts"],
    "ITCHY": ["In need of a scratch", "Like a woollen jumper"],
    "HEIST": ["Big-screen bank job", "Elaborate robbery"],
    "DENIM": ["Jeans fabric", "Blue twill for trousers"],
    "THORN": ["A rose's defence", "Prickly problem"],
    "GLOVE": ["Hand warmer", "Boxer's padding"],
    "HASTY": ["Done in a rush", "Regrettably quick"],
    "PLUSH": ["Luxuriously soft", "Like a fancy hotel lobby"],
    "KYOTO": ["Japan's old capital", "Protocol city of 1997"],
    "ADAPT": ["Adjust to new conditions", "Turn a novel into a film"],
    "MILKY": ["Like tea with too much dairy", "Cloudy white"],
    "STERN": ["Back of a boat", "Strict and unsmiling"],
    "TUTOR": ["Private teacher", "Coach one to one"],
    "HINTS": ["Clues, of a sort", "Drops subtle suggestions"],
    "IDIOT": ["Complete fool", "One who parks across two bays"],
    "DEBIT": ["Card that isn't credit", "Withdrawal on a statement"],
    "RAVEN": ["Poe's croaking visitor", "Glossy black bird at the Tower"],
    "ELVIS": ["The King of rock and roll", "Graceland's famous resident"],
    "ASPEN": ["Colorado ski town", "Tree with quivering leaves"],
    "VENUS": ["Second planet from the sun", "Tennis's elder Williams"],
    "SNAPS": ["Breaks with a crack", "Quick photos"],
    "SHUTS": ["Closes for the night", "Bangs the door on"],
    "DEMON": ["Hell's foot soldier", "Fiendish tormentor"],
    "COUCH": ["Living room seat for three", "Phrase in careful terms"],
    "ROGUE": ["Off the rails, as an agent", "Lovable scoundrel"],
    "JOKER": ["Card that's wild", "Batman's grinning foe"],
    "GRIEF": ["Sorrow after a loss", "Hassle, informally"],
    "SWEAT": ["What a workout brings on", "Worry, slangily"],
    "CELEB": ["Red carpet regular", "Star, informally"],
    "QUAKE": ["Tremble with fear", "San Andreas event"],
    "ALLEY": ["Narrow lane behind the shops", "Bowling venue"],
    "DARED": ["Had the nerve to", "Egged on with a challenge"],
    "TWAIN": ["Mark of American letters", "Author of Tom Sawyer"],
    "RENAL": ["Kidney-related", "Of the body's filters"],
    "SPITE": ["Sheer malice", "Ill will toward another"],
    "FIRED": ["Let go from a job", "Shot, as an arrow"],
    "VIVID": ["Bright and intense", "Like a dream you remember"],
    "BYRON": ["Romantic poet Lord", "He wrote Don Juan"],
    "SKULL": ["Bony head case", "Jolly Roger feature"],
    "NINJA": ["Stealthy Japanese fighter", "Expert, in modern slang"],
    "FREUD": ["Father of psychoanalysis", "He would blame your childhood"],
    "CARVE": ["Work with a chisel", "Slice the Sunday joint"],
    "BRINK": ["The very edge", "Point of no return, nearly"],
    "STEAK": ["Rare or well done order", "Cut from the grill"],
    "COBRA": ["Hooded snake", "Yoga pose on your belly"],
    "THREW": ["Tossed the ball", "Hosted, as a party"],
    "MARRY": ["Tie the knot", "Join in matrimony"],
    "VOUCH": ["Speak up for someone", "Back a claim"],
    "WALKS": ["Strolls round the block", "Free passes in baseball"],
    "DRAKE": ["Male duck on a pond", "Sir Francis of the Armada"],
    "CAIRO": ["Egypt's capital", "Big city on the Nile"],
    "WOODY": ["Cowboy in Toy Story", "Full of trees"],
    "RIVAL": ["Team you love to beat", "Competitor for the same prize"],
    "BEIGE": ["Bland shade of tan", "Colour of an old computer"],
    "GENUS": ["Category above species", "Panthera, for one"],
    "FIXES": ["Sorts out a problem", "Rigs, as a match"],
    "SENDS": ["Puts in the post", "Dispatches"],
    "WHOOP": ["Excited cry", "Shout at a touchdown"],
    "WOKEN": ["Roused from sleep", "Stirred by an alarm"],
    "HUBBY": ["Spouse, informally", "The mister of the house"],
    "STEED": ["Knight's mount", "Trusty horse"],
    "HIGHS": ["Best moments", "Pressure areas on a weather map"],
    "PLUCK": ["Nerve and grit", "Pull at a guitar string"],
    "WOVEN": ["Made on a loom", "Interlaced, as a basket"],
    "RACKS": ["Holders for wine or spices", "Pool table setups"],
    "RIGID": ["Utterly inflexible", "Stiff as a board"],
    "SALSA": ["Dip for tortilla chips", "Dance from Latin America"],
    "WATTS": ["Units on a light bulb", "Measures of power"],
    "BLOWN": ["Like a fuse that went", "Squandered, as a chance"],
    "BATON": ["Conductor's stick", "Relay race handoff"],
    "TUBES": ["Toothpaste containers", "London Underground, with 'the'"],
    "ABBEY": ["Home for monks", "Road the Beatles crossed"],
    "SKINS": ["Banana discards", "What snakes shed"],
    "EXAMS": ["Tests at term's end", "Revision leads up to them"],
    "TEMPT": ["Dangle a doughnut before", "Try to lure in"],
    "MELON": ["Cantaloupe or honeydew", "Summer picnic fruit"],
    "BELLY": ["Paunch below the ribs", "Where a certain button sits"],
    "SAUNA": ["Steamy Finnish room", "Hot box at the gym"],
    "HAIRS": ["Strands on your head", "Things split in a quibble"],
    "KILOS": ["Metric weights", "Airline luggage limit units"],
    "HEAVE": ["Hoist with effort", "Give a great sigh"],
    "CRUEL": ["Heartlessly mean", "Like a joke that stings"],
    "DANDY": ["Flashy dresser of old", "Just splendid"],
    "ANKLE": ["Joint above the foot", "Twisted part in a sprain"],
    "RANKS": ["Army hierarchy levels", "Sorts by order of merit"],
    "TWEET": ["Chirp from a nest", "Short online post"],
    "SKUNK": ["Stripy stinker", "Beat soundly, in games"],
    "BLUNT": ["Not at all sharp", "Frank to a fault"],
    "REACT": ["Respond to news", "Answer chemically"],
    "CHANT": ["Terrace crowd's cry", "Monks' repeated singing"],
    "ALIAS": ["Name on a fake passport", "Also known as"],
    "NEWER": ["More recent", "Fresher off the line"],
    "FLUTE": ["Woodwind held sideways", "Glass for champagne"],
    "HINDI": ["Language of Delhi", "Bollywood's main tongue"],
    "BURMA": ["Old name for Myanmar", "Land renamed in 1989"],
    "CEASE": ["Stop entirely", "Bring to an end"],
    "BANGS": ["Fringe, in America", "Loud sudden noises"],
    "COMFY": ["Snug as an old sofa", "Cosy, informally"],
    "SIOUX": ["Plains people of the Dakotas", "Nation of Sitting Bull"],
    "EQUIP": ["Kit out for a trip", "Supply with gear"],
    "HEDGE": ["Garden boundary of shrubs", "Avoid committing"],
    "DUCKY": ["Bathtub toy, to a tot", "Just peachy"],
    "CURRY": ["Takeaway with a spice blend", "___ favour with the boss"],
    "LIONS": ["Pride members", "Beasts in Daniel's den"],
    "POOLS": ["Places to swim lengths", "Combines resources"],
    "POUCH": ["Kangaroo's carrier", "Small drawstring bag"],
    "LUPIN": ["Spiky cottage-garden bloom", "Tall flower in a border"],
    "SPOON": ["Utensil for soup", "Cuddle closely in bed"],
    "SAVES": ["Goalkeeper's stops", "Puts money aside"],
    "CIGAR": ["Havana smoke", "Close, but no ___"],
    "CURSE": ["Witch's hex", "Swear word"],
    "TITAN": ["Giant of Greek myth", "Saturn's largest moon"],
    "SHOUT": ["Yell across the street", "Call out loudly"],
    "HOLLY": ["Christmas wreath plant", "Prickly leaves, red berries"],
    "SILLY": ["Not to be taken seriously", "Daft as a brush"],
    "SUEDE": ["Napped leather", "Blue shoes in a song"],
    "BOSOM": ["Close, as friends", "Chest, in old novels"],
    "UNCUT": ["Not trimmed at all", "Like a director's full version"],
    "ABYSS": ["Bottomless chasm", "The void you shouldn't stare into"],
    "NIXON": ["Watergate president", "He resigned in 1974"],
    "FREAK": ["Lose one's cool, with 'out'", "Unusual specimen"],
    "BLUFF": ["Poker player's fake", "Cliff above the sea"],
    "CLAWS": ["Cat's retractables", "Lobster's grabbers"],
    "SHEER": ["Utter, as nonsense", "Thin enough to see through"],
    "HATCH": ["Come out of an egg", "Opening in a ship's deck"],
    "CLINK": ["Toast sound", "Jail, in slang"],
    "STEIN": ["Hefty German beer mug", "Vessel raised at Oktoberfest"],
    "SPILL": ["Knock over the milk", "Tell all, with 'the beans'"],
    "DRIFT": ["Snow piled by the wind", "General gist"],
    "GRAIL": ["Holy quest object", "Ultimate goal"],
    "THINE": ["Yours, in old English", "Biblical possessive"],
    "CRISP": ["Fresh and snappy", "Potato snack, in Britain"],
    "DECOY": ["Duck hunter's fake", "Lure for the unwary"],
    "SHAKY": ["Unsteady on its feet", "Like a poor alibi"],
    "ASSAY": ["Test the purity of", "Analyse an ore sample"],
    "GOOFY": ["Disney dog with a hat", "Endearingly daft"],
    "GOODY": ["Treat in a party bag", "___ two-shoes"],
    "TUNES": ["Catchy melodies", "Adjusts a guitar"],
    "SNACK": ["Bite between meals", "Crisps or nuts, say"],
    "SQUID": ["Calamari source", "Ten-armed sea creature"],
    "MAXIM": ["Pithy saying", "Rule of thumb in a sentence"],
    "LOCKS": ["What keys turn", "Canal chambers for boats"],
    "SLATE": ["Roofing stone", "Schedule, as a meeting"],
    "HIRED": ["Taken on for a job", "Rented, as a car in Britain"],
    "SLIME": ["Gooey children's toy", "A snail's trail"],
    "LUIGI": ["Mario's taller brother", "Green-capped Nintendo plumber"],
    "PAGAN": ["Pre-Christian believer", "Solstice celebrant"],
    "WIDOW": ["Spider with a red hourglass", "Bereaved wife"],
    "KILLS": ["Slays, in comedy", "Switches off, as an engine"],
    "JUICY": ["Dripping with flavour", "Like the best gossip"],
    "NAILS": ["Hammer targets", "Aces the routine"],
    "RIDES": ["Fairground attractions", "Sits on a horse"],
    "MOODY": ["Prone to sulks", "Atmospheric, as lighting"],
    "DISKS": ["Round flat objects", "Old computer storage"],
    "PEDAL": ["Bike part for the foot", "Push it to the metal"],
    "CHUMP": ["Gullible sort", "Sucker, quaintly"],
    "FIRES": ["Campground blazes", "Sacks, as staff"],
    "TERRA": ["___ firma, i.e. solid ground", "Earth, in Latin"],
    "VAPOR": ["Steam, essentially", "What a kettle puts out"],
    "ALOUD": ["Not silently", "How you read to a child"],
    "SONAR": ["Submarine's pinger", "Bat-like navigation"],
    "GOOSE": ["Bird that honks", "Gander's mate"],
    "POSSE": ["Sheriff's gathered crew", "One's entourage"],
    "NOISY": ["Far from quiet", "Like a school canteen"],
    "ABIDE": ["Put up with", "Stick to the rules"],
    "THUDS": ["Sounds of books dropping", "Heavy dull noises"],
    "AMUSE": ["Tickle the funny bone", "Keep entertained"],
    "LORRY": ["Truck, in Britain", "Motorway hauler"],
    "BLISS": ["Perfect happiness", "Ignorance is this, they say"],
    "PARSE": ["Break down a sentence", "Analyse grammatically"],
    "GAVEL": ["Judge's rapper", "Auctioneer's hammer"],
    "FEARS": ["Phobias, loosely", "Dreads the worst"],
    "JERKS": ["Sudden movements", "Rude sorts"],
    "THUMP": ["Dull heavy knock", "Heart's loud beat"],
    "SATAN": ["The devil himself", "Lucifer, by another name"],
    "BUDGE": ["Move an inch", "Give way at last"],
    "BUCKS": ["Deer with antlers", "Dollars, informally"],
    "HOMEY": ["Cosy and welcoming", "Like a lived-in kitchen"],
    "CLAMP": ["Workbench gripper", "Wheel immobiliser"],
    "BUSES": ["Public transport fleet", "Double-deckers"],
    "GUILT": ["Nagging sense of wrongdoing", "What a jury may find"],
    "RELIC": ["Object from a bygone age", "Saint's preserved bone"],
    "SPADE": ["Digging tool", "Suit in a card deck"],
    "LUNAR": ["Of the moon", "Calendar based on phases"],
    "NOSES": ["Things that run in winter", "Wine tasters' assets"],
    "CUPID": ["Valentine's archer", "Winged matchmaker"],
    "WIVES": ["Henry VIII had six", "Spouses, plural"],
    "WEIGH": ["Step on the scales", "Consider carefully"],
    "RODEO": ["Bull-riding show", "Drive in Beverly Hills"],
    "MOOSE": ["Antlered Canadian giant", "Elk's North American cousin"],
    "SCALP": ["Under the hair", "Resell tickets at a markup"],
    "SORTS": ["Types and varieties", "Puts into order"],
    "LIARS": ["Pants on fire crowd", "Ones not to be believed"],
    "TASTY": ["Full of flavour", "Worth a second helping"],
    "ABBOT": ["Monastery head", "One in charge of monks"],
    "COCOA": ["Hot chocolate powder", "Winter mug filler"],
    "PIPES": ["Under-sink plumbing", "Singer's vocal power, slangily"],
    "CUFFS": ["Shirt sleeve ends", "Police restraints"],
    "ORION": ["Constellation with a belt", "Hunter in the night sky"],
    "CLASH": ["Come into conflict", "What mismatched colours do"],
    "FADES": ["Loses colour in the sun", "Gradually disappears"],
    "GROWS": ["Gets taller", "Tends in the garden"],
    "REIGN": ["Time on the throne", "Rule as monarch"],
    "DARES": ["Ventures boldly", "Truth or ___ prompts"],
    "STIFF": ["Hard to bend", "Strong, as a drink"],
    "RABBI": ["Synagogue leader", "One who leads a bar mitzvah"],
    "SUSHI": ["Rice and raw fish dish", "Rolls served with wasabi"],
    "PUFFY": ["Swollen, as eyes", "Like a cumulus cloud"],
    "DOCKS": ["Harbour berths", "Cuts from wages"],
    "GROWL": ["Dog's warning", "Hungry stomach's noise"],
    "PICKY": ["Hard to please at dinner", "Fussy eater's trait"],
    "STARK": ["Bleak and bare", "Utter, as a contrast"],
    "CIRCA": ["About, in dates", "Approximately, on a label"],
    "LEDGE": ["Narrow shelf on a cliff", "Sill for a window box"],
    "LINED": ["Ruled, as paper", "Wrinkled, as a face"],
    "BOXED": ["Packaged in cardboard", "Fought in the ring"],
    "RAZOR": ["Sharp shaving blade", "Occam's ___"],
    "COUGH": ["Symptom of a cold", "___ up the money"],
    "SPREE": ["Shopping splurge", "Wild run of activity"],
    "TESLA": ["Nikola of electricity", "Unit of magnetic flux"],
    "TIBET": ["Himalayan plateau region", "Lhasa's homeland"],
    "FLYER": ["Leaflet handed out in the street", "Frequent air traveller"],
    "STALE": ["Like day-old bread", "Well past its best"],
    "BATHS": ["Tubs of hot water", "Roman public washhouses"],
    "MUNCH": ["Eat noisily", "Painter of The Scream"],
    "BRONX": ["New York borough", "Yankee Stadium's home"],
    "GLOSS": ["Shiny paint finish", "Brief note in a margin"],
    "DOVER": ["English Channel port", "White cliffs town"],
    "PORCH": ["Where the swing hangs", "Sheltered entrance"],
    "TELLY": ["What Brits watch of an evening", "Set in the living room"],
    "CHOPS": ["Cuts of lamb", "Fells with an axe"],
    "BELTS": ["Trouser holders", "Sings out loudly"],
    "DINAR": ["Currency in Baghdad", "Money in Tunisia"],
    "CARAT": ["Diamond weight unit", "Gold purity measure"],
    "NOBEL": ["Prize awarded in Stockholm", "Dynamite inventor Alfred"],
    "GEESE": ["Flock flying in a V", "Gaggle members"],
    "MOSES": ["Parter of the Red Sea", "He came down with tablets"],
    "PLUMP": ["Pleasantly round", "Fluff up a cushion"],
    "MIDST": ["In the thick of it", "Middle of the action"],
    "BORNE": ["Carried along", "Endured, as pain"],
    "DRYER": ["Laundry room appliance", "Blower for hair"],
}
